<!-- 
/**
 * PpitCore V1.0 (https://github.com/p-pit/PpitCore)
 *
 * @link      https://github.com/p-pit/PpitCore
 * @copyright Copyright (c) 2016 Bruno Lartillot
 * @license   https://github.com/p-pit/PpitCore/blob/master/license.txt GNU-GPL license
 */
-->

<!-- Load the common form javascript functions -->
<?php echo $this->partial('/partials/common-form-js.phtml'); ?>

<?php
$title = $context->getConfig('event/index/planning')['title'][$context->getLocale()];
$this->headTitle($title);
echo $this->partial('/partials/header');
?>
	
	<div>&nbsp;</div>
	
	<div class="row" id="main_menu" >

<?php foreach ($context->getConfig('menus')['p-pit-studies'] as $entryId => $entry) : ?>
	<?php if ($context->isAllowed($entry['route'])) : ?>
		<?php if ($entryId == 'planning') $color = 'btn-primary'; else $color = 'btn-default' ?>
		<div class="col-md-2">
				<button type="button" class="btn <?php echo $color ?> menu-btn" style="width:100%; text-align: left" id="<?php echo $entryId ?>-anchor">
		<?php if (array_key_exists('glyphicon', $entry)) : ?>
					<span class="glyphicon <?php echo $entry['glyphicon'] ?>"></span>
		<?php endif;?>
					<?php echo $entry['label'][$context->getLocale()] ?>
				</button>
		</div>
	<?php endif ?>
<?php endforeach ?>

	</div>

	<div>&nbsp;</div>

	<!-- Main panel -->
	<div class="row">
	    <div class="col-md-12 ppit-panel" id="index_action"></div>
	</div>
	
	<!-- Login -->
	<div class="row">
	    <div class="col-md-6 col-md-offset-3 ppit-panel" id="login-panel">
		</div>
	</div>

<!-- MDB core JavaScript -->
<script type="text/javascript" src="<?php echo $this->basePath('mdb-free/js/mdb.min.js') ?>"></script>

<script>

<?php
echo $this->partial('/partials/event-scripts');
echo $this->partial('/partials/ppit-controller') 
?>

<?php foreach ($context->getConfig('menus')['p-pit-studies'] as $entryId => $entry) : ?>
	$('#<?php echo $entryId ?>-anchor').click(function () { $(location).attr('href', '<?php echo $this->url($entry['route'], $entry['params']) ?>'); });
<?php endforeach;?>

activateEvent();

</script>
