<?php 
$spa = $context->isSpaMode();
$anchorStyle = ($spa) ? $context->getAnchorStyle() : 'classic';
?>

<!-- Display header on MPA mode -->
<?php if (!$spa) : ?>
	<?php 
	$this->current = 'customer';
	echo $this->partial('/partials/menu'); 
	?>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
<?php endif;?>

		<div class="panel panel-default">
			<div class="panel-heading">
				<strong><?php echo $this->translate('Delete a contact', 'ppit-contact', $context->getLocale()) ?></strong>
 				<div class="btn-group pull-right">
					<?php echo $this->partial('/partials/anchor-widget.phtml', array(
							'glyphicon' => 'glyphicon-remove',
							'title' => $this->translate('Return to list', 'ppit-core', $context->getLocale()),
							'id' => 'remove-anchor',
							'anchorStyle' => $anchorStyle,
							'spa' => $spa,
					)) ?>
 				</div>
			</div>
           	<div class="panel-body">

				<table class="table-condensed">
				
<!-- Last, first name -->
				    <tr class="row">
						<td align="right"><strong><?php echo $this->translate('Name', 'ppit-contact', $context->getLocale()) ?></strong></td>
						<td><?php echo $contact->n_fn ?></td>
					</tr>
           	
<!-- email -->
<?php if ($contact->email) : ?>
					<tr class="row">
						<td align="right"><strong><?php echo $this->translate('email', 'ppit-contact', $context->getLocale()) ?></strong></td>
						<td><?php echo $contact->email ?></td>
					</tr>
<?php endif;?>
           	
<!-- Cellular -->
<?php if ($contact->tel_cell) : ?>
					<tr class="row">
						<td align="right"><strong><?php echo $this->translate('Cellular phone', 'ppit-contact', $context->getLocale()) ?></strong></td>
						<td><?php echo $contact->tel_cell ?></td>
					</tr>
<?php endif;?>
           	
<!-- Work phone -->
<?php if ($contact->tel_work) : ?>
					<tr class="row">
						<td align="right"><strong><?php echo $this->translate('Work phone', 'ppit-contact', $context->getLocale()) ?></strong></td>
						<td><?php echo $contact->tel_work ?></td>
					</tr>
<?php endif;?>

				</table>
 
<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
	'id' => $id,
	'update_time' => $contact->update_time,
	'message' => $message,
	'error' => $error,
	'csrfForm' => $csrfForm,
	'context' => $context,
)) ?>

<!-- Form footer -->
<?php echo $this->partial('/partials/form-footer', array(
	'class' => 'btn-danger',
	'message' => $message,
	'context' => $context,
)) ?>
 
 			</div>
		</div>

<?php if (!$context->isSpaMode()) : ?>
	</div>
</div>
<?php endif;?>

<script id='vcard_delete_script'>

// Close form
<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'remove-anchor',
		'route' => $this->url('vcard/index', array('instance_id' => $contact->instance_id, 'community_id' => $contact->community_id)),
		'spa' => $spa,
)) ?>

<?php if ($message == 'OK') : ?>

<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'foot-return-anchor',
		'route' => $this->url('vcard/index', array('instance_id' => $contact->instance_id, 'community_id' => $contact->community_id)),
		'spa' => $spa,
)) ?>

<?php else : ?>

<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'cancel-anchor',
		'route' => $this->url('vcard/index', array('instance_id' => $contact->instance_id, 'community_id' => $contact->community_id)),
		'spa' => $spa,
)) ?>

// Submit
<?php echo $this->partial('/partials/form-button-script', array(
		'context' => $context,
		'id' => 'submit-button',
		'checkFunction' => 'checkForm',
		'formRoute' => $this->url('vcard/delete', array('id' => $id)),
		'formScript' =>'customer_delete_script',
		'properties' => array(),
		'mainRoute' => $this->url('vcard/index', array('instance_id' => $contact->instance_id, 'community_id' => $contact->community_id)),
		'mainScript' =>'vcard_script',
		'hideForm' => true,
)) ?>

<?php endif;?>

function checkForm() 
{
	return true;
}

</script>
