<?php 
header('Content-Type: text/csv; charset=utf-8');
header("Content-disposition: filename=contacts-<?php echo date('Y-m-d').csv");
echo "\xEF\xBB\xBF";
 
echo
$this->translate('Title', 'ppit-contact', $context->getLocale()).";".
$this->translate('First name', 'ppit-contact', $context->getLocale()).";".
$this->translate('Last name', 'ppit-contact', $context->getLocale()).";".
$this->translate('Email', 'ppit-contact', $context->getLocale()).";".
$this->translate('Cellular', 'ppit-contact', $context->getLocale()).";".
$this->translate('Work phone', 'ppit-contact', $context->getLocale()).";".
$this->translate('Address - street', 'ppit-contact', $context->getLocale()).";".
$this->translate('Address - extended', 'ppit-contact', $context->getLocale()).";".
$this->translate('Address - post office box', 'ppit-contact', $context->getLocale()).";".
$this->translate('Address - zip', 'ppit-contact', $context->getLocale()).";".
$this->translate('Address - city', 'ppit-contact', $context->getLocale()).";".
$this->translate('Address - state', 'ppit-contact', $context->getLocale()).";".
$this->translate('Address - country', 'ppit-contact', $context->getLocale()).";".
$this->translate('Sex', 'ppit-contact', $context->getLocale()).";".
$this->translate('Birth date', 'ppit-contact', $context->getLocale()).";".
$this->translate('Place of birth', 'ppit-contact', $context->getLocale()).";".
$this->translate('Nationality', 'ppit-contact', $context->getLocale())."\n";

foreach ($vcards as $vcard) {
	echo
	$vcard->n_title.";".
	$vcard->n_first.";".
	$vcard->n_last.";".
	$vcard->email.";".
	$vcard->tel_cell.";".
	$vcard->tel_work.";".
	$vcard->adr_street.";".
	$vcard->adr_extended.";".
	$vcard->adr_post_office_box.";".
	$vcard->adr_zip.";".
	$vcard->adr_city.";".
	$vcard->adr_state.";".
	$vcard->adr_country.";".
	$vcard->sex.";".
	$vcard->birth_date.";".
	$vcard->place_of_birth.";".
	$vcard->nationality."\n";
}
