
<!-- Load the form header -->
<?php echo $this->partial('/partials/form-header.phtml', array(
			'update_time' => $studentSport->update_time,
			'message' => $message,
			'error' => $error,
			'csrfForm' => $csrfForm,
			'context' => $context,
));
?>

<?php if ($message == 'OK') $isDisabled = true; else $isDisabled = false; ?>
		
<!-- Sport -->
		<div class="form-group" id="sport_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Sport', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select name="sport" id="sport" class="form-control" <?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
					<option value=""><-- <?php echo $this->translate('Please select a value', 'ppit-core', $context->getLocale()) ?> --></option>
	<?php foreach ($config['ppitStudies']['sports'] as $sport => $sportProperties) : ?>
		    		<option value="<?php echo $sport ?>" <?php if ($studentSport->sport == $sport) echo ' selected="selected"' ?>><?php echo $config['ppitStudies']['sports'][$sport]['labels'][$context->getLocale()] ?></option>
	<?php endforeach;?>
		    	</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="sport_error"></p></div>
		</div>
		
<!-- Category -->
		<div class="form-group" id="category_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Category', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="category" id="category" class="form-control" value="<?php echo $studentSport->category ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="category_error"></p></div>
		</div>

<!-- Licence holder -->
		<div class="form-group" id="licence_holder_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Licence', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="n_title" id="n_title" class="form-control" value="<?php echo $studentSport->licence_holder ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="licence_holder_error"></p></div>
		</div>

<!-- Level -->
		<div class="form-group" id="level_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Level', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="level" id="level" class="form-control" value="<?php echo $studentSport->level ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="level_error"></p></div>
		</div>

<!-- Results -->
		<div class="form-group" id="results_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Results', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="results" id="results" class="form-control" value="<?php echo $studentSport->results ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="results_error"></p></div>
		</div>
		
<!-- Left/right handed -->
		<div class="form-group" id="left_right_handed_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Left/right handed', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select name="left_right_handed" id="left_right_handed" class="form-control" <?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
					<option value=""><-- <?php echo $this->translate('Please select a value', 'ppit-core', $context->getLocale()) ?> --></option>
		    		<option value="Left handed" <?php if ($studentSport->left_right_handed == 'Left handed') echo ' selected="selected"' ?>><?php echo $this->translate('Left handed', 'ppit-studies', $context->getLocale()) ?></option>
		    		<option value="Right handed" <?php if ($studentSport->left_right_handed == 'Right handed') echo ' selected="selected"' ?>><?php echo $this->translate('Right handed', 'ppit-studies', $context->getLocale()) ?></option>
		    	</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="left_right_handed_error"></p></div>
		</div>

<!-- Main post -->
		<div class="form-group" id="main_post_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Main post', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="main_post" id="main_post" class="form-control" value="<?php echo $studentSport->main_post ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="main_post_error"></p></div>
		</div>

<!-- Secondary posts -->
		<div class="form-group" id="secondary_posts_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Secondary posts', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="secondary_posts" id="secondary_posts" class="form-control" value="<?php echo $studentSport->secondary_posts ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="secondary_posts_error"></p></div>
		</div>

<!-- Club -->
		<div class="form-group" id="club_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Club', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="club" id="club" class="form-control" value="<?php echo $studentSport->club ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="club_error"></p></div>
		</div>

<!-- Coach name -->
		<div class="form-group" id="coach_name_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Coach', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="coach_name" id="coach_name" class="form-control" value="<?php echo $studentSport->coach_name ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="coach_name_error"></p></div>
		</div>

<!-- Coach tel -->
		<div class="form-group" id="coach_tel_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Coach: phone', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="coach_tel" id="coach_tel" class="form-control" value="<?php echo $studentSport->coach_tel ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="coach_tel_error"></p></div>
		</div>

<!-- Weight -->
		<div class="form-group" id="weight_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Weight (pounds)', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="weight" id="weight" class="form-control" value="<?php echo $studentSport->weight ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="weight_error"></p></div>
		</div>

<!-- Height -->
		<div class="form-group" id="height_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Height (inches)', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="height" id="height" class="form-control" value="<?php echo $studentSport->height ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="height_error"></p></div>
		</div>

<!-- Wear size -->
		<div class="form-group" id="wear_size_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Wear size', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="wear_size" id="wear_size" class="form-control" value="<?php echo $studentSport->wear_size ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="wear_size_error"></p></div>
		</div>

<!-- Shoe size -->
		<div class="form-group" id="shoe_size_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Shoe size', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="shoe_size" id="shoe_size" class="form-control" value="<?php echo $studentSport->shoe_size ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="shoe_size_error"></p></div>
		</div>

<!-- Medical histories -->
		<div class="form-group" id="medical_histories_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Medical histories', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="medical_histories" id="medical_histories" class="form-control" value="<?php echo $studentSport->medical_histories ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="medical_histories_error"></p></div>
		</div>

<!-- Medical checkup -->
		<div class="form-group" id="medical_chekup_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Medical checkup', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="medical_checkup" id="medical_checkup" class="form-control" value="<?php echo $studentSport->medical_checkup ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="medical_checkup_error"></p></div>
		</div>

<!-- Muscle checkup -->
		<div class="form-group" id="muscle_checkup_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Muscle checkup', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="muscle_checkup" id="muscle_checkup" class="form-control" value="<?php echo $studentSport->muscle_checkup ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="muscle_checkup_error"></p></div>
		</div>

<!-- Stretching checkup -->
		<div class="form-group" id="stretching_checkup_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Stretching checkup', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="stretching_checkup" id="stretching_checkup" class="form-control" value="<?php echo $studentSport->stretching_checkup ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="stretching_checkup_error"></p></div>
		</div>

<!-- ECG -->
		<div class="form-group" id="ecg_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('ECG', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="ecg" id="ecg" class="form-control" value="<?php echo $studentSport->ecg ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="ecg_error"></p></div>
		</div>

<!-- Oro-dental checkup -->
		<div class="form-group" id="oro_dental_checkup_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Oro-dental checkup', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="oro_dental_checkup" id="oro_dental_checkup" class="form-control" value="<?php echo $studentSport->oro_dental_checkup ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="oro_dental_checkup_error"></p></div>
		</div>

<!-- Primary doctor -->
		<div class="form-group" id="primary_doctor_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Primary doctor', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="primary_doctor" id="primary_doctor" class="form-control" value="<?php echo $studentSport->primary_doctor ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="primary_doctor_error"></p></div>
		</div>
		
<?php if ($message == 'OK') : ?>

<!-- Foot return link -->
			<div class="form-group" id="foot_return_link">
				<div class="col-sm-4">&nbsp;</div>
				<div class="col-sm-8">
					<button type="button" class="btn btn-default" title="<?php echo $this->translate('Close', 'ppit-core', $context->getLocale()) ?>" id="return-anchor">
						<span><?php echo $this->translate('Return', 'ppit-core', $context->getLocale()) ?></span>
					</button>
				</div>
			</div>

<?php else : ?>

<!-- Submit button -->
		    <div class="form-group">
				<div class="col-sm-4">&nbsp;</div>
				<div class="col-sm-8">
					<input name="submit" type="submit" id="submit-button" class="btn btn-warning" value="<?php echo $this->translate('Confirm', 'ppit-core', $context->getLocale()) ?>">
					&nbsp;&nbsp;
					<button type="button" class="btn btn-default" title="<?php echo $this->translate('Cancel', 'ppit-core', $context->getLocale()) ?>" id="cancel-anchor">
						<span><?php echo $this->translate('Cancel', 'ppit-core', $context->getLocale()) ?></span>
					</button>
				</div>
			</div>

<?php endif;?>

		</form>
