<style>
table.note-report {
	font-size: 0.83em;
	border-width:1px; 
 	border-style:solid; 
	border-color:gray;
}
table.note-report caption { 
	font-size:1.5em; 
	padding:1em 0 0.5em 1em;
}
table.note-report th {
	color: #666;
//    font-size:0.83em;
	text-align: center;
	border-width:1px; 
 	border-style:solid; 
	border-color:gray;
	background-color:#DDD;
}

table.note-report td {
	color: #666;
//	font-size: 0.83em;
	border-width:1px; 
 	border-style:solid; 
	border-color:gray;
}

table.note-report td.subject {
	font-weight: bold;
}

table.note-report tr.period {
	background-color:#DDD;
}
</style>

<?php foreach ($periods as $periodId => $period) : ?>
	<?php 
	$params = explode('.', $periodId); 
	$school_year = $params[0];
	$school_period = $params[1];
	?>
	
    <!--Card content-->
<div class="card-block" style="color: #686868">
    <!--Title-->
    <h4 class="card-title" style="text-align: center">
		<?php echo $context->localize($context->getConfig('student/property/school_year')['labels']) ?>:
		<?php echo $context->localize($context->getConfig('student/property/school_year')['modalities'][$school_year]) ?> &mdash;
		<?php echo $context->localize($context->getConfig('student/property/school_period')['modalities'][$school_period]) ?>
	</h4>
	<!--Text-->
		<div><a href="<?php echo $this->url('student/download', array('category' => 'absence', 'account_id' => $account->id, 'school_year' => $school_year, 'school_period' => $school_period)) ?>"><?php echo $this->translate('Download in PDF format', 'ppit-studies', $context->getLocale()) ?></a></div>
		<table class="table note-report">
			<tr>
				<th><?php echo $this->translate('Type', 'ppit-core', $context->getLocale()) ?></th>
				<th><?php echo $this->translate('Subject', 'ppit-studies', $context->getLocale()) ?></th>
				<th><?php echo $this->translate('Date', 'ppit-core', $context->getLocale()) ?></th>
				<th><?php echo $this->translate('Motive', 'ppit-studies', $context->getLocale()) ?></th>
				<th><?php echo $this->translate('Observations', 'ppit-studies', $context->getLocale()) ?></th>
			</tr>
	<?php $first=true; foreach ($period as $absLate) : ?>
			<tr>
				<td class="subject">
					<?php echo $this->translate((($absLate->category == 'absence') ? 'Absence' : 'Lateness'), 'ppit-studies', $context->getLocale()) ?>
				</td>
				<td class="subject">
					<?php echo ($absLate->subject) ? $context->localize($context->getConfig('student/property/school_subject')['modalities'][$absLate->subject]) : '' ?>
				</td>
		<?php if ($absLate->end_date > $absLate->begin_date) : ?>
				<td><?php echo $this->translate('From the', 'ppit-studies', $context->getLocale()).' '.$context->decodeDate($absLate->begin_date).'<br>'.$this->translate('to the', 'ppit-studies', $context->getLocale()).' '.$context->decodeDate($absLate->end_date) ?></td>
		<?php else : ?>
				<td><?php echo $context->decodeDate($absLate->begin_date) ?></td>
		<?php endif;?>
				<td><?php if ($absLate->motive) echo $context->localize($context->getConfig('absence/property/motive')['modalities'][$absLate->motive]) ?></td>
				<td><?php echo $absLate->observations ?></td>
			</tr>
	<?php endforeach;?>
		</table>
</div>
<?php endforeach;?>

<?php if (count($absences) > 0) : ?>

<!-- Absences -->
<div class="card-block" style="color: #686868">
	<!--Title-->
<!--	<h4 class="card-title" style="text-align: center">
		<?php echo $this->translate('Number of absences on period', 'ppit-studies', $context->getLocale()) ?>:
		<strong><?php echo $absenceCount ?></strong>
	<?php if ($cumulativeAbsence) : ?>
		&mdash;
		<?php echo $this->translate('Cumulative duration', 'ppit-studies', $context->getLocale()) ?>:
		<strong><?php if ((int)($cumulativeAbsence/60)) echo ((int)($cumulativeAbsence/60)).'h' ?><?php if ($cumulativeAbsence%60) echo sprintf('%02u', $cumulativeAbsence%60).'mn' ?></strong>
	<?php endif;?>
	</h4> -->

	<!--Text-->
<!--	<?php $first=true; foreach ($absences as $absence) : ?>
	<div>
	<?php if ($absence->end_date > $absence->begin_date) : ?>
		<?php echo $this->translate('From the', 'ppit-studies', $context->getLocale()) ?>
		<strong><?php echo $context->decodeDate($absence->begin_date) ?></strong>
		<?php echo $this->translate('to the', 'ppit-studies', $context->getLocale()) ?>
		<strong><?php echo $context->decodeDate($absence->end_date) ?></strong>
	<?php else : ?>
		<strong><?php echo $context->decodeDate($absence->begin_date) ?></strong>
	<?php endif;?>
	<?php if ($absence->subject) : ?>
		&mdash;
		<?php echo $context->localize($context->getConfig('student/property/school_subject')['modalities'][$absence->subject]) ?>
	<?php endif;?>
	<?php if ($absence->duration) : ?>
		&mdash;
		<?php echo $this->translate('Duration', 'ppit-studies', $context->getLocale()) ?>:
		<strong><?php if ((int)($absence->duration/60)) echo ((int)($absence->duration/60)).'h' ?><?php if ($absence->duration%60) echo sprintf('%02u', $absence->duration%60).'mn' ?></strong>
	<?php elseif ($absence->end_date == $absence->begin_date) : ?>
		&mdash;
		<strong><?php echo $this->translate('Entire day', 'ppit-studies', $context->getLocale()) ?></strong>
	<?php endif;?>
	<?php if ($absence->motive) : ?>
		&mdash;
		<?php echo $this->translate('Motive', 'ppit-studies', $context->getLocale()) ?>:
		<strong><?php echo $context->localize($context->getConfig('absence/property/motive')['modalities'][$absence->motive]) ?></strong>
	<?php endif;?>
	<?php if ($absence->observations) : ?>
		<br><?php echo $absence->observations ?>
	<?php endif;?>
	</div>

	<?php $first=false; endforeach;?>
<hr/> -->
</div>
<?php endif;?>

<?php if (count($latenesss) > 0) : ?>

<!-- Lateness -->
<div class="card-block" style="color: #686868">
	<!--Title-->
<!--	<h4 class="card-title" style="text-align: center">
		<?php echo $this->translate('Number of lateness on period', 'ppit-studies', $context->getLocale()) ?>:
		<strong><?php echo $latenessCount ?></strong>
	<?php if ($cumulativeLateness) : ?>
		&mdash;
		<?php echo $this->translate('Cumulative duration', 'ppit-studies', $context->getLocale()) ?>:
		<strong><?php if ((int)($cumulativeLateness/60)) echo ((int)($cumulativeLateness/60)).'h' ?><?php if ($cumulativeLateness%60) echo sprintf('%02u', $cumulativeLateness%60).'mn' ?></strong>
	<?php endif;?>
	</h4> -->

	<!--Text-->
<!--	<?php $first=true; foreach ($latenesss as $lateness) : ?>
	<div>
		<strong><?php echo $context->decodeDate($lateness->begin_date) ?></strong>
	<?php if ($lateness->subject) : ?>
		&mdash;
		<?php echo $context->localize($context->getConfig('student/property/school_subject')['modalities'][$lateness->subject][$context->getLocale()]) ?>
	<?php endif;?>
	<?php if ($lateness->duration) : ?>
		&mdash;
		<?php echo $this->translate('Duration', 'ppit-studies', $context->getLocale()) ?>:
		<strong><?php if ((int)($lateness->duration/60)) echo ((int)($lateness->duration/60)).'h' ?><?php if ($lateness->duration%60) echo sprintf('%02u', $lateness->duration%60).'mn' ?></strong>
	<?php endif;?>
	<?php if ($lateness->motive) : ?>
		&mdash;
		<?php echo $this->translate('Motive', 'ppit-studies', $context->getLocale()) ?>:
		<strong><?php echo $context->localize($context->getConfig('absence/property/motive')['modalities'][$lateness->motive]) ?></strong>
	<?php endif;?>
	<?php if ($lateness->observations) : ?>
		<br><?php echo $lateness->observations ?>
	<?php endif;?>
	</div>

	<?php $first=false; endforeach;?>
<hr/> -->
</div>
<?php endif;?>
