<style>
table.note-report {
	font-size: 0.83em;
	border-width:1px; 
 	border-style:solid; 
	border-color:gray;
}
table.note-report caption { 
	font-size:1.5em; 
	padding:1em 0 0.5em 1em;
}
table.note-report th {
	color: #666;
//    font-size:0.83em;
	text-align: center;
	border-width:1px; 
 	border-style:solid; 
	border-color:gray;
	background-color:#DDD;
}

table.note-report td {
	color: #666;
//	font-size: 0.83em;
	border-width:1px; 
 	border-style:solid; 
	border-color:gray;
}

table.note-report td.subject {
	font-weight: bold;
}

table.note-report tr.period {
	background-color:#DDD;
}
</style>

<?php if (count($absences) > 0) : ?>

<!-- Absences -->
<div class="card-block" style="color: #686868">
	<!--Title-->
	<h4 class="card-title" style="text-align: center">
		<?php echo $this->translate('Number of absences on period', 'ppit-studies', $context->getLocale()) ?>:
		<strong><?php echo $absenceCount ?></strong>
		&mdash;
		<?php echo $this->translate('Cumulative duration', 'ppit-studies', $context->getLocale()) ?>:
		<strong><?php if ((int)($cumulativeAbsence/60)) echo ((int)($cumulativeAbsence/60)).'h' ?><?php if ($cumulativeAbsence%60) echo sprintf('%02u', $cumulativeAbsence%60).'mn' ?></strong>
	</h4>

	<!--Text-->
	<?php $first=true; foreach ($absences as $absence) : ?>
	<div>
		<strong><?php echo $context->decodeDate($absence->begin_date) ?></strong>
		&mdash;
		<?php echo $context->getConfig('student/property/school_subject')['modalities'][$absence->subject][$context->getLocale()] ?>
		&mdash;
		<?php echo $this->translate('Duration', 'ppit-studies', $context->getLocale()) ?>:
		<strong><?php if ((int)($absence->duration/60)) echo ((int)($absence->duration/60)).'h' ?><?php if ($absence->duration%60) echo sprintf('%02u', $absence->duration%60).'mn' ?></strong>
	<?php if ($absence->motive) : ?>
		&mdash;
		<?php echo $this->translate('Motive', 'ppit-studies', $context->getLocale()) ?>:
		<strong><?php echo $context->getConfig('absence/property/motive')['modalities'][$absence->motive][$context->getLocale()] ?></strong>
	<?php endif;?>
	<?php if ($absence->observations) : ?>
		<br><?php echo $absence->observations ?>
	<?php endif;?>
	</div>

	<?php $first=false; endforeach;?>
<hr/>
</div>
<?php endif;?>

<?php if (count($latenesss) > 0) : ?>

<!-- Lateness -->
<div class="card-block" style="color: #686868">
	<!--Title-->
	<h4 class="card-title" style="text-align: center">
		<?php echo $this->translate('Number of lateness on period', 'ppit-studies', $context->getLocale()) ?>:
		<strong><?php echo $latenessCount ?></strong>
		&mdash;
		<?php echo $this->translate('Cumulative duration', 'ppit-studies', $context->getLocale()) ?>:
		<strong><?php if ((int)($cumulativeLateness/60)) echo ((int)($cumulativeLateness/60)).'h' ?><?php if ($cumulativeLateness%60) echo sprintf('%02u', $cumulativeLateness%60).'mn' ?></strong>
	</h4>

	<!--Text-->
	<?php $first=true; foreach ($latenesss as $lateness) : ?>
	<div>
		<strong><?php echo $context->decodeDate($lateness->begin_date) ?></strong>
		&mdash;
		<?php echo $context->getConfig('student/property/school_subject')['modalities'][$lateness->subject][$context->getLocale()] ?>
		&mdash;
		<?php echo $this->translate('Duration', 'ppit-studies', $context->getLocale()) ?>:
		<strong><?php if ((int)($lateness->duration/60)) echo ((int)($lateness->duration/60)).'h' ?><?php if ($lateness->duration%60) echo sprintf('%02u', $lateness->duration%60).'mn' ?></strong>
	<?php if ($lateness->motive) : ?>
		&mdash;
		<?php echo $this->translate('Motive', 'ppit-studies', $context->getLocale()) ?>:
		<strong><?php echo $context->getConfig('absence/property/motive')['modalities'][$lateness->motive][$context->getLocale()] ?></strong>
	<?php endif;?>
	<?php if ($lateness->observations) : ?>
		<br><?php echo $lateness->observations ?>
	<?php endif;?>
	</div>

	<?php $first=false; endforeach;?>
<hr/>
</div>
<?php endif;?>
