<style>
table.note-report {
	font-size: 0.83em;
	border-width:1px; 
 	border-style:solid; 
	border-color:gray;
}
table.note-report caption { 
	font-size:1.5em; 
	padding:1em 0 0.5em 1em;
}
table.note-report th {
	color: #666;
//    font-size:0.83em;
	text-align: center;
	border-width:1px; 
 	border-style:solid; 
	border-color:gray;
	background-color:#DDD;
}

table.note-report td {
	color: #666;
//	font-size: 0.83em;
	border-width:1px; 
 	border-style:solid; 
	border-color:gray;
}

table.note-report td.subject {
	font-weight: bold;
}

table.note-report tr.period {
	background-color:#DDD;
}
</style>

      <div class="modal-header">
        <h5 class="modal-title"><?php echo $this->translate('Absence/Lateness', 'ppit-studies', $context->getLocale()) ?></h5>
        <div>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close" title="<?php echo $this->translate('Cancel', 'ppit-core', $context->getLocale()) ?>">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
      <div class="modal-body">
        <div class="container">

<?php foreach ($periods as $periodId => $period) : ?>
	<?php 
	$params = explode('.', $periodId); 
	$school_year = $params[0];
	$school_period = $params[1];
	$params = ['category' => 'absence', 'account_id' => $account->id, 'school_year' => $school_year];
	if ($school_period) $params['school_period'] = $school_period;
	?>
	
    <!--Card content-->
<div class="card-block" style="color: #686868">
    <!--Title-->
    <h4 class="card-title" style="text-align: center">
		<?php echo $context->localize($context->getConfig('student/property/school_year')['labels']) ?>:
		<?php echo $context->localize($context->getConfig('student/property/school_year')['modalities'][$school_year]) ?> &mdash;
		<?php if ($school_period) echo $context->localize($context->getConfig('student/property/school_period')['modalities'][$school_period]) ?>
	</h4>
	<!--Text-->
		<div><a href="<?php echo $this->url('student/download', $params, ['query' => ['start_date' => $start_date, 'end_date' => $end_date]]) ?>"><?php echo $this->translate('Download in PDF format', 'ppit-studies', $context->getLocale()) ?></a></div>
		<table class="table note-report">
			<tr>
				<th><?php echo $this->translate('Type', 'ppit-core', $context->getLocale()) ?></th>
				<th><?php echo $this->translate('Subject', 'ppit-studies', $context->getLocale()) ?></th>
				<th><?php echo $this->translate('Date', 'ppit-core', $context->getLocale()) ?></th>
				<th><?php echo $this->translate('Motive', 'ppit-studies', $context->getLocale()) ?></th>
				<th><?php echo $this->translate('Observations', 'ppit-studies', $context->getLocale()) ?></th>
			</tr>
	<?php $first=true; foreach ($period as $absLate) : ?>
			<tr>
				<td class="subject">
					<?php echo $this->translate((($absLate['category'] == 'absence') ? 'Absence' : 'Lateness'), 'ppit-studies', $context->getLocale()) ?>
				</td>
				<td class="subject">
					<?php echo ($absLate['subject']) ? $context->localize($context->getConfig('student/property/school_subject')['modalities'][$absLate['subject']]) : '' ?>
				</td>
		<?php if ($absLate['end_date'] > $absLate['begin_date']) : ?>
				<td><?php echo $this->translate('From the', 'ppit-studies', $context->getLocale()).' '.$context->decodeDate($absLate['begin_date']).'<br>'.$this->translate('to the', 'ppit-studies', $context->getLocale()).' '.$context->decodeDate($absLate['end_date']) ?></td>
		<?php else : ?>
				<td><?php echo $context->decodeDate($absLate['begin_date']) ?></td>
		<?php endif;?>
				<td><?php if ($absLate['motive']) echo $context->localize($context->getConfig('absence/property/motive')['modalities'][$absLate['motive']]) ?></td>
				<td><?php echo $absLate['observations'] ?></td>
			</tr>
	<?php endforeach;?>
		</table>
</div>
<?php endforeach;?>

  </div>
</div>