<?php if ($message == 'OK') : ?>

<!-- Global message -->
<div id="message">
  <h5 class="alert alert-success my-3 text-center"><?php echo $this->translate('Your request has been registered', 'ppit-core', $context->getLocale()) ?></h5>
</div>

<?php endif;?>

<?php if ($error == 'Duplicate') : ?>

<!-- Duplicate error -->
<div class="alert alert-danger my-3 text-center"><?php echo $this->translate('This record already exist', 'ppit-core', $context->getLocale()) ?></div>

<?php endif;?>

<?php if ($error == 'Isolation') : ?>

<!-- Isolation error -->
<div class="alert alert-danger my-3 text-center"><?php echo $this->translate('The database has evolved in the meantime, please input again', 'ppit-core', $context->getLocale()) ?></div>

<?php endif;?>

<?php if ($error == 'Consistency') : ?>

<!-- Consistency error -->
<div class="alert alert-danger my-3 text-center"><?php echo $this->translate('The data are not consistent', 'ppit-core', $context->getLocale()) ?></div>

<?php endif;?>

<!-- CSRF -->
<?php $element = $csrfForm->get('csrf') ?>
<div class="form-group">
  <?php echo $this->formElement($element) ?>
<?php if ($this->formElementErrors($element)) : ?>
  <h5 class="alert alert-danger my-3 text-center"><?php echo $this->translate('The form has expired, please input again', 'ppit-core', $context->getLocale()) ?></h5>
<?php endif;?>
</div>

<?php if ($message != 'OK') : ?>
<div class="form-group row">
  <div class="col-sm-5">&nbsp;</div>
  <div class="col-sm-7">
    <input name="submit" id="up-submit-button" class="btn btn-warning" value="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
  </div>
</div>
<?php endif;?>

<?php if ($message == 'OK') $isDisabled = true; else $isDisabled = false; ?>

<!-- Title -->
<div class="form-group row" id="title_group">
  <label class="col-sm-5 col-form-label">* <?php echo $this->translate('Object', 'ppit-commitment', $context->getLocale()) ?></label>
  <div class="col-sm-7">
    <textarea class="form-control" id="title" <?php if ($isDisabled) echo 'disabled="disabled"'?>><?php echo $event->title ?></textarea>
    <div class="invalid-feedback" id="title_error"></div>
  </div>
</div>
		
<!-- Begin time -->
<?php $beginDate = ($event->begin_time) ? substr($event->begin_time, 0, 10) : Date('Y-m-d') ?>
<input type="hidden" id="begin_date" />
<div class="form-group row" id="input_begin_date_group">
  <label class="col-sm-5 col-form-label"><?php echo $this->translate('Begin', 'ppit-commitment', $context->getLocale()) ?></label>
  <div class="col-sm-7">
    <input class="form-control" id="input_begin_date" value="<?php echo $context->decodeDate($beginDate) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
    <div class="invalid-feedback" id="input_begin_date_error"></div>
  </div>
</div>
<div class="form-group row">
  <label class="col-sm-5 col-form-label"></label>
  <div class="col-sm-3">
    <select class="form-control" id="begin_h" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
<?php for ($i = 0; $i < 24; $i++) : ?>
      <option value="<?php echo sprintf('%02d', $i) ?>" <?php if ((int)substr($event->begin_time, 11,2) == $i) echo ' selected="selected"' ?>><?php echo sprintf('%02d', $i) ?></option>
<?php endfor;?>
    </select>
  </div>
  <label class="col-sm-1 col-form-label"></label>
  <div class="col-sm-3">
    <select class="form-control" id="begin_m" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
<?php for ($i = 0; $i < 60; $i++) : ?>
      <option value="<?php echo sprintf('%02d', $i) ?>" <?php if ((int)substr($event->begin_time, 14,2) == $i) echo ' selected="selected"' ?>><?php echo sprintf('%02d', $i) ?></option>
<?php endfor;?>
    </select>
  </div>
</div>

<!-- End time -->
<?php $endDate = ($event->end_time) ? substr($event->end_time, 0, 10) : null ?>
<input type="hidden" id="end_date" />
<div class="form-group row" id="input_end_date_group">
  <label class="col-sm-5 col-form-label"><?php echo $this->translate('Display end', 'ppit-commitment', $context->getLocale()) ?></label>
  <div class="col-sm-7">
    <input class="form-control" id="input_end_date" value="<?php echo $context->decodeDate($endDate) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
    <div class="invalid-feedback" id="input_end_date_error"></div>
  </div>
</div>
<div class="form-group row">
  <label class="col-sm-5 col-form-label"></label>
  <div class="col-sm-3">
    <select class="form-control" id="end_h" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
<?php for ($i = 0; $i < 24; $i++) : ?>
      <option value="<?php echo sprintf('%02d', $i) ?>" <?php if ((int)substr($event->end_time, 11,2) == $i) echo ' selected="selected"' ?>><?php echo sprintf('%02d', $i) ?></option>
<?php endfor;?>
    </select>
  </div>
  <label class="col-sm-1 col-form-label"></label>
  <div class="col-sm-3">
    <select class="form-control" id="end_m" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
<?php for ($i = 0; $i < 60; $i++) : ?>
      <option value="<?php echo sprintf('%02d', $i) ?>" <?php if ((int)substr($event->end_time, 14,2) == $i) echo ' selected="selected"' ?>><?php echo sprintf('%02d', $i) ?></option>
<?php endfor;?>
    </select>
  </div>
</div>

<!-- Location -->
<div class="form-group row" id="location_group">
  <label class="col-sm-5 col-form-label">* <?php echo $this->translate('Location', 'ppit-commitment', $context->getLocale()) ?></label>
  <div class="col-sm-7">
    <input class="form-control" id="location" value="<?php echo $event->location ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
    <div class="invalid-feedback" id="location_error"></div>
  </div>
</div>

<hr/>
		
<!-- Comment -->
<?php if (!$isDisabled) : ?>
<div class="form-group row" id="comment_group">
  <label class="col-sm-5 col-form-label"><?php echo $this->translate('Comment (non visible to the student)', 'ppit-studies', $context->getLocale()) ?></label>
  <div class="col-sm-7">
    <textarea class="form-control" id="comment"></textarea>
    <div class="invalid-feedback" id="comment_error"></div>
  </div>
</div>
<?php endif;?>

<?php if ($message != 'OK') : ?>
<div class="form-group row">
  <div class="col-sm-5">&nbsp;</div>
  <div class="col-sm-7">
    <input name="submit" id="down-submit-button" class="btn btn-warning" value="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
  </div>
</div>
<?php endif;?>
