<div class="panel panel-default">
	<div class="panel-heading" style="background: #AFAFFC; color: #FFFFFF">
		<strong><?php echo $this->translate('Add a student file', 'ppit-studies', $context->getLocale()) ?></strong>
		<div class="btn-group pull-right">
			<button type="button" class="btn btn-default" title="<?php echo $this->translate('Close', 'ppit-core', $context->getLocale()) ?>" id="remove-anchor">
				<span class="glyphicon glyphicon-remove"></span>
			</button>
		</div>
	</div>
	<div class="panel-body">

<!-- Load the form header -->
<?php echo $this->partial('/partials/form-header.phtml', array(
			'update_time' => $student->update_time,
			'message' => $message,
			'error' => $error,
			'csrfForm' => $csrfForm,
			'context' => $context,
));
?>

<?php if ($message == 'OK') $isDisabled = true; else $isDisabled = false; ?>

<!-- Center -->
		<?php $place_id = ($student->place_id) ? $student->place_id : $context->getPlace()->id ?>
		<div class="form-group" id="place_id_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Center', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select name="place_id" id="place_id" class="form-control" <?php /*if (isset($isDisabled) && $isDisabled)*/ echo ' disabled ="disabled"' ?>>
					<option value=""><-- <?php echo $this->translate('Please select a value', 'ppit-core', $context->getLocale()) ?> --></option>
<?php foreach ($places as $place) : ?>
		    		<option value="<?php echo $place->id ?>" <?php if ($place->id == $place_id) echo ' selected="selected"' ?>><?php echo $place->name ?></option>
<?php endforeach;?>
		    	</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="place_id_error"></p></div>
		</div>

<!-- First name -->
		<div class="form-group" id="n_first_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('First name', 'ppit-contact', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="n_first" id="n_first" class="form-control" value="<?php echo $student->studentContact->n_first ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="n_first_error"></p></div>
		</div>

<!-- Last name -->
		<div class="form-group" id="n_last_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Last name', 'ppit-contact', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="n_last" id="n_last" class="form-control" value="<?php echo $student->studentContact->n_last ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="n_last_error"></p></div>
		</div>

<!-- Photo -->
		<div class="form-group" id="place_id_group">
			<label class="col-sm-5 control-label"></label>
			<div class="col-sm-7">
				<img height="150" src="<?php echo $this->url('vcard/photo', array('id' => $student->student_contact_id)) ?>"/>
			</div>
			<div class="col-sm-12"><p class="help-block" id="place_id_error"></p></div>
		</div>
<?php if ($message != 'OK') : ?>
		<div class="photo-group">
			<label class="col-sm-5 control-label"></label>
			<div class="col-sm-7">
				<input type="file" name="photo" id="photo" class="form-control" />
			</div>
		</div>
<?php endif; ?>
		<div>&nbsp;</div>
		
<!-- Email -->
		<div class="form-group" id="email_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Email', 'ppit-contact', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="email" id="email" class="form-control" value="<?php echo $student->studentContact->email ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="email_error"></p></div>
		</div>
		
<!-- School year -->
		<?php $school_year = ($student->school_year) ? $student->school_year : $config['ppitStudies']['currentSchoolYear'] ?>
		<div class="form-group" id="input_school_year_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('School year', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input type="hidden" name="school_year" id="school_year" />
				<input name="input_school_year" id="input_school_year" class="form-control" value="<?php echo $school_year ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="input_school_year_error"></p></div>
		</div>

<!-- Class -->
		<div class="form-group" id="class_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Class', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select name="class" id="class" class="form-control" <?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
					<option value=""><-- <?php echo $this->translate('Please select a value', 'ppit-core', $context->getLocale()) ?> --></option>
<?php foreach ($config['ppitStudies']['classes'] as $class) : ?>
		    		<option value="<?php echo $class ?>" <?php if ($class == $student->class) echo ' selected="selected"' ?>><?php echo $class ?></option>
<?php endforeach;?>
		    	</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="class_error"></p></div>
		</div>

<!-- Specialty -->
		<div class="form-group" id="specialty_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Specialty', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select name="specialty" id="specialty" class="form-control" <?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
					<option value=""></option>
<?php foreach ($config['ppitStudies']['specialties'] as $specialty) : ?>
		    		<option value="<?php echo $specialty ?>" <?php if ($specialty == $student->specialty) echo ' selected="selected"' ?>><?php echo $specialty ?></option>
<?php endforeach;?>
		    	</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="specialty_error"></p></div>
		</div>

<!-- Boarding school -->
		<div class="form-group" id="boarding_school_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Boarding school option', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select name="boarding_school" id="boarding_school" class="form-control" <?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
					<option value=""></option>
<?php foreach ($config['ppitStudies']['boardingSchool'] as $boardingSchool) : ?>
		    		<option value="<?php echo $boardingSchool ?>" <?php if ($boardingSchool == $student->boarding_school) echo ' selected="selected"' ?>><?php echo $boardingSchool ?></option>
<?php endforeach;?>
		    	</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="boarding_school_error"></p></div>
		</div>

<!-- Emergency phone 1 -->
		<div class="form-group" id="emergency_phone_1_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Emergency phone', 'ppit-studies', $context->getLocale()) ?> 1</label>
			<div class="col-sm-7">
				<input name="emergency_phone_1" id="emergency_phone_1" class="form-control" value="<?php echo $student->emergency_phone_1 ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="emergency_phone_1_error"></p></div>
		</div>

<!-- Emergency phone 2 -->
		<div class="form-group" id="emergency_phone_2_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Emergency phone', 'ppit-studies', $context->getLocale()) ?> 2</label>
			<div class="col-sm-7">
				<input name="emergency_phone_2" id="emergency_phone_2" class="form-control" value="<?php echo $student->emergency_phone_2 ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="emergency_phone_2_error"></p></div>
		</div>
		
<!-- Birth date -->
		<div class="form-group" id="input_birth_date_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Birth date', 'ppit-contact', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input type="hidden" name="birth_date" id="birth_date" />
				<input name="input_birth_date" id="input_birth_date" class="form-control" value="<?php echo $context->decodeDate($student->studentContact->birth_date) ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="input_birth_date_error"></p></div>
		</div>
		
<!-- Place of birth -->
		<div class="form-group" id="place_of_birth_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Place of birth', 'ppit-contact', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="place_of_birth" id="place_of_birth" class="form-control" value="<?php echo $student->studentContact->place_of_birth ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="place_of_birth_error"></p></div>
		</div>
		
<!-- Nationality -->
		<div class="form-group" id="nationality_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Nationality', 'ppit-contact', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="nationality" id="nationality" class="form-control" value="<?php echo $student->studentContact->nationality ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="nationality_error"></p></div>
		</div>
		
<!-- Sisters & brothers -->
		<div class="form-group" id="sisters_brothers_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Sisters & brothers', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="sisters_brothers" id="sisters_brothers" class="form-control" value="<?php echo $student->sisters_brothers ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="sisters_brothers_error"></p></div>
		</div>

<!-- Parents marital status -->
		<div class="form-group" id="parents_marital_status_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Parents marital status', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select name="parents_marital_status" id="parents_marital_status" class="form-control" <?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
					<option value=""></option>
<?php foreach ($config['ppitStudies']['maritalStatuses'] as $maritalStatus) : ?>
		    		<option value="<?php echo $maritalStatus ?>" <?php if ($maritalStatus == $student->parents_marital_status) echo ' selected="selected"' ?>><?php echo $maritalStatus ?></option>
<?php endforeach;?>
		    	</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="parents_marital_status_error"></p></div>
		</div>
		
<!-- Health insurance -->
		<div class="form-group" id="health_insurance_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Health insurance', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="health_insurance" id="health_insurance" class="form-control" value="<?php echo $student->health_insurance ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="health_insurance_error"></p></div>
		</div>
		
<!-- Id card, passport -->
		<div class="form-group" id="id_card_passport_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Id card, passport', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="id_card_passport" id="id_card_passport" class="form-control" value="<?php echo $student->id_card_passport ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="id_card_passport_error"></p></div>
		</div>
		
<!-- Medical examination date -->
		<div class="form-group" id="input_medical_examination_date_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Medical examination date', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input type="hidden" name="medical_examination_date" id="medical_examination_date" class="form-control" />
				<input name="input_medical_examination_date" id="input_medical_examination_date" class="form-control" value="<?php echo $context->decodeDate($student->medical_examination_date) ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="input_medical_examination_date_error"></p></div>
		</div>
		
<!-- Previous class -->
		<div class="form-group" id="previous_class_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Previous class', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="previous_class" id="previous_class" class="form-control" value="<?php echo $student->previous_class ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="previous_class_error"></p></div>
		</div>
		
<!-- Previous school -->
		<div class="form-group" id="previous_school_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Previous school', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="previous_school" id="previous_school" class="form-control" value="<?php echo $student->previous_school ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="previous_school_error"></p></div>
		</div>
		
<!-- Main school -->
		<div class="form-group" id="main_school_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Main school', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="main_school" id="main_school" class="form-control" value="<?php echo $student->main_school ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="main_school_error"></p></div>
		</div>

<!-- Previous quarter average -->
		<div class="form-group" id="input_previous_quarter_average_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Previous quarter average (on 20)', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input type="hidden" name="previous_quarter_average" id="previous_quarter_average" />
				<input name="input_previous_quarter_average" id="input_previous_quarter_average" class="form-control" value="<?php if ($student->previous_quarter_average) echo $context->formatFloat($student->previous_quarter_average, 2) ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="input_previous_quarter_average_error"></p></div>
		</div>
		
<!-- Orientation -->
		<div class="form-group" id="orientation_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Orientation', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="orientation" id="orientation" class="form-control" value="<?php echo $student->orientation ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="orientation_error"></p></div>
		</div>
		
<!-- Mother tongue -->
		<div class="form-group" id="mother_tongue_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Mother tongue', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="mother_tongue" id="mother_tongue" class="form-control" value="<?php echo $student->mother_tongue ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="mother_tongue_error"></p></div>
		</div>
		
<!-- Living language 1 -->
		<div class="form-group" id="living_language_1_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Living language 1', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="living_language_1" id="living_language_1" class="form-control" value="<?php echo $student->living_language_1 ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="living_language_1_error"></p></div>
		</div>
		
<!-- Living language 2 -->
		<div class="form-group" id="living_language_2_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Living language 2', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="living_language_2" id="living_language_2" class="form-control" value="<?php echo $student->living_language_2 ?>"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="living_language_2_error"></p></div>
		</div>
		
<!-- Observations -->
		<div class="form-group" id="observations_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Observations', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<textarea name="observations" id="observations" rows="3" class="form-control" <?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>><?php echo $student->observations ?></textarea>
			</div>
			<div class="col-sm-12"><p class="help-block" id="observations_error"></p></div>
		</div>

<?php if ($message == 'OK') : ?>

<!-- Foot return link -->
			<div class="form-group" id="foot_return_link">
				<div class="col-sm-4">&nbsp;</div>
				<div class="col-sm-8">
					<button type="button" class="btn btn-default" title="<?php echo $this->translate('Return', 'ppit-core', $context->getLocale()) ?>" id="return-anchor">
						<span><?php echo $this->translate('Return', 'ppit-core', $context->getLocale()) ?></span>
					</button>
				</div>
			</div>

<?php else : ?>
		
<!-- Submit button -->
		    <div class="form-group">
				<div class="col-sm-4">&nbsp;</div>
				<div class="col-sm-8">
					<input name="submit" type="submit" id="submit-button" class="btn btn-warning" value="<?php echo $this->translate('Confirm', 'ppit-core', $context->getLocale()) ?>">
					&nbsp;&nbsp;
					<button type="button" class="btn btn-default" title="<?php echo $this->translate('Cancel', 'ppit-core', $context->getLocale()) ?>" id="cancel-anchor">
						<span><?php echo $this->translate('Cancel', 'ppit-core', $context->getLocale()) ?></span>
					</button>
				</div>
			</div>
<?php endif;?>

		</form>
	</div>
</div>

