<div class="panel panel-default">
	<div class="panel-heading" style="background:  <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<strong><?php echo $account->name ?></strong>
		
<?php if ($context->isDemoModeActive()) : ?>
		<a class="tip" href="#"
title="
<h4><?php echo $this->translate('Page d\'accueil élève', 'ppit-studies', $context->getLocale()) ?></h4>
<p><?php echo $this->translate("Ce panneau est la page d'accueil de l'élève ou du parent connecté. Il est accessible, pour contrôle, à l'équipe pédagogique et au personnel du centre, à partir du bouton <san class='glyphicon glyphicon-zoom-in' /> en regard de chaque élève de la liste.", 'ppit-studies', $context->getLocale()) ?></p>
<p><?php echo $this->translate("Notez l'organisation de l'information en onglets thématiques. Le personnel accède aux seuls onglets pour lesquels il est habilité. Par exemple, seul le personnel médical ou sportif est habilité aux informations médicales.", 'ppit-studies', $context->getLocale()) ?></p>
">
		    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
		</a>
<?php endif;?>	
		
	</div>
	<div class="panel-body">

<!-- Banner -->
		<div style="text-align: center">
<?php if ($account->place->banner_href) : ?>
			<a href="<?php echo $account->place->banner_href ?>" rel="follow" target="_blank">
<?php endif;?>
				<img width="100%" src="<?php echo $this->basePath($account->place->banner_src) ?>" alt="<?php echo $context->getInstance()->caption ?> banner" />
<?php if ($account->place->banner_href) : ?>
			</a>
<?php endif;?>
		</div>

		<div>&nbsp;</div>

<!-- Photo -->
		<div style="text-align: center">
<?php if ($account->place->logo_href) : ?>
			<a href="<?php echo $account->place->logo_href ?>" rel="follow" target="_blank">
<?php endif;?>
				<img height="60" src="<?php echo $this->basePath($account->place->logo_src) ?>" alt="<?php echo $context->getInstance()->caption ?> logo" />
<?php if ($account->place->logo_href) : ?>
			</a>
<?php endif;?>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<img height="150" src="<?php echo $this->url('vcard/photo', array('id' => $account->contact_1_id)) ?>"/>
		</div>

		<div>&nbsp;</div>
				
		<ul class="nav nav-tabs">
<?php if ($context->hasRole('student') || $context->hasRole('manager')) : ?>
		  <li data-toggle="tab" class="student-tab active" id="news_flash-tab"><a><?php echo $this->translate('Planning', 'ppit-studies', $context->getLocale()) ?></a></li>
<?php endif;?>

<?php if ($context->hasRole('student') || $context->hasRole('manager') || $context->hasRole('coach')) : ?>
		  <li data-toggle="tab" class="student-tab"><a id="sport-tab"><?php echo $this->translate('Sport', 'ppit-studies', $context->getLocale()) ?></a></li>
<?php endif;?>

<?php if ($context->hasRole('student') || $context->hasRole('manager') || $context->hasRole('teacher')) : ?>
		  <li data-toggle="tab" class="student-tab"><a id="schooling-tab"><?php echo $this->translate('Schooling', 'ppit-studies', $context->getLocale()) ?></a></li>
<?php endif;?>
<!--
<?php if ($context->hasRole('student') || $context->hasRole('manager') || $context->hasRole('boarding_school_headmaster')) : ?>
		  <li data-toggle="tab" class="student-tab"><a id="boarding-school-tab"><?php //echo $this->translate('Boarding school', 'ppit-studies', $context->getLocale()) ?></a></li>
<?php endif;?>

<?php if ($context->hasRole('student') || $context->hasRole('manager') || $context->hasRole('medical')) : ?>
		  <li data-toggle="tab" class="student-tab"><a id="medical-tab"><?php //echo $this->translate('Medical', 'ppit-studies', $context->getLocale()) ?></a></li>
<?php endif;?> -->

<?php if ($context->hasRole('student') || $context->hasRole('manager')) : ?>
		  <li data-toggle="tab" class="student-tab" id="file-tab"><a><?php echo $this->translate('Student file', 'ppit-studies', $context->getLocale()) ?></a></li>
<?php endif;?>
		</ul>

		<div class="tab-content">
			<div class="tab-pane fade in active" id="news_flash-panel"></div>
		</div>
	</div>
</div>