<?php 
header('Content-Type: text/csv; charset=utf-8');
header("Content-disposition: filename=contacts-<?php echo date('Y-m-d').csv");
echo "\xEF\xBB\xBF";
 
echo
$this->translate('Status', 'ppit-core', $context->getLocale()).";".
$this->translate('School year', 'ppit-studies', $context->getLocale()).";".
$this->translate('Emergency phone', 'ppit-studies', $context->getLocale()).' 1'.";".
$this->translate('Emergency phone', 'ppit-studies', $context->getLocale()).' 2'.";".
$this->translate('Emergency email', 'ppit-studies', $context->getLocale()).";".
$this->translate('Sport', 'ppit-studies', $context->getLocale()).";".
$this->translate('Category', 'ppit-studies', $context->getLocale()).";".
$this->translate('Class', 'ppit-studies', $context->getLocale()).";".
$this->translate('Specialty', 'ppit-studies', $context->getLocale()).";".
$this->translate('Boarding school', 'ppit-studies', $context->getLocale()).";".
$this->translate('First name', 'ppit-contact', $context->getLocale()).";".
$this->translate('Last name', 'ppit-contact', $context->getLocale()).";".
$this->translate('Email', 'ppit-contact', $context->getLocale()).";".
$this->translate('Cellular', 'ppit-contact', $context->getLocale()).";".
$this->translate('Sex', 'ppit-contact', $context->getLocale()).";".
$this->translate('Birth date', 'ppit-contact', $context->getLocale()).";".
$this->translate('Place of birth', 'ppit-contact', $context->getLocale()).";".
$this->translate('Nationality', 'ppit-contact', $context->getLocale()).";".
$this->translate('Sisters & brothers', 'ppit-studies', $context->getLocale()).";".
$this->translate('Parents marital status', 'ppit-studies', $context->getLocale()).";".
$this->translate('Health insurance', 'ppit-studies', $context->getLocale()).";".
$this->translate('Id card, passport', 'ppit-studies', $context->getLocale()).";".
$this->translate('Medical examination date', 'ppit-studies', $context->getLocale()).";".
$this->translate('Observations', 'ppit-studies', $context->getLocale()).";".
$this->translate('Licence holder', 'ppit-studies', $context->getLocale()).";".
$this->translate('Level', 'ppit-studies', $context->getLocale()).";".
$this->translate('Results', 'ppit-studies', $context->getLocale()).";".
$this->translate('Left/right handed', 'ppit-studies', $context->getLocale()).";".
$this->translate('Main post', 'ppit-studies', $context->getLocale()).";".
$this->translate('Secondary post', 'ppit-studies', $context->getLocale()).";".
$this->translate('Club', 'ppit-studies', $context->getLocale()).";".
$this->translate('Coach', 'ppit-studies', $context->getLocale()).";".
$this->translate('Coach: phone', 'ppit-studies', $context->getLocale()).";".
$this->translate('Weight', 'ppit-studies', $context->getLocale()).";".
$this->translate('Height', 'ppit-studies', $context->getLocale()).";".
$this->translate('Wear size', 'ppit-studies', $context->getLocale()).";".
$this->translate('Shoe size', 'ppit-studies', $context->getLocale()).";".
$this->translate('Medical histories', 'ppit-studies', $context->getLocale()).";".
$this->translate('Medical checkup', 'ppit-studies', $context->getLocale()).";".
$this->translate('Muscle checkup', 'ppit-studies', $context->getLocale()).";".
$this->translate('Streatching checkup', 'ppit-studies', $context->getLocale()).";".
$this->translate('ECG', 'ppit-studies', $context->getLocale()).";".
$this->translate('Oro-dental checkup', 'ppit-studies', $context->getLocale()).";".
$this->translate('Primary doctor', 'ppit-studies', $context->getLocale()).";".
"\n";

foreach ($students as $student) {
	echo $config['ppitStudies']['status'][$student->status]['labels'][$context->getLocale()].";";
	echo $student->school_year.";";
	echo $student->emergency_phone_1.";";
	echo $student->emergency_phone_2.";";
	echo $student->emergency_email.";";
	echo $student->sport.";";
	echo $student->category.";";
	echo $student->class.";";
	echo $student->specialty.";";
	echo $student->boarding_school.";";
	echo $student->n_title.";";
	echo $student->n_first.";";
	echo $student->n_last.";";
	echo $student->email.";";
	echo $student->tel_cell.";";
	echo $student->sex.";";
	echo $context->decodeDate($student->birth_date).";";
	echo $student->place_of_birth.";";
	echo $student->nationality.";";
	echo $student->sisters_brothers.";";
	echo $student->parents_marital_status.";";
	echo $student->health_insurance.";";
	echo $student->id_card_passport.";";
	echo $student->medical_examination_date.";";
	echo $student->observations.";";
	echo $student->licence_holder.";";
	echo $student->level.";";
	echo $student->results.";";
	echo $student->left_right_handed.";";
	echo $student->main_post.";";
	echo $student->secondary_post.";";
	echo $student->club.";";
	echo $student->coach_name.";";
	echo $student->coach_tel.";";
	echo $student->weight.";";
	echo $student->height.";";
	echo $student->wear_size.";";
	echo $student->shoe_size.";";
	echo $student->medical_histories.";";
	echo $student->medical_checkup.";";
	echo $student->muscle_checkup.";";
	echo $student->streatching_checkup.";";
	echo $student->ecg.";";
	echo $student->oro_dental_checkup.";";
	echo $student->primary_doctor.";";
	echo "\n";
}
