<!-- 
/**
 * PpitCore V1.0 (https://github.com/p-pit/PpitCore)
 *
 * @link      https://github.com/p-pit/PpitCore
 * @copyright Copyright (c) 2016 Bruno Lartillot
 * @license   https://github.com/p-pit/PpitCore/blob/master/license.txt GNU-GPL license
 */
-->

<hr>
<h4 style="text-align: center">
	<strong><?php echo $this->translate('Student file', 'ppit-studies', $context->getLocale()) ?></strong>
</h4>
	
		<div class="form-group" id="attachment_group">
			<label class="col-sm-5 control-label">
				<?php echo $this->translate('Attachment', 'ppit-contact', $context->getLocale()) ?>
			</label>
			<div class="col-sm-6">
				<select class="form-control" id="attachment">
					<option />
		<?php foreach ($documentList as $document) : ?>
					<option value="<?php echo $document ?>"><?php echo $document ?></option>
		<?php endforeach;?>
				</select>
			</div>
			<div class="col-sm-1"><span id="attachment_link"/></div>
			<div class="col-sm-12"><p class="help-block" id="attachment_error"></p></div>
		</div>
	</div>
</form