<input type="hidden" id="structured-document-download-href" value="<?php echo $this->url('student/downloadAttendance', ['account_id' => $account_id, 'start_date' => $start_date, 'end_date' => $end_date]) ?>" />

<a id="structured-document-download-anchor" role="button">
  <?php echo $this->translate('Download the PDF document', 'ppit-commitment', $context->getLocale()) ?>
</a>

<?php echo $html ?>