<!-- 
/**
 * PpitCore V1.0 (https://github.com/p-pit/PpitCore)
 *
 * @link      https://github.com/p-pit/PpitCore
 * @copyright Copyright (c) 2016 Bruno Lartillot
 * @license   https://github.com/p-pit/PpitCore/blob/master/license.txt GNU-GPL license
 */
-->

<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title"><?php echo $this->translate('Grouped actions', 'ppit-core', $context->getLocale()) ?></h5>
      <div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" title="<?php echo $this->translate('Cancel', 'ppit-core', $context->getLocale()) ?>">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
    <div class="modal-body">

        <input type="hidden" id="group-nb-criteria" value="<?php //echo count($criteria) ?>" />

<?php /*$i = 0; foreach ($criteria as $criterionId => $criterionValue) : ?>
	<?php
	$property = $context->getConfig('core_account/p-pit-studies/property/'.$criterionId);
	if ($property['definition'] != 'inline') $property = $context->getConfig($property['definition']);
	$label = $context->localize($property['labels']);
	if ($criterionId == 'place_id') $value = $places[$criterionValue]->caption; 
	elseif ($property['type'] == 'select') $value = $context->localize($property['modalities'][$criterionValue]);
	else $value = $criterionValue;*/
	?>
        <input type="hidden" id="group-criterion-id_<?php //echo $i ?>" value="<?php //echo $criterionId ?>" />
        <input type="hidden" id="group-criterion_<?php //echo $i ?>" value="<?php //echo $value ?>" />
	
<?php //$i++; endforeach;?>

        <div class="card my-3">
          <div class="card-body">
            
            <h5 class="card-title text-muted"><?php echo $this->translate('Selected students', 'ppit-studies', $context->getLocale()) ?></h5>

            <input type="hidden" id="group-nb-account" value="<?php echo count($accounts) ?>" />

<?php $i = 0; foreach ($accounts as $account) : ?>
	
            <input type="hidden"  id="group-account_<?php echo $i ?>" value="<?php echo $account->id ?>" />

            <div class="form-group row">
              <label class="col-sm-5 control-label">&nbsp;</label>
              <div class="col-sm-7">
                <input class="form-control" disabled="disabled" value="<?php echo $account->contact_1->n_fn ?>" />
              </div>
            </div>

<?php $i++; endforeach;?>
      
          </div>
        </div>
        
        <div class="card my-3">
           
        <div class="card-body">

		<div class="group-panel" id="schooling-panel">
    <ul class="nav nav-pills nav-justified">
      <li class="nav-item">
        <a class="nav-link action-btn" href="#" id="note-add-anchor" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
         <span class="fas fa-plus"></span>&nbsp; <?php echo $this->translate('Teaching content', 'ppit-studies', $context->getLocale()) ?>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link action-btn" href="#" <?php if (!$context->hasRole('admin') && !$current_school_period) echo 'disabled' ?> id="note-evaluation-anchor" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('Add an evaluation', 'ppit-studies', $context->getLocale()) ?>">
          <span class="fas fa-plus"></span>&nbsp;<?php echo $this->translate('Evaluation', 'ppit-studies', $context->getLocale()) ?>
        </a>
      </li>
<?php if (false) : // ($context->hasRole('admin')) : ?>
      <li class="nav-item">
        <a class="nav-link action-btn" href="#" id="evaluation-add-anchor" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
          <?php echo $this->translate('Evaluation avant 2019-2020', 'ppit-studies', $context->getLocale()) ?>
        </a>
      </li>
<?php endif;?>
    </ul>
		</div>

        <div id="grouped-action-panel"></div>
	    </div>
        </div>
	</div>
  </div>
</div>
	