      <div class="modal-header">
        <h5 class="modal-title"><?php echo $this->translate('Homework notebook', 'ppit-studies', $context->getLocale()) ?> &mdash; <?php echo $context->localize($context->getConfig('student/property/school_subject')['modalities'][$subject]) ?></h5>
        <div>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close" title="<?php echo $this->translate('Cancel', 'ppit-core', $context->getLocale()) ?>">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
      <div class="modal-body">
        <div class="container">
	      <div>
	        <div class="text-center text-muted font-weight-bold">
<?php if ($type == 'done-work') : ?>
	          <?php echo $this->translate('Done the', 'ppit-studies', $context->getLocale()).' '.$context->decodeDate($date) ?>
<?php elseif (in_array($type, ['todo-work', 'event'])) : ?>
            <?php echo $this->translate('For the', 'ppit-studies', $context->getLocale()).' '.$context->decodeDate($date) ?>
<?php endif;?>
	        </div>
          
<?php foreach ($notes as $note) : ?>
	        <div class="text-muted" id="student-homework-observations"><?php echo $note->observations ?></div>
  <?php if ($note->properties['documents']) : ?>
	        <div>
	          <?php echo $this->translate('Attachment', 'ppit-commitment', $context->getLocale()) ?>:
    <?php foreach ($note->properties['documents'] as $document_id => $document) : ?>
	          <a href="<?php echo $this->url('document/download', ['id' => $document_id]) ?>" target="_blank">
	            <?php echo $document['name'] ?>
	          </a>
    <?php endforeach;?>
	        </div>
  <?php endif;?>

<?php endforeach;?>

	      </div>
        </div>
      </div>

