
<!-- Main menu -->
<?php echo $this->partial('partials/core-menu.phtml') ?>

<div class="container-fluid">

	<!-- Main panel -->
	<div class="row">
	    <div class="col-md-12 ppit-panel" id="index_panel"></div>
	</div>

</div>

<!-- Modals -->

<!-- Form opening tag -->
<div class="modal fade" id="modalForm" tabindex="-1" role="dialog" data-backdrop="static" aria-labelledby="modalFormLabel" aria-hidden="true"></div>

<!-- document modal -->
<div class="modal fade" id="shared-document-modal" tabindex="-1" role="dialog" data-backdrop="static" aria-labelledby="modalFormLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
	<div class="modal-content">
	  <div class="modal-header">
	    <h5 class="modal-title"><?php echo $this->translate('Shared documents', 'ppit-core', $context->getLocale()) ?> - <em>P-Pit Studies</em></h5>
	    <div>
	      <button type="button" class="close" data-dismiss="modal" aria-label="Close" title="<?php echo $this->translate('Cancel', 'ppit-core', $context->getLocale()) ?>">
	        <span aria-hidden="true">&times;</span>
	      </button>
	    </div>
	  </div>
	  <div class="modal-body" id="document-list-panel"></div>
    </div>
  </div>
</div>

<!-- document modal -->
<div class="modal fade" id="student-home-modal" tabindex="-1" role="dialog" data-backdrop="static" aria-labelledby="modalFormLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title"><?php echo $this->translate('Student home page', 'ppit-studies', $context->getLocale()) ?></h5>
      <div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" title="<?php echo $this->translate('Cancel', 'ppit-core', $context->getLocale()) ?>">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
    <div class="modal-body" id="student-home-panel"></div>
    </div>
  </div>
</div>
