<table class="table table-striped ppit_index">
	<tr>
		<th>&nbsp;</th>
		<th>&nbsp;</th>

<?php foreach ($context->getConfig('commitmentAccount/list') as $propertyId => $rendering) : ?>
		<th align="center">
	<?php $label = $context->getConfig('commitmentAccount')['properties'][$propertyId]['labels'][$context->getLocale()] ?>
	<?php if ($label) : ?>
			<button type="button" class="btn btn-default btn-xs ppit-sort-anchor" id="<?php echo $propertyId ?>-anchor">
				<span><?php echo $label ?></span>
<?php if ($major == $propertyId) : ?>
				<span class="glyphicon glyphicon-triangle-<?php echo ($dir == 'ASC') ? 'top' : 'bottom' ?>"></span>
<?php endif ?>
			</button>
	<?php endif;?>
		</th>
<?php endforeach;?>

	<tr>
		<td>
			<input type="checkbox" class="account-checkbox" id="account-checkbox" title="<?php echo $this->translate('Check all', 'ppit-core', $context->getLocale()) ?>"></input>
		</td>

		<td style="text-align: center">
			<button type="button" class="btn btn-default btn-xs index-btn account-group-anchor" title="<?php echo $this->translate('Grouped actions', 'ppit-core', $context->getLocale())?>" id="account-group-anchor">
				<span class="glyphicon glyphicon-list-alt" id="group-glyphicon"></span>
			</button>
		</td>
		
		<td colspan="6">&nbsp;</td>
	</tr>

	<input type="hidden" id="account-number" value="<?php echo count($accounts) ?>" />

<?php $i = 0; foreach ($accounts as $account) : ?>
	
	<input type="hidden"  id="account_<?php echo $i ?>" value="<?php echo $account->id ?>" />
	
	<tr class="account" style="text-align: center">
		<td>
			<input type="checkbox" class="account-checkbox" id="account-checkbox_<?php echo $i ?>"></input>
		</td>

		<td style="text-align: center">
			<button type="button" class="btn btn-default btn-xs index-btn account-detail-anchor" title="<?php echo $this->translate('Unitary actions', 'ppit-core', $context->getLocale())?>" id="account-detail-anchor_<?php echo $account->id ?>">
				<span class="glyphicon glyphicon-zoom-in" id="group-glyphicon"></span>
			</button>
		</td>

	<?php foreach ($context->getConfig('commitmentAccount/list') as $propertyId => $rendering) : ?>
	
		<?php if ($propertyId == 'customer_name') : ?>
		<td><?php echo $account->customer_name ?></td>
	
		<?php elseif ($rendering == 'text') : ?>
		<td><?php echo $account->properties[$propertyId] ?></td>
	
		<?php elseif ($rendering == 'photo') : ?>
		<td>
			<span class="info">
				<img height="40" src="<?php echo $this->url('vcard/photo', array('id' => $account->properties[$propertyId])) ?>"/>
				<span><img height="150" src="<?php echo $this->url('vcard/photo', array('id' => $account->properties[$propertyId])) ?>"/></span>
			</span>
		</td>

		<?php elseif ($rendering == 'image') : ?>
		<td style="text-align: center">
			<img height="20" src="<?php echo $this->basePath('/img/'.$context->getInstance()->caption.'/'.$account->properties[$propertyId].'.png') ?>" title="<?php echo $account->properties[$propertyId] ?>" alt="<?php echo $account->properties[$propertyId] ?>" /><br>
		</td>

		<?php elseif ($rendering == 'phone') : ?>
		<td>
			<a href="tel:<?php echo $account->properties[$propertyId] ?>"><?php echo $account->properties[$propertyId] ?></a>
		</td>
	
		<?php else : ?>
		<td><?php echo $account->properties[$propertyId] ?></td>
		
		<?php endif;?>
		
	<?php endforeach;?>
	</tr>
	
<?php $i++; endforeach; ?>

	<tr>
		<td>
			<input type="checkbox" class="account-checkbox" id="down-account-checkbox"></input>
		</td>

		<td style="text-align: center">
			<button type="button" class="btn btn-default btn-xs bindex-btn account-group-anchor" title="<?php echo $this->translate('Grouped actions', 'ppit-core', $context->getLocale())?>" id="account-down-group-anchor">
				<span class="glyphicon glyphicon-list-alt" id="down-group-glyphicon"></span>
			</button>
		</td>
		
		<td colspan="6">&nbsp;</td>
	</tr>

</table>
