<?php
$title = 'Charger la photo';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'eleve',
    array(
        'action' => 'photo',
        'id'     => $this->id,
    )
));
$form->prepare();
echo $this->form()->openTag($form);
?>

<table>
  <tfoot>
    <tr><td colspan=2><?php
        echo $this->formInput($form->get('submit'));
        echo $this->formElementErrors($form->get('submit'));?>
        &nbsp;&nbsp;&nbsp;
        <a href="<?php echo $this->url('eleve', array('action'=>'index'));?>">Retour</a>
    </td></tr>
  </tfoot>
  <tbody>
	<tr><th><?php echo $this->formLabel($form->get('piece_jointe')); ?></th>
    	<td><?php 
        	echo $this->formFile($form->get('piece_jointe'));
        	echo $this->formElementErrors($form->get('piece_jointe'), array('class' => 'error_list'));
    	?></td>
    </tr>
  </tbody>
</table>

<?php echo $this->form()->closeTag();