<div>&nbsp;</div>
<input type="hidden" id="events-route" value="<?php echo $eventsRoute ?>" />
<div class="row">
  <div class="col-md-9" id="calendar"></div>
  <div class="col-md-3">
    <div><span class="chip chip-lg my-3" style="background-color: <?php echo $context->getConfig('note/colour')['done-work'] ?>"><?php echo $this->translate('Done work', 'ppit-studies', $context->getLocale()) ?></span></div>
    <div><span class="chip chip-lg my-3" style="background-color: <?php echo $context->getConfig('note/colour')['todo-work'] ?>"><?php echo $this->translate('Work to do', 'ppit-studies', $context->getLocale()) ?></span></div>
    <div><span class="chip chip-lg my-3" style="background-color: <?php echo $context->getConfig('note/colour')['event'] ?>"><?php echo $this->translate('Event', 'ppit-studies', $context->getLocale()) ?></span></div>
    <div id="homework-detail">
      <h3 id="homework-event-title"></h3>
      <div id="homework-event-description"></div>
    </div>
  </div>
</div>