<div>&nbsp;</div>
<input type="hidden" id="events-route" value="<?php echo $eventsRoute ?>" />
<div class="row">
  <div class="col-md-10" id="calendar"></div>
  <div class="col-md-2 text-center">
    <div>Légende</div>
    <div><span class="chip chip-lg my-3" style="background-color: <?php echo $context->getConfig('note/colour')['done-work'] ?>"><?php echo $this->translate('Done', 'ppit-studies', $context->getLocale()) ?></span></div>
    <div><span class="chip chip-lg my-3" style="background-color: <?php echo $context->getConfig('note/colour')['todo-work'] ?>"><?php echo $this->translate('To do', 'ppit-studies', $context->getLocale()) ?></span></div>
    <div><span class="chip chip-lg my-3" style="background-color: <?php echo $context->getConfig('note/colour')['event'] ?>"><?php echo $this->translate('Event', 'ppit-studies', $context->getLocale()) ?></span></div>
    <div><span class="chip chip-lg my-3" style="color: white; background-color: red"><?php echo $this->translate('Absence', 'ppit-studies', $context->getLocale()) ?></span></div>
    <div><span class="chip chip-lg my-3" style="color: white; background-color: orange"><?php echo $this->translate('Lateness', 'ppit-studies', $context->getLocale()) ?></span></div>
    <div class="text-left"><a id="absence-statement-anchor" href="#"><?php echo $this->translate('Absence statement', 'ppit-studies', $context->getLocale()) ?></a></div>
    <div id="homework-detail">
      <h3 id="homework-event-title"></h3>
      <div id="homework-event-description"></div>
    </div>
  </div>
</div>