<?php 
use PpitStudies\ViewHelper\PdfReportTableViewHelper;
?>

<style>
table.note-report {
	font-size: 0.83em;
	border-width:1px; 
 	border-style:solid; 
	border-color:gray;
}
table.note-report caption { 
	font-size:1.5em; 
	padding:1em 0 0.5em 1em;
}
table.note-report th {
	color: #666;
//    font-size:0.83em;
	text-align: center;
	border-width:1px; 
 	border-style:solid; 
	border-color:gray;
	background-color:#DDD;
}

table.note-report td {
	color: #666;
//	font-size: 0.83em;
	border-width:1px; 
 	border-style:solid; 
	border-color:gray;
}

table.note-report td.subject {
	font-weight: bold;
}

table.note-report tr.period {
	background-color:#DDD;
}
</style>

<!-- Reports -->

<?php foreach ($periods as $periodId => $period) : ?>
	<?php 
	$report = PdfReportTableViewHelper::render($period);
	$params = explode('.', $periodId); 
	$school_year = $params[0];
	$school_period = $params[1];
	$visible = false;
	foreach ($period as $averagePerSubject) {
		if ($averagePerSubject->subject == 'global' && $averagePerSubject->date && $averagePerSubject->date <= date('Y-m-d')) $visible = true;
	}
	?>
	<?php if ($context->hasRole('manager') || $context->hasRole('teacher') || $visible) : ?>	
	            <!--Card content-->
	            <div class="container card-block" style="color: #686868">
	                <!--Title-->
	                <h4 class="card-title mt-3" style="text-align: center">
      <?php if (array_key_exists($school_year, $context->getConfig('student/property/school_year')['modalities'])) : ?>
	                	<?php echo $context->localize($context->getConfig('student/property/school_year')['labels']) ?>:
	                	<?php echo $context->localize($context->getConfig('student/property/school_year')['modalities'][$school_year]) ?> &mdash;
      <?php endif;?>
	                	<?php echo $context->localize($context->getConfig('student/property/school_period')['modalities'][$school_period]) ?>
	                	<?php if (!$visible) echo '('.$this->translate('Non yet visible', 'ppit-studies', $context->getLocale()).')' ?>
	                </h4>
	                <!--Text-->
<?php if ($context->getInstance()->caption == 'ESI') : //Transient ?>
                    <div><a href="<?php echo $this->basePath('/my-gema/download-report/report/' . $account->id . '/' . $school_year) ?>"><?php echo $this->translate('Download in PDF format', 'ppit-studies', $context->getLocale()) ?></a></div>
<?php else : ?>
					<div><a href="<?php echo $this->url('student/download', array('category' => 'report', 'account_id' => $account->id, 'school_year' => $school_year, 'school_period' => $school_period)) ?>"><?php echo $this->translate('Download in PDF format', 'ppit-studies', $context->getLocale()) ?></a></div>
<?php endif;?>
                    <div class="mt-3"><?php echo $report ?></div>
	            </div>
	            <!--/.Card content-->
		<div>&nbsp;</div>
	<?php endif;?>
<?php endforeach;?>
