
<div class="card">
  <h5 class="card-header text-center" style="background: <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
    <?php 
	$title = (isset ($context->getConfig('student/search')['title']) ? $context->localize($context->getConfig('student/search')['title']) : $this->translate('Accounts', 'ppit-commitment', $context->getLocale()));
    echo $title;
    ?>
    (<span id="mode-text"></span>)
  </h5>
  <div class="card-body">

<!-- Filters -->
    <form class="form-inline">
      <div class="row">

<?php foreach ($context->getConfig('student/search')['main'] as $propertyId => $rendering) : ?>
	<?php 
	$property = $context->getConfig('core_account/p-pit-studies/property/'.$propertyId);
	if (!$property) $property = $context->getConfig('core_account/generic/property/'.$propertyId);
	if ($property['definition'] != 'inline') $property = $context->getConfig($property['definition']);

	if ($propertyId == 'groups') {
		$property['modalities'] = array();
		foreach ($groups as $group) $property['modalities'][$group->id] = ['default' => $group->name];
	}
	
    $label = $context->localize($property['labels']);
    $options = (array_key_exists('options', $property)) ? $property['options'] : [];
    ?>

        <div class="col-md-3">

	<?php if ($rendering != 'select') $label = $context->localize($property['labels']); ?>

  <?php if (in_array($property['type'], array('date', 'datetime'))) : ?>

          <div class="input-group input-group-sm mb-2 mr-sm-2">
            <input type="hidden" value="0" class="search_check_value" id="search_check_value-<?php echo $propertyId ?>" />
            <div class="input-group-prepend">
              <button type="button" class="btn btn-secondary input-group-text search_check" id="search_check-<?php echo $propertyId ?>"><?php echo $label ?></button>
            </div>
        <input class="form-control search_input search_input_date search_input_date_min" type="text" id="search_min-<?php echo $propertyId ?>" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
            <input class="form-control search_input search_input_date search_input_date_max" type="text" id="search_max-<?php echo $propertyId ?>" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
          </div>


  <?php elseif (in_array($property['type'], array('time', 'number'))) : ?>

          <div class="input-group input-group-sm mb-2 mr-sm-2">
            <input type="hidden" value="0" class="search_check_value" id="search_check_value-<?php echo $propertyId ?>" />
            <div class="input-group-prepend">
              <button type="button" class="btn btn-secondary input-group-text search_check" id="search_check-<?php echo $propertyId ?>"><?php echo $label ?></button>
            </div>
            <input class="form-control search_input search_input_text_min" type="text" id="search_min-<?php echo $propertyId ?>" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
            <input class="form-control search_input search_input_text_max" type="text" id="search_max-<?php echo $propertyId ?>" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
          </div>

  <?php elseif ($rendering == 'select') : ?>

    <?php
		
    $modalities = array();
    if (array_key_exists('p-pit-studies', $context->getPerimeters()) && array_key_exists($propertyId, $context->getPerimeters()['p-pit-studies'])) {
      foreach ($context->getPerimeters()['p-pit-studies'][$propertyId] as $modalityId) {
        if ($propertyId == 'place_id') $modalities[$modalityId] = $places[$modalityId]->caption;
        else $modalities[$modalityId] = $context->localize($property['modalities'][$modalityId]);
      } 
    }
    else {
      if ($propertyId == 'place_id') foreach ($places as $place) {
        $modalities[$place->id] = $place->caption;
      } 
      else foreach ($property['modalities'] as $modalityId => $modality) {
        $modalities[$modalityId] = $context->localize($modality);
      } 
    }

    if (array_key_exists('multiple', $options) && $options['multiple']) $multiple = true; else $multiple = false;
    ?>
         <div class="input-group input-group-sm mb-2 mr-sm-2">
            <input type="hidden" value="0" class="search_check_value" id="search_check_value-<?php echo $propertyId ?>" />
            <div class="input-group-prepend">
              <button type="button" class="btn btn-secondary input-group-text search_check" id="search_check-<?php echo $propertyId ?>"><?php echo $label ?></button>
            </div>
            <select class="form-control search_input search_input_select <?php if ($multiple) echo 'selectpicker search_selectpicker' ?>" id="search-<?php echo $propertyId ?>" <?php if ($multiple) echo 'data-none-selected-text' ?> <?php if ($multiple) echo 'multiple' ?>>
    <?php if (!$multiple) : ?>
              <option value=""></option>
    <?php endif;?>
    <?php foreach ($modalities as $modalityId => $modalityLabel) : ?>
              <option value="<?php echo $modalityId ?>"><?php echo $modalityLabel ?></option>
    <?php endforeach;?>
            </select>
          </div>
  
  <?php else : ?>
         <div class="input-group input-group-sm mb-2 mr-sm-2">
            <input type="hidden" value="0" class="search_check_value" id="search_check_value-<?php echo $propertyId ?>" />
            <div class="input-group-prepend">
              <button type="button" class="btn btn-secondary input-group-text search_check" id="search_check-<?php echo $propertyId ?>"><?php echo $label ?></button>
            </div>
            <input class="form-control search_input search_input_text" type="text" id="search-<?php echo $propertyId ?>" />
          </div>

  <?php endif;?>
        </div> <!-- col -->
<?php endforeach;?>

        <div class="col-md-3">    
          <div class="input-group input-group-sm mb-2 mr-sm-2">
            <button type="button" class="btn btn-default input-group-text" disabled data-toggle="tooltip" title="<?php echo $this->translate('Erase', 'ppit-core', $context->getLocale()) ?>" id="erase-button">
              <i class="fa fa-times text-center"></i>
            </button>
            <button type="button" class="btn btn-default input-group-text shared-document-button" data-toggle="tooltip" title="<?php echo $this->translate('Shared documents', 'ppit-core', $context->getLocale()) ?>">
              <i class="fa fa-folder-open text-center"></i>
            </button>
            <a type="button" class="input-group-text btn" role="button" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('Export', 'ppit-core', $context->getLocale()) ?>" id="export-button">
              <i class="fa fa-cloud-download-alt"></i>
            </a>
          </div>
        </div> <!-- col -->
       
      </div> <!-- row -->
    </form>

<!-- Add or update section -->
    <div style="background-color: #ffffff;" class="row">
      <div>&nbsp;</div>
      <input type="hidden" id="limit" value="50" />
      <div class="table-responsive" id="account-list-panel"></div>
    </div>
  </div>
</div>
