<div class="panel panel-default">
	<div class="panel-heading" style="background: <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<strong>
			<?php 
			$title = (isset ($context->getConfig('commitmentAccount/search/p-pit-studies')['title']) ? $context->getConfig('commitmentAccount/search/p-pit-studies')['title'][$context->getLocale()] : $this->translate('Accounts', 'ppit-commitment', $context->getLocale()));
			echo $title;
			?>
			(<span id="mode-text"></span>)
		</strong>
	
<?php if ($context->isDemoModeActive()) : ?>
		<a class="tip" href="#"
title="
<h4><?php echo $this->translate('Student list', 'ppit-studies', $context->getLocale()) ?></h4>
<p><?php echo $this->translate('As a default, all the currently registered students are presented in the list.', 'ppit-studies', $context->getLocale()) ?></p>
<p><?php echo $this->translate('As soon as a criterion below is specified, the list switch in search mode.', 'ppit-studies', $context->getLocale()) ?></p>
">
		    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
		</a>
<?php endif;?>
	</div>
	<div class="panel-body">

<!-- Filters -->

		<div class="form-group">
			<label class="col-sm-4 control-label">
				<span class="glyphicon glyphicon-search"></span>
			</label>
			<div class="col-sm-1 control-label">
<?php if ($context->isDemoModeActive()) : ?>
				<a class="tip" href="#"
title="
<h4><?php echo $this->translate('Return in default mode', 'ppit-studies', $context->getLocale()) ?></h4>
<p><?php echo $this->translate('The <code>x</code> button reinitializes all the search criteria and reset the list in default mode (registered students).', 'ppit-studies', $context->getLocale()) ?></p>
">
				    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
				</a>
<?php endif;?>
			</div>
			<div class="col-sm-7">
	    		<button type="button" class="form-control btn btn-default btn-xs" title="<?php echo $this->translate('Erase', 'ppit-core', $context->getLocale()) ?>" id="erase-button">
					<span class="glyphicon glyphicon-remove"></span>
				</button>
			</div>
		</div>
		
<?php foreach ($context->getConfig('commitmentAccount/search/p-pit-studies')['main'] as $propertyId => $rendering) : ?>
	<?php $label = $context->getConfig('commitmentAccount/p-pit-studies')['properties'][$propertyId]['labels'][$context->getLocale()] ?>
	
	<?php if ($rendering == 'contains') : ?>
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $label ?></label>
			<div class="col-sm-7">
				<input class="form-control" type="text" id="search_<?php echo $propertyId ?>" placeholder="<?php echo $this->translate('Contains', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

	<?php elseif ($rendering == 'range') : ?>

		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $label ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_min_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_max_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

	<?php elseif ($rendering == 'select') : ?>

		<?php
		$modalities = array();
		foreach ($context->getConfig('commitmentAccount/p-pit-studies')['properties'][$propertyId]['modalities'] as $modalityId => $modality) {
			$modalities[$modalityId] = $modality[$context->getLocale()];
		} 
		?>
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $label ?></label>
			<div class="col-sm-7">
				<select id="search_<?php echo $propertyId ?>" class="form-control">
					<option value=""></option>
		<?php foreach ($modalities as $modalityId => $modalityLabel) : ?>
		    		<option value="<?php echo $modalityId ?>"><?php echo $modalityLabel ?></option>
		<?php endforeach;?>
		    	</select>
			</div>
		</div>

	<?php endif;?>
<?php endforeach;?>
	
		<div><a id="add-criteria" href="#"><?php echo $this->translate('More criteria', 'ppit-core', $context->getLocale())?></a></div>
		<div id="search-area">
		
<?php foreach ($context->getConfig('commitmentAccount/search/p-pit-studies')['more'] as $propertyId => $rendering) : ?>
	<?php $label = $context->getConfig('commitmentAccount/p-pit-studies')['properties'][$propertyId]['labels'][$context->getLocale()] ?>

	<?php if ($propertyId == 'place_id') : ?>
			<div class="form-group">
				<label class="col-sm-5 control-label"><?php echo $label ?></label>
				<div class="col-sm-7">
					<select id="search_<?php echo $propertyId ?>" class="form-control">
						<option value=""><-- <?php echo $this->translate('Please select a value', 'ppit-core', $context->getLocale()) ?> --></option>
			<?php foreach ($places as $place) : ?>
			    		<option value="<?php echo $place->id ?>"><?php echo $place->name ?></option>
			<?php endforeach;?>
			    	</select>
				</div>
			</div>
	
	<?php elseif ($rendering == 'contains') : ?>
			<div class="form-group">
				<label class="col-sm-5 control-label"><?php echo $label ?></label>
				<div class="col-sm-7">
					<input class="form-control" type="text" id="search_<?php echo $propertyId ?>" placeholder="<?php echo $this->translate('Contains', 'ppit-core', $context->getLocale()) ?>" />
				</div>
			</div>

	<?php elseif ($rendering == 'range') : ?>

			<div class="form-group">
				<label class="col-sm-5 control-label"><?php echo $label ?></label>
				<div class="col-sm-7">
		    		<input class="form-control" type="text" id="search_min_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
				</div>
			</div>

			<div class="form-group">
				<label class="col-sm-5 control-label">&nbsp;</label>
				<div class="col-sm-7">
		    		<input class="form-control" type="text" id="search_max_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
				</div>
			</div>

	<?php elseif ($rendering == 'select') : ?>

		<?php
		$modalities = array();
		foreach ($context->getConfig('commitmentAccount/p-pit-studies')['properties'][$propertyId]['modalities'] as $modalityId => $modality) {
			$modalities[$modalityId] = $modality[$context->getLocale()];
		} 
		?>
			<div class="form-group">
				<label class="col-sm-5 control-label"><?php echo $label ?></label>
				<div class="col-sm-7">
					<select id="search_<?php echo $propertyId ?>" class="form-control">
						<option value=""></option>
		<?php foreach ($modalities as $modalityId => $modalityLabel) : ?>
			    		<option value="<?php echo $modalityId ?>"><?php echo $modalityLabel ?></option>
		<?php endforeach;?>
			    	</select>
				</div>
			</div>

	<?php endif;?>
<?php endforeach;?>

		</div>

	    <div>&nbsp;</div>

<!-- Actions -->
	    <div>
	    		<button type="button" class="btn btn-default" title="<?php echo $this->translate('Export', 'ppit-core', $context->getLocale()) ?>" id="export-button">
					<span class="glyphicon glyphicon-cloud-download"></span>
					<span><?php echo $this->translate('Export', 'ppit-core', $context->getLocale())?></span>
				</button>
<?php if ($context->isDemoModeActive()) : ?>
				<a class="tip" href="#" title="
<h4><?php echo $this->translate('List export', 'ppit-core', $context->getLocale()) ?></h4>
<p><?php echo $this->translate('The list is exported as it is presented: defaulting list or list resulting of a multi-criteria search.', 'ppit-core', $context->getLocale()) ?></p>
">
				    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
				</a>
<?php endif;?>
	    </div>
	    
		<div>&nbsp;</div>

<!-- Add or update section -->
		<div id="account-list-panel"></div>
	</div>
</div>
