
<div class="panel panel-default">
	<div class="panel-heading" style="background: <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<strong>
			<?php 
			$title = (isset ($context->getConfig('student/search')['title']) ? $context->getConfig('student/search')['title'][$context->getLocale()] : $this->translate('Accounts', 'ppit-commitment', $context->getLocale()));
			echo $title;
			?>
			(<span id="mode-text"></span>)
		</strong>
	
<?php if ($context->isDemoModeActive()) : ?>
		<a class="tip" href="#" title="<?php echo $context->getConfig('demo')['student/search/title'][$context->getLocale()] ?>">
		    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
		</a>
<?php endif;?>
	</div>
	<div class="panel-body">
	    <div class="col-md-6">


<!-- Filters -->

<?php foreach ($context->getConfig('student/search')['main'] as $propertyId => $rendering) : ?>
	<?php 
	$property = $context->getConfig('core_account/p-pit-studies/property/'.$propertyId);
	if ($property['definition'] != 'inline') $property = $context->getConfig($property['definition']);
	?>

	<?php if ($rendering != 'select') $label = $property['labels'][$context->getLocale()]; ?>

	<?php if ($rendering == 'select') : ?>

		<?php
		$label = $property['labels'][$context->getLocale()];
		
		$modalities = array();
		if (array_key_exists('p-pit-studies', $context->getPerimeters()) && array_key_exists($propertyId, $context->getPerimeters()['p-pit-studies'])) {
			foreach ($context->getPerimeters()['p-pit-studies'][$propertyId] as $modalityId) {
				if ($propertyId == 'place_id') $modalities[$modalityId] = $places[$modalityId]->caption;
				else $modalities[$modalityId] = $property['modalities'][$modalityId][$context->getLocale()];
			} 
		}
		else {
			if ($propertyId == 'place_id') foreach ($places as $place) {
				$modalities[$place->id] = $place->caption;
			} 
			else foreach ($property['modalities'] as $modalityId => $modality) {
				$modalities[$modalityId] = $modality[$context->getLocale()];
			} 
		}
		?>
			<label class="col-sm-6 control-label"><?php echo $label ?></label>
			<div class="input-group search">
			    <span class="input-group-addon">
					<input type="checkbox" class="search_check" id="search_check_<?php echo $propertyId ?>">
				</span>
				<select id="search_<?php echo $propertyId ?>" class="selectpicker search_input" multiple>
					<option value=""></option>
		<?php foreach ($modalities as $modalityId => $modalityLabel) : ?>
		    		<option value="<?php echo $modalityId ?>"><?php echo $modalityLabel ?></option>
		<?php endforeach;?>
		    	</select>
			</div>
	
	<?php elseif ($rendering == 'contains') : ?>
			<label class="col-sm-6 control-label"><?php echo $label ?></label>
			<div class="input-group search">
              <span class="input-group-addon">
                <input type="checkbox" class="search_check" id="search_check_<?php echo $propertyId ?>">
              </span>
              <input class="form-control search_input" type="text" id="search_<?php echo $propertyId ?>" placeholder="<?php echo $this->translate('Contains', 'ppit-core', $context->getLocale()) ?>" />
			</div>

	<?php elseif ($rendering == 'range') : ?>

			<label class="col-sm-6 control-label"><?php echo $label ?></label>
			<div class="input-group search">
              <span class="input-group-addon">
                <input type="checkbox" class="search_check" id="search_check_<?php echo $propertyId ?>">
              </span>
              <input class="form-control" type="text" id="search_min_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>

			<label class="col-sm-6 control-label">&nbsp;</label>
			<div class="input-group search">
              <span class="input-group-addon">
                <input type="checkbox" class="search_check" id="search_check_<?php echo $propertyId ?>">
              </span>
              <input class="form-control search_input" type="text" id="search_max_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>

	<?php endif;?>
<?php endforeach;?>

      <div class="col-sm-6">&nbsp;</div>
       <div class="col-sm-6 search">
          <button type="button" class="form-control btn btn-default btn-xs" title="<?php echo $this->translate('Erase', 'ppit-core', $context->getLocale()) ?>" id="erase-button">
          <span class="glyphicon glyphicon-remove"></span>
        </button>
<?php if ($context->isDemoModeActive()) : ?>
        <a class="tip" href="#" title="<?php echo $context->getConfig('demo')['student/search/x'][$context->getLocale()] ?>">
            <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
        </a>
<?php endif;?>
      </div>

      <div class="col-sm-6">&nbsp;</div>

		</div>

<!-- Add or update section -->
		<input type="hidden" id="limit" value="50" />
		<div id="account-list-panel"></div>

	</div>
</div>
