<!-- 
/**
 * PpitCore V1.0 (https://github.com/p-pit/PpitCore)
 *
 * @link      https://github.com/p-pit/PpitCore
 * @copyright Copyright (c) 2016 Bruno Lartillot
 * @license   https://github.com/p-pit/PpitCore/blob/master/license.txt GNU-GPL license
 */
-->

<div class="modal-dialog modal-xl" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="modalFormLabel"><?php echo $this->translate('Student home page', 'ppit-studies', $context->getLocale()) ?></h5>
      <div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" title="<?php echo $this->translate('Cancel', 'ppit-core', $context->getLocale()) ?>">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
    <div class="modal-body">
      <div class="container">
        <div><iframe src="<?php echo $this->url('public/community', array('identifier' => 'p-pit-studies', 'place_identifier' => $place->identifier, 'subject_id' => $account->contact_1_id)) ?>" height="1000" style="width: 100%; border: none"></iframe></div>
      </div>
    </div>
  </div>
</div>