
<!-- Load the common form javascript functions -->
<?php echo $this->partial('/partials/common-form-js.phtml'); ?>

<?php
$title = $context->getConfig('student/index')['title'][$context->getLocale()];
$this->headTitle($title);
echo $this->partial('/partials/header');
?>

<div class="container">
	
	<div>&nbsp;</div>
	
	<div id="main_menu" >
	    <div class="col-md-10 col-md-offset-1">
			<div align="center">

	<!-- Main panel -->
	<div class="row">
		<div class="col-md-6 col-md-offset-3 ppit-panel" id="main-panel"></div>
	</div>
	
	<!-- Login -->
	<div class="row">
	    <div class="col-md-6 col-md-offset-3 ppit-panel" id="login-panel">
		</div>
	</div>
</div>

<script>

<?php
echo $this->partial('/partials/student-home-scripts');
?>

activateStudentHome();

</script>
