
<!-- Load the common form javascript functions -->
<?php echo $this->partial('/partials/common-form-js.phtml'); ?>

<?php
$title = $context->getConfig('student/index')['title'][$context->getLocale()];
$this->headTitle($title);
echo $this->partial('/partials/header');
?>
	
	<div>&nbsp;</div>
	
	<div id="main_menu" >
	    <div class="col-md-10 col-md-offset-1">
			<div align="center">

<?php foreach ($context->getConfig('menus')['p-pit-hr-portal'] as $entryId => $entryDef) : ?>
	<?php if ($context->isAllowed($entryDef['route'])) : ?>
				<button type="button" class="btn menu-btn <?php echo ($entryId == 'employeeFile') ? 'btn-primary' : 'btn-default' ?>" id="<?php echo $entryId ?>-anchor">
		<?php if (array_key_exists('glyphicon', $entryDef)) : ?>
					<span class="glyphicon <?php echo $entryDef['glyphicon'] ?>"></span>
		<?php endif;?>
					<?php echo $entryDef['label'][$context->getLocale()] ?>
				</button>
	<?php endif ?>
<?php endforeach;?>

			</div>
			<div>&nbsp;</div>
		</div>
	</div>

	<!-- Main panel -->
	<div class="row">
		<div class="col-md-12 ppit-panel" id="main-panel"></div>
	</div>
	
	<!-- Login -->
	<div class="row">
	    <div class="col-md-6 col-md-offset-3 ppit-panel" id="login-panel">
		</div>
	</div>

<script>

<?php
echo $this->partial('/partials/student-home-scripts');
echo $this->partial('/partials/ppit-controller') 
?>

<?php foreach ($context->getConfig('menus')['p-pit-hr-portal'] as $entryId => $entryDef) : ?>
$('#<?php echo $entryId ?>-anchor').click(function () { $(location).attr('href', '<?php echo $this->url($entryDef['route']) ?>'); });
<?php endforeach;?>

activateStudentHome();

</script>
