<style>
.ppit-header-caption {
	text-align: right;
	font-weight: bold;
}
</style>

<?php
$title = $this->translate('Delete a message', 'ppit-contact', $context->getLocale());
echo $this->partial('/partials/menu');
$this->headTitle($title);
?>
<div class="row">
    <div class="col-md-6 col-md-offset-3">

<?php
if (!$context->isSpaMode()) $returnHref = $this->url('sms');
else $returnHref = "#";
?>
    <div class="panel panel-default">
            <div class="panel-heading">
				<strong><?php echo $this->translate($title);?></strong>
            </div>
           	<div class="panel-body">
				<table class="table-condensed">

<?php if ($message == 'OK') : ?>
           			<tr id="return">
						<td colspan="2">
							<a id="message_delete_anchor_return" class="glyphicon glyphicon-circle-arrow-left" href="<?php echo $returnHref ?>"></a>
							<a id="message_delete_anchor_return_2" href="<?php echo $returnHref ?>"><?php echo $this->translate('Return', 'ppit-core', $context->getLocale()) ?></a>
						</td>
					</tr>
<?php endif;?>

<!-- Type -->
					<tr>
						<td class="ppit-header-caption"><?php echo $this->translate('Media', 'ppit-contact', $context->getLocale())?></td>
						<td><?php echo $modelMessage->type; ?></td>
					</tr>

<!-- From -->
					<tr>
						<td class="ppit-header-caption"><?php echo $this->translate('From', 'ppit-contact', $context->getLocale())?></td>
						<td><?php echo $modelMessage->from; ?></td>
					</tr>

<!-- Center -->
					<tr>
						<td class="ppit-header-caption"><?php echo $this->translate('Center', 'ppit-studies', $context->getLocale())?></td>
						<td><?php echo (isset($modelMessage->to->center_id)) ? $modelMessage->to->center_id : $this->translate('Any center', 'ppit-studies', $context->getLocale()) ?></td>
					</tr>

<!-- Sport -->
					<tr>
						<td class="ppit-header-caption"><?php echo $this->translate('Sport', 'ppit-studies', $context->getLocale())?></td>
						<td><?php echo (isset($modelMessage->to->sport)) ? $modelMessage->to->sport : $this->translate('Any sport', 'ppit-studies', $context->getLocale()) ?></td>
					</tr>

<!-- Class -->
					<tr>
						<td class="ppit-header-caption"><?php echo $this->translate('Class', 'ppit-studies', $context->getLocale())?></td>
						<td><?php echo (isset($modelMessage->to->class)) ? $modelMessage->to->class : $this->translate('Any class', 'ppit-studies', $context->getLocale()) ?></td>
					</tr>

<!-- Boarding school -->
					<tr>
						<td class="ppit-header-caption"><?php echo $this->translate('Boarding school option', 'ppit-studies', $context->getLocale())?></td>
						<td><?php echo (isset($modelMessage->to->boarding_school)) ? $modelMessage->to->boarding_school : $this->translate('Interns & externs', 'ppit-studies', $context->getLocale()) ?></td>
					</tr>
					
<!-- Subject -->
					<tr>
						<td class="ppit-header-caption"><?php echo $this->translate('Subject', 'ppit-contact', $context->getLocale())?></td>
						<td><?php echo $modelMessage->subject ?></td>
					</tr>

				</table>

<!-- Form provided for MPA view mode -->
<?php if (!$context->isSpaMode()) : ?>
				<form action="<?php echo $this->url('sms/delete', array('id' => $this->id)); ?>" method="post">
<?php endif;?>

<?php if ($message == 'OK') : ?>
<!-- Global message -->
					<div class="form-group" id="message">
						<div class="col-sm-12"><h3><?php echo $this->translate('Your request have been registered', 'ppit-core', $context->getLocale()) ?></h3></div>
					</div>
<?php endif;?>
				
<!-- Hidden database update time provided for isolation check -->
					<input type="hidden" name="db_update_time" id="db_update_time" value="<?php echo $modelMessage->update_time ?>"? />
<?php if ($error == 'Isolation') : ?>
					<div class="form-group">
						<div class="col-sm-12"><h4 class="help-block"><?php echo $this->translate('The database has evolved in the meantime, please input again', 'ppit-core', $context->getLocale()) ?></h4></div>
					</div>
<?php endif;?>

<!--  CSRF -->
<?php $element = $csrfForm->get('csrf') ?>
				    <div class="form-group">
						<?php echo $this->formElement($element) ?>
<?php if ($this->formElementErrors($element)) : ?>
						<div class="col-sm-12"><p class="help-block"><?php echo $this->translate('The form has expired, please input again', 'ppit-core', $context->getLocale()) ?></p></div>
<?php endif;?>
					</div>

<?php if ($message == 'OK') : ?>

<!-- Foot return link -->
					<div class="form-group">
						<div class="col-sm-5">&nbsp;</div>
						<div class="col-sm-7">
							<a id='message_delete_anchor_foot_return' href="<?php echo $returnHref ?>"><?php echo $this->translate('Return', 'ppit-core', $context->getLocale()) ?></a>
						</div>
					</div>

<?php else : ?>

<!-- Submit button -->
				    <div class="form-group">
						<div class="col-sm-5">&nbsp;</div>
						<div class="col-sm-7">
							<input name="submit" type="submit" id="message_delete_button" class="btn btn-primary" value="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>" />
							&nbsp;&nbsp;
							<a id="message_delete_cancel" href="<?php echo $returnHref ?>"><?php echo $this->translate('Cancel', 'ppit-core', $context->getLocale()) ?></a>
						</div>
					</div>
<?php endif;?>

<?php if (!$context->isSpaMode()) : ?>
				</form>
<?php endif;?>
			</div>
		</div>
	</div>
</div>

<?php if (!$context->isSpaMode()) echo $this->partial('partials/view-controller') ?>

<script id='message_delete_script'>
//Menu
$("#message_delete_anchor_return").click(function () { hideForm(); } );
$("#message_delete_anchor_return_2").click(function () { hideForm(); } );

<?php if ($message == 'OK') : ?>

	//Foot return
	$("#message_delete_anchor_foot_return").click(function () { hideForm(); } );

<?php else : ?>

	//Button
	$("#message_delete_button").click(function () { messageDeleteForm(); } );
	$("#message_delete_cancel").click(function () { hideForm(); } );

<?php endif;?>

//The elements are checked last to first so the focus is positionned on the first element on error
function messageDeleteForm() 
{
	
	// Form provided for MPA view mode
<?php if (!$context->isSpaMode()) : ?>
	return true;
<?php else : ?>
	var data = new FormData();
	data.append('db_update_time', document.getElementById("db_update_time").value);
	postForm("<?php echo $this->url('sms/delete', array('id' => $id)) ?>", 'message_delete_script', 'form_action', data);
	reload('<?php echo $this->url('sms') ?>', 'message_script', false);
<?php endif;?>
}

</script>
