<?php $i=0; foreach ($contacts as $contact) if ($contact->ok) $i++; ?>

<h5>
	<?php echo $this->translate('Result', 'ppit-contact', $context->getLocale()) ?>:
	<?php echo $i ?> <?php echo $this->translate('reachable numbers', 'ppit-contact', $context->getLocale()) ?> -
	<?php echo $this->translate('Cost', 'ppit-contact', $context->getLocale()) ?>
	<?php if ($i) echo '= '.$context->formatFloat($i * $config['ppitContactSettings']['smsCost'], 2) ?> €
</h5>
<table class="table table-striped">

<?php foreach ($contacts as $contact) : ?>
<?php if ($contact->ok) { $icon = 'thumbs-up'; $color = 'green'; } else { $icon = 'thumbs-down'; $color = 'red'; } ?>
	<tr>
		<td><?php echo $contact->n_first ?> <?php echo $contact->n_last ?></td>
		<td><?php echo $contact->center_id ?></td>
		<td><?php echo $contact->sport ?></td>
		<td><?php echo $contact->class ?></td>
		<td><?php echo $contact->boarding_school ?></td>
		<td style="color: <?php echo $color ?>"><?php echo $contact->tel_cell ?></td>
		<td><span class="glyphicon glyphicon-<?php echo $icon ?>" style="color: <?php echo $color ?>"></span></td>
	</tr>
<?php endforeach; ?>

</table>