<style>
.ppit-header-caption {
	text-align: right;
	font-weight: bold;
}
</style>

<?php
$title = $this->translate('Send a message', 'ppit-contact', $context->getLocale());
echo $this->partial('/partials/menu');
$this->headTitle($title);
?>
<div class="row">
    <div class="col-md-6 col-md-offset-3">

<?php $returnHref = "#" ?>
    <div class="panel panel-default">
            <div class="panel-heading">
				<strong><?php echo $this->translate($title);?></strong>
            </div>
           	<div class="panel-body">
				<table class="table-condensed">

<?php if ($message == 'OK') : ?>
           			<tr id="return">
						<td colspan="2">
							<a id="message_update_anchor_return" class="glyphicon glyphicon-circle-arrow-left" href="<?php echo $returnHref ?>"></a>
							<a id="message_update_anchor_return_2" href="<?php echo $returnHref ?>"><?php echo $this->translate('Return', 'ppit-core', $context->getLocale()) ?></a>
						</td>
					</tr>
<?php endif;?>

<!-- Type -->
					<tr>
						<td class="ppit-header-caption"><?php echo $this->translate('Media', 'ppit-contact', $context->getLocale())?></td>
						<td><?php echo $modelMessage->type; ?></td>
					</tr>

<!-- Credits -->
<?php if ($modelMessage->type == 'SMS') : ?>
					<tr>
						<td class="ppit-header-caption"><?php echo $this->translate('Credit', 'ppit-contact', $context->getLocale())?></td>
						<td><?php echo $modelMessage->credits; ?></td>
					</tr>
<?php endif;?>

				</table>
				<hr>

<?php if ($message == 'OK') : ?>
<!-- Global message -->
			<div class="form-group" id="message">
				<div class="col-sm-12"><h3><?php echo $this->translate('Your request has been registered', 'ppit-core', $context->getLocale()) ?></h3></div>
			</div>
<?php endif;?>

<!--  Error -->
<?php if ($error == 'Invalid') : ?>
					<div class="form-group">
						<div class="col-sm-12"><p class="help-block"><?php echo $this->translate('Invalid request', 'ppit-core', $context->getLocale()) ?></p></div>
					</div>
<?php endif;?>

<?php if ($error == 'Insufficient') : ?>
					<div class="form-group">
						<div class="col-sm-12"><p class="help-block"><?php echo $this->translate('You do not have enough credit to transmit this message', 'ppit-core', $context->getLocale()) ?></p></div>
					</div>
<?php endif;?>
				
<!-- Hidden database update time provided for isolation check -->
					<input type="hidden" name="db_update_time" id="db_update_time" value="<?php echo $modelMessage->update_time ?>" />
<?php if ($error == 'Isolation') : ?>
					<div class="form-group">
						<div class="col-sm-12"><h4 class="help-block"><?php echo $this->translate('The database has evolved in the meantime, please input again', 'ppit-core', $context->getLocale()) ?></h4></div>
					</div>
<?php endif;?>

<!--  CSRF -->
<?php $element = $csrfForm->get('csrf') ?>
				    <div class="form-group">
						<?php echo $this->formElement($element) ?>
<?php if ($this->formElementErrors($element)) : ?>
						<div class="col-sm-12"><p class="help-block"><?php echo $this->translate('The form has expired, please input again', 'ppit-core', $context->getLocale()) ?></p></div>
<?php endif;?>
					</div>
					
<!-- Subject -->
				    <div class="form-group" id="subject_group">
						<label class="col-sm-4 control-label"><?php echo $this->translate('Subject', 'ppit-contact', $context->getLocale()) ?></label>
				    	<div class="col-sm-8">
							<textarea name="subject" id="subject" rows="5" class="form-control"<?php if ($message == 'OK') echo 'disabled="disabled"' ?>><?php echo $modelMessage->subject ?></textarea>
						</div>
						<div class="col-sm-12"><p class="help-block" id="subject_error"></p></div>
					</div>

					<h4><?php echo $this->translate('Targeting', 'ppit-contact', $context->getLocale()) ?></h4>

<!-- Center -->
					<div class="form-group" id="center_id_group">
						<label class="col-sm-4 control-label"><?php echo $this->translate('Center', 'ppit-studies', $context->getLocale()) ?></label>
						<div class="col-sm-8">
							<select name="center_id" id="center_id" class="form-control" onchange="simulate()"<?php if ($message == 'OK') echo 'disabled="disabled"' ?>>
								<option value=""><-- <?php echo $this->translate('Any center', 'ppit-studies', $context->getLocale()) ?> --></option>
<?php foreach ($target->centers as $center) : ?>
								<option value="<?php echo $center->name ?>" <?php if ($center->name == $target->center_id) echo 'selected="selected"'; ?>><?php echo $center->name ?></option>
<?php endforeach;?>
							</select>
						</div>
						<div class="col-sm-12"><p class="help-block" id="center_id_error"></p></div>
					</div>

<!-- Sport -->
					<div class="form-group" id="sport_group">
						<label class="col-sm-4 control-label"><?php echo $this->translate('Sport', 'ppit-studies', $context->getLocale()) ?></label>
						<div class="col-sm-8">
							<select name="sport" id="sport" class="form-control" onchange="simulate()"<?php if ($message == 'OK') echo 'disabled="disabled"' ?>>
								<option value=""><-- <?php echo $this->translate('Any sport', 'ppit-studies', $context->getLocale()) ?> --></option>
<?php foreach ($config['ppitStudies']['sports'] as $sport) : ?>
								<option value="<?php echo $sport ?>" <?php if ($sport == $target->sport) echo 'selected="selected"'; ?>><?php echo $this->translate($sport, 'ppit-studies', $context->getLocale()) ?></option>
<?php endforeach;?>
							</select>
						</div>
						<div class="col-sm-12"><p class="help-block" id="sport_error"></p></div>
					</div>

<!-- Class -->
					<div class="form-group" id="class_group">
						<label class="col-sm-4 control-label"><?php echo $this->translate('Class', 'ppit-studies', $context->getLocale()) ?></label>
						<div class="col-sm-8">
							<select name="class" id="class" class="form-control" onchange="simulate()"<?php if ($message == 'OK') echo 'disabled="disabled"' ?>>
								<option value=""><-- <?php echo $this->translate('Any class', 'ppit-studies', $context->getLocale()) ?> --></option>
<?php foreach ($config['ppitStudies']['classes'] as $class) : ?>
								<option value="<?php echo $class ?>" <?php if ($sport == $target->class) echo 'selected="selected"'; ?>><?php echo $this->translate($class, 'ppit-studies', $context->getLocale()) ?></option>
<?php endforeach;?>
							</select>
						</div>
						<div class="col-sm-12"><p class="help-block" id="sport_error"></p></div>
					</div>

<!-- Boarding school -->
					<div class="form-group" id="boarding_school_group">
						<label class="col-sm-4 control-label"><?php echo $this->translate('Boarding school', 'ppit-studies', $context->getLocale()) ?></label>
						<div class="col-sm-8">
							<select name="boarding_school" id="boarding_school" class="form-control" onchange="simulate()"<?php if ($message == 'OK') echo 'disabled="disabled"' ?>>
								<option value=""><-- <?php echo $this->translate('Interns & externs', 'ppit-studies', $context->getLocale()) ?> --></option>
<?php foreach ($config['ppitStudies']['boardingSchoolOptions'] as $option) : ?>
								<option value="<?php echo $option ?>" <?php if ($option == $target->boarding_school) echo 'selected="selected"'; ?>><?php echo $this->translate($option, 'ppit-studies', $context->getLocale()) ?></option>
<?php endforeach;?>
							</select>
						</div>
						<div class="col-sm-12"><p class="help-block" id="boarding_school_error"></p></div>
					</div>

<?php if ($message == 'OK') : ?>
					
<!-- Foot return link -->
					<div class="form-group">
						<div class="col-sm-4">&nbsp;</div>
						<div class="col-sm-8">
							<a id='message_update_anchor_foot_return' href="<?php echo $returnHref ?>"><?php echo $this->translate('Return', 'ppit-core', $context->getLocale()) ?></a>
						</div>
					</div>

<?php else : ?>

<!-- Submit button -->
				    <div class="form-group">
						<div class="col-sm-4">&nbsp;</div>
						<div class="col-sm-8">
							<input type="hidden" id="action" name="action"/>
							<input name="save" type="submit" id="message_save_button" class="btn btn-primary" value="<?php echo $this->translate('Save', 'ppit-contact', $context->getLocale()) ?>" />
							&nbsp;&nbsp;
							<input name="emit" type="submit" id="message_transmit_button" class="btn btn-primary" value="<?php echo $this->translate('Transmit', 'ppit-contact', $context->getLocale()) ?>" />
							&nbsp;&nbsp;
							<a id="message_update_cancel" href="<?php echo $returnHref ?>"><?php echo $this->translate('Cancel', 'ppit-core', $context->getLocale()) ?></a>
						</div>
					</div>
<?php endif;?>

<!-- Result -->
				<hr>
				<div id="sms_update_target"></div>
			</div>
		</div>
	</div>
</div>

<script id='message_update_script'>
//Menu
$("#message_update_anchor_return").click(function () { hideForm(); } );
$("#message_update_anchor_return_2").click(function () { hideForm(); } );

<?php if ($message == 'OK') : ?>

	//Foot return
	$("#message_update_anchor_foot_return").click(function () { hideForm(); } );

<?php else : ?>

	//Button
	$("#message_save_button").click(function () { return messageSaveForm(); } );
	$("#message_transmit_button").click(function () { return messageTransmitForm(); } );
	$("#message_update_cancel").click(function () { hideForm(); } );

<?php endif;?>

// Simulate the "to" list according to the target criteria
function simulate() {
	var xhttp = new XMLHttpRequest();
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4/* && xhttp.status == 200*/) {
			document.getElementById("sms_update_target").innerHTML = xhttp.responseText;
		}
	}
	var params = '';
	params += 'center_id=' + document.getElementById("center_id").value;
	params += '&sport=' + document.getElementById("sport").value;
	params += '&class=' + document.getElementById("class").value;
	params += '&boarding_school=' + document.getElementById("boarding_school").value;
	params += '&subject=' + document.getElementById("subject").value;
	
	xhttp.open("POST", "<?php echo $this->url('sms/simulate') ?>", true);
	xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
	xhttp.setRequestHeader("Content-length", params.length);
	xhttp.setRequestHeader("Connection", "close");
	xhttp.send(params);
}

<?php if ($id) : ?>
simulate();
<?php endif;?>

//The elements are checked last to first so the focus is positionned on the first element on error
function messageForm() 
{
	var validity = true;

	// Subject
	subject = document.getElementById("subject").value;
	if (subject == '') {
	 	renderElement("subject", "<?php echo $this->translate('Please input a value', 'ppit-core', $context->getLocale()) ?>");
 		validity = false;
	}
	else if (subject.length > 160) {
	 	renderElement("subject", "<?php echo $this->translate('The input is too long', 'ppit-core', $context->getLocale()) ?>");
 		validity = false;
 	}
 	else {
 		renderElement("subject", null);
	}
	if (validity) {
		var data = new FormData();
		data.append('center_id', document.getElementById("center_id").value);
		data.append('sport', document.getElementById("sport").value);
		data.append('class', document.getElementById("class").value);
		data.append('boarding_school', document.getElementById("boarding_school").value);
		postForm("<?php echo $this->url('sms/update', array('id' => $id)) ?>", 'message_update_script', 'form_action', data);
		reload('<?php echo $this->url('sms') ?>', 'message_index_script', false);
	}
}

function messageSaveForm() 
{
	document.getElementById("action").value = 'save';
	return messageForm();
}

function messageTransmitForm() 
{
	document.getElementById("action").value = 'transmit';
	return messageForm();
}
</script>
