
function connectRemoveIcon(id, target)
{
	$('#' + id).click(function () {
		$('#' + target).hide();
		filterStudentList();
	});
}

function getParams() {
	// Create a new FormData object.
	var params = '?', todo = true;

	var status = document.getElementById('search_status').value;
	if (status) { params += 'status=' + status + '&'; todo = false; }
	
	var center_name = document.getElementById('search_center_name').value;
	if (center_name) { params += 'center_name=' + center_name + '&'; todo = false; }

	var n_fn = document.getElementById('search_n_fn').value;
	if (n_fn.length >= 2) { params += 'n_fn=' + n_fn + '&'; todo = false; }

	var min_school_year = document.getElementById('search_min_school_year').value;
	if (min_school_year.length >= 2) { params += 'min_school_year=' + min_school_year + '&'; todo = false; }

	var max_school_year = document.getElementById('search_max_school_year').value;
	if (max_school_year.length >= 2) { params += 'max_school_year=' + max_school_year + '&'; todo = false; }

<?php if ($config['ppitStudies']['sportOption']) : ?>
	var sport = document.getElementById('search_sport').value;
	if (sport.length >= 2) { params += 'sport=' + sport + '&'; todo = false; }

	var category = document.getElementById('search_category').value;
	if (category.length >= 2) { params += 'category=' + category + '&'; todo = false; }
<?php endif ?>

	var student_class = document.getElementById('search_class').value;
	if (student_class.length >= 2) { params += 'class=' + student_class + '&'; todo = false; }

<?php if (!$properties || array_key_exists('specialty', $properties)) : ?>
	var specialty = document.getElementById('search_specialty').value;
	if (specialty.length >= 2) { params += 'specialty=' + specialty + '&'; todo = false; }
<?php endif ?>

<?php if (!$properties || array_key_exists('boarding_school', $properties)) : ?>
	var boarding_school = document.getElementById('search_boarding_school').value;
	if (boarding_school.length >= 2) { params += 'boarding_school=' + boarding_school + '&'; todo = false; }
<?php endif ?>

<?php if (!$properties || array_key_exists('adr_city', $properties)) : ?>
	var adr_city = document.getElementById('search_adr_city').value;
	if (adr_city.length >= 2) { params += 'adr_city=' + adr_city + '&'; todo = false; }
<?php endif ?>

<?php if (!$properties || array_key_exists('adr_state', $properties)) : ?>
	var adr_state = document.getElementById('search_adr_state').value;
	if (adr_state.length >= 2) { params += 'adr_state=' + adr_state + '&'; todo = false; }
<?php endif ?>

<?php if (!$properties || array_key_exists('adr_country', $properties)) : ?>
	var adr_country = document.getElementById('search_adr_country').value;
	if (adr_country.length >= 2) { params += 'adr_country=' + adr_country + '&'; todo = false; }
<?php endif ?>

<?php if (!$properties || array_key_exists('sex', $properties)) : ?>
	var sex = document.getElementById('search_sex').value;
	if (sex != '') { params += 'sex=' + sex + '&'; todo = false; }
<?php endif ?>

<?php if (!$properties || array_key_exists('birth_date', $properties)) : ?>
	var min_birth_date = document.getElementById('search_min_birth_date').value;
	if (min_birth_date) min_birth_date = encodeDate(min_birth_date);
	if (min_birth_date.length >= 2) { params += 'min_birth_date=' + min_birth_date + '&'; todo = false; }

	var max_birth_date = document.getElementById('search_max_birth_date').value;
	if (max_birth_date) max_birth_date = encodeDate(max_birth_date);
	if (max_birth_date.length >= 2) { params += 'max_birth_date=' + max_birth_date + '&'; todo = false; }
<?php endif ?>

	$('#mode-text').text((todo) ? ' (<?php echo $this->translate('Todo list', 'ppit-studies', $context->getLocale()) ?>)' : '(<?php echo $this->translate('Search', 'ppit-core', $context->getLocale())?>)');

	return params;
}

// Export the list
function exportStudentList() {

	params = getParams();
	document.location.href = '<?php echo $this->url('student/export') ?>' + params;
}

function eraseStudentSearch() {
	$('#form_action').hide();
	$('#search_center_name').val('');
	$('#search_status').val('');
	$('#search_n_fn').val('');
	$('#search_min_school_year').val('');
	$('#search_max_school_year').val('');

<?php if ($config['ppitStudies']['sportOption']) : ?>
	$('#search_sport').val('');
	$('#search_category').val('');
<?php endif ?>

	$('#search_class').val('');

<?php if (!$properties || array_key_exists('specialty', $properties)) : ?>
	$('#search_specialty').val('');
<?php endif ?>

<?php if (!$properties || array_key_exists('boarding_school', $properties)) : ?>
	$('#search_boarding_school').val('');
<?php endif ?>
	
<?php if (!$properties || array_key_exists('adr_city', $properties)) : ?>
	$('#search_adr_city').val('');
<?php endif ?>

<?php if (!$properties || array_key_exists('adr_state', $properties)) : ?>
	$('#search_adr_state').val('');
<?php endif ?>

<?php if (!$properties || array_key_exists('adr_country', $properties)) : ?>
	$('#search_adr_country').val('');
<?php endif ?>

<?php if (!$properties || array_key_exists('sex', $properties)) : ?>
	$('#search_sex').val('');
<?php endif ?>

<?php if (!$properties || array_key_exists('birth_date', $properties)) : ?>
	$('#search_min_birth_date').val('');
	$('#search_max_birth_date').val('');
<?php endif ?>

	getStudentList(getParams(), 'n_fn', 'ASC');
}

function sortStudentList(criterion) {
	var dir;
	$('#form_action').hide();
	ascCriterion = $('.glyphicon-triangle-top').first().parent().attr('id');
	descCriterion = $('.glyphicon-triangle-bottom').first().parent().attr('id');
	if (criterion + '-anchor' == ascCriterion) dir = 'DESC'; else dir = 'ASC';
	getStudentList(getParams(), criterion, dir);
}

function filterStudentList() {
	$('#form_action').hide();
	ascCriterion = $('.glyphicon-triangle-top').first().parent().attr('id');
	descCriterion = $('.glyphicon-triangle-bottom').first().parent().attr('id');
	if (ascCriterion) {
		criterion = ascCriterion.split('-')[0];
		dir = 'ASC';
	}
	getStudentList(getParams(), criterion, dir);
}

function connectStudentSearchInputs() {
	$("#search_min_birth_date").datepicker();
	$("#search_max_birth_date").datepicker();

	$('#export-button').click(exportStudentList);
	
	//Events on search inputs

	$('#search_center_name').change(filterStudentList);

	$('#search_status').change(filterStudentList);

	$('#search_n_fn').keyup(function () { filterStudentList(); });
	$('#search_min_school_year').change(filterStudentList);
	$('#search_max_school_year').change(filterStudentList);

<?php if ($config['ppitStudies']['sportOption']) : ?>
	$('#search_sport').change(filterStudentList);
	$('#search_category').keyup(filterStudentList);
<?php endif ?>

	$('#search_class').keyup(filterStudentList);

<?php if (!$properties || array_key_exists('specialty', $properties)) : ?>
	$('#search_specialty').keyup(filterStudentList);
<?php endif ?>

<?php if (!$properties || array_key_exists('boarding_school', $properties)) : ?>
	$('#search_boarding_school').keyup(filterStudentList);
<?php endif ?>
	
<?php if (!$properties || array_key_exists('adr_city', $properties)) : ?>
	$('#search_adr_city').keyup(filterStudentList);
<?php endif ?>

<?php if (!$properties || array_key_exists('adr_state', $properties)) : ?>
	$('#search_adr_state').keyup(filterStudentList);
<?php endif ?>

<?php if (!$properties || array_key_exists('adr_country', $properties)) : ?>
	$('#search_adr_country').keyup(filterStudentList);
<?php endif ?>

<?php if (!$properties || array_key_exists('sex', $properties)) : ?>
	$('#search_sex').change(filterStudentList);
<?php endif ?>

<?php if (!$properties || array_key_exists('birth_date', $properties)) : ?>
	$('#search_min_birth_date').change(filterStudentList);
	$('#search_max_birth_date').change(filterStudentList);
<?php endif ?>

	$('#erase-button').click(eraseStudentSearch);
}

// Load the list
function getStudentList(params, major, dir) {		

	// Ensure the target is masked

	// Execute the ajax request
	route = '<?php echo $this->url('student/list') ?>' + params + '&major=' + major + ((dir =='ASC') ? '&dir=ASC' : '&dir=DESC');
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 <?php if (!$config['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('student-list-panel').innerHTML = xhttp.responseText;
<?php if ($config['ppitCoreSettings']['isTraceActive']) : ?>
			console.log('showing panel: student-list-panel, url = ' + route);
			console.log(xhttp.responseText);
<?php endif;?>
			
			// Connect the sort anchors
			$('.ppit-sort-anchor').each(function () {
				$(this).click(function () {
					sortStudentList($(this).attr('id').split('-')[0]);
				});
			});
	
			// Connect the search inputs
			connectStudentSearchInputs();

			// Connect the add anchor
			$('#student-add-anchor').click(function () {
				getStudentAdd();
			});
			
			// Connect the detail anchors
			$('.student-detail-anchor').each(function () {
				$(this).click(function () {
					getStudentDetail($(this).attr('id').split('_')[1]);
				});
			});
		}
	}
	xhttp.send();
}

////////////////////////////////
// Student add & update panel //
////////////////////////////////

<?php 
$properties = array();
$properties['living_language_2'] = array('type' => 'input', 'mandatory' => false, 'maxSize' => 255);
$properties['living_language_1'] = array('type' => 'input', 'mandatory' => false, 'maxSize' => 255);
$properties['mother_tongue'] = array('type' => 'input', 'mandatory' => false, 'maxSize' => 255);
$properties['orientation'] = array('type' => 'input', 'mandatory' => false, 'maxSize' => 255);
$properties['previous_quarter_average'] = array('type' => 'number', 'mandatory' => false, 'minValue' => 0, 'maxValue' => 20);
$properties['main_school'] = array('type' => 'input', 'mandatory' => false, 'maxSize' => 255);
$properties['previous_school'] = array('type' => 'input', 'mandatory' => false, 'maxSize' => 255);
$properties['previous_class'] = array('type' => 'input', 'mandatory' => false, 'maxSize' => 255);
$properties['observations'] = array('type' => 'textarea', 'mandatory' => false, 'maxSize' => 2047);
$properties['medical_examination_date'] = array('type' => 'date', 'mandatory' => false);
$properties['id_card_passport'] = array('type' => 'input', 'mandatory' => false, 'maxSize' => 255);
$properties['health_insurance'] = array('type' => 'input', 'mandatory' => false, 'maxSize' => 255);
$properties['parents_marital_status'] = array('type' => 'select', 'mandatory' => false, 'maxSize' => 255);
$properties['sisters_brothers'] = array('type' => 'input', 'mandatory' => false, 'maxSize' => 255);
$properties['nationality'] = array('type' => 'input', 'mandatory' => false, 'maxSize' => 255);
$properties['place_of_birth'] = array('type' => 'input', 'mandatory' => false, 'maxSize' => 255);
$properties['birth_date'] = array('type' => 'date', 'mandatory' => false);
$properties['emergency_phone_2'] = array('type' => 'phone', 'mandatory' => false);
$properties['emergency_phone_1'] = array('type' => 'phone', 'mandatory' => true);
$properties['boarding_school'] = array('type' => 'select', 'mandatory' => false);
$properties['specialty'] = array('type' => 'select', 'mandatory' => false);
$properties['class'] = array('type' => 'select', 'mandatory' => true);
$properties['school_year'] = array('type' => 'number', 'mandatory' => true, 'minValue' => 2014, 'maxValue' => '2999');
$properties['place_id'] = array('type' => 'select', 'mandatory' => true);
$properties['email'] = array('type' => 'email', 'mandatory' => true);
$properties['photo'] = array('type' => 'file');
$properties['n_last'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 255);
$properties['n_first'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 255);
$properties['status'] = array('type' => 'select', 'mandatory' => true);
$properties['update_time'] = array('type' => 'hidden');
echo $this->partial('/partials/check-update-properties', array('entity' => 'Student', 'context' => $context, 'properties' => $properties)) 
?>

function connectStudentUpdateForm(id)
{
<?php foreach ($properties as $property_id => $property) : ?>
	<?php if ($property['type'] == 'date') : ?>
		$('#input_<?php echo $property_id ?>').datepicker();
	<?php endif;?>
<?php endforeach ?>

	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {
		
		event.preventDefault();
	
		// Check validity
		var validity = checkStudentUpdateProperties(id);
	
		if (validity) {
		
			// Create a new FormData object.
			var formData = new FormData();
			
			// Get the properties values
<?php foreach ($properties as $property_id => $property) : ?>

	<?php if ($property['type'] == 'input' || $property['type'] == 'date' || $property['type'] == 'textarea' || $property['type'] == 'select' || $property['type'] == 'number' || $property['type'] == 'email' || $property['type'] == 'phone' || $property['type'] == 'hidden') : ?>
			formData.append('<?php echo $property_id ?>', document.getElementById('<?php echo $property_id ?>').value);

	<?php elseif ($property['type'] == 'checkbox') : ?>
			formData.append('<?php echo $property_id ?>', ((document.getElementById('<?php echo $property_id ?>').checked) ? 1 : 0));

	<?php elseif ($property['type'] == 'file') : ?>
			var fileSelect = document.getElementById('photo');
			if (fileSelect) {
				var files = fileSelect.files;
				for (var i = 0; i < files.length; i++) {
					var file = files[i];
					formData.append('photo', file, file.name);
				}
			}

	<?php endif ?>

<?php endforeach ?>

			var xhttp = new XMLHttpRequest();
			var route, target;
			if (id == 0) {
				route = '<?php echo $this->url('student/add') ?>';
				target = 'form_action';
			}
			else {
				route = '<?php echo $this->url('student/update') ?>/' + id;
				target = 'student-update-panel';
			}
			xhttp.open('POST', route, true);
			// Set up a handler for when the request finishes.
			xhttp.onload = function () {
				if (xhttp.readyState == 4 <?php if (!$context->getConfig()['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {

<?php if ($context->getConfig()['ppitCoreSettings']['isTraceActive']) : ?>
					console.log('post, route = ' + route);
					console.log(xhttp.responseText);
<?php endif;?>
					document.getElementById(target).innerHTML = xhttp.responseText;
					getStudentList('?', 'n_fn', 'ASC');
					connectRemoveIcon('remove-anchor', target);
					connectRemoveIcon('return-anchor', target);
				}
			};
			xhttp.send(formData);
		}
		else return false;
	}
}

function getStudentAdd() {
	
	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('student/add') ?>';
	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 <?php if (!$config['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('form_action').innerHTML = xhttp.responseText;
<?php if ($config['ppitCoreSettings']['isTraceActive']) : ?>
			console.log('form_action, route = ' + route);
			console.log(xhttp.responseText);
<?php endif;?>

			connectRemoveIcon('remove-anchor', 'form_action');
			connectStudentUpdateForm(0);
			connectRemoveIcon('cancel-anchor', 'form_action');
}
		
	}
	xhttp.send();
}

function getStudentUpdate(id) {

	$('.dropdown').removeClass("active");
	$('#student-dropdown').addClass("active");
	$('#student-dropdown-toggle').attr("aria-expanded", "true");
	$('.dropdown-item').removeClass("active");
	$('#student-inscription-dropdown-item').addClass("active");
	
	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('student/update') ?>/' + id;
	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 <?php if (!$config['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('student-update-panel').innerHTML = xhttp.responseText;
<?php if ($config['ppitCoreSettings']['isTraceActive']) : ?>
			console.log('student-update-panel, route = ' + route);
			console.log(xhttp.responseText);
<?php endif;?>
			
			connectRemoveIcon('remove-anchor', 'student-update-panel');
			connectStudentUpdateForm(id);
			connectRemoveIcon('cancel-anchor', 'student-update-panel');
}
		
	}
	xhttp.send();
}

// Load the student sport update panel
function getStudentSportUpdate(id) {
	$('.dropdown').removeClass("active");
	$('#student-dropdown').addClass("active");
	$('.dropdown-item').removeClass("active");
	$('#student-dropdown-item').addClass("active");
	
	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('student/updateSport') ?>/' + id;
	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 <?php if (!$config['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('student-update-panel').innerHTML = xhttp.responseText;
<?php if ($config['ppitCoreSettings']['isTraceActive']) : ?>
			console.log('student-update-panel, route = ' + route);
			console.log(xhttp.responseText);
<?php endif;?>
		}
	}
	xhttp.send();
}

// Load the main contact update panel
function getStudentMainContactUpdate(id) {
	$('.dropdown').removeClass("active");
	$('#contacts-dropdown').addClass("active");
	$('.dropdown-item').removeClass("active");
	$('#student-main-contact-dropdown-item').addClass("active");
	
	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('student/updateMainContact') ?>/' + id;
	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 <?php if (!$config['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('student-update-panel').innerHTML = xhttp.responseText;
<?php if ($config['ppitCoreSettings']['isTraceActive']) : ?>
			console.log('student-update-panel, route = ' + route);
			console.log(xhttp.responseText);
<?php endif;?>
		}
	}
	xhttp.send();
}

// Load the backup contact update panel
function getStudentBackupContactUpdate(id) {
	$('.dropdown').removeClass("active");
	$('#contacts-dropdown').addClass("active");
	$('.dropdown-item').removeClass("active");
	$('#student-backup-contact-dropdown-item').addClass("active");
	
	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('student/updateBackupContact') ?>/' + id;
	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 <?php if (!$config['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('student-update-panel').innerHTML = xhttp.responseText;
<?php if ($config['ppitCoreSettings']['isTraceActive']) : ?>
			console.log('student-update-panel, route = ' + route);
			console.log(xhttp.responseText);
<?php endif;?>
		}
	}
	xhttp.send();
}

// Load the bill contact update panel
function getStudentBillContactUpdate(id) {
	$('.dropdown').removeClass("active");
	$('#contacts-dropdown').addClass("active");
	$('.dropdown-item').removeClass("active");
	$('#student-bill-contact-dropdown-item').addClass("active");
	
	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('student/updateBillContact') ?>/' + id;
	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 <?php if (!$config['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('student-update-panel').innerHTML = xhttp.responseText;
<?php if ($config['ppitCoreSettings']['isTraceActive']) : ?>
			console.log('student-update-panel, route = ' + route);
			console.log(xhttp.responseText);
<?php endif;?>
		}
	}
	xhttp.send();
}

//////////////////////////
// Student delete panel //
//////////////////////////

function connectStudentDeleteForm(id)
{
	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {
		
		event.preventDefault();
		
		// Create a new FormData object.
		var formData = new FormData();
		formData.append('update_time', document.getElementById('update_time').value);

		var xhttp = new XMLHttpRequest();
		var route = '<?php echo $this->url('student/delete') ?>/' + id;
		xhttp.open('POST', route, true);
		// Set up a handler for when the request finishes.
		xhttp.onload = function () {
			if (xhttp.readyState == 4 <?php if (!$context->getConfig()['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {

<?php if ($context->getConfig()['ppitCoreSettings']['isTraceActive']) : ?>
				console.log('post, route = ' + route);
				console.log(xhttp.responseText);
<?php endif;?>
				document.getElementById('form_action').innerHTML = xhttp.responseText;
				getStudentList('?', 'n_fn', 'ASC');
				connectRemoveIcon('remove-anchor', 'form_action');
				connectRemoveIcon('return-anchor', 'form_action');
			}
		};
		xhttp.send(formData);
	}
}

function getStudentDelete(id) {
	
	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('student/delete') ?>/' + id;
	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 <?php if (!$config['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('form_action').innerHTML = xhttp.responseText;
<?php if ($config['ppitCoreSettings']['isTraceActive']) : ?>
			console.log('form_action, route = ' + route);
			console.log(xhttp.responseText);
<?php endif;?>
			
			connectRemoveIcon('remove-anchor', 'form_action');
			connectStudentDeleteForm(id);
			connectRemoveIcon('cancel-anchor', 'form_action');
		}
	}
	xhttp.send();
}

/////////////////////////////
// Student duplicate panel //
/////////////////////////////

function connectStudentDuplicateForm(id)
{
	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {
		
		event.preventDefault();
		
		// Create a new FormData object.
		var formData = new FormData();

		var xhttp = new XMLHttpRequest();
		var route = '<?php echo $this->url('student/duplicate') ?>/' + id;
		xhttp.open('POST', route, true);
		// Set up a handler for when the request finishes.
		xhttp.onload = function () {
			if (xhttp.readyState == 4 <?php if (!$context->getConfig()['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {

<?php if ($context->getConfig()['ppitCoreSettings']['isTraceActive']) : ?>
				console.log('post, route = ' + route);
				console.log(xhttp.responseText);
<?php endif;?>
				document.getElementById('form_action').innerHTML = xhttp.responseText;
				getStudentList('?', 'n_fn', 'ASC');
				connectRemoveIcon('remove-anchor', 'form_action');
				connectRemoveIcon('return-anchor', 'form_action');
			}
		};
		xhttp.send(formData);
	}
}

function getStudentDuplicate(id) {
	
	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('student/duplicate') ?>/' + id;
	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 <?php if (!$config['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('form_action').innerHTML = xhttp.responseText;
<?php if ($config['ppitCoreSettings']['isTraceActive']) : ?>
			console.log('form_action, route = ' + route);
			console.log(xhttp.responseText);
<?php endif;?>
			
			connectRemoveIcon('remove-anchor', 'form_action');
			connectStudentDeleteForm(id);
			connectRemoveIcon('cancel-anchor', 'form_action');
		}
	}
	xhttp.send();
}

//////////////////////////
// Student detail panel //
//////////////////////////

// Load the detail panel
function getStudentDetail(id) {

	// Ensure the target is displayed
	$('#form_action').show();

	// Anchor to the new panel
	$(location).attr('hash', 'form_action');

	// Execute the ajax request
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", '<?php echo $this->url('student/detail') ?>/' + id, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 && xhttp.status == 200) {
			document.getElementById('form_action').innerHTML = xhttp.responseText;
	<?php if ($config['ppitCoreSettings']['isTraceActive']) : ?>
			console.log('showing panel: form_action, url = <?php echo $this->url('student/detail') ?>/' + id);
			console.log(xhttp.responseText);
	<?php endif;?>

			connectRemoveIcon('remove-anchor', 'form_action');
			$('#delete-anchor').click(function() { getStudentDelete(id); });
			$('#duplicate-anchor').click(function() { getStudentDuplicate(id); });
			$('#student-inscription-anchor').click(function() { getStudentUpdate(id); });
			$('#student-anchor').click(function() { getStudentUpdate(id); });
			$('#student-main-contact-anchor').click(function() { getStudentMainContactUpdate(id); });
			$('#student-backup-contact-anchor').click(function() { getStudentBackupContactUpdate(id); });
			$('#student-bill-contact-anchor').click(function() { getStudentBillContactUpdate(id); });
			getStudentUpdate(id);

			// Highlight the clicked button (and only it in its class)
			$('.student-detail-anchor').removeClass("btn-primary").addClass("btn-default");
			$('#student-detail-anchor_' + id).removeClass("btn-default").addClass("btn-primary");
		}
	}
	xhttp.send();
}

function activateStudent() {

	// Load the search panel and highlight the menu entry
	$('#form_action').hide();
	loadPanel('index_action', '<?php echo $this->url('student/search') ?>');
	$('.menu-btn').removeClass("btn-primary").addClass("btn-default");
	$('#student-anchor').removeClass("btn-default").addClass("btn-primary");
	$('#mode-text').text(' (<?php echo $this->translate('Todo list', 'ppit-studies', $context->getLocale()) ?>)');
	
	getStudentList('?', 'n_fn', 'ASC');
	
	$('#add-criteria').click(function () {
		$('#search-area').show();
		$('#add-criteria').hide();
	});
	$('#search-area').hide();
}
$('#student-anchor').click(activateStudent);
