
function connectRemoveIcon(id, target)
{
	$('#' + id).click(function () {
		$('#' + target).hide();
		$('.account-checkbox').attr('disabled', null);
        $('.account-checkbox-all').attr('disabled', null);
		$('.index-btn').removeClass("btn-primary").addClass("btn-default");
	});
}

function getParams() {

	var params = '?', todo = true;

<?php foreach ($context->getConfig('student/search')['main'] as $propertyId => $rendering) : ?>

	<?php if ($rendering == 'range') : ?>
	
	var min_<?php echo $propertyId ?> = document.getElementById('search_min_<?php echo $propertyId ?>').value;
	if (min_<?php echo $propertyId ?>) min_<?php echo $propertyId ?> = encodeDate(min_<?php echo $propertyId ?>);
	if (min_<?php echo $propertyId ?>.length >= 2) { params += 'min_<?php echo $propertyId ?>=' + min_<?php echo $propertyId ?> + '&'; todo = false; }

	var max_<?php echo $propertyId ?> = document.getElementById('search_max_<?php echo $propertyId ?>').value;
	if (max_<?php echo $propertyId ?>) max_<?php echo $propertyId ?> = encodeDate(max_<?php echo $propertyId ?>);
	if (max_<?php echo $propertyId ?>.length >= 2) { params += 'max_<?php echo $propertyId ?>=' + max_<?php echo $propertyId ?> + '&'; todo = false; }

	<?php elseif ($rendering == 'select') : ?>

	var <?php echo $propertyId ?> = $('#search_<?php echo $propertyId ?>').val();
	if (<?php echo $propertyId ?>) { params += '<?php echo $propertyId ?>=' + <?php echo $propertyId ?> + '&'; todo = false; }

	<?php else : ?>

	var prop_<?php echo $propertyId ?> = document.getElementById('search_<?php echo $propertyId ?>').value;
	if (prop_<?php echo $propertyId ?>.length >= 2) { params += '<?php echo $propertyId ?>=' + prop_<?php echo $propertyId ?> + '&'; todo = false; }
	
	<?php endif;?>

<?php endforeach;?>

	<?php
	$todoTitle = (isset ($context->getConfig('student/search')['todoTitle']) ? $context->getConfig('student/search')['todoTitle'][$context->getLocale()] : $this->translate('active', 'ppit-core', $context->getLocale()));
	$searchTitle = (isset ($context->getConfig('student/search')['searchTitle']) ? $context->getConfig('student/search')['searchTitle'][$context->getLocale()] : $this->translate('search', 'ppit-core', $context->getLocale()));
	?>
	$('#mode-text').text((todo) ? '<?php echo $todoTitle ?>' : '<?php echo $searchTitle ?>');
	if (!todo) $('#limit').val('');

	return params;
}

function sortStudentList(criterion) {

	var dir;
	ascCriterion = $('.glyphicon-triangle-top').first().parent().attr('id');
	descCriterion = $('.glyphicon-triangle-bottom').first().parent().attr('id');
	if (criterion + '-anchor' == ascCriterion) dir = 'DESC'; else dir = 'ASC';
	getStudentList(getParams(), criterion, dir);
}

function filterStudentList() {

	ascCriterion = $('.glyphicon-triangle-top').first().parent().attr('id');
	descCriterion = $('.glyphicon-triangle-bottom').first().parent().attr('id');
	if (ascCriterion) {
		criterion = ascCriterion.split('-')[0];
		dir = 'ASC';
	}
	else {
		criterion = descCriterion.split('-')[0];
		dir = 'ASC';
	}
	getStudentList(getParams(), criterion, dir);
}

function connectStudentSearchInputs() {

  $('#erase-button').click(function () {
    $('.search_input').val('');
    $('.selectpicker').selectpicker('deselectAll');
    $('.search_check').attr('checked', false);
    getStudentList(getParams(), 'n_fn', 'ASC');
  });

<?php foreach ($context->getConfig('student/search')['main'] as $propertyId => $rendering) : ?>
  <?php 
  $property = $context->getConfig('core_account/p-pit-studies/property/'.$propertyId);
  if ($property['definition'] != 'inline') $property = $context->getConfig($property['definition']);
  ?>

  <?php if ($rendering == 'range') : ?>

  $('#search_check_min_<?php echo $propertyId ?>').change(function () {
    if (!document.getElementById('search_check_min_<?php echo $propertyId ?>').checked) {
      $('#search_min_<?php echo $propertyId ?>').val('');
      filterStudentList(); 
    }
  });
  $('#search_min_<?php echo $propertyId ?>').keyup(function () { 
    document.getElementById('search_check_min_<?php echo $propertyId ?>').checked = true; 
    filterStudentList(); 
  });
  
  $('#search_check_max_<?php echo $propertyId ?>').change(function () {
    if (!document.getElementById('search_check_max_<?php echo $propertyId ?>').checked) {
      $('#search_max_<?php echo $propertyId ?>').val('');
      filterStudentList(); 
    }
  });
  $('#search_max_<?php echo $propertyId ?>').keyup(function () { 
    document.getElementById('search_check_max_<?php echo $propertyId ?>').checked = true; 
    filterStudentList(); 
  });

		<?php if ($property['type'] == 'date') : ?>
	$("#search_min_<?php echo $propertyId ?>").datepicker();
	$("#search_max_<?php echo $propertyId ?>").datepicker();
	$('#search_min_<?php echo $propertyId ?>').change(function () { filterStudentList(); });
	$('#search_max_<?php echo $propertyId ?>').change(function () { filterStudentList(); });
		<?php endif;?>
	
	<?php elseif ($rendering == 'select') : ?>
  $('#search_check_<?php echo $propertyId ?>').change(function () {
    if (!document.getElementById('search_check_<?php echo $propertyId ?>').checked) {
      $('#search_<?php echo $propertyId ?>').val('');
      $('#search_<?php echo $propertyId ?>').selectpicker('deselectAll');
      filterStudentList(); 
    }
  });
  $('#search_<?php echo $propertyId ?>').change(function () { 
    document.getElementById('search_check_<?php echo $propertyId ?>').checked = true; 
    filterStudentList(); 
  });
	
	<?php else : ?>
  $('#search_check_<?php echo $propertyId ?>').change(function () {
    if (!document.getElementById('search_check_<?php echo $propertyId ?>').checked) {
      $('#search_<?php echo $propertyId ?>').val('');
      filterStudentList(); 
    }
  });
  $('#search_<?php echo $propertyId ?>').keyup(function () { 
    document.getElementById('search_check_<?php echo $propertyId ?>').checked = true; 
    filterStudentList(); 
  });

		<?php if ($property['type'] == 'date') : ?>
	$("#search_<?php echo $propertyId ?>").datepicker();
	$('#search_<?php echo $propertyId ?>').change(function () { filterStudentList(); });
		<?php endif;?>

	<?php endif;?>

<?php endforeach;?>
}

// Load the list
function getStudentList(params, major, dir) {		

	// Execute the ajax request
	route = '<?php echo $this->url('student/list') ?>' + params + '&major=' + major + ((dir =='ASC') ? '&dir=ASC' : '&dir=DESC') + '&limit=' + $('#limit').val();
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById('account-list-panel').innerHTML = xhttp.responseText;

			$('.detail-row').hide();
			$('.invisible').hide();
			
			$(function () {
			    $('.tip').tooltip({
			        content: function () {
			            return $(this).prop('title');
			        }
			    });
			});
			
			// Connect the sort anchors
			$('.ppit-sort-anchor').each(function () {
				$(this).click(function () {
					sortStudentList($(this).attr('id').split('-')[0]);
				});
			});

			// Connect the more anchor
			$('#account-more-anchor').click(function () {
				$('#limit').val('');
				filterStudentList();
			});

			// Able the group action button
			$('.account-checkbox').click(function () {
				$('.account-group-anchor').removeAttr('disabled');
			});

			// Connect the check all checkbox
		    $('.account-checkbox-all').click(function () {
                let current = $(this).prop('checked');
	            $('.account-checkbox').prop('checked', (current) ? true : false);
	            $('.account-checkbox-all').prop('checked', (current) ? true : false);
	            $('.account-group-anchor').prop('disabled', false);
			});
			
			// Connect the grouped actions anchors
			$('.account-group-anchor').each(function () {
				$(this).click(function () {
					getStudentGroup();
				});
			});
			
			// Connect the detail anchors
			$('.account-detail-anchor').each(function () {
				$(this).click(function () {
					getStudentHome($(this).attr('id').split('_')[1]);
				});
			});
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();
}

// Retrieve the events
function getEvents(id) {

	// Execute the ajax request
	route = '<?php echo $this->url('studentEvent/planning') ?>?account_id=' + id;
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
		    $('#calendar').fullCalendar({
		    	lang: '<?php echo substr($context->getLocale(), 0, 2) ?>',
		        defaultView: 'agendaWeek',
		        minTime: '08:00:00'
		    });
			obj = jQuery.parseJSON(xhttp.responseText);

			jQuery.each(obj.planning, function (name, value) {
				var color = 'lightBlue', textColor = 'black';			
<?php foreach ($context->getConfig('commitmentEvent/p-pit-studies')['category'] as $categoryId => $category) : ?>
	<?php foreach ($category['color'] as $color => $unused) : ?>
				if (value.properties['category'] == '<?php echo $categoryId ?>') {
					color = '<?php echo $color ?>';
					textColor = 'white';
				}
	<?php endforeach;?>
<?php endforeach;?>

				var title = '';
				if (value.properties['property_3']) title += value.properties['property_3'];
				if (value.properties['property_3'] && value.properties['caption']) title += ' - ';
				if (value.properties['caption']) title += value.properties['caption'];
				if (value.properties['location']) title += ' (' + value.properties['location'] + ')';
				var event={
					id:value.id,
					title: title,
					color: color,
					textColor: textColor,
					start:  $.fullCalendar.moment(value.properties['begin_date'] + ' ' + value.properties['begin_time']), 
					end:  $.fullCalendar.moment(value.properties['begin_date'] + ' ' + value.properties['end_time'])
				};
				$('#calendar').fullCalendar('renderEvent', event, true);
			});

			jQuery.each(obj.events, function (name, value) {
				var color = 'lightBlue', textColor = 'black';			
<?php foreach ($context->getConfig('commitmentEvent/p-pit-studies')['category'] as $categoryId => $category) : ?>
	<?php foreach ($category['color'] as $color => $unused) : ?>
				if (value.category == '<?php echo $categoryId ?>') {
					color = '<?php echo $color ?>';
					textColor = 'white';
				}
	<?php endforeach;?>
<?php endforeach;?>

				var event={
					id:value.id,
					title: value.title + ' (' + value.location + ')',
					color: color,
					textColor: textColor,
					start:  $.fullCalendar.moment(value.begin_time), 
					end:  $.fullCalendar.moment(value.end_time)
				};
				$('#calendar').fullCalendar('renderEvent', event, true);
			});
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();
}

// Load the detail panel
function connectNewsFlashTab(route, id) {

	// Execute the ajax request
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById('news_flash-panel').innerHTML = xhttp.responseText;
			getEvents(id);
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();
}

// Load the detail panel
function connectStudentTab(route) {
	var isAbsenceOpen = false, isLatenessOpen = false, isEventOpen = true, isHomeworkOpen = true, isEvaluationOpen = true;

	// Execute the ajax request
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById('news_flash-panel').innerHTML = xhttp.responseText;
			
			$('#absence-panel').hide(); 
			$('#absence-button').click(function() { 
				if (isAbsenceOpen) {
					$('#absence-panel').hide(); 
					$('#absence-button').removeClass('glyphicon-triangle-bottom').addClass('glyphicon-triangle-right');
					isAbsenceOpen = false;
				}
				else {
					$('#absence-panel').show(); 
					$('#absence-button').removeClass('glyphicon-triangle-right').addClass('glyphicon-triangle-bottom');
					isAbsenceOpen = true;
				}
			});

			$('#lateness-panel').hide(); 
			$('#lateness-button').click(function() { 
				if (isLatenessOpen) {
					$('#lateness-panel').hide(); 
					$('#lateness-button').removeClass('glyphicon-triangle-bottom').addClass('glyphicon-triangle-right');
					isLatenessOpen = false;
				}
				else {
					$('#lateness-panel').show(); 
					$('#lateness-button').removeClass('glyphicon-triangle-right').addClass('glyphicon-triangle-bottom');
					isLatenessOpen = true;
				}
			});

			$('#event-button').click(function() { 
				if (isEventOpen) {
					$('#event-panel').hide(); 
					$('#event-button').removeClass('glyphicon-triangle-bottom').addClass('glyphicon-triangle-right');
					isEventOpen = false;
				}
				else {
					$('#event-panel').show(); 
					$('#event-button').removeClass('glyphicon-triangle-right').addClass('glyphicon-triangle-bottom');
					isEventOpen = true;
				}
			});

			$('#homework-button').click(function() { 
				if (isHomeworkOpen) {
					$('#homework-panel').hide(); 
					$('#homework-button').removeClass('glyphicon-triangle-bottom').addClass('glyphicon-triangle-right');
					isHomeworkOpen = false;
				}
				else {
					$('#homework-panel').show(); 
					$('#homework-button').removeClass('glyphicon-triangle-right').addClass('glyphicon-triangle-bottom');
					isHomeworkOpen = true;
				}
			});

			$('#evaluation-button').click(function() { 
				if (isEvaluationOpen) {
					$('#evaluation-panel').hide(); 
					$('#evaluation-button').removeClass('glyphicon-triangle-bottom').addClass('glyphicon-triangle-right');
					isEvaluationOpen = false;
				}
				else {
					$('#evaluation-panel').show(); 
					$('#evaluation-button').removeClass('glyphicon-triangle-right').addClass('glyphicon-triangle-bottom');
					isEvaluationOpen = true;
				}
			});

			$('.report-button').click(function() { 
				id = $(this).attr('id').split('_')[1];
				if ($('#is-report-open_' + id).val() == 1) {
					$('#report-panel_' + id).hide(); 
					$('#report-button_' + id).removeClass('glyphicon-triangle-bottom').addClass('glyphicon-triangle-right');
					$('#is-report-open_' + id).val(0);
				}
				else {
					$('#report-panel_' + id).show(); 
					$('#report-button_' + id).removeClass('glyphicon-triangle-right').addClass('glyphicon-triangle-bottom');
					$('#is-report-open_' + id).val(1);
				}
			});
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();
}

// Load the detail panel
function getStudentHome(id) {

	// Ensure the target is displayed
	$('#form_action').show();

	var route = '<?php echo $this->url('student/studentHome') ?>/' + id;

	// Execute the ajax request
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById('detail-div_' + id).innerHTML = xhttp.responseText;
			connectRemoveIcon('remove-anchor_' + id, 'detail-row_' + id);

			// Ensure the target is displayed
			$('.detail-row').hide();
			$('#detail-row_' + id).show();
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?> 
		}
	}
	xhttp.send();

	// Highlight the clicked button (and only it in its class)
	$('.index-btn').removeClass("btn-primary").addClass("btn-default");
	$('#account-detail-anchor_' + id).removeClass("btn-default").addClass("btn-primary");
}

/////////////////////////
// student/addAbsence //
/////////////////////////

<?php 
$properties = array();
$properties['category'] = array('type' => 'select', 'mandatory' => true);
$properties['school_period'] = array('type' => 'select', 'mandatory' => true);
$properties['motive'] = array('type' => 'select', 'mandatory' => false);
$properties['begin_date'] = array('type' => 'date', 'mandatory' => true);
$properties['end_date'] = array('type' => 'date', 'mandatory' => false);
$properties['duration'] = array('type' => 'number', 'mandatory' => false, 'minValue' => 0, 'maxValue' => 999);
$properties['subject'] = array('type' => 'select', 'mandatory' => false);
$properties['observations'] = array('type' => 'textarea', 'mandatory' => false, 'maxSize' => 2047);
$properties['comment'] = array('type' => 'textarea', 'mandatory' => false, 'maxSize' => 2047);
$properties['update_time'] = array('type' => 'hidden');
echo $this->partial('/partials/check-update-properties', array('entity' => 'Absence', 'context' => $context, 'properties' => $properties)) 
?>

<?php foreach ($context->getConfig('absence')['types'] as $typeId => $type) : ?>

function connectAdd<?php echo $typeId ?>AbsenceForm()
{
	$('#input_begin_date').datepicker();
	$('#input_end_date').datepicker();

	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {
		
		event.preventDefault();

		// Check validity
		var validity = checkAbsenceUpdateProperties();

		if (validity) {
            var xhttp = new XMLHttpRequest();
            var route, target;
            route = '<?php echo $this->url('student/addAbsence', array('type' => $typeId)) ?>?';
            target = 'grouped-action-panel';
/*
			var criteriaNumber = $('#group-nb-criteria').val();
			for (i = 0; i < criteriaNumber; i++) {
				formData.append('criterion-id_' + i, $('#group-criterion-id_' + i).val());
				formData.append('criterion_' + i, $('#group-criterion_' + i).val());
			}
			formData.append('nb-criteria', i);*/

	    route += '&accounts=';
	    let first = true;
	    $('.account-checkbox').each(function () {
	        let account_id = $(this).attr('id').split('_')[1];
			if ($(this).prop('checked')) {
	            if (!first) route += ',';
	            first = false;
	            route += account_id;
			}
		});
    
      // Create a new FormData object.
      var formData = new FormData();
			
			// Get the properties values
<?php foreach ($properties as $propertyId => $property) : ?>
				formData.append('<?php echo $propertyId ?>', $('#<?php echo $propertyId ?>').val());
<?php endforeach ?>
			formData.append('duration', $('#duration').val());

			xhttp.open('POST', route, true);
			// Set up a handler for when the request finishes.
			xhttp.onload = function () {
				if (xhttp.readyState == 4 <?php if (!$context->getConfig()['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
					document.getElementById(target).innerHTML = xhttp.responseText;
					$('.action-btn').removeClass('btn-primary').addClass('btn-default');
					if ($('#category').val() != 'absence') $('#input_end_date_group').hide();
					$('#category').change(function () {
						if ($('#category').val() == 'absence') $('#input_end_date_group').show();
						else $('#input_end_date_group').hide();
					});
				}
			};
			xhttp.send(formData);
		}
		else return false;
	}
}

function getAdd<?php echo $typeId?>Absence() {
	
	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('student/addAbsence', array('type' => $typeId)) ?>?';

	    route += '&accounts=';
	    let first = true;
	    $('.account-checkbox').each(function () {
	        let account_id = $(this).attr('id').split('_')[1];
			if ($(this).prop('checked')) {
	            if (!first) route += ',';
	            first = false;
	            route += account_id;
			}
		});

	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById('grouped-action-panel').innerHTML = xhttp.responseText;			
			connectAdd<?php echo $typeId ?>AbsenceForm();
			if ($('#category').val() != 'absence') $('#input_end_date_group').hide();
			$('#category').change(function () {
				if ($('#category').val() == 'absence') $('#input_end_date_group').show();
				else $('#input_end_date_group').hide();
			});
			$('#category').focus();

<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();

	// Highlight the clicked button (and only it in its class)
	$('.action-btn').removeClass("btn-primary").addClass("btn-default");
	$('#<?php echo $typeId ?>-absence-add-anchor').removeClass("btn-default").addClass("btn-primary");
}

<?php endforeach;?>

//////////////////////
// student/addEvent //
//////////////////////

<?php 
$properties = array();

$properties['begin_date'] = array('type' => 'date', 'mandatory' => false);
$properties['begin_h'] = array('type' => 'select', 'mandatory' => false);
$properties['begin_m'] = array('type' => 'select', 'mandatory' => false);
$properties['end_date'] = array('type' => 'date', 'mandatory' => false);
$properties['end_h'] = array('type' => 'select', 'mandatory' => false);
$properties['end_m'] = array('type' => 'select', 'mandatory' => false);
$properties['location'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 65535);
$properties['title'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 65535);
$properties['comment'] = array('type' => 'textarea', 'mandatory' => false, 'maxSize' => 2047);

echo $this->partial('/partials/check-update-properties', array('entity' => 'Event', 'context' => $context, 'properties' => $properties)) 
?>

function connectAddEventForm(category)
{
	$('#input_begin_date').datepicker();
	$('#input_end_date').datepicker();

	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {
		
		event.preventDefault();

		// Check validity
		var validity = checkEventUpdateProperties();

		if (validity) {
		
			// Create a new FormData object.
			var formData = new FormData();

			var criteriaNumber = $('#group-nb-criteria').val();
			for (i = 0; i < criteriaNumber; i++) {
				formData.append('criterion-id_' + i, $('#group-criterion-id_' + i).val());
				formData.append('criterion_' + i, $('#group-criterion_' + i).val());
			}
			formData.append('nb-criteria', i);

			var accountNumber = $('#group-nb-account').val();
			for (var i = 0; i < accountNumber; i++) {
				account_id = $('#group-account_' + i).val();
				formData.append('account_' + i, account_id);
			}
			formData.append('nb-account', accountNumber);
			
			// Get the properties values
<?php foreach ($properties as $propertyId => $property) : ?>
				formData.append('<?php echo $propertyId ?>', document.getElementById('<?php echo $propertyId ?>').value);
<?php endforeach ?>

			var xhttp = new XMLHttpRequest();
			var route, target;
			route = '<?php echo $this->url('student/addEvent') ?>/' + category;
			target = 'grouped-action-panel';
			xhttp.open('POST', route, true);
			// Set up a handler for when the request finishes.
			xhttp.onload = function () {
				if (xhttp.readyState == 4 <?php if (!$context->getConfig()['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
					document.getElementById(target).innerHTML = xhttp.responseText;
					$('.action-btn').removeClass('btn-primary').addClass('btn-default');
				}
			};
			xhttp.send(formData);
		}
		else return false;
	}
}

function getAddEvent(category) {
	
	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('student/addEvent') ?>/' + category;
	var formData = new FormData();

	var criteriaNumber = $('#group-nb-criteria').val();
	for (i = 0; i < criteriaNumber; i++) {
		formData.append('criterion-id_' + i, $('#group-criterion-id_' + i).val());
		formData.append('criterion_' + i, $('#group-criterion_' + i).val());
	}
	formData.append('nb-criteria', i);

	var accountNumber = $('#account-number').val();
	for (i = 0, j = 0; i < accountNumber; i++) {
		if (document.getElementById('account-checkbox_' + i).checked) {
			formData.append('account_' + j, $('#account_' + i).val());
			j++;
		}
	}
	formData.append('nb-account', j);

	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById('grouped-action-panel').innerHTML = xhttp.responseText;
			connectAddEventForm(category);
			$('#subject').focus();
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();

	// Highlight the clicked button (and only it in its class)
	$('.action-btn').removeClass("btn-primary").addClass("btn-default");
	$('#' + category + '-event-add-anchor').removeClass("btn-default").addClass("btn-primary");
}

/////////////////////
// student/addNote //
/////////////////////

<?php 
$properties = array();
$properties['place_id'] = array('type' => 'select', 'mandatory' => true);
$properties['class'] = array('type' => 'select', 'mandatory' => true);
$properties['school_period'] = array('type' => 'select', 'mandatory' => true);
$properties['subject'] = array('type' => 'select', 'mandatory' => true);
$properties['date'] = array('type' => 'date', 'mandatory' => true);
$properties['type'] = array('type' => 'select', 'mandatory' => true);
$properties['target_date'] = array('type' => 'date', 'mandatory' => true);
$properties['observations'] = array('type' => 'ckeditor', 'mandatory' => true, 'maxSize' => 2047);
$properties['document'] = array('type' => 'dropbox', 'mandatory' => false);
$properties['comment'] = array('type' => 'textarea', 'mandatory' => false, 'maxSize' => 2047);
$properties['update_time'] = array('type' => 'hidden');
echo $this->partial('/partials/check-update-properties', array('entity' => 'Note', 'context' => $context, 'properties' => $properties)) 
?>

var currentPlaceId = '', currentClass = '', currentSubject = '', currentType = '';

function connectAddNoteForm(classe)
{
	$('#input_date').datepicker();
	$('#input_target_date').datepicker();

	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {
		
		event.preventDefault();

		// Check validity
		var validity = checkNoteUpdateProperties();

		if (validity) {
		    var xhttp = new XMLHttpRequest();
		    var route, target;
	        route = '<?php echo $this->url('student/addNote', array('type' => 'homework')) ?>?';
		    if (classe) route += '&class=' + classe;
		    target = 'grouped-action-panel';
/*			
			var criteriaNumber = $('#group-nb-criteria').val();
			for (i = 0; i < criteriaNumber; i++) {
			  route += '&' + $('#group-criterion-id_' + i).val() + '=' + $('#group-criterion_' + i).val();
	  		}*/

  	    route += '&accounts=';
  	    let first = true;
  	    $('.account-checkbox').each(function () {
  	        let account_id = $(this).attr('id').split('_')[1];
  			if ($(this).prop('checked')) {
  	            if (!first) route += ',';
  	            first = false;
  	            route += account_id;
  			}
  		});

		    // Create a new FormData object.
		    var formData = new FormData();

			// Get the properties values
<?php foreach ($properties as $propertyId => $property) : ?>
	<?php if ($property['type'] == 'ckeditor') : ?>
			formData.append('<?php echo $propertyId ?>', CKEDITOR.instances.<?php echo $propertyId ?>.getData());
	<?php else : ?>	
				formData.append('<?php echo $propertyId ?>', document.getElementById('<?php echo $propertyId ?>').value);
	<?php endif;?>
    <?php if ($propertyId == 'place_id') : ?>
                currentPlaceId = $('#place_id').val();
    <?php elseif ($propertyId == 'class') : ?>
                currentClass = $('#class').val();
    <?php elseif ($propertyId == 'school_period') : ?>
                currentPeriod = $('#school_period').val();
    <?php elseif ($propertyId == 'subject') : ?>
                currentSubject = $('#subject').val();
    <?php elseif ($propertyId == 'type') : ?>
                currentType = $('#type').val();
    <?php endif;?>
<?php endforeach ?>

			xhttp.open('POST', route, true);
			// Set up a handler for when the request finishes.
			xhttp.onload = function () {
				if (xhttp.readyState == 4 <?php if (!$context->getConfig()['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
					document.getElementById(target).innerHTML = xhttp.responseText;
					$('.action-btn').removeClass('btn-primary').addClass('btn-default');

					CKEDITOR.replace('observations');
			
					if ($('#type').val() == 'done-work') {
						$('#input_target_date_group').hide();
						$('#observations_group').css('background-color', '<?php echo $context->getConfig('note/colour')['done-work'] ?>');
					}
					else if ($('#type').val() == 'todo-work') {
						$('#input_target_date_group').show();
						$('#observations_group').css('background-color', '<?php echo $context->getConfig('note/colour')['todo-work'] ?>');
					}
					else {
						$('#input_target_date_group').show();
						$('#observations_group').css('background-color', '<?php echo $context->getConfig('note/colour')['event'] ?>');
					}
				}
			};
			xhttp.send(formData);
		}
		else return false;
	}
}

function getAddNote(classe) {
	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('student/addNote', array('type' => 'homework')) ?>?';
	if (classe) route += '&class=' + classe;
/*
	var criteriaNumber = $('#group-nb-criteria').val();
	for (i = 0; i < criteriaNumber; i++) {
        route += '&' + $('#group-criterion-id_' + i).val() + '=' + $('#group-criterion_' + i).val();
	}*/

  	    route += '&accounts=';
  	    let first = true;
  	    $('.account-checkbox').each(function () {
  	        let account_id = $(this).attr('id').split('_')[1];
  			if ($(this).prop('checked')) {
  	            if (!first) route += ',';
  	            first = false;
  	            route += account_id;
  			}
  		});

	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById('grouped-action-panel').innerHTML = xhttp.responseText;
			
            if (!$('#place_id').val()) $('#place_id').val(currentPlaceId);
            if (!$('#class').val()) $('#class').val(currentClass);
            $('#subject').val(currentSubject);
            $('#type').val(currentType);
            
			$(function () {
			    $('.tip').tooltip({
			        content: function () {
			            return $(this).prop('title');
			        }
			    });
			});

			connectAddNoteForm(classe);
			$('#school_year').focus();
			
			$('#input_target_date_group').hide();
			CKEDITOR.replace('observations');
			$('#type').change(function () { 
				if ($('#type').val() == 'done-work') {
					$('#input_target_date_group').hide();
					$('#observations_group').css('background-color', 'LightGreen');
				}
				else if ($('#type').val() == 'todo-work') {
					$('#input_target_date_group').show();
					$('#observations_group').css('background-color', 'LightSalmon');
				}
				else {
					$('#input_target_date_group').show();
					$('#observations_group').css('background-color', 'LightBlue');
				}
			});
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();

	// Highlight the clicked button (and only it in its class)
	$('.action-btn').removeClass("btn-primary").addClass("btn-default");
	$('#note-add-anchor').removeClass("btn-default").addClass("btn-primary");
}

///////////////////////////
// student/addEvaluation //
///////////////////////////

<?php 
$properties = array();
$properties['place_id'] = array('type' => 'select', 'mandatory' => true);
$properties['class'] = array('type' => 'select', 'mandatory' => true);
$properties['level'] = array('type' => 'select', 'mandatory' => false);
$properties['school_period'] = array('type' => 'select', 'mandatory' => true);
//$properties['teacher_n_fn'] = array('type' => 'text', 'mandatory' => true);
$properties['teacher_id'] = array('type' => 'select', 'mandatory' => true);
$properties['subject'] = array('type' => 'select', 'mandatory' => true);
$properties['date'] = array('type' => 'date', 'mandatory' => true);
$properties['reference_value'] = array('type' => 'number', 'mandatory' => true, 'minValue' => 0, 'maxValue' => 100);
$properties['weight'] = array('type' => 'number', 'mandatory' => true, 'minValue' => 0, 'maxValue' => 100);
$properties['observations'] = array('type' => 'textarea', 'mandatory' => false, 'maxSize' => 2047);
$properties['comment'] = array('type' => 'textarea', 'mandatory' => false, 'maxSize' => 2047);
$properties['update_time'] = array('type' => 'hidden');
echo $this->partial('/partials/check-update-properties', array('entity' => 'Evaluation', 'context' => $context, 'properties' => $properties)) 
?>

function connectAddEvaluationForm(type, classe)
{
	$('#input_date').datepicker();

	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {
		
		event.preventDefault();

		// Check validity
		var validity = checkEvaluationUpdateProperties();

		if (validity) {
		    var xhttp = new XMLHttpRequest();
		    var route, target;
		    route = '<?php echo $this->url('student/addEvaluation') ?>/' + type + '?';
		    if (classe) route += '&class=' + classe;
		    target = 'grouped-action-panel';
		
			// Create a new FormData object.
			var formData = new FormData();
/*
			var criteriaNumber = $('#group-nb-criteria').val();
			for (i = 0; i < criteriaNumber; i++) {
		        route += '&' + $('#group-criterion-id_' + i).val() + '=' + $('#group-criterion_' + i).val();
			}*/

            route += '&accounts=';
            let first = true;
            $('.account-checkbox').each(function () {
              let account_id = $(this).attr('id').split('_')[1];
              if ($(this).prop('checked')) {
                if (!first) route += ',';
                first = false;
                route += account_id;

                value = $('#input_value_' + account_id).val();
                if (value != '') {
                  error = checkNumber(value, 0, 100);
                  if (error) {
                    renderElement('input_value_' + account_id, error);
                    validity = false;
                  }
                    else { 
                    renderElement('input_value_' + account_id, null);
                    value = getNumber(value, 2);
                    $('#value_' + account_id).val(value);
                  }
                }
                
                formData.append('value_' + account_id, value);
      
                mention = $('#select_value_' + account_id).val();
                formData.append('mention_' + account_id, mention);
      
                formData.append('assessment_' + account_id, $('#assessment_' + account_id).val());
              }
            });
			
			// Get the properties values
<?php foreach ($properties as $propertyId => $property) : ?>
				formData.append('<?php echo $propertyId ?>', document.getElementById('<?php echo $propertyId ?>').value);
<?php endforeach ?>

			xhttp.open('POST', route, true);
			// Set up a handler for when the request finishes.
			xhttp.onload = function () {
				if (xhttp.readyState == 4 <?php if (!$context->getConfig()['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
					document.getElementById(target).innerHTML = xhttp.responseText;
					$('.action-btn').removeClass('btn-primary').addClass('btn-default');
				}
			};
			xhttp.send(formData);
		}
		else return false;
	}
}

function getAddEvaluation(type, classe) {
	
	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('student/addEvaluation') ?>/' + type + '?';
	if (classe) route += '&class=' + classe;
/*
	var criteriaNumber = $('#group-nb-criteria').val();
	for (i = 0; i < criteriaNumber; i++) {
        route += '&' + $('#group-criterion-id_' + i).val() + '=' + $('#group-criterion_' + i).val();
	}*/

    route += '&accounts=';
    let first = true;
    $('.account-checkbox').each(function () {
        let account_id = $(this).attr('id').split('_')[1];
		if ($(this).prop('checked')) {
            if (!first) route += ',';
            first = false;
            route += account_id;
		}
	});

	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById('grouped-action-panel').innerHTML = xhttp.responseText;
			$('.report-attachment').hide();
			$('#subject').change(function () {
				if ($('#subject').val() == 'global') $('.report-attachment').show();
				else $('.report-attachment').hide();
			});
			
			$(function () {
			    $('.tip').tooltip({
			        content: function () {
			            return $(this).prop('title');
			        }
			    });
			});

			if (type == 'report') {
				$('.select_value').hide();
				$('#subject').change(function () { 
					if ($('#subject').val() == 'global') {
						$('.select_value').show();
					}
					else {
						$('.select_value').hide();
					}
				});
			}

			connectAddEvaluationForm(type, classe);
			$('#subject').focus();
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();

	// Highlight the clicked button (and only it in its class)
	$('.action-btn').removeClass("btn-primary").addClass("btn-default");
	if (type == 'note') $('#evaluation-add-anchor').removeClass("btn-default").addClass("btn-primary");
	else if (type == 'report') $('#report-add-anchor').removeClass("btn-default").addClass("btn-primary");
	else if (type == 'exam') $('#exam-add-anchor').removeClass("btn-default").addClass("btn-primary");
}

/////////////////////////////
// student/addNotification //
/////////////////////////////

function connectContentPanel()
{
	$('#content-panel').hide();
	$('#content-label').click(function () {
		if ($('#content-label').text() == '<?php echo $this->translate('Show', 'ppit-core', $context->getLocale()) ?>') {
			$('#content-panel').show();
			$('#content-label').text('<?php echo $this->translate('Mask', 'ppit-core', $context->getLocale()) ?>');
		}
		else {
			$('#content-panel').hide();
			$('#content-label').text('<?php echo $this->translate('Show', 'ppit-core', $context->getLocale()) ?>');
		}
	});
}

function uploadImage()
{
	// Create a new FormData object.
	var formData = new FormData();

	// Get the uploaded images
	var fileSelect = document.getElementById('image-upload');
	if (fileSelect) {
		var files = fileSelect.files;
		for (var i = 0; i < files.length; i++) {
			var file = files[i];
			formData.append('order_form', file, file.name);
		}
	}

	var xhttp = new XMLHttpRequest();
	var route, target;
	route = '<?php echo $this->url('instance/addImage') ?>';
	xhttp.open('POST', route, true);
	// Set up a handler for when the request finishes.
	xhttp.onload = function () {
		if (xhttp.readyState == 4 <?php if (!$context->getConfig()['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('image-preview').innerHTML = xhttp.responseText;
			$('.image-select').each(function () {
				$(this).click(function () {
					$('.image-select').css('border-style', 'none');
					$(this).css('border-style', 'solid');
					$('#image_src').val($('#image_' + $(this).attr('id').split('_')[1]).val());
				});
			});
			
			$('#image-delete-btn').click(function () {
				$('.image-select').css('border-style', 'none');
				$('#image_src').val('');
			});
		}
	};
	xhttp.send(formData);
}

<?php 
$properties = array();

$properties['title'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 255);
$properties['content'] = array('type' => 'ckeditor', 'mandatory' => false, 'maxSize' => 16777215);
$properties['image_src'] = array('type' => 'select', 'mandatory' => false);
$properties['image_style'] = array('type' => 'select', 'mandatory' => false);
$properties['image_width'] = array('type' => 'input', 'mandatory' => false, 'maxSize' => 255);
$properties['image_href'] = array('type' => 'input', 'mandatory' => false, 'maxSize' => 255);
$properties['begin_date'] = array('type' => 'date', 'mandatory' => false);
$properties['end_date'] = array('type' => 'date', 'mandatory' => false);
$properties['attachment_label'] = array('type' => 'input', 'mandatory' => false, 'maxSize' => 255);
$properties['attachment_path'] = array('type' => 'select', 'mandatory' => false);
$properties['comment'] = array('type' => 'textarea', 'mandatory' => false, 'maxSize' => 2047);

echo $this->partial('/partials/check-update-properties', array('entity' => 'Notification', 'context' => $context, 'properties' => $properties)) 
?>

function connectAddNotificationForm(category)
{
	$('#input_begin_date').datepicker();
	$('#input_end_date').datepicker();
	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {

		event.preventDefault();

		// Check validity
		var validity = checkNotificationUpdateProperties();

		if (validity) {
		
			// Create a new FormData object.
			var formData = new FormData();

			var criteriaNumber = $('#group-nb-criteria').val();
			for (i = 0; i < criteriaNumber; i++) {
				formData.append('criterion-id_' + i, $('#group-criterion-id_' + i).val());
				formData.append('criterion_' + i, $('#group-criterion_' + i).val());
			}
			formData.append('nb-criteria', i);

			var accountNumber = $('#group-nb-account').val();
			for (var i = 0; i < accountNumber; i++) {
				account_id = $('#group-account_' + i).val();
				formData.append('account_' + i, account_id);
			}
			formData.append('nb-account', accountNumber);

			// Get the properties values
<?php foreach ($properties as $propertyId => $property) : ?>
	<?php if ($property['type'] == 'ckeditor') : ?>
			formData.append('<?php echo $propertyId ?>', CKEDITOR.instances.<?php echo $propertyId ?>.getData());
	<?php else : ?>	
				formData.append('<?php echo $propertyId ?>', document.getElementById('<?php echo $propertyId ?>').value);
	<?php endif;?>
<?php endforeach ?>

			var xhttp = new XMLHttpRequest();
			var route, target;
			route = '<?php echo $this->url('student/addNotification') ?>/' + category;
			target = 'grouped-action-panel';
			xhttp.open('POST', route, true);
			// Set up a handler for when the request finishes.
			xhttp.onload = function () {
				if (xhttp.readyState == 4 <?php if (!$context->getConfig()['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
					document.getElementById(target).innerHTML = xhttp.responseText;
					$('.action-btn').removeClass('btn-primary').addClass('btn-default');
					CKEDITOR.replace('content');
					connectContentPanel();
				}
			};
			xhttp.send(formData);
		}
		else return false;
	}
}

function getAddNotification(category) {
	
	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('student/addNotification') ?>/' + category;
	var formData = new FormData();

	var criteriaNumber = $('#group-nb-criteria').val();
	for (i = 0; i < criteriaNumber; i++) {
		formData.append('criterion-id_' + i, $('#group-criterion-id_' + i).val());
		formData.append('criterion_' + i, $('#group-criterion_' + i).val());
	}
	formData.append('nb-criteria', i);

	var accountNumber = $('#account-number').val();
	for (i = 0, j = 0; i < accountNumber; i++) {
		if (document.getElementById('account-checkbox_' + i).checked) {
			formData.append('account_' + j, $('#account_' + i).val());
			j++;
		}
	}
	formData.append('nb-account', j);

	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById('grouped-action-panel').innerHTML = xhttp.responseText;
			
			$(function () {
			    $('.tip').tooltip({
			        content: function () {
			            return $(this).prop('title');
			        }
			    });
			});

			CKEDITOR.replace('content');
			connectContentPanel();
			connectAddNotificationForm(category);
			$('#image-upload-btn').click(uploadImage);
			$('#subject').focus();
			$('.image-select').each(function () {
				$(this).click(function () {
					$('.image-select').css('border-style', 'none');
					$(this).css('border-style', 'solid');
					$('#image_src').val($('#image_' + $(this).attr('id').split('_')[1]).val());
				});
			});
			
			$('#image-delete-btn').click(function () {
				$('.image-select').css('border-style', 'none');
				$('#image_src').val('');
			});
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();

	// Highlight the clicked button (and only it in its class)
	$('.action-btn').removeClass("btn-primary").addClass("btn-default");
	$('#' + category + '-notification-add-anchor').removeClass("btn-default").addClass("btn-primary");
}

/////////////////////////
// student/addProgress //
/////////////////////////

<?php 
$properties = array();
$properties['school_year'] = array('type' => 'select', 'mandatory' => true);
$properties['period'] = array('type' => 'select', 'mandatory' => true);
$properties['comment'] = array('type' => 'textarea', 'mandatory' => false, 'maxSize' => 2047);
$properties['update_time'] = array('type' => 'hidden');
echo $this->partial('/partials/check-update-properties', array('entity' => 'Progress', 'context' => $context, 'properties' => $properties)) 
?>

function connectAddProgressForm(sport)
{
	$('#input_date').datepicker();

	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {

		event.preventDefault();

		// Check validity
		var validity = checkProgressUpdateProperties();

		if (validity) {
		
			// Create a new FormData object.
			var formData = new FormData();

			var criteriaNumber = $('#group-nb-criteria').val();
			for (i = 0; i < criteriaNumber; i++) {
				formData.append('criterion-id_' + i, $('#group-criterion-id_' + i).val());
				formData.append('criterion_' + i, $('#group-criterion_' + i).val());
			}
			formData.append('nb-criteria', i);

			var accountNumber = $('#group-nb-account').val();
			for (i = 0; i < accountNumber; i++) {
				formData.append('account_' + i, $('#group-account_' + i).val());
			}
			formData.append('nb-account', i);
			
			// Get the properties values
<?php foreach ($properties as $propertyId => $property) : ?>
				formData.append('<?php echo $propertyId ?>', document.getElementById('<?php echo $propertyId ?>').value);
<?php endforeach ?>

			var xhttp = new XMLHttpRequest();
			var route, target;
			route = '<?php echo $this->url('student/addProgress') ?>/' + sport;
			target = 'grouped-action-panel';
			xhttp.open('POST', route, true);
			// Set up a handler for when the request finishes.
			xhttp.onload = function () {
				if (xhttp.readyState == 4 <?php if (!$context->getConfig()['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
					document.getElementById(target).innerHTML = xhttp.responseText;
//					filterProgressList();
					$('.index-btn').removeClass('btn-primary').addClass('btn-default');
				}
			};
			xhttp.send(formData);
		}
		else return false;
	}
}

function getAddProgress(sport) {
	
	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('student/addProgress') ?>/' + sport;

	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById('grouped-action-panel').innerHTML = xhttp.responseText;			
			connectAddProgressForm(sport);
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();

	// Highlight the clicked button (and only it in its class)
	$('.action-btn').removeClass("btn-primary").addClass("btn-default");
	$('#progress-add-anchor').removeClass("btn-default").addClass("btn-primary");
}

function getStudentGroup() {

	// Ensure the target is displayed
	$('#form_action').show();
	$(location).attr('hash', 'form_action');

	// Disabled the list checkboxes
	$('.account-checkbox').attr('disabled', 'disabled');
	var route = '<?php echo $this->url('student/group') ?>?';

    route += '&accounts=';
    let first = true;
    $('.account-checkbox').each(function () {
        let account_id = $(this).attr('id').split('_')[1];
		if ($(this).prop('checked')) {
            if (!first) route += ',';
            first = false
            route += account_id;
		}
	});

	// Execute the ajax request
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
			if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>

			document.getElementById('detail-div_0').innerHTML = xhttp.responseText;
			connectRemoveIcon('remove-anchor_0', 'detail-row_0');

			// Ensure the target is displayed
			$('.detail-row').hide();
			$('#detail-row_0').show();
			
			$(function () {
			    $('.tip').tooltip({
			        content: function () {
			            return $(this).prop('title');
			        }
			    });
			});
	
			$('.group-panel').hide();
			$('#schooling-tab').addClass('active');
			$('#schooling-panel').show();
			
			$('#news_flash-tab').click(function () {
				$('#grouped-action-panel').hide();
				$('.action-btn').removeClass('btn-primary').addClass('btn-default');
				$('.group-tab').removeClass('active');
				$('#news_flash-tab').addClass('active');
				$('.group-panel').hide();
				$('#news_flash-panel').show();
			});

			$('#sport-tab').click(function () {
				$('#grouped-action-panel').hide();
				$('.action-btn').removeClass('btn-primary').addClass('btn-default');
				$('.group-tab').removeClass('active');
				$('#sport-tab').addClass('active');
				$('.group-panel').hide();
				$('#sport-panel').show();
			});

			$('#schooling-tab').click(function () {
				$('#grouped-action-panel').hide();
				$('.action-btn').removeClass('btn-primary').addClass('btn-default');
				$('.group-tab').removeClass('active');
				$('#schooling-tab').addClass('active');
				$('.group-panel').hide();
				$('#schooling-panel').show();
			});

			$('#boarding_school-tab').click(function () {
				$('#grouped-action-panel').hide();
				$('.action-btn').removeClass('btn-primary').addClass('btn-default');
				$('.group-tab').removeClass('active');
				$('#boarding_school-tab').addClass('active');
				$('.group-panel').hide();
				$('#boarding_school-panel').show();
			});

			$('#medical-tab').click(function () {
				$('#grouped-action-panel').hide();
				$('.action-btn').removeClass('btn-primary').addClass('btn-default');
				$('.group-tab').removeClass('active');
				$('#medical-tab').addClass('active');
				$('.group-panel').hide();
				$('#medical-panel').show();
			});

<?php foreach ($context->getConfig('absence')['types'] as $typeId => $type) : ?>
			$('#<?php echo $typeId ?>-absence-add-anchor').click(function () { 
				$('#grouped-action-panel').show();
				getAdd<?php echo $typeId ?>Absence(); 
			});
<?php endforeach;?>

<?php foreach ($context->getConfig('commitmentNotification/p-pit-studies')['category'] as $categoryId => $category) : ?>
			$('#<?php echo $categoryId ?>-notification-add-anchor').click(function () { 
				$('#grouped-action-panel').show();
				getAddNotification('<?php echo $categoryId ?>'); 
			});
<?php endforeach;?>

<?php foreach ($context->getConfig('commitmentEvent/p-pit-studies')['category'] as $categoryId => $category) : ?>
			$('#<?php echo $categoryId ?>-event-add-anchor').click(function () { 
				$('#grouped-action-panel').show();
				getAddEvent('<?php echo $categoryId ?>'); 
			});
<?php endforeach;?>

			$('#note-add-anchor').click(function () { 
				$('#grouped-action-panel').show();
				getAddNote($('#search_property_7').val()); // Class
			});

			$('#evaluation-add-anchor').click(function () { 
				$('#grouped-action-panel').show();
				getAddEvaluation('note', $('#search_property_7').val()); // Class
			});

			$('#report-add-anchor').click(function () { 
				$('#grouped-action-panel').show();
				getAddEvaluation('report', $('#search_property_7').val()); // Class
			});

			$('#exam-add-anchor').click(function () { 
				$('#grouped-action-panel').show();
				getAddEvaluation('exam', $('#search_property_7').val()); // Class
			});

			$('#progress-add-anchor').click(function () { 
				$('#grouped-action-panel').show();
				getAddProgress(sport); 
			});
	<?php if (!$config['isTraceActive']) : ?>
			}
	<?php endif;?>
		}
	}
	xhttp.send();

	// Highlight the clicked button (and only it in its class)
	$('.index-btn').removeClass("btn-primary").addClass("btn-default");
	$('.account-group-anchor').removeClass("btn-default").addClass("btn-primary");
}

function activateStudent() {

	// Load the search panel and highlight the menu entry
	loadPanel('index_action', '<?php echo $this->url('student/search') ?>');
	$('.menu-btn').removeClass("btn-primary").addClass("btn-default");
	var studentAnchor;
	studentAnchor = '#student-anchor';
	$(studentAnchor).removeClass("btn-default").addClass("btn-primary");

	<?php
	$todoTitle = (isset ($context->getConfig('core_account/search/p-pit-studies')['todoTitle']) ? $context->getConfig('core_account/search/p-pit-studies')['todoTitle'][$context->getLocale()] : $this->translate('active', 'ppit-core', $context->getLocale()));
	?>
	$('#mode-text').text('<?php echo $todoTitle ?>');
		
	// Connect the search inputs
	connectStudentSearchInputs();
	
	getStudentList('?', 'n_fn', 'ASC');
}

// Session maintening
setInterval(function () {
  var xhttp = new XMLHttpRequest();
  xhttp.open('GET', '<?php echo $this->url('user/maintainSession') ?>', true);
  xhttp.send();
}, 60000);