
function connectRemoveIcon(id, target)
{
	$('#' + id).click(function () {
		$('#' + target).hide();
		$('.account-checkbox').attr('disabled', null);
		$('.index-btn').removeClass("btn-primary").addClass("btn-default");
	});
}

function getParams() {

	// Create a new FormData object.
	var params = '?', todo = true;

<?php foreach ($context->getConfig('commitmentAccount/search/p-pit-studies')['main'] as $propertyId => $rendering) : ?>

	<?php if ($rendering == 'range') : ?>
	
	var min_<?php echo $propertyId ?> = document.getElementById('search_min_<?php echo $propertyId ?>').value;
	if (min_<?php echo $propertyId ?>) min_<?php echo $propertyId ?> = encodeDate(min_<?php echo $propertyId ?>);
	if (min_<?php echo $propertyId ?>.length >= 2) { params += 'min_<?php echo $propertyId ?>=' + min_<?php echo $propertyId ?> + '&'; todo = false; }

	var max_<?php echo $propertyId ?> = document.getElementById('search_max_<?php echo $propertyId ?>').value;
	if (max_<?php echo $propertyId ?>) max_<?php echo $propertyId ?> = encodeDate(max_<?php echo $propertyId ?>);
	if (max_<?php echo $propertyId ?>.length >= 2) { params += 'max_<?php echo $propertyId ?>=' + max_<?php echo $propertyId ?> + '&'; todo = false; }

	<?php else : ?>

	var <?php echo $propertyId ?> = document.getElementById('search_<?php echo $propertyId ?>').value;
	if (<?php echo $propertyId ?>.length >= 2) { params += '<?php echo $propertyId ?>=' + <?php echo $propertyId ?> + '&'; todo = false; }
	
	<?php endif;?>

<?php endforeach;?>

<?php foreach ($context->getConfig('commitmentAccount/search/p-pit-studies')['more'] as $propertyId => $rendering) : ?>

	<?php if ($rendering == 'range') : ?>
	
	var min_<?php echo $propertyId ?> = document.getElementById('search_min_<?php echo $propertyId ?>').value;
	if (min_<?php echo $propertyId ?>) min_<?php echo $propertyId ?> = encodeDate(min_<?php echo $propertyId ?>);
	if (min_<?php echo $propertyId ?>.length >= 2) { params += 'min_<?php echo $propertyId ?>=' + min_<?php echo $propertyId ?> + '&'; todo = false; }

	var max_<?php echo $propertyId ?> = document.getElementById('search_max_<?php echo $propertyId ?>').value;
	if (max_<?php echo $propertyId ?>) max_<?php echo $propertyId ?> = encodeDate(max_<?php echo $propertyId ?>);
	if (max_<?php echo $propertyId ?>.length >= 2) { params += 'max_<?php echo $propertyId ?>=' + max_<?php echo $propertyId ?> + '&'; todo = false; }

	<?php elseif ($rendering == 'select') : ?>

	var <?php echo $propertyId ?> = document.getElementById('search_<?php echo $propertyId ?>').value;
	if (<?php echo $propertyId ?>) { params += '<?php echo $propertyId ?>=' + <?php echo $propertyId ?> + '&'; todo = false; }
	
	<?php else : ?>

	var <?php echo $propertyId ?> = document.getElementById('search_<?php echo $propertyId ?>').value;
	if (<?php echo $propertyId ?>.length >= 2) { params += '<?php echo $propertyId ?>=' + <?php echo $propertyId ?> + '&'; todo = false; }
	
	<?php endif;?>

<?php endforeach;?>

	<?php
	$todoTitle = (isset ($context->getConfig('commitmentAccount/search/p-pit-studies')['todoTitle']) ? $context->getConfig('commitmentAccount/search/p-pit-studies')['todoTitle'][$context->getLocale()] : $this->translate('active', 'ppit-core', $context->getLocale()));
	$searchTitle = (isset ($context->getConfig('commitmentAccount/search/p-pit-studies')['searchTitle']) ? $context->getConfig('commitmentAccount/search/p-pit-studies')['searchTitle'][$context->getLocale()] : $this->translate('search', 'ppit-core', $context->getLocale()));
	?>
	$('#mode-text').text((todo) ? '<?php echo $todoTitle ?>' : '<?php echo $searchTitle ?>');

	return params;
}

// Export the list
function exportStudentList() {

	var params = getParams();
	document.location.href = '<?php echo $this->url('commitmentAccount/export', array('type' => '/p-pit-studies')) ?>' + params;
}

function eraseStudentSearch() {

<?php foreach ($context->getConfig('commitmentAccount/search/p-pit-studies')['main'] as $propertyId => $rendering) : ?>

	<?php if ($rendering == 'range') : ?>
	$('#search_min_<?php echo $propertyId ?>').val('');
	$('#search_max_<?php echo $propertyId ?>').val('');

	<?php else : ?>
	$('#search_<?php echo $propertyId ?>').val('');
	
	<?php endif;?>

<?php endforeach;?>

<?php foreach ($context->getConfig('commitmentAccount/search/p-pit-studies')['more'] as $propertyId => $rendering) : ?>

	<?php if ($rendering == 'range') : ?>
	$('#search_min_<?php echo $propertyId ?>').val('');
	$('#search_max_<?php echo $propertyId ?>').val('');

	<?php else : ?>
	$('#search_<?php echo $propertyId ?>').val('');
	
	<?php endif;?>

<?php endforeach;?>

	getStudentList(getParams(), 'customer_name', 'ASC');
}

function sortStudentList(criterion) {

	var dir;
	ascCriterion = $('.glyphicon-triangle-top').first().parent().attr('id');
	descCriterion = $('.glyphicon-triangle-bottom').first().parent().attr('id');
	if (criterion + '-anchor' == ascCriterion) dir = 'DESC'; else dir = 'ASC';
	getStudentList(getParams(), criterion, dir);
}

function filterStudentList() {

	ascCriterion = $('.glyphicon-triangle-top').first().parent().attr('id');
	descCriterion = $('.glyphicon-triangle-bottom').first().parent().attr('id');
	if (ascCriterion) {
		criterion = ascCriterion.split('-')[0];
		dir = 'ASC';
	}
	else {
		criterion = descCriterion.split('-')[0];
		dir = 'ASC';
	}
	getStudentList(getParams(), criterion, dir);
}

function connectStudentSearchInputs() {

	$('#export-button').click(function () { exportStudentList(); });
	
	$('#erase-button').unbind();
	$('#erase-button').click(function () { eraseStudentSearch(); });

<?php foreach ($context->getConfig('commitmentAccount/search/p-pit-studies')['main'] as $propertyId => $rendering) : ?>

	<?php if ($rendering == 'range') : ?>
	$('#search_min_<?php echo $propertyId ?>').keyup(function () { filterStudentList(); });
	$('#search_max_<?php echo $propertyId ?>').keyup(function () { filterStudentList(); });

		<?php if ($context->getConfig('commitmentAccount/p-pit-studies')['properties'][$propertyId]['type'] == 'date') : ?>
	$("#search_min_<?php echo $propertyId ?>").datepicker();
	$("#search_max_<?php echo $propertyId ?>").datepicker();
	$('#search_min_<?php echo $propertyId ?>').change(function () { filterStudentList(); });
	$('#search_max_<?php echo $propertyId ?>').change(function () { filterStudentList(); });
		<?php endif;?>
	
	<?php elseif ($rendering == 'select') : ?>
		$('#search_<?php echo $propertyId ?>').change(function () { filterStudentList(); });
	
	<?php else : ?>
		$('#search_<?php echo $propertyId ?>').keyup(function () { filterStudentList(); });

		<?php if ($context->getConfig('commitmentAccount/p-pit-studies')['properties'][$propertyId]['type'] == 'date') : ?>
	$("#search_<?php echo $propertyId ?>").datepicker();
	$('#search_<?php echo $propertyId ?>').change(function () { filterStudentList(); });
		<?php endif;?>

	<?php endif;?>

<?php endforeach;?>

<?php foreach ($context->getConfig('commitmentAccount/search/p-pit-studies')['more'] as $propertyId => $rendering) : ?>

	<?php if ($rendering == 'range') : ?>
	$('#search_min_<?php echo $propertyId ?>').keyup(function () { filterStudentList(); });
	$('#search_max_<?php echo $propertyId ?>').keyup(function () { filterStudentList(); });

		<?php if ($context->getConfig('commitmentAccount/p-pit-studies')['properties'][$propertyId]['type'] == 'date') : ?>
	$("#search_min_<?php echo $propertyId ?>").datepicker();
	$("#search_max_<?php echo $propertyId ?>").datepicker();
	$('#search_min_<?php echo $propertyId ?>').change(function () { filterStudentList(); });
	$('#search_max_<?php echo $propertyId ?>').change(function () { filterStudentList(); });
		<?php endif;?>
	
	<?php elseif ($rendering == 'select') : ?>
		$('#search_<?php echo $propertyId ?>').change(function () { filterStudentList(); });

	<?php else : ?>
		$('#search_<?php echo $propertyId ?>').keyup(function () { filterStudentList(); });

		<?php if ($context->getConfig('commitmentAccount/p-pit-studies')['properties'][$propertyId]['type'] == 'date') : ?>
	$("#search_<?php echo $propertyId ?>").datepicker();
	$('#search_<?php echo $propertyId ?>').change(function () { filterStudentList(); });
		<?php endif;?>
		
	<?php endif;?>

<?php endforeach;?>
}

// Load the list
function getStudentList(params, major, dir) {		

	// Execute the ajax request
	route = '<?php echo $this->url('student/list') ?>' + params + '&major=' + major + ((dir =='ASC') ? '&dir=ASC' : '&dir=DESC');
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {

		if (xhttp.readyState == 4 <?php if (!$config['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('account-list-panel').innerHTML = xhttp.responseText;
			
			// Connect the sort anchors
			$('.ppit-sort-anchor').each(function () {
				$(this).click(function () {
					sortStudentList($(this).attr('id').split('-')[0]);
				});
			});

			// Connect the check all checkbox
			$('#account-checkbox').click(function () {
				var current = document.getElementById('account-checkbox').checked;
				var accountNumber = $('#account-number').val();
				document.getElementById('down-account-checkbox').checked = (current) ? true : false;
				for (i = 0; i < accountNumber; i++) {
					document.getElementById('account-checkbox_' + i).checked = (current) ? true : false;
				}
			});
			$('#down-account-checkbox').click(function () {
				var current = document.getElementById('down-account-checkbox').checked;
				var accountNumber = $('#account-number').val();
				document.getElementById('account-checkbox').checked = (current) ? true : false;
				for (i = 0; i < accountNumber; i++) {
					document.getElementById('account-checkbox_' + i).checked = (current) ? true : false;
				}
			});
			
			// Connect the grouped actions anchors
			$('.account-group-anchor').each(function () {
				$(this).click(function () {
					getStudentGroup();
				});
			});
			
			// Connect the detail anchors
			$('.account-detail-anchor').each(function () {
				$(this).click(function () {
					getStudentDetail($(this).attr('id').split('_')[1]);
				});
			});
		}
	}
	xhttp.send();
}

// Retrieve the events
function getEvents(id) {

	// Execute the ajax request
	route = '<?php echo $this->url('studentEvent/get') ?>?account_id=' + id;
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 <?php if (!$config['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
		    $('#calendar').fullCalendar({
		    	lang: '<?php echo substr($context->getLocale(), 0, 2) ?>',
		        defaultView: 'agendaWeek'
		    });
			obj = jQuery.parseJSON(xhttp.responseText);

			jQuery.each(obj, function (name, value) {
				var color;			
<?php foreach ($context->getConfig('commitmentEvent/p-pit-studies')['category'] as $categoryId => $category) : ?>
	<?php foreach ($category['color'] as $color => $unused) : ?>
				if (value.category == '<?php echo $categoryId ?>') color = '<?php echo $color ?>';
	<?php endforeach;?>
<?php endforeach;?>

				var event={
					id:value.id,
					title: value.title + ' (' + value.location + ')',
					color: color,
					start:  $.fullCalendar.moment(value.begin_time), 
					end:  $.fullCalendar.moment(value.end_time)
				};
				$('#calendar').fullCalendar('renderEvent', event, true);
			});
		}
	}
	xhttp.send();
}

// Load the detail panel
function connectNewsFlashTab(route, id) {

	// Execute the ajax request
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 <?php if (!$config['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('news_flash-panel').innerHTML = xhttp.responseText;
			getEvents(id);
		}
	}
	xhttp.send();
}

// Load the detail panel
function connectStudentTab(route) {

	// Execute the ajax request
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 <?php if (!$config['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('news_flash-panel').innerHTML = xhttp.responseText;
		}
	}
	xhttp.send();
}

// Load the detail panel
function getStudentDetail(id) {

	// Ensure the target is displayed
	$('#form_action').show();

	// Anchor to the new panel
	$(location).attr('hash', 'form_action');

	var route = '<?php echo $this->url('student/detail') ?>' + '/' + id;

	// Execute the ajax request
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 <?php if (!$config['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('form_action').innerHTML = xhttp.responseText;
			
			connectRemoveIcon('remove-anchor', 'form_action');
			connectNewsFlashTab('<?php echo $this->url('student/dashboard') ?>/' + id + '/news_flash', id);
			
			$('#news_flash-tab').click(function () {
				$('.student-tab').removeClass('active');
				$('#news_flash-tab').addClass('active');
				connectNewsFlashTab('<?php echo $this->url('student/dashboard') ?>/' + id + '/news_flash', id);
			});

			$('#sport-tab').click(function () {
				$('.student-tab').removeClass('active');
				$('#sport-tab').addClass('active');
				connectStudentTab('<?php echo $this->url('student/dashboard') ?>/' + id + '/sport');
			});

			$('#schooling-tab').click(function () {
				$('.student-tab').removeClass('active');
				$('#schooling-tab').addClass('active');
				connectStudentTab('<?php echo $this->url('student/dashboard') ?>/' + id + '/schooling');
			});

			$('#medical-tab').click(function () {
				$('.student-tab').removeClass('active');
				$('#medical-tab').addClass('active');
				connectStudentTab('<?php echo $this->url('student/dashboard') ?>/' + id + '/medical');
			});
		}
	}
	xhttp.send();

	// Highlight the clicked button (and only it in its class)
	$('.index-btn').removeClass("btn-primary").addClass("btn-default");
	$('#account-detail-anchor_' + id).removeClass("btn-default").addClass("btn-primary");
}

/////////////////////////
// student/addAbsence //
/////////////////////////

<?php 
$properties = array();
$properties['school_year'] = array('type' => 'select', 'mandatory' => true);
$properties['subject'] = array('type' => 'select', 'mandatory' => true);
$properties['date'] = array('type' => 'date', 'mandatory' => true);
$properties['comment'] = array('type' => 'textarea', 'mandatory' => false, 'maxSize' => 2047);
$properties['update_time'] = array('type' => 'hidden');
echo $this->partial('/partials/check-update-properties', array('entity' => 'Absence', 'context' => $context, 'properties' => $properties)) 
?>

<?php foreach ($context->getConfig('absence')['types'] as $typeId => $type) : ?>

function connectAdd<?php echo $typeId ?>AbsenceForm()
{
	$('#input_date').datepicker();

	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {
		
		event.preventDefault();

		// Check validity
		var validity = checkAbsenceUpdateProperties();

		if (validity) {
		
			// Create a new FormData object.
			var formData = new FormData();

			var criteriaNumber = $('#group-nb-criteria').val();
			for (i = 0; i < criteriaNumber; i++) {
				formData.append('criterion-id_' + i, $('#group-criterion-id_' + i).val());
				formData.append('criterion_' + i, $('#group-criterion_' + i).val());
			}
			formData.append('nb-criteria', i);

			var accountNumber = $('#group-nb-account').val();
			for (i = 0; i < accountNumber; i++) {
				formData.append('account_' + i, $('#group-account_' + i).val());
			}
			formData.append('nb-account', i);
			
			// Get the properties values
<?php foreach ($properties as $propertyId => $property) : ?>
				formData.append('<?php echo $propertyId ?>', document.getElementById('<?php echo $propertyId ?>').value);
<?php endforeach ?>

			var xhttp = new XMLHttpRequest();
			var route, target;
			route = '<?php echo $this->url('student/addAbsence', array('type' => $typeId)) ?>';
			target = 'grouped-action-panel';
			xhttp.open('POST', route, true);
			// Set up a handler for when the request finishes.
			xhttp.onload = function () {
				if (xhttp.readyState == 4 <?php if (!$context->getConfig()['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
					document.getElementById(target).innerHTML = xhttp.responseText;
					$('.action-btn').removeClass('btn-primary').addClass('btn-default');
				}
			};
			xhttp.send(formData);
		}
		else return false;
	}
}

function getAdd<?php echo $typeId?>Absence() {
	
	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('student/addAbsence', array('type' => $typeId)) ?>';

	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 <?php if (!$config['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('grouped-action-panel').innerHTML = xhttp.responseText;			
			connectAdd<?php echo $typeId ?>AbsenceForm();
		}
	}
	xhttp.send();

	// Highlight the clicked button (and only it in its class)
	$('.action-btn').removeClass("btn-primary").addClass("btn-default");
	$('#<?php echo $typeId ?>-absence-add-anchor').removeClass("btn-default").addClass("btn-primary");
}

<?php endforeach;?>

//////////////////////
// student/addEvent //
//////////////////////

<?php 
$properties = array();

$properties['begin_date'] = array('type' => 'date', 'mandatory' => false);
$properties['begin_h'] = array('type' => 'select', 'mandatory' => false);
$properties['begin_m'] = array('type' => 'select', 'mandatory' => false);
$properties['end_date'] = array('type' => 'date', 'mandatory' => false);
$properties['end_h'] = array('type' => 'select', 'mandatory' => false);
$properties['end_m'] = array('type' => 'select', 'mandatory' => false);
$properties['location'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 65535);
$properties['title'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 65535);
$properties['comment'] = array('type' => 'textarea', 'mandatory' => false, 'maxSize' => 2047);

echo $this->partial('/partials/check-update-properties', array('entity' => 'Event', 'context' => $context, 'properties' => $properties)) 
?>

function connectAddEventForm(category)
{
	$('#input_begin_date').datepicker();
	$('#input_end_date').datepicker();

	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {
		
		event.preventDefault();

		// Check validity
		var validity = checkEventUpdateProperties();

		if (validity) {
		
			// Create a new FormData object.
			var formData = new FormData();

			var criteriaNumber = $('#group-nb-criteria').val();
			for (i = 0; i < criteriaNumber; i++) {
				formData.append('criterion-id_' + i, $('#group-criterion-id_' + i).val());
				formData.append('criterion_' + i, $('#group-criterion_' + i).val());
			}
			formData.append('nb-criteria', i);

			var accountNumber = $('#group-nb-account').val();
			for (var i = 0; i < accountNumber; i++) {
				account_id = $('#group-account_' + i).val();
				formData.append('account_' + i, account_id);
			}
			formData.append('nb-account', accountNumber);
			
			// Get the properties values
<?php foreach ($properties as $propertyId => $property) : ?>
				formData.append('<?php echo $propertyId ?>', document.getElementById('<?php echo $propertyId ?>').value);
<?php endforeach ?>

			var xhttp = new XMLHttpRequest();
			var route, target;
			route = '<?php echo $this->url('student/addEvent') ?>/' + category;
			target = 'grouped-action-panel';
			xhttp.open('POST', route, true);
			// Set up a handler for when the request finishes.
			xhttp.onload = function () {
				if (xhttp.readyState == 4 <?php if (!$context->getConfig()['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
					document.getElementById(target).innerHTML = xhttp.responseText;
					$('.action-btn').removeClass('btn-primary').addClass('btn-default');
				}
			};
			xhttp.send(formData);
		}
		else return false;
	}
}

function getAddEvent(category) {
	
	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('student/addEvent') ?>/' + category;
	var formData = new FormData();

	var criteriaNumber = $('#group-nb-criteria').val();
	for (i = 0; i < criteriaNumber; i++) {
		formData.append('criterion-id_' + i, $('#group-criterion-id_' + i).val());
		formData.append('criterion_' + i, $('#group-criterion_' + i).val());
	}
	formData.append('nb-criteria', i);

	var accountNumber = $('#account-number').val();
	for (i = 0, j = 0; i < accountNumber; i++) {
		if (document.getElementById('account-checkbox_' + i).checked) {
			formData.append('account_' + j, $('#account_' + i).val());
			j++;
		}
	}
	formData.append('nb-account', j);

	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 <?php if (!$config['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('grouped-action-panel').innerHTML = xhttp.responseText;
			connectAddEventForm(category);
			$('#subject').focus();
		}
	}
	xhttp.send();

	// Highlight the clicked button (and only it in its class)
	$('.action-btn').removeClass("btn-primary").addClass("btn-default");
	$('#' + category + '-event-add-anchor').removeClass("btn-default").addClass("btn-primary");
}

/////////////////////
// student/addNote //
/////////////////////

<?php 
$properties = array();
$properties['school_year'] = array('type' => 'select', 'mandatory' => true);
$properties['subject'] = array('type' => 'select', 'mandatory' => true);
$properties['date'] = array('type' => 'date', 'mandatory' => true);
$properties['reference_value'] = array('type' => 'number', 'mandatory' => true, 'minValue' => 0, 'maxValue' => 100);
$properties['weight'] = array('type' => 'number', 'mandatory' => true, 'minValue' => 0, 'maxValue' => 100);
$properties['comment'] = array('type' => 'textarea', 'mandatory' => false, 'maxSize' => 2047);
$properties['update_time'] = array('type' => 'hidden');
echo $this->partial('/partials/check-update-properties', array('entity' => 'Note', 'context' => $context, 'properties' => $properties)) 
?>

function connectAddNoteForm()
{
	$('#input_date').datepicker();

	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {
		
		event.preventDefault();

		// Check validity
		var validity = checkNoteUpdateProperties();

		if (validity) {
		
			// Create a new FormData object.
			var formData = new FormData();

			var criteriaNumber = $('#group-nb-criteria').val();
			for (i = 0; i < criteriaNumber; i++) {
				formData.append('criterion-id_' + i, $('#group-criterion-id_' + i).val());
				formData.append('criterion_' + i, $('#group-criterion_' + i).val());
			}
			formData.append('nb-criteria', i);

			var accountNumber = $('#group-nb-account').val();
			for (var i = 0; i < accountNumber; i++) {
				account_id = $('#group-account_' + i).val();
				formData.append('account_' + i, account_id);

				value = $('#input_value_' + account_id).val();
				error = checkNumber(value, 0, 100);
				if (error) {
					renderElement('input_value_' + account_id, error);
					validity = false;
				}
			    else { 
					renderElement('input_value_' + account_id, null);
					value = getNumber(value, 2);
					$('#value_' + account_id).val(value);
				}
				
				formData.append('value_' + account_id, value);
			}
			formData.append('nb-account', accountNumber);
			
			// Get the properties values
<?php foreach ($properties as $propertyId => $property) : ?>
				formData.append('<?php echo $propertyId ?>', document.getElementById('<?php echo $propertyId ?>').value);
<?php endforeach ?>

			var xhttp = new XMLHttpRequest();
			var route, target;
			route = '<?php echo $this->url('student/addNote', array('type' => 'schooling')) ?>';
			target = 'grouped-action-panel';
			xhttp.open('POST', route, true);
			// Set up a handler for when the request finishes.
			xhttp.onload = function () {
				if (xhttp.readyState == 4 <?php if (!$context->getConfig()['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
					document.getElementById(target).innerHTML = xhttp.responseText;
					$('.action-btn').removeClass('btn-primary').addClass('btn-default');
				}
			};
			xhttp.send(formData);
		}
		else return false;
	}
}

function getAddNote() {
	
	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('student/addNote', array('type' => 'schooling')) ?>';
	var formData = new FormData();

	var criteriaNumber = $('#group-nb-criteria').val();
	for (i = 0; i < criteriaNumber; i++) {
		formData.append('criterion-id_' + i, $('#group-criterion-id_' + i).val());
		formData.append('criterion_' + i, $('#group-criterion_' + i).val());
	}
	formData.append('nb-criteria', i);

	var accountNumber = $('#account-number').val();
	for (i = 0, j = 0; i < accountNumber; i++) {
		if (document.getElementById('account-checkbox_' + i).checked) {
			formData.append('account_' + j, $('#account_' + i).val());
			j++;
		}
	}
	formData.append('nb-account', j);

	xhttp.open('POST', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 <?php if (!$config['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('grouped-action-panel').innerHTML = xhttp.responseText;
			connectAddNoteForm();
			$('#subject').focus();
		}
	}
	xhttp.send(formData);

	// Highlight the clicked button (and only it in its class)
	$('.action-btn').removeClass("btn-primary").addClass("btn-default");
	$('#evaluation-add-anchor').removeClass("btn-default").addClass("btn-primary");
}

/////////////////////////////
// student/addNotification //
/////////////////////////////

function connectContentPanel()
{
	$('#content-panel').hide();
	$('#content-label').click(function () {
		if ($('#content-label').text() == '<?php echo $this->translate('Show', 'ppit-core', $context->getLocale()) ?>') {
			$('#content-panel').show();
			$('#content-label').text('<?php echo $this->translate('Mask', 'ppit-core', $context->getLocale()) ?>');
		}
		else {
			$('#content-panel').hide();
			$('#content-label').text('<?php echo $this->translate('Show', 'ppit-core', $context->getLocale()) ?>');
		}
	});
}

function uploadImage()
{
	// Create a new FormData object.
	var formData = new FormData();

	// Get the uploaded images
	var fileSelect = document.getElementById('image-upload');
	if (fileSelect) {
		var files = fileSelect.files;
		for (var i = 0; i < files.length; i++) {
			var file = files[i];
			formData.append('order_form', file, file.name);
		}
	}

	var xhttp = new XMLHttpRequest();
	var route, target;
	route = '<?php echo $this->url('instance/addImage') ?>';
	xhttp.open('POST', route, true);
	// Set up a handler for when the request finishes.
	xhttp.onload = function () {
		if (xhttp.readyState == 4 <?php if (!$context->getConfig()['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('image-preview').innerHTML = xhttp.responseText;
			$('.image-select').each(function () {
				$(this).click(function () {
					$('.image-select').css('border-style', 'none');
					$(this).css('border-style', 'solid');
					$('#image_src').val($('#image_' + $(this).attr('id').split('_')[1]).val());
				});
			});
			
			$('#image-delete-btn').click(function () {
				$('.image-select').css('border-style', 'none');
				$('#image_src').val('');
			});
		}
	};
	xhttp.send(formData);
}

<?php 
$properties = array();

$properties['title'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 255);
$properties['content'] = array('type' => 'ckeditor', 'mandatory' => false, 'maxSize' => 16777215);
$properties['image_src'] = array('type' => 'select', 'mandatory' => false);
$properties['image_style'] = array('type' => 'select', 'mandatory' => false);
$properties['image_width'] = array('type' => 'input', 'mandatory' => false, 'maxSize' => 255);
$properties['image_href'] = array('type' => 'input', 'mandatory' => false, 'maxSize' => 255);
$properties['begin_date'] = array('type' => 'date', 'mandatory' => false);
$properties['end_date'] = array('type' => 'date', 'mandatory' => false);
$properties['comment'] = array('type' => 'textarea', 'mandatory' => false, 'maxSize' => 2047);

echo $this->partial('/partials/check-update-properties', array('entity' => 'Notification', 'context' => $context, 'properties' => $properties)) 
?>

function connectAddNotificationForm(category)
{
	$('#input_begin_date').datepicker();
	$('#input_end_date').datepicker();
	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {

		event.preventDefault();

		// Check validity
		var validity = checkNotificationUpdateProperties();

		if (validity) {
		
			// Create a new FormData object.
			var formData = new FormData();

			var criteriaNumber = $('#group-nb-criteria').val();
			for (i = 0; i < criteriaNumber; i++) {
				formData.append('criterion-id_' + i, $('#group-criterion-id_' + i).val());
				formData.append('criterion_' + i, $('#group-criterion_' + i).val());
			}
			formData.append('nb-criteria', i);

			var accountNumber = $('#group-nb-account').val();
			for (var i = 0; i < accountNumber; i++) {
				account_id = $('#group-account_' + i).val();
				formData.append('account_' + i, account_id);
			}
			formData.append('nb-account', accountNumber);

			// Get the properties values
<?php foreach ($properties as $propertyId => $property) : ?>
	<?php if ($property['type'] == 'ckeditor') : ?>
			formData.append('<?php echo $propertyId ?>', CKEDITOR.instances.<?php echo $propertyId ?>.getData());
	<?php else : ?>	
				formData.append('<?php echo $propertyId ?>', document.getElementById('<?php echo $propertyId ?>').value);
	<?php endif;?>
<?php endforeach ?>

			var xhttp = new XMLHttpRequest();
			var route, target;
			route = '<?php echo $this->url('student/addNotification') ?>/' + category;
			target = 'grouped-action-panel';
			xhttp.open('POST', route, true);
			// Set up a handler for when the request finishes.
			xhttp.onload = function () {
				if (xhttp.readyState == 4 <?php if (!$context->getConfig()['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
					document.getElementById(target).innerHTML = xhttp.responseText;
					$('.action-btn').removeClass('btn-primary').addClass('btn-default');
					CKEDITOR.replace('content');
					connectContentPanel();
				}
			};
			xhttp.send(formData);
		}
		else return false;
	}
}

function getAddNotification(category) {
	
	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('student/addNotification') ?>/' + category;
	var formData = new FormData();

	var criteriaNumber = $('#group-nb-criteria').val();
	for (i = 0; i < criteriaNumber; i++) {
		formData.append('criterion-id_' + i, $('#group-criterion-id_' + i).val());
		formData.append('criterion_' + i, $('#group-criterion_' + i).val());
	}
	formData.append('nb-criteria', i);

	var accountNumber = $('#account-number').val();
	for (i = 0, j = 0; i < accountNumber; i++) {
		if (document.getElementById('account-checkbox_' + i).checked) {
			formData.append('account_' + j, $('#account_' + i).val());
			j++;
		}
	}
	formData.append('nb-account', j);

	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 <?php if (!$config['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('grouped-action-panel').innerHTML = xhttp.responseText;
			CKEDITOR.replace('content');
			connectContentPanel();
			connectAddNotificationForm(category);
			$('#image-upload-btn').click(uploadImage);
			$('#subject').focus();
			$('.image-select').each(function () {
				$(this).click(function () {
					$('.image-select').css('border-style', 'none');
					$(this).css('border-style', 'solid');
					$('#image_src').val($('#image_' + $(this).attr('id').split('_')[1]).val());
				});
			});
			
			$('#image-delete-btn').click(function () {
				$('.image-select').css('border-style', 'none');
				$('#image_src').val('');
			});
		}
	}
	xhttp.send();

	// Highlight the clicked button (and only it in its class)
	$('.action-btn').removeClass("btn-primary").addClass("btn-default");
	$('#' + category + '-notification-add-anchor').removeClass("btn-default").addClass("btn-primary");
}

/////////////////////////
// student/addProgress //
/////////////////////////

<?php 
$properties = array();
$properties['school_year'] = array('type' => 'select', 'mandatory' => true);
$properties['period'] = array('type' => 'select', 'mandatory' => true);
$properties['comment'] = array('type' => 'textarea', 'mandatory' => false, 'maxSize' => 2047);
$properties['update_time'] = array('type' => 'hidden');
echo $this->partial('/partials/check-update-properties', array('entity' => 'Progress', 'context' => $context, 'properties' => $properties)) 
?>

function connectAddProgressForm(sport)
{
	$('#input_date').datepicker();

	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {

		event.preventDefault();

		// Check validity
		var validity = checkProgressUpdateProperties();

		if (validity) {
		
			// Create a new FormData object.
			var formData = new FormData();

			var criteriaNumber = $('#group-nb-criteria').val();
			for (i = 0; i < criteriaNumber; i++) {
				formData.append('criterion-id_' + i, $('#group-criterion-id_' + i).val());
				formData.append('criterion_' + i, $('#group-criterion_' + i).val());
			}
			formData.append('nb-criteria', i);

			var accountNumber = $('#group-nb-account').val();
			for (i = 0; i < accountNumber; i++) {
				formData.append('account_' + i, $('#group-account_' + i).val());
			}
			formData.append('nb-account', i);
			
			// Get the properties values
<?php foreach ($properties as $propertyId => $property) : ?>
				formData.append('<?php echo $propertyId ?>', document.getElementById('<?php echo $propertyId ?>').value);
<?php endforeach ?>

			var xhttp = new XMLHttpRequest();
			var route, target;
			route = '<?php echo $this->url('student/addProgress') ?>/' + sport;
			target = 'grouped-action-panel';
			xhttp.open('POST', route, true);
			// Set up a handler for when the request finishes.
			xhttp.onload = function () {
				if (xhttp.readyState == 4 <?php if (!$context->getConfig()['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
					document.getElementById(target).innerHTML = xhttp.responseText;
//					filterProgressList();
					$('.index-btn').removeClass('btn-primary').addClass('btn-default');
				}
			};
			xhttp.send(formData);
		}
		else return false;
	}
}

function getAddProgress(sport) {
	
	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('student/addProgress') ?>/' + sport;

	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 <?php if (!$config['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('grouped-action-panel').innerHTML = xhttp.responseText;			
			connectAddProgressForm(sport);
		}
	}
	xhttp.send();

	// Highlight the clicked button (and only it in its class)
	$('.action-btn').removeClass("btn-primary").addClass("btn-default");
	$('#progress-add-anchor').removeClass("btn-default").addClass("btn-primary");
}

function getStudentGroup() {

	// Ensure the target is displayed
	$('#form_action').show();
	$(location).attr('hash', 'form_action');

	// Disabled the list checkboxes
	$('.account-checkbox').attr('disabled', 'disabled');
	var route = '<?php echo $this->url('student/group') ?>';
	var formData = new FormData();

	var accountNumber = $('#account-number').val();
	for (i = 0, j = 0; i < accountNumber; i++) {
		if (document.getElementById('account-checkbox_' + i).checked) {
			formData.append('account_' + j, $('#account_' + i).val());
			j++;
		}
	}
	formData.append('nb-account', j);

	var sport;

<?php foreach ($context->getConfig('commitmentAccount/search/p-pit-studies')['main'] as $propertyId => $rendering) : ?>
	<?php if ($rendering == 'range') : ?>

	formData.append('min_<?php echo $propertyId ?>', $('#search_min_<?php echo $propertyId ?>').val());
	formData.append('max_<?php echo $propertyId ?>', $('#search_max_<?php echo $propertyId ?>').val());

	<?php else : ?>

	<?php if ($propertyId == 'property_1') : ?>
	sport = $('#search_property_1').val();
	<?php endif;?>

	formData.append('<?php echo $propertyId ?>', $('#search_<?php echo $propertyId ?>').val());
	
	<?php endif;?>
<?php endforeach;?>

<?php foreach ($context->getConfig('commitmentAccount/search/p-pit-studies')['more'] as $propertyId => $rendering) : ?>
	<?php if ($rendering == 'range') : ?>
	
	formData.append('min_<?php echo $propertyId ?>', $('#search_min_<?php echo $propertyId ?>').val());
	formData.append('max_<?php echo $propertyId ?>', $('#search_max_<?php echo $propertyId ?>').val());

	<?php else : ?>

	<?php if ($propertyId == 'property_1') : ?>
	sport = $('#search_property_1').val();
	<?php endif;?>

	formData.append('<?php echo $propertyId ?>', $('#search_<?php echo $propertyId ?>').val());
	
	<?php endif;?>
<?php endforeach;?>

	// Execute the ajax request
	xhttp = new XMLHttpRequest();
	xhttp.open("POST", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 <?php if (!$config['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('form_action').innerHTML = xhttp.responseText;
<?php if ($config['ppitCoreSettings']['isTraceActive']) : ?>
			console.log('showing panel: form_action, url = ' + route);
			console.log(xhttp.responseText);
<?php endif;?>
			
			connectRemoveIcon('remove-anchor', 'form_action');
	
			$('.group-panel').hide();
			$('#news_flash-panel').show();
			
			$('#news_flash-tab').click(function () {
				$('#grouped-action-panel').hide();
				$('.action-btn').removeClass('btn-primary').addClass('btn-default');
				$('.group-tab').removeClass('active');
				$('#news_flash-tab').addClass('active');
				$('.group-panel').hide();
				$('#news_flash-panel').show();
			});

			$('#sport-tab').click(function () {
				$('#grouped-action-panel').hide();
				$('.action-btn').removeClass('btn-primary').addClass('btn-default');
				$('.group-tab').removeClass('active');
				$('#sport-tab').addClass('active');
				$('.group-panel').hide();
				$('#sport-panel').show();
			});

			$('#schooling-tab').click(function () {
				$('#grouped-action-panel').hide();
				$('.action-btn').removeClass('btn-primary').addClass('btn-default');
				$('.group-tab').removeClass('active');
				$('#schooling-tab').addClass('active');
				$('.group-panel').hide();
				$('#schooling-panel').show();
			});

			$('#boarding_school-tab').click(function () {
				$('#grouped-action-panel').hide();
				$('.action-btn').removeClass('btn-primary').addClass('btn-default');
				$('.group-tab').removeClass('active');
				$('#boarding_school-tab').addClass('active');
				$('.group-panel').hide();
				$('#boarding_school-panel').show();
			});

			$('#medical-tab').click(function () {
				$('#grouped-action-panel').hide();
				$('.action-btn').removeClass('btn-primary').addClass('btn-default');
				$('.group-tab').removeClass('active');
				$('#medical-tab').addClass('active');
				$('.group-panel').hide();
				$('#medical-panel').show();
			});

<?php foreach ($context->getConfig('absence')['types'] as $typeId => $type) : ?>
			$('#<?php echo $typeId ?>-absence-add-anchor').click(function () { 
				$('#grouped-action-panel').show();
				getAdd<?php echo $typeId ?>Absence(); 
			});
<?php endforeach;?>

<?php foreach ($context->getConfig('commitmentNotification/p-pit-studies')['category'] as $categoryId => $category) : ?>
			$('#<?php echo $categoryId ?>-notification-add-anchor').click(function () { 
				$('#grouped-action-panel').show();
				getAddNotification('<?php echo $categoryId ?>'); 
			});
<?php endforeach;?>

<?php foreach ($context->getConfig('commitmentEvent/p-pit-studies')['category'] as $categoryId => $category) : ?>
			$('#<?php echo $categoryId ?>-event-add-anchor').click(function () { 
				$('#grouped-action-panel').show();
				getAddEvent('<?php echo $categoryId ?>'); 
			});
<?php endforeach;?>

			$('#evaluation-add-anchor').click(function () { 
				$('#grouped-action-panel').show();
				getAddNote(); 
			});

			$('#progress-add-anchor').click(function () { 
				$('#grouped-action-panel').show();
				getAddProgress(sport); 
			});
		}
	}
	xhttp.send(formData);

	// Highlight the clicked button (and only it in its class)
	$('.index-btn').removeClass("btn-primary").addClass("btn-default");
	$('.account-group-anchor').removeClass("btn-default").addClass("btn-primary");
}

function activateStudent() {

	// Load the search panel and highlight the menu entry
	loadPanel('index_action', '<?php echo $this->url('student/search') ?>');
	$('.menu-btn').removeClass("btn-primary").addClass("btn-default");
	var studentAnchor;
	studentAnchor = '#student-anchor';
	$(studentAnchor).removeClass("btn-default").addClass("btn-primary");

	<?php
	$todoTitle = (isset ($context->getConfig('commitmentAccount/search/p-pit-studies')['todoTitle']) ? $context->getConfig('commitmentAccount/search/p-pit-studies')['todoTitle'][$context->getLocale()] : $this->translate('active', 'ppit-core', $context->getLocale()));
	?>
	$('#mode-text').text('<?php echo $todoTitle ?>');
		
	// Connect the search inputs
	connectStudentSearchInputs();
	
	getStudentList('?', 'customer_name', 'ASC');
	
	$('#add-criteria').click(function () {
		mode = $('#add-criteria').text();
		if (mode == '<?php echo $this->translate('More criteria', 'ppit-core', $context->getLocale()) ?>') {
			$('#add-criteria').text('<?php echo $this->translate('Less criteria', 'ppit-core', $context->getLocale()) ?>');
			$('#search-area').show();
		}
		else {
			$('#add-criteria').text('<?php echo $this->translate('More criteria', 'ppit-core', $context->getLocale()) ?>');
			$('#search-area').hide();
		}
	});
	$('#search-area').hide();
}
