<?php
function feu($critere, $libelle)
{
	if ($libelle == 'NA') echo '<img height="20" src="/img/rouge.png"/> '.$critere.'<br>';
	if ($libelle == 'EC') echo '<img height="20" src="/img/orange.png"/> '.$critere.'<br>';
	if ($libelle == 'AC') echo '<img height="20" src="/img/vert.png"/> '.$critere.'<br>';
}

function footTitre($libelle, $p1, $p2, $p3, $p4, $p5)
{
	echo '<tr>';
	if ($p1) echo '<td>&nbsp;</td>';
	if ($p2) echo '<td>&nbsp;</td>';
	if ($p3) echo '<td>&nbsp;</td>';
	if ($p4) echo '<td>&nbsp;</td>';
	if ($p5) echo '<td>&nbsp;</td>';
	echo '<td><b>'.$libelle.'</b></td>';
	echo '</tr>';
}

function foot($critere, $libelle, $p1, $p2, $p3, $p4, $p5)
{
	$ret = NULL;
	$boo = 0;
	if ($p1) {
		if ($p1->$critere) $boo = 1;
		if ($p1->$critere == 'NA') $ret = $ret.'<td><img height="20" src="/img/rouge.png"/></td>';
		elseif ($p1->$critere == 'EC') $ret = $ret.'<td><img height="20" src="/img/orange.png"/></td>';
		elseif ($p1->$critere == 'AC') $ret = $ret.'<td><img height="20" src="/img/vert.png"/></td>';
		else $ret = $ret.'<td>&nbsp;</td>';
	}

	if ($p2) {
		if ($p2->$critere) $boo = 1;
		if ($p2->$critere == 'NA') $ret = $ret.'<td><img height="20" src="/img/rouge.png"/></td>';
		elseif ($p2 && $p2->$critere == 'EC') $ret = $ret.'<td><img height="20" src="/img/orange.png"/></td>';
		elseif ($p2 && $p2->$critere == 'AC') $ret = $ret.'<td><img height="20" src="/img/vert.png"/></td>';
		else $ret = $ret.'<td>&nbsp;</td>';
	}

	if ($p3) {
		if ($p3->$critere) $boo = 1;
		if ($p3->$critere == 'NA') $ret = $ret.'<td><img height="20" src="/img/rouge.png"/></td>';
		elseif ($p3 && $p3->$critere == 'EC') $ret = $ret.'<td><img height="20" src="/img/orange.png"/></td>';
		elseif ($p3 && $p3->$critere == 'AC') $ret = $ret.'<td><img height="20" src="/img/vert.png"/></td>';
		else $ret = $ret.'<td>&nbsp;</td>';
	}

	if ($p4) {
		if ($p4->$critere) $boo = 1;
		if ($p4->$critere == 'NA') $ret = $ret.'<td><img height="20" src="/img/rouge.png"/></td>';
		elseif ($p4 && $p4->$critere == 'EC') $ret = $ret.'<td><img height="20" src="/img/orange.png"/></td>';
		elseif ($p4 && $p4->$critere == 'AC') $ret = $ret.'<td><img height="20" src="/img/vert.png"/></td>';
		else $ret = $ret.'<td>&nbsp;</td>';
	}

	if ($p5) {
		if ($p5->$critere) $boo = 1;
		if ($p5->$critere == 'NA') $ret = $ret.'<td><img height="20" src="/img/rouge.png"/></td>';
		elseif ($p5 && $p5->$critere == 'EC') $ret = $ret.'<td><img height="20" src="/img/orange.png"/></td>';
		elseif ($p5 && $p5->$critere == 'AC') $ret = $ret.'<td><img height="20" src="/img/vert.png"/></td>';
		else $ret = $ret.'<td>&nbsp;</td>';
	}

	if ($boo != 0) {
		$ret = '<tr>'.$ret;
		$ret = $ret.'<td>&nbsp;'.$libelle.'</td>';
		$ret = $ret.'</tr>';
		echo $ret;
	}
}

function facebook($centre) {
	switch ($centre) {
		case 'Verneuil' :
			echo '<a target="_blank" href="https://www.facebook.com/pages/FM-Sports-Etudes-Verneuil/130547293688905"><img width="61" height="23" alt="" src="/img/logo-facebook.jpg"/></a>';
			break;
		case 'Cholet' :
			echo '<a target="_blank" href="https://www.facebook.com/pages/FM-Sports-Etudes-Cholet/672455216118639?fref=ts"><img width="61" height="23" alt="" src="/img/logo-facebook.jpg"/></a>';
			break;
		case 'Moisson' :
			echo '<a target="_blank" href="https://www.facebook.com/fmetudesmoisson"><img width="61" height="23" alt="" src="/img/logo-facebook.jpg"/></a>';
			break;
	}
}


$title = $this->escapeHtml($eleve->n_first) . ' ' . $this->escapeHtml($eleve->n_last);
$this->headTitle($title);
?>
<br>
	<div class="jumbotron">
        	<?php if ($eleve->sport == 'Football' && $eleve->center_id == 'Verneuil') : ?>
        		<img width="1000", src="<?php echo $this->basePath('photos/photo-football.jpg');?>"/>&nbsp;&nbsp;&nbsp;
        	<?php else : ?>
        		<img height="160", src="<?php echo $this->basePath('photos/'.$eleve->sport.'.png');?>"/>&nbsp;&nbsp;&nbsp;
        	<?php endif; ?><br><br>
		<table>
			<tr>
				<td><?php $path = 'photos/eleve'.$eleve->id; echo '<img src="'.$this->basePath($path).'.jpg"/>&nbsp;&nbsp;&nbsp;';?></td>
				<td align='center'	>
					<?php echo $eleve->n_first.'&nbsp;'.$eleve->n_last ?>&nbsp;&nbsp;&nbsp;<br>
					</b><?php echo $eleve->class.' '.$eleve->specialty ?>
				</td>
	            <td><?php facebook($eleve->center_id); ?></td>
			</tr>
		</table>
	</div>
	<div class="row">
       	<div class="col-md-4">
			<div class="panel panel-default">
            	<div class="panel-heading">
					<h3 class="panel-title">Flash Infos</h3>
            	</div>
            	<div class="panel-body">
            		<?php foreach ($messageTable->fetchAll() as $message) : ?>
						<?php
							$d1 = new DateTime($message->date_modif.' 00:00:00');
							$d2 = new DateTime();
							$diff = $d1->diff($d2)->days;
							if ($message->espace == 'Flash-info' && ($complet || $diff < 70)) {
								$select = 1;
								if ($message->dest_centre) {
									if ($message->dest_centre == 'Verneuil + Moisson') {
										if ($eleve->center_id != 'Verneuil' && $eleve->center_id != 'Moisson') $select = 0;
									}
									elseif ($message->dest_centre != $eleve->center_id) $select = 0;
								}
								if ($message->dest_sport && $message->dest_sport != $eleve->sport) $select = 0;
								if ($message->dest_categorie && $message->dest_categorie != $eleve->category) $select = 0;
								if ($message->dest_classe && $message->dest_classe != $eleve->class) $select = 0;
								if ($message->dest_formule && $message->dest_formule != $eleve->boarding_school) $select = 0;
								if ($select == 1) {
									echo '<b>'.$message->date_modif.' - '.$message->objet.'</b><br>';
									echo nl2br($message->texte).'<br>';
									if ($message->piece_jointe) echo '<b>Piece jointe : </b><a target="_blank", href="'.$this->basePath('resources/'.$message->piece_jointe).'">'.$this->escapeHtml($message->piece_jointe).'</a><br>';
									echo '<br>';
								}
							}
						?>
					<?php endforeach; ?>
					<?php if (!$complet) : ?>
						<a href="<?php echo $this->url('eleve', array('action'=>'home', 'eid' => $eleve->id));?>?complet=1">archives</a><br>
					<?php endif;?>
					<?php 
						$first = 1;
						foreach ($absences as $absence) {
							if ($first) echo '<br><b>Absences internat</b><br>';
							$first = 0;
							echo $this->escapeHtml($absence->date_releve.' '.$absence->type).'<br>';
						}?>
				</div>
			</div>
		</div>
    	<div class="col-md-4">
			<div class="panel panel-default">
            	<div class="panel-heading">
					<h3 class="panel-title">SPORTS</h3>
            	</div>
            	<div class="panel-body">
					<?php if ($eleve->category) echo '<b>Catégorie : </b>'.$eleve->category.'<br>'?>
					<?php if ($eleve->sport == 'Football') : ?>
            			<?php
							$p1 = $resultSportTable->getEleveResultSportPeriode($eleve->id, 'Sept./Oct.');
							$p2 = $resultSportTable->getEleveResultSportPeriode($eleve->id, 'Nov./Déc.');
	            			$p3 = $resultSportTable->getEleveResultSportPeriode($eleve->id, 'Jan./Fév.');
	            			$p4 = $resultSportTable->getEleveResultSportPeriode($eleve->id, 'Mars/Avril');
	            			$p5 = $resultSportTable->getEleveResultSportPeriode($eleve->id, 'Mai/Juin');
	            			
		            		if ($eleve->nom_club) echo '<b>Club : </b>'.$eleve->nom_club.'<br>';
	            			if ($eleve->previous_club) echo '<b>Club N-1 : </b>'.$eleve->previous_club.'<br>';
	            			if ($p5 && $p5->poste_1) echo '<b>Poste : </b>'.$this->escapeHtml($p5->poste_1).'<br><br>';
	            			elseif ($p4 && $p4->poste_1) echo '<b>Poste : </b>'.$this->escapeHtml($p4->poste_1).'<br><br>';
	            			elseif ($p3 && $p3->poste_1) echo '<b>Poste : </b>'.$this->escapeHtml($p3->poste_1).'<br><br>';
	            			elseif ($p2 && $p2->poste_1) echo '<b>Poste : </b>'.$this->escapeHtml($p2->poste_1).'<br><br>';
	            			elseif ($p1 && $p1->poste_1) echo '<b>Poste : </b>'.$this->escapeHtml($p1->poste_1).'<br><br>';

	            			if ($p5 && $p5->observations) echo '<b>Observations : </b>'.$this->escapeHtml($p5->observations).'<br><br>';
	            			elseif ($p4 && $p4->observations) echo '<b>Observations : </b>'.$this->escapeHtml($p4->observations).'<br><br>';
	            			elseif ($p3 && $p3->observations) echo '<b>Observations : </b>'.$this->escapeHtml($p3->observations).'<br><br>';
	            			elseif ($p2 && $p2->observations) echo '<b>Observations : </b>'.$this->escapeHtml($p2->observations).'<br><br>';
	            			elseif ($p1 && $p1->observations) echo '<b>Observations : </b>'.$this->escapeHtml($p1->observations).'<br><br>';
	            			
							echo '<table>';
	            				echo '<tr><td><img height="20" src="/img/rouge.png"/> Non acquis</td><td>&nbsp;&nbsp;<b>P1</b> : Sept./Oct.</td></tr>';
	            				echo '<tr><td><img height="20" src="/img/orange.png"/> En cours</td><td>&nbsp;&nbsp;<b>P2</b> : Nov./Déc.</td></tr>';
	            				echo '<tr><td><img height="20" src="/img/vert.png"/> Acquis</td><td>&nbsp;&nbsp;<b>P3</b> : Jan./Fév.</td></tr>';
	            				echo '<tr><td>&nbsp;</td><td>&nbsp;&nbsp;<b>P4</b> : Mars/Avril</td></tr>';
	            				echo '<tr><td>&nbsp;</td><td>&nbsp;&nbsp;<b>P5</b> : Mai/Juin</td></tr>';
	            			echo '</table>';

							if ($p5 && $p5->piece_jointe) echo '<b>P5 : </b><a target="_blank", href="'.$this->basePath('resources/'.$p5->piece_jointe).'">'.$this->escapeHtml($p5->piece_jointe).'</a><br>';
							if ($p5 && $p5->lien) echo '<b>P5 : </b><a target="_blank", href="'.$p5->lien.'">'.'Bonus !'.'</a><br>';
							if ($p4 && $p4->piece_jointe) echo '<b>P4 : </b><a target="_blank", href="'.$this->basePath('resources/'.$p4->piece_jointe).'">'.$this->escapeHtml($p4->piece_jointe).'</a><br>';
	            			if ($p4 && $p4->lien) echo '<b>P4 : </b><a target="_blank", href="'.$p4->lien.'">'.'Bonus !'.'</a><br>';
							if ($p3 && $p3->piece_jointe) echo '<b>P3 : </b><a target="_blank", href="'.$this->basePath('resources/'.$p3->piece_jointe).'">'.$this->escapeHtml($p3->piece_jointe).'</a><br>';
	            			if ($p3 && $p3->lien) echo '<b>P3 : </b><a target="_blank", href="'.$p3->lien.'">'.'Bonus !'.'</a><br>';
							if ($p2 && $p2->piece_jointe) echo '<b>P2 : </b><a target="_blank", href="'.$this->basePath('resources/'.$p2->piece_jointe).'">'.$this->escapeHtml($p2->piece_jointe).'</a><br>';
	            			if ($p2 && $p2->lien) echo '<b>P2 : </b><a target="_blank", href="'.$p2->lien.'">'.'Bonus !'.'</a><br>';
							if ($p1 && $p1->piece_jointe) echo '<b>P1 : </b><a target="_blank", href="'.$this->basePath('resources/'.$p1->piece_jointe).'">'.$this->escapeHtml($p1->piece_jointe).'</a><br>';
							if ($p1 && $p1->lien) echo '<b>P1 : </b><a target="_blank", href="'.$p1->lien.'">'.'Bonus !'.'</a><br>';
								
							echo '<br><table>';
							echo '<tr>';
							if ($p1) echo '<td><b>P1</b></td>';
							if ($p2) echo '<td><b>P2</b></td>';
							if ($p3) echo '<td><b>P3</b></td>';
							if ($p4) echo '<td><b>P4</b></td>';
							if ($p5) echo '<td><b>P5</b></td>';
							echo '</tr>';
								
							footTitre('Techniques offensives', $p1, $p2, $p3, $p4, $p5);
							foot('f_passes_pd', 'Passes PD', $p1, $p2, $p3, $p4, $p5);
							foot('f_passes_pg', 'Passes PG', $p1, $p2, $p3, $p4, $p5);
							foot('f_controle_ballon', 'Contrôle du ballon', $p1, $p2, $p3, $p4, $p5);
							foot('f_tirs_pd', 'Tirs PD', $p1, $p2, $p3, $p4, $p5);
							foot('f_tirs_pg', 'Tirs PG', $p1, $p2, $p3, $p4, $p5);
							foot('f_jeu_tete', 'Jeu de tête', $p1, $p2, $p3, $p4, $p5);
							foot('f_jeu_court', 'Jeu court', $p1, $p2, $p3, $p4, $p5);
							foot('f_jeu_mi_long', 'Jeu mi-long', $p1, $p2, $p3, $p4, $p5);
							foot('f_jeu_long', 'Jeu long', $p1, $p2, $p3, $p4, $p5);
							foot('f_feintes_dribbles', 'Feintes Dribbles', $p1, $p2, $p3, $p4, $p5);
							foot('f_protection_ballon', 'Protection du ballon', $p1, $p2, $p3, $p4, $p5);
							foot('f_jeu_combine', 'Jeu combiné', $p1, $p2, $p3, $p4, $p5);

							footTitre('Techniques défensives', $p1, $p2, $p3, $p4, $p5);
							foot('f_duel_off', 'Duels offensifs', $p1, $p2, $p3, $p4, $p5);
							foot('f_jeu_tete_def', 'Jeu de tête', $p1, $p2, $p3, $p4, $p5);
							foot('f_interception', 'Interception', $p1, $p2, $p3, $p4, $p5);
							foot('f_duel_def', 'Duels défensifs (tacle, charge...)', $p1, $p2, $p3, $p4, $p5);

							footTitre('Tactique - Principes défensifs', $p1, $p2, $p3, $p4, $p5);
							foot('f_placement_def', 'Placement', $p1, $p2, $p3, $p4, $p5);
							foot('f_replacement', 'Replacement', $p1, $p2, $p3, $p4, $p5);
							foot('f_cadrage', 'Cadrage', $p1, $p2, $p3, $p4, $p5);
							foot('f_couverture', 'Couverture', $p1, $p2, $p3, $p4, $p5);
							foot('f_effic_def', 'Efficacité défensive individuelle', $p1, $p2, $p3, $p4, $p5);
							foot('f_ges_desequilibre', 'Gestion déséquilibres', $p1, $p2, $p3, $p4, $p5);
							foot('f_trans_def_off', 'Transition déf./off. (efficacité)', $p1, $p2, $p3, $p4, $p5);

							footTitre('Tactique - Principes offensifs', $p1, $p2, $p3, $p4, $p5);
							foot('f_placement_off', 'Placement', $p1, $p2, $p3, $p4, $p5);
							foot('f_demarquage', 'Démarquage / Disponibilité', $p1, $p2, $p3, $p4, $p5);
							foot('f_jeu_combine_tact', 'Jeu combiné', $p1, $p2, $p3, $p4, $p5);
							foot('f_jeu_appui', 'Jeu en appui', $p1, $p2, $p3, $p4, $p5);
							foot('f_jeu_soutien', 'Jeu en soutien', $p1, $p2, $p3, $p4, $p5);
							foot('f_vision_jeu', 'VIsion du jeu', $p1, $p2, $p3, $p4, $p5);
							foot('f_dernier_geste', 'Dernière passe / dernier geste', $p1, $p2, $p3, $p4, $p5);
							foot('f_finition', 'Finition', $p1, $p2, $p3, $p4, $p5);
							foot('f_effic_off', 'Efficacité offensive individuelle', $p1, $p2, $p3, $p4, $p5);

							footTitre('Physique', $p1, $p2, $p3, $p4, $p5);
							foot('f_vitesse', 'Vitesse', $p1, $p2, $p3, $p4, $p5);
							foot('f_explosivite', 'Explosivité', $p1, $p2, $p3, $p4, $p5);
							foot('f_resistance', 'Résistance', $p1, $p2, $p3, $p4, $p5);
							foot('f_endurance', 'Endurance', $p1, $p2, $p3, $p4, $p5);
							foot('f_puissance', 'Puissance', $p1, $p2, $p3, $p4, $p5);
							foot('f_souplesse', 'Souplesse', $p1, $p2, $p3, $p4, $p5);
							foot('f_coordination', 'Coordination', $p1, $p2, $p3, $p4, $p5);

							footTitre('Mental', $p1, $p2, $p3, $p4, $p5);
							foot('f_volonte', 'Volonté/Investissement', $p1, $p2, $p3, $p4, $p5);
							foot('f_agressivite', 'Agressivité', $p1, $p2, $p3, $p4, $p5);
							foot('f_prise_info', 'Prise d\'information', $p1, $p2, $p3, $p4, $p5);
							foot('f_concentration', 'Concentration/Ecoute/Compréhension', $p1, $p2, $p3, $p4, $p5);
							foot('f_choix', 'Choix', $p1, $p2, $p3, $p4, $p5);
							foot('f_emotion', 'Contrôle émotionnel', $p1, $p2, $p3, $p4, $p5);
							foot('f_positif', 'Esprit positif', $p1, $p2, $p3, $p4, $p5);
							foot('f_fair_play', 'Fair-play', $p1, $p2, $p3, $p4, $p5);
							foot('f_respect', 'Respect', $p1, $p2, $p3, $p4, $p5);
							foot('f_comportement', 'Comportement général', $p1, $p2, $p3, $p4, $p5);
							foot('f_humilite', 'Humilité', $p1, $p2, $p3, $p4, $p5);
							echo '</table>';
						?>
            		<?php else : ?>
	            		<?php foreach ($resultSports as $resultSport) : ?>
							<br><b>Période : </b><?php echo $this->escapeHtml($resultSport->periode);?><br>
							<?php switch ($eleve->sport) {

								case 'Equitation' :
										
								echo '<br><b>Technique</b><br>';
								echo 'Confiance en soi, confiance dans ses chevaux (attitude mentale) : '.$this->escapeHtml($resultSport->e_att_mentale).'<br>';
								echo 'Posture et mise en selle : '.$this->escapeHtml($resultSport->e_mise_selle).'<br>';
								echo 'Ecole des aides : '.$this->escapeHtml($resultSport->e_ecole_aide).'<br>';
								echo 'Travail à l’obstacle et en extérieur : '.$this->escapeHtml($resultSport->e_travail_obstacle).'<br>';
								echo 'Travail à pied, soins aux chevaux : '.$this->escapeHtml($resultSport->e_travail_pied).'<br>';

								echo '<br><b>Objectifs</b><br>';
								echo 'Court terme : '.$this->escapeHtml($resultSport->obj_ct).'<br>';
								echo 'Long terme : '.$this->escapeHtml($resultSport->obj_mt).'<br>';

								echo '<br><b>Observations</b><br>';
								echo $this->escapeHtml($resultSport->observations).'<br>';
								
								if ($resultSport->piece_jointe) echo '<br>Piece jointe : <a target="_blank", href="'.$this->basePath('resources/'.$resultSport->piece_jointe).'">'.$this->escapeHtml($resultSport->piece_jointe).'</a><br>';
							
								break;
								
								case 'Golf' :
							
								echo '<br><b>Technique</b><br>';
								echo 'Long jeu :'.$this->escapeHtml($resultSport->g_long_jeu).'<br>';
								echo 'Chipping : '.$this->escapeHtml($resultSport->g_chipping).'<br>';
								echo 'Putting : '.$this->escapeHtml($resultSport->g_putting).'<br>';
								echo 'Bunker : '.$this->escapeHtml($resultSport->g_bunker).'<br>';
								echo 'Parcours : '.$this->escapeHtml($resultSport->g_parcours).'<br>';
							
								echo '<br><b>Mental : </b>'.$this->escapeHtml($resultSport->mental).'<br>';
							
								echo '<br><b>Objectifs</b><br>';
								echo 'Court terme : '.$this->escapeHtml($resultSport->obj_ct).'<br>';
								echo 'Moyen terme : '.$this->escapeHtml($resultSport->obj_mt).'<br>';

								echo '<br><b>Observations</b><br>';
								echo $this->escapeHtml($resultSport->observations).'<br>';
								
								if ($resultSport->piece_jointe) echo '<br>Piece jointe : <a target="_blank", href="'.$this->basePath('resources/'.$resultSport->piece_jointe).'">'.$this->escapeHtml($resultSport->piece_jointe).'</a><br>';
								
								break;
								
								case 'Tennis' :
										
								echo '<br><b>Technique</b><br>';
								echo 'Coup droit :'.$this->escapeHtml($resultSport->t_coup_droit).'<br>';
								echo 'Revers : '.$this->escapeHtml($resultSport->t_revers).'<br>';
								echo 'Service : '.$this->escapeHtml($resultSport->t_service).'<br>';
								echo 'Volee : '.$this->escapeHtml($resultSport->t_volee).'<br>';
								echo 'Smash : '.$this->escapeHtml($resultSport->t_smash).'<br>';

								echo '<br><b>Physique</b><br>';
								echo 'Placement : '.$this->escapeHtml($resultSport->t_placement).'<br>';
								echo 'Jeux de jambe : '.$this->escapeHtml($resultSport->t_jeux_jambe).'<br>';
								echo 'Foncier : '.$this->escapeHtml($resultSport->t_foncier).'<br>';
								echo 'Vitesse : '.$this->escapeHtml($resultSport->t_vitesse).'<br>';
								echo 'Tests : '.$this->escapeHtml($resultSport->t_tests).'<br>';

								echo '<br><b>Mental : </b>'.$this->escapeHtml($resultSport->mental).'<br>';

								echo '<br><b>Objectifs</b><br>';
								echo 'Court terme : '.$this->escapeHtml($resultSport->obj_ct).'<br>';
								echo 'Moyen terme : '.$this->escapeHtml($resultSport->obj_mt).'<br>';

								echo '<br><b>Observations</b><br>';
								echo $this->escapeHtml($resultSport->observations).'<br>';
								
								if ($resultSport->piece_jointe) echo '<br>Piece jointe : <a target="_blank", href="'.$this->basePath('resources/'.$resultSport->piece_jointe).'">'.$this->escapeHtml($resultSport->piece_jointe).'</a><br>';
								
								break;
							}?>
						<?php endforeach; ?>
					<?php endif; ?>
					<br>
					<?php foreach ($messageTable->fetchAll() as $message) : ?>
						<?php
							if ($message->espace == 'Sports') {
								$select = 1;
								if ($message->dest_centre) {
									if ($message->dest_centre == 'Verneuil + Moisson') {
										if ($eleve->center_id != 'Verneuil' && $eleve->center_id != 'Moisson') $select = 0;
									}
									elseif ($message->dest_centre != $eleve->center_id) $select = 0;
								}
								if ($message->dest_sport && $message->dest_sport != $eleve->sport) $select = 0;
								if ($message->dest_categorie && $message->dest_categorie != $eleve->category) $select = 0;
								if ($message->dest_classe && $message->dest_classe != $eleve->class) $select = 0;
								if ($message->dest_formule && $message->dest_formule != $eleve->boarding_school) $select = 0;
								if ($select == 1) {
									echo '<b>'.$message->date_modif.' - '.$message->objet.'</b><br>';
									echo nl2br($message->texte).'<br>';
									if ($message->piece_jointe) echo '<b>Piece jointe : </b><a target="_blank", href="'.$this->basePath('resources/'.$message->piece_jointe).'">'.$this->escapeHtml($message->piece_jointe).'</a><br><br>';
								}
							}
						?>
					<?php endforeach; ?>
				</div>
			</div>
		</div>
		<div class="col-md-4">
        	<div class="panel panel-default">
            	<div class="panel-heading">
					<h3 class="panel-title">ETUDES</h3>
            	</div>
            	<div class="panel-body">
            		<b>CNED</b>
            		<br>&nbsp;&nbsp;<a target="_blank", href="http://www.academie-en-ligne.fr">Académie en ligne</a>
            		<br>&nbsp;&nbsp;<a target="_blank",  href="http://espaceinscrit.cned.fr/">Espace inscrit</a>
					<br><br><b>Classe : </b><?php echo $eleve->class ?><br>
					<?php foreach ($messageTable->fetchAll() as $message) : ?>
						<?php
							if ($message->espace == 'Etudes') {
								$select = 1;
								if ($message->dest_centre) {
									if ($message->dest_centre == 'Verneuil + Moisson') {
										if ($eleve->center_id != 'Verneuil' && $eleve->center_id != 'Moisson') $select = 0;
									}
									elseif ($message->dest_centre != $eleve->center_id) $select = 0;
								}
								if ($message->dest_sport && $message->dest_sport != $eleve->sport) $select = 0;
								if ($message->dest_categorie && $message->dest_categorie != $eleve->category) $select = 0;
								if ($message->dest_classe && $message->dest_classe != $eleve->class) $select = 0;
								if ($message->dest_formule && $message->dest_formule != $eleve->boarding_school) $select = 0;
								if ($select == 1) {
									echo '<br><b>'.$message->date_modif.' - '.$message->objet.'</b><br>';
									echo nl2br($message->texte).'<br>';
								}
							}
						?>
					<?php endforeach; ?>
<?php
echo $this->partial('/partials/learning-evaluation', array(
			'config' => $config,
    		'context' => $context,
           	'evaluations' => $evaluations,
    ));
?>				</div>
			</div>
       	</div>
       	<div class="col-md-4">
			<div class="panel panel-default">
			<?php
			    echo $this->partial('/partials/link-index', array('context' => $context, 'dir' => $dir, 'links' => $links, 'parent' => $parent, 'id' => $id, 'major' => $major));
			?>
		</div>
		</div>
       	<div class="col-md-4">
			<div class="panel panel-default">
            	<div class="panel-heading">
					<h3 class="panel-title">Médical</h3>
            	</div>
            	<div class="panel-body">
            		<?php
						foreach ($rdvs as $rdv) {
            				if ($rdv->rdv && $rdv->type) {
								echo '<b>'.$this->escapeHtml($rdv->rdv);
								if ($rdv->heure) echo ' '.$this->escapeHtml($rdv->heure);
								echo '</b> - '.$this->escapeHtml($rdv->type).'<br>';
								if ($rdv->lieu) echo '<b>Lieu : </b>'.$this->escapeHtml($rdv->lieu).'<br>';
								if ($rdv->nom_responsable) echo '<b>Accompagnateur : </b>'.$this->escapeHtml($rdv->nom_responsable).'<br>';
            				}
            				if ($rdv->medecin) {
								echo nl2br($rdv->medecin).'<br>';
            				}
	        				if ($rdv->entraineur) {
            					echo '(entraineur)<br>';
								echo nl2br($rdv->entraineur).'<br>';
            				}
            				if ($rdv->piece_jointe) echo '&nbsp;&nbsp;Piece jointe : <a target="_blank", href="'.$this->basePath('resources/'.$rdv->piece_jointe).'">'.$this->escapeHtml($rdv->piece_jointe).'</a><br><br>';
						}?>
				</div>
			</div>
		</div>
