
function connectRemoveIcon(id, target)
{
	$('#' + id).click(function () {
		$('#' + target).hide();
		$('.progress-detail-anchor').removeClass('btn-primary').addClass('btn-default');
	});
}

function getParams() {

	var params = '?', todo = true;

<?php foreach ($context->getConfig('commitmentEvent/search/p-pit-studies')['main'] as $propertyId => $rendering) : ?>

	<?php if ($rendering == 'range') : ?>
	
	var min_<?php echo $propertyId ?> = document.getElementById('search_min_<?php echo $propertyId ?>').value;
	if (min_<?php echo $propertyId ?>) min_<?php echo $propertyId ?> = encodeDate(min_<?php echo $propertyId ?>);
	if (min_<?php echo $propertyId ?>.length >= 2) { params += 'min_<?php echo $propertyId ?>=' + min_<?php echo $propertyId ?> + '&'; todo = false; }

	var max_<?php echo $propertyId ?> = document.getElementById('search_max_<?php echo $propertyId ?>').value;
	if (max_<?php echo $propertyId ?>) max_<?php echo $propertyId ?> = encodeDate(max_<?php echo $propertyId ?>);
	if (max_<?php echo $propertyId ?>.length >= 2) { params += 'max_<?php echo $propertyId ?>=' + max_<?php echo $propertyId ?> + '&'; todo = false; }

	<?php else : ?>

	var v_<?php echo $propertyId ?> = document.getElementById('search_<?php echo $propertyId ?>').value;
	if (v_<?php echo $propertyId ?>.length >= 2) { params += '<?php echo $propertyId ?>=' + v_<?php echo $propertyId ?> + '&'; todo = false; }
	
	<?php endif;?>

<?php endforeach;?>

<?php foreach ($context->getConfig('commitmentEvent/search/p-pit-studies')['more'] as $propertyId => $rendering) : ?>

	<?php if ($rendering == 'range') : ?>
	
	var min_<?php echo $propertyId ?> = document.getElementById('search_min_<?php echo $propertyId ?>').value;
	if (min_<?php echo $propertyId ?>) min_<?php echo $propertyId ?> = encodeDate(min_<?php echo $propertyId ?>);
	if (min_<?php echo $propertyId ?>.length >= 2) { params += 'min_<?php echo $propertyId ?>=' + min_<?php echo $propertyId ?> + '&'; todo = false; }

	var max_<?php echo $propertyId ?> = document.getElementById('search_max_<?php echo $propertyId ?>').value;
	if (max_<?php echo $propertyId ?>) max_<?php echo $propertyId ?> = encodeDate(max_<?php echo $propertyId ?>);
	if (max_<?php echo $propertyId ?>.length >= 2) { params += 'max_<?php echo $propertyId ?>=' + max_<?php echo $propertyId ?> + '&'; todo = false; }
	
	<?php else : ?>

	var v_<?php echo $propertyId ?> = document.getElementById('search_<?php echo $propertyId ?>').value;
	if (v_<?php echo $propertyId ?>.length >= 2) { params += '<?php echo $propertyId ?>=' + v_<?php echo $propertyId ?> + '&'; todo = false; }
	
	<?php endif;?>

<?php endforeach;?>

	<?php
	$todoTitle = (isset ($context->getConfig('commitmentEvent/search/p-pit-studies')['todoTitle']) ? $context->getConfig('commitmentNotification/search/p-pit-studies')['todoTitle'][$context->getLocale()] : $this->translate('active', 'ppit-core', $context->getLocale()));
	$searchTitle = (isset ($context->getConfig('commitmentEvent/search/p-pit-studies')['searchTitle']) ? $context->getConfig('commitmentNotification/search/p-pit-studies')['searchTitle'][$context->getLocale()] : $this->translate('search', 'ppit-core', $context->getLocale()));
	?>
	$('#mode-text').text((todo) ? '<?php echo $todoTitle ?>' : '<?php echo $searchTitle ?>');

	return params;
}

// Export the list
function exportEventList() {

	$('#form_action').hide();

	var params = getParams();
	document.location.href = '<?php echo $this->url('studentEvent/export') ?>' + params;
}

function eraseEventSearch() {

<?php foreach ($context->getConfig('commitmentEvent/search/p-pit-studies')['main'] as $propertyId => $rendering) : ?>

	$('#form_action').hide();

	<?php if ($rendering == 'range') : ?>
	$('#search_min_<?php echo $propertyId ?>').val('');
	$('#search_max_<?php echo $propertyId ?>').val('');

	<?php else : ?>
	$('#search_<?php echo $propertyId ?>').val('');
	
	<?php endif;?>

<?php endforeach;?>

<?php foreach ($context->getConfig('commitmentEvent/search/p-pit-studies')['more'] as $propertyId => $rendering) : ?>

	<?php if ($rendering == 'range') : ?>
	$('#search_min_<?php echo $propertyId ?>').val('');
	$('#search_max_<?php echo $propertyId ?>').val('');

	<?php else : ?>
	$('#search_<?php echo $propertyId ?>').val('');
	
	<?php endif;?>

<?php endforeach;?>

	getEventList(getParams(), 'end_time', 'ASC');
}

function sortEventList(criterion) {

	$('#form_action').hide();

	var dir;
	ascCriterion = $('.glyphicon-triangle-top').first().parent().attr('id');
	descCriterion = $('.glyphicon-triangle-bottom').first().parent().attr('id');
	if (criterion + '-anchor' == ascCriterion) dir = 'DESC'; else dir = 'ASC';
	getEventList(getParams(), criterion, dir);
}

function filterEventList() {

	ascCriterion = $('.glyphicon-triangle-top').first().parent().attr('id');
	descCriterion = $('.glyphicon-triangle-bottom').first().parent().attr('id');
	if (ascCriterion) {
		criterion = ascCriterion.split('-')[0];
		dir = 'ASC';
	}
	else {
		criterion = descCriterion.split('-')[0];
		dir = 'ASC';
	}
	getEventList(getParams(), criterion, dir);
}

function connectEventSearchInputs() {

	$('#export-button').click(function () { exportEventList(); });
	
	$('#erase-button').unbind();
	$('#erase-button').click(function () { eraseEventSearch(); });

<?php foreach ($context->getConfig('commitmentEvent/search/p-pit-studies')['main'] as $propertyId => $rendering) : ?>
	<?php 
	$property = $context->getConfig('core_account/p-pit-studies/property'.$propertyId);
	if ($property['definition'] != 'inline') $property = $context->getConfig($property['definition']);
	?>
	
	<?php if (
			$propertyId == 'category'
		||	$propertyId == 'discipline'
		||	$propertyId == 'level'
		||	$propertyId == 'specialty'
		||	$propertyId == 'school_year') : ?>
	$('#search_<?php echo $propertyId ?>').change(function () { filterEventList(); });

	<?php elseif ($rendering == 'range') : ?>
	$('#search_min_<?php echo $propertyId ?>').keyup(function () { filterEventList(); });
	$('#search_max_<?php echo $propertyId ?>').keyup(function () { filterEventList(); });

		<?php if ($property['type'] == 'date') : ?>
	$("#search_min_<?php echo $propertyId ?>").datepicker();
	$("#search_max_<?php echo $propertyId ?>").datepicker();
	$('#search_min_<?php echo $propertyId ?>').change(function () { filterEventList(); });
	$('#search_max_<?php echo $propertyId ?>').change(function () { filterEventList(); });
		<?php endif;?>
	
	<?php elseif ($rendering == 'select') : ?>
		$('#search_<?php echo $propertyId ?>').change(function () { filterEventList(); });
	
	<?php else : ?>
		$('#search_<?php echo $propertyId ?>').keyup(function () { filterEventList(); });

	<?php endif;?>

<?php endforeach;?>

<?php foreach ($context->getConfig('commitmentEvent/search/p-pit-studies')['more'] as $propertyId => $rendering) : ?>
	
	<?php if (
			$propertyId == 'category'
		||	$propertyId == 'discipline'
		||	$propertyId == 'level'
		||	$propertyId == 'specialty'
		||	$propertyId == 'school_year') : ?>
	$('#search_<?php echo $propertyId ?>').change(function () { filterEventList(); });

	<?php elseif ($rendering == 'range') : ?>
	$('#search_min_<?php echo $propertyId ?>').keyup(function () { filterEventList(); });
	$('#search_max_<?php echo $propertyId ?>').keyup(function () { filterEventList(); });

	<?php elseif ($rendering == 'date') : ?>
	$("#search_min_<?php echo $propertyId ?>").datepicker();
	$("#search_max_<?php echo $propertyId ?>").datepicker();
	$('#search_min_<?php echo $propertyId ?>').change(function () { filterEventList(); });
	$('#search_max_<?php echo $propertyId ?>').change(function () { filterEventList(); });
	
	<?php elseif ($rendering == 'select') : ?>
		$('#search_<?php echo $propertyId ?>').change(function () { filterEventList(); });
	
	<?php else : ?>
		$('#search_<?php echo $propertyId ?>').keyup(function () { filterEventList(); });

	<?php endif;?>

<?php endforeach;?>
}

// Load the list
function getEventList(params, major, dir) {		

	// Execute the ajax request
	route = '<?php echo $this->url('studentEvent/list') ?>' + params + '&major=' + major + ((dir =='ASC') ? '&dir=ASC' : '&dir=DESC');
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById('event-list-panel').innerHTML = xhttp.responseText;
			
			// Connect the sort anchors
			$('.ppit-sort-anchor').each(function () {
				$(this).click(function () {
					sortEventList($(this).attr('id').split('-')[0]);
				});
			});
			
			// Connect the detail anchors
			$('.event-detail-anchor').each(function () {
				$(this).click(function () {
					getEventUpdate($(this).attr('id').split('_')[1]);
				});
			});
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();
}

function connectAuditPanel()
{
	$('#audit-panel').hide();
	$('#audit-label').click(function () {
		if ($('#audit-label').text() == '<?php echo $this->translate('Show', 'ppit-core', $context->getLocale()) ?>') {
			$('#audit-panel').show();
			$('#audit-label').text('<?php echo $this->translate('Mask', 'ppit-core', $context->getLocale()) ?>');
		}
		else {
			$('#audit-panel').hide();
			$('#audit-label').text('<?php echo $this->translate('Show', 'ppit-core', $context->getLocale()) ?>');
		}
	});
}

<?php 
$properties = array();

foreach ($context->getConfig('commitmentEvent/update/p-pit-studies')['criteria'] as $criterionId => $unused) {
	$criterion = $context->getConfig('core_account/p-pit-studies/property/'.$criterionId);
	if ($criterion['definition'] != 'inline') $criterion = $context->getConfig($criterion['definition']);
	$properties[$criterionId] = array('type' => $criterion['type'], 'mandatory' => false, 'maxSize' => 255);
}

$properties['category'] = array('type' => 'select', 'mandatory' => true);
$properties['begin_date'] = array('type' => 'date', 'mandatory' => false);
$properties['begin_h'] = array('type' => 'select', 'mandatory' => false);
$properties['begin_m'] = array('type' => 'select', 'mandatory' => false);
$properties['end_date'] = array('type' => 'date', 'mandatory' => false);
$properties['end_h'] = array('type' => 'select', 'mandatory' => false);
$properties['end_m'] = array('type' => 'select', 'mandatory' => false);
$properties['location'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 65535);
$properties['title'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 65535);
$properties['comment'] = array('type' => 'textarea', 'mandatory' => false, 'maxSize' => 2047);
$properties['update_time'] = array('type' => 'hidden');

echo $this->partial('/partials/check-update-properties', array('entity' => 'Event', 'context' => $context, 'properties' => $properties)) 
?>

function connectEventUpdateForm(id)
{
	$('#input_begin_date').datepicker();
	$('#input_end_date').datepicker();
	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {
		
		event.preventDefault();

		// Check validity
		var validity = checkEventUpdateProperties();

		if (validity) {

			// Create a new FormData object.
			var formData = new FormData();
			
			// Get the properties values
<?php foreach ($properties as $propertyId => $property) : ?>
	<?php if ($property['type'] == 'ckeditor') : ?>
			formData.append('<?php echo $propertyId ?>', CKEDITOR.instances.<?php echo $propertyId ?>.getData());
	<?php else : ?>	
			formData.append('<?php echo $propertyId ?>', document.getElementById('<?php echo $propertyId ?>').value);
	<?php endif;?>
<?php endforeach ?>

			var account_id, val;
			for (i=0; i < $('#matching-account-number').val(); i++) {
				account_id = $('#matching-account_' + i).val();
				if (document.getElementById('target_' + account_id + '_checkbox').checked) {
					$('#target_' + account_id).val(1);
				}
				else {
					$('#target_' + account_id).val(0);
				}
				formData.append('target_' + account_id, $('#target_' + account_id).val());
			}

			var xhttp = new XMLHttpRequest();
			var route, target;
			route = '<?php echo $this->url('studentEvent/update') ?>/' + id;
			target = 'form_action';
			xhttp.open('POST', route, true);
			// Set up a handler for when the request finishes.
			xhttp.onload = function () {
				if (xhttp.readyState == 4 <?php if (!$context->getConfig()['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
					document.getElementById(target).innerHTML = xhttp.responseText;
					connectRemoveIcon('remove-anchor', 'form_action');
					connectAuditPanel();
/*					CKEDITOR.replace('content');
					connectContentPanel();*/
					filterEventList();
				}
			};
			xhttp.send(formData);
		}
		else return false;
	}
}

function getEventUpdate(id) {

	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('studentEvent/update') ?>/' + id;

	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			$('#form_action').show();
			$(location).attr('href', '#form_action');
			document.getElementById('form_action').innerHTML = xhttp.responseText;			
			connectRemoveIcon('remove-anchor', 'form_action');
			connectAuditPanel();
/*			CKEDITOR.replace('content');
			connectContentPanel();*/
			connectEventUpdateForm(id);
			
			// Connect the delete anchor
			$('#delete-anchor').click(function () {
				getEventDelete(id);
			});
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();

	// Highlight the clicked button (and only it in its class)
	$('.index-btn').removeClass("btn-primary").addClass("btn-default");
	$('#event-detail-anchor_' + id).removeClass("btn-default").addClass("btn-primary");
}

function connectEventDeleteForm(id)
{
	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {
		
		event.preventDefault();

		// Create a new FormData object.
		var formData = new FormData();
			
		// Get the properties values
		formData.append('status', 'deleted');
		formData.append('update_time', $('#update_time').val());

		var xhttp = new XMLHttpRequest();
		var route, target;
		route = '<?php echo $this->url('studentEvent/delete') ?>/' + id;
		target = 'form_action';
		xhttp.open('POST', route, true);
		// Set up a handler for when the request finishes.
		xhttp.onload = function () {
			if (xhttp.readyState == 4 <?php if (!$context->getConfig()['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
				document.getElementById(target).innerHTML = xhttp.responseText;
				connectRemoveIcon('remove-anchor', 'form_action');
				filterEventList();
			}
		};
		xhttp.send(formData);
	}
}

function getEventDelete(id) {

	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('studentEvent/delete') ?>/' + id;

	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			$('#form_action').show();
			document.getElementById('form_action').innerHTML = xhttp.responseText;			
			connectRemoveIcon('remove-anchor', 'form_action');
			connectEventDeleteForm(id);
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();

	// Highlight the clicked button (and only it in its class)
	$('.detail-menu-btn').removeClass("btn-primary").addClass("btn-default");
	$('#delete-anchor').removeClass("btn-default").addClass("btn-primary");
}

function activateEvent() {

	// Load the search panel and highlight the menu entry
	loadPanel('index_action', '<?php echo $this->url('studentEvent/search') ?>');
	$('.menu-btn').removeClass("btn-primary").addClass("btn-default");
	var eventAnchor = '#event-anchor';
	$(eventAnchor).removeClass("btn-default").addClass("btn-primary");

	<?php
	$todoTitle = (isset ($context->getConfig('commitmentEvent/search/p-pit-studies')['todoTitle']) ? $context->getConfig('commitmentEvent/search/p-pit-studies')['todoTitle'][$context->getLocale()] : $this->translate('active', 'ppit-core', $context->getLocale()));
	?>
	$('#mode-text').text('<?php echo $todoTitle ?>');
		
	// Connect the search inputs
	connectEventSearchInputs();
	
	getEventList('?', 'begin_time', 'ASC');
	
	$('#add-criteria').click(function () {
		mode = $('#add-criteria').text();
		if (mode == '<?php echo $this->translate('More criteria', 'ppit-core', $context->getLocale()) ?>') {
			$('#add-criteria').text('<?php echo $this->translate('Less criteria', 'ppit-core', $context->getLocale()) ?>');
			$('#search-area').show();
		}
		else {
			$('#add-criteria').text('<?php echo $this->translate('More criteria', 'ppit-core', $context->getLocale()) ?>');
			$('#search-area').hide();
		}
	});
	$('#search-area').hide();
}
