
function getEvents(print = false) {

	// Execute the ajax request
	route = '<?php echo $this->url('studentEvent/planning').'?account_id='.$account_id ?>';
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			var minTime = (print) ? '08:00:00' : '00:00:00';
		    $('#calendar').fullCalendar({
		    	lang: '<?php echo substr($context->getLocale(), 0, 2) ?>',
		    	height: 650,
		        defaultView: 'agendaWeek',
		        scrollTime: '08:00:00',
		        minTime: minTime,
		        businessHours: {
				   	dow: [ 1, 2, 3, 4, 5, 6], // Monday - Thursday
				    start: '08:00',
				    end: '18:00'
			    },
				customButtons: {
			        myCustomButton: {
			            text: '<?php echo $this->translate('Printable', 'ppit-document', $context->getLocale()) ?>',
			            click: function() {
			                window.open('<?php echo $this->url('public/communityHomePrint') ?>');
			            }
			        }
			    },
    			header: {
				    left: 'prev,next today myCustomButton',
				    center: 'title',
				    right: 'month,agendaWeek,agendaDay'
				}
    		});
			obj = jQuery.parseJSON(xhttp.responseText);

			jQuery.each(obj.planning, function (name, value) {
				var color = 'lightBlue', textColor = 'black';			
<?php foreach ($context->getConfig('commitmentEvent/p-pit-studies')['category'] as $categoryId => $category) : ?>
	<?php foreach ($category['color'] as $color => $unused) : ?>
				if (value.properties['category'] == '<?php echo $categoryId ?>') {
					color = '<?php echo $color ?>';
					textColor = 'white';
				}
	<?php endforeach;?>
<?php endforeach;?>

				var title = value.properties['property_3'];
				if (value.properties['caption']) title += ' - ' + value.properties['caption'];
				if (value.properties['location']) title += ' (' + value.properties['location'] + ')';
				var event={
					id:value.id,
					title: title,
					color: color,
					textColor: textColor,
					start:  $.fullCalendar.moment(value.properties['begin_date'] + ' ' + value.properties['begin_time']), 
					end:  $.fullCalendar.moment(value.properties['begin_date'] + ' ' + value.properties['end_time'])
				};
				$('#calendar').fullCalendar('renderEvent', event, true);
			});

			jQuery.each(obj.events, function (name, value) {
				var color = 'lightBlue', textColor = 'black';			
<?php foreach ($context->getConfig('commitmentEvent/p-pit-studies')['category'] as $categoryId => $category) : ?>
	<?php foreach ($category['color'] as $color => $unused) : ?>
				if (value.category == '<?php echo $categoryId ?>') {
					color = '<?php echo $color ?>';
					textColor = 'white';
				}
	<?php endforeach;?>
<?php endforeach;?>

				var event={
					id:value.id,
					allDay: true,
					title: value.title + ' (' + value.location + ')',
					color: color,
					textColor: textColor,
					start:  $.fullCalendar.moment(value.begin_time), 
					end:  $.fullCalendar.moment(value.end_time)
				};
				$('#calendar').fullCalendar('renderEvent', event, true);
			});
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();
}

function connectNewsFlashTab(route) {

	// Execute the ajax request
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById('news_flash-panel').innerHTML = xhttp.responseText;
			getEvents();
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();
}

function connectStudentTab(route) {

	// Execute the ajax request
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById('news_flash-panel').innerHTML = xhttp.responseText;
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();
}

function getStudentDetail() {

	// Ensure the target is displayed
	$('#main-panel').show();

	var route = '<?php echo $this->url('student/detail', array('id' => $account_id)) ?>';

	// Execute the ajax request
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById('main-panel').innerHTML = xhttp.responseText;
			
			connectNewsFlashTab('<?php echo $this->url('student/dashboard', array('account_id' => $account_id, 'category' => 'news_flash')) ?>');
			
			$('#news_flash-tab').click(function () {
				$('.student-tab').removeClass('active');
				$('#news_flash-tab').addClass('active');
				connectNewsFlashTab('<?php echo $this->url('student/dashboard', array('account_id' => $account_id, 'category' => 'news_flash')) ?>');
			});
			
			$('#file-tab').click(function () {
				$('.student-tab').removeClass('active');
				$('#file-tab').addClass('active');
				connectStudentTab('<?php echo $this->url('document/list', array('account_id' => $account_id)) ?>/' + '1849');
			});

			$('#sport-tab').click(function () {
				$('.student-tab').removeClass('active');
				$('#sport-tab').addClass('active');
				connectStudentTab('<?php echo $this->url('student/dashboard', array('account_id' => $account_id, 'category' => 'sport')) ?>');
			});

			$('#schooling-tab').click(function () {
				$('.student-tab').removeClass('active');
				$('#schooling-tab').addClass('active');
				connectStudentTab('<?php echo $this->url('student/dashboard', array('account_id' => $account_id, 'category' => 'schooling')) ?>');
			});
/*
			$('#boarding-school-tab').click(function () {
				$('.student-tab').removeClass('active');
				$('#boarding-school-tab').addClass('active');
				connectStudentTab('<?php echo $this->url('student/dashboard', array('account_id' => $account_id, 'category' => 'boarding_school')) ?>');
			});

			$('#medical-tab').click(function () {
				$('.student-tab').removeClass('active');
				$('#medical-tab').addClass('active');
				connectStudentTab('<?php echo $this->url('student/dashboard', array('account_id' => $account_id, 'category' => 'medical')) ?>');
			});*/
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();
}

function activateStudentHome() {
	getStudentDetail();
}
