<?php
    echo $this->partial('/partials/sport-studies-home', array(
           	'eleve' => $eleve,
           	'evaluations' => $evaluations,
           	'resultSports' => $resultSports,
           	'resultSportTable' => $resultSportTable,
    		'absences' => $absences,
    		'rdvs' => $rdvs,
    		'messageTable' => $messageTable,
    		'complet' => $complet,

			'config' => $config,
    		'currentUser' => $currentUser,
    		'dir' => $dir,
    		'major' => $major,
    		'links' => $links,
       		'parent' => $parent,
    		'id' => $id,
    ));
?>