<?php

$title = 'Nouveau mot de passe';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title)?></h1>
<br>
<a href="<?php echo $this->url('home', array('action'=>'index'));?>">Annuler</a>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('home', array('action' => 'password', 'id' => $this->id)));
	$form->prepare();
	echo $this->form()->openTag($form);
?>
<?php foreach ($form as $element) : ?>
 
    <div style="width: 330px;" class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
        <?php
            if ('submit' != $element->getAttribute('type')) { ?>
                <label class="control-label"><?php echo $element->getLabel() ?></label>
                <?php
                $element->setAttribute('class', 'form-control')
                        ->setAttribute('placeholder', $element->getLabel());
            } else {
                $element->setAttribute('class', 'btn btn-success');
            }
            echo $this->formElement($element);
            if ($this->formElementErrors($element)) : ?>
                <?php
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<p class="help-block">')
                    ->setMessageSeparatorString('</p><p class="help-block">')
                    ->setMessageCloseString('</p>')
                    ->render($element);
                ?>
            <?php endif; ?>
    </div>
 
<?php
endforeach;
echo $this->form()->closeTag();
?>