<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
		'update_time' => $absence->update_time,
		'message' => $message,
		'error' => $error,
		'csrfForm' => $csrfForm,
		'context' => $context,
));
?>

<!-- Subject -->
<?php if ($message == 'OK') $isDisabled = true; else $isDisabled = false; ?>
		<div class="form-group" id="subject_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Subject', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<select class="form-control" id="subject" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
	    			<option value=""><-- <?php echo $this->translate('Please choose', 'ppit-core', $context->getLocale()) ?> --></option>
<?php foreach ($config['absence/update']['types'][$type]['subjects'] as $subject) : ?>
	<?php $caption = $subject[$context->getLocale()]; ?>
	    			<option value="<?php echo $caption ?>" <?php if ($absence->subject == $caption) echo 'selected="selected"' ?>><?php echo $caption ?></option>
<?php endforeach;?>
	    		</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="subject_error"></p></div>
		</div>

<!-- Absence date -->
<?php $absenceDate = ($absence->date) ? $absence->date : Date('Y-m-d') ?>
		<input type="hidden" id="date" />
		<div class="form-group" id="input_date_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Date', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input class="form-control" id="input_date" value="<?php echo $context->decodeDate($absenceDate) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			</div>
			<div class="col-sm-12"><p class="help-block" id="input_date_error"></p></div>
		</div>

<!-- Comment -->
		<div class="form-group" id="comment_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Comment', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<textarea class="form-control" id="comment" <?php if ($isDisabled) echo 'disabled="disabled"'?>></textarea>
			</div>
			<div class="col-sm-12"><p class="help-block" id="comment_error"></p></div>
		</div>

<?php if ($message != 'OK') : ?>
		<div class="form-group">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<input name="submit" type="submit" id="submit-button" class="btn btn-warning" value="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
			</div>
		</div>
<?php endif;?>

	</form>
