<div class="panel panel-default">
	<div class="panel-heading" style="background:  <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<strong><?php echo $this->translate('Detail', 'ppit-core', $context->getLocale()) ?></strong>
 		<div class="btn-group pull-right">
			<button type="button" class="btn btn-default" title="<?php echo $this->translate('Return to list', 'ppit-core', $context->getLocale()) ?>" id="remove-anchor">
				<span class="glyphicon glyphicon-remove"></span>
			</button>
 		 </div>
	</div>
	<div class="panel-body">

<!-- Menu -->
		<div>
			<button type="button" class="btn btn-default btn-xs detail-menu-btn" title="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale())?>" id="delete-anchor">
				<span class="glyphicon glyphicon-trash" id="group-glyphicon"></span>
			</button>
		</div>

<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
		'update_time' => $absence->update_time,
		'message' => $message,
		'error' => $error,
		'csrfForm' => $csrfForm,
		'context' => $context,
));
?>

<?php if ($message == 'OK') $isDisabled = true; else $isDisabled = false; ?>

	<?php if (!$isDisabled) : ?>
<!-- Up submit -->
		<div class="form-group">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<input name="submit" type="submit" id="up-submit-button" class="btn btn-danger" value="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>">
			</div>
		</div>
	<?php endif;?>

<!-- Name -->

	<div class="form-group" id="product_group">
		<label class="col-sm-5 control-label">&nbsp;</label>
		<div class="col-sm-7">
			<input class="form-control" disabled="disabled" value="<?php echo $absence->name ?>" />
		</div>
	</div>

<!-- School year -->
		<div class="form-group" id="school_year_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('School year', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select class="form-control" id="school_year" disabled="disabled">
	<?php foreach ($context->getConfig('student/property/school_year')['modalities'] as $schoolYearId => $schoolYear) : ?>
					<option value="<?php echo $schoolYearId ?>" <?php if ($absence->school_year == $schoolYearId) echo ' selected="selected"' ?>><?php echo $schoolYear[$context->getLocale()] ?></option>
	<?php endforeach;?>
				</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="school_year_error"></p></div>
		</div>

<!-- Absence date -->
<?php $absenceDate = ($absence->date) ? $absence->date : Date('Y-m-d') ?>
		<input type="hidden" id="date" />
		<div class="form-group" id="input_date_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Date', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input class="form-control" id="input_date" value="<?php echo $context->decodeDate($absenceDate) ?>" disabled="disabled" />
			</div>
			<div class="col-sm-12"><p class="help-block" id="input_date_error"></p></div>
		</div>

<!-- Subject -->
		<div class="form-group" id="subject_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Subject', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input class="form-control" id="input_date" value="<?php echo $absence->subject ?>" disabled="disabled" />
			</div>
			<div class="col-sm-12"><p class="help-block" id="subject_error"></p></div>
		</div>

<!-- Observations -->
		<div class="form-group" id="observations_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Observations', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<textarea class="form-control" id="observations" disabled="disabled"><?php echo $absence->observations ?></textarea>
			</div>
			<div class="col-sm-12"><p class="help-block" id="observations_error"></p></div>
		</div>

	<?php if (!$isDisabled) : ?>
		<div class="form-group">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<input name="submit" type="submit" id="submit-button" class="btn btn-danger" value="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>">
			</div>
		</div>
	<?php endif;?>

	</form>
	</div>
</div>
