<!-- 
/**
 * 2pit V2.0
 *
 * @link      https://github.com/2pit-io/2pit.io/tree/master/vendor/PpitCore
 * @license   https://github.com/2pit-io/2pit.io/blob/master/vendor/PpitCore/license.txt GNU-GPL license
 */
-->

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 ppit-panel" id="index-panel"></div>
  </div>
</div>

<!-- Modal -->

<!-- Form opening tag -->
<div class="modal fade" id="modalForm" tabindex="-1" role="dialog" data-backdrop="static" aria-labelledby="modalFormLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalFormLabel"><?php echo $this->translate('Detail', 'ppit-core', $context->getLocale()) ?></h5>
      <div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" title="<?php echo $this->translate('Cancel', 'ppit-core', $context->getLocale()) ?>">
          <span aria-hidden="true">&times;</span>
        </button>
        </div>
      </div>
      <div class="modal-body">
        <div class="container" id ="absence-update-panel"></div>
      </div>
    </div>
  </div>
</div>
