<table class="table table-striped ppit_index">
	<tr>
		<th>&nbsp;</th>

<?php foreach ($context->getConfig('absence/list') as $propertyId => $rendering) : ?>
		<th align="center">
	<?php 
	$property = $context->getConfig('absence')['properties'][$propertyId];
	if ($property['type'] == 'repository') $property = $context->getConfig($property['definition']);
	$label = $property['labels'][$context->getLocale()];
	?>
	<?php if ($label) : ?>
			<button type="button" class="btn btn-default btn-xs ppit-sort-anchor" id="<?php echo $propertyId ?>-anchor">
				<span><?php echo $label ?></span>
		<?php if ($major == $propertyId) : ?>
				<span class="glyphicon glyphicon-triangle-<?php echo ($dir == 'ASC') ? 'top' : 'bottom' ?>"></span>
		<?php endif ?>
			</button>
	<?php endif;?>
		</th>
<?php endforeach;?>

	</tr>

<?php $i = 0; $sum = 0;
foreach ($absences as $absence) : ?>
	<?php $sum += $absence->duration; ?> 
	
	<input type="hidden" id="absence_<?php echo $i ?>" value="<?php echo $absence->id ?>" />
	
	<tr>

		<td>
			<button type="button" class="btn btn-default index-btn absence-detail-anchor" title="<?php echo $this->translate('Detail', 'ppit-core', $context->getLocale())?>" id="absence-detail-anchor_<?php echo $absence->id ?>">
				<span class="glyphicon glyphicon-zoom-in" id="group-glyphicon"></span>
			</button>
		</td>

	<?php foreach ($context->getConfig('absence/list') as $propertyId => $rendering) : ?>
	
		<?php if ($propertyId == 'subject') : ?>
		<td><?php echo $context->getConfig('absence')['types'][$absence->type]['subject']['modalities'][$absence->subject][$context->getLocale()] ?></td>
		
		<?php else : ?>
			<?php $property = $context->getConfig('absence')['properties'][$propertyId] ?>
			<?php if ($property['type'] == 'repository') $property = $context->getConfig($property['definition']) ?>
	
			<?php if ($propertyId == 'n_fn') : ?>
		<td><?php echo $absence->n_fn ?></td>
	
			<?php elseif ($propertyId == 'duration') : ?>
		<td style="text-align: right"><?php if ((int)($absence->duration/60)) echo ((int)($absence->duration/60)).'h' ?><?php if ($absence->duration%60) echo ($absence->duration%60).'mn' ?></td>

			<?php elseif ($rendering == 'date') : ?>
		<td><?php echo $context->decodeDate($absence->properties[$propertyId]) ?></td>

			<?php elseif ($rendering == 'number') : ?>
		<td style="text-align: right"><?php if ($absence->category == 'lateness') echo $absence->properties[$propertyId] ?></td>

			<?php elseif ($rendering =='select') : ?>
		<td><?php echo $property['modalities'][$absence->properties[$propertyId]][$context->getLocale()] ?></td>

			<?php else : ?>
		<td><?php echo $absence->properties[$propertyId] ?></td>

			<?php endif;?>
		<?php endif;?>
		
	<?php endforeach;?>
	
	</tr>
	
	<tr class="detail-row" id="detail-row_<?php echo $absence->id ?>" rowspan="2"><td colspan="99"><div class="col-md-6 col-md-offset-3 ppit-panel" id="detail-div_<?php echo $absence->id ?>"></div></td></tr>
	<tr class="invisible"><td colspan="99"></td></tr>
	
<?php $i++; endforeach; ?>
	
	<tr>
		<td colspan="<?php echo count($context->getConfig('absence/list')) ?>" style="font-weight: bold; text-align:right"><?php echo $this->translate('Total duration', 'ppit-studies', $context->getLocale()) ?></td>
		<td style="font-weight: bold; text-align:right"><?php if ((int)($sum/60)) echo ((int)($sum/60)).'h' ?><?php if ($sum%60) echo sprintf("%02u", $sum%60).'mn' ?></td>
	</tr>

</table>
