<table class="table table-striped ppit_index">
	<tr>
		<th>&nbsp;</th>

<?php foreach ($context->getConfig('absence/list') as $propertyId => $rendering) : ?>
		<th align="center">
	<?php $label = $context->getConfig('student')['properties'][$propertyId]['labels'][$context->getLocale()] ?>
	<?php if ($label) : ?>
			<button type="button" class="btn btn-default btn-xs ppit-sort-anchor" id="<?php echo $propertyId ?>-anchor">
				<span><?php echo $label ?></span>
<?php if ($major == $propertyId) : ?>
				<span class="glyphicon glyphicon-triangle-<?php echo ($dir == 'ASC') ? 'top' : 'bottom' ?>"></span>
<?php endif ?>
			</button>
	<?php endif;?>
		</th>
<?php endforeach;?>

	</tr>

<?php foreach ($absences as $absence) : ?>
	
	<input type="hidden" id="absence_<?php echo $i ?>" value="<?php echo $absence->id ?>" />
	
	<tr>

		<td>
			<button type="button" class="btn btn-default btn-xs index-btn absence-detail-anchor" title="<?php echo $this->translate('Detail', 'ppit-core', $context->getLocale())?>" id="absence-detail-anchor_<?php echo $absence->id ?>">
				<span class="glyphicon glyphicon-zoom-in" id="group-glyphicon"></span>
			</button>
		</td>

	<?php foreach ($context->getConfig('absence/list') as $propertyId => $rendering) : ?>
	
		<?php $property = $context->getConfig('student')['properties'][$propertyId] ?>
	
		<?php if ($propertyId == 'name') : ?>
		<td><?php echo $absence->name ?></td>

		<?php elseif ($propertyId == 'sport') : ?>
		<td style="text-align: center">
			<img height="20" src="<?php echo $this->basePath('/img/p-pit-studies/'.$absence->sport.'.png') ?>" title="<?php echo $absence->sport ?>" alt="<?php echo $absence->sport ?>" />
		</td>

		<?php elseif ($propertyId == 'class') : ?>
		<td><?php echo $property['modalities'][$absence->class][$context->getLocale()] ?>

		<?php elseif ($propertyId == 'specialty') : ?>
		<td><?php echo $property['modalities'][$absence->specialty][$context->getLocale()] ?>
	
		<?php elseif ($propertyId == 'photo') : ?>
		<td>
			<span class="info">
				<img height="40" src="<?php echo $this->url('vcard/photo', array('id' => $absence->photo)) ?>"/>
				<span><img height="150" src="<?php echo $this->url('vcard/photo', array('id' => $absence->photo)) ?>"/></span>
			</span>
		</td>
	
		<?php elseif ($rendering == 'text') : ?>
		<td><?php echo $absence->properties[$propertyId] ?></td>

		<?php elseif ($rendering == 'image') : ?>
		<td style="text-align: center">
			<img height="20" src="<?php echo $this->basePath('/img/'.$context->getInstance()->caption.'/'.$absence->properties[$propertyId].'.png') ?>" title="<?php echo $absence->properties[$propertyId] ?>" alt="<?php echo $absence->properties[$propertyId] ?>" />
		</td>

		<?php elseif ($rendering == 'phone') : ?>
		<td>
			<a href="tel:<?php echo $absence->properties[$propertyId] ?>"><?php echo $absence->properties[$propertyId] ?></a>
		</td>

		<?php elseif ($rendering == 'select') : ?>
		<td><?php echo $property['modalities'][$absence->properties[$propertyId]][$context->getLocale()] ?>
		</td>
	
		<?php else : ?>
		<td><?php echo $absence->properties[$propertyId] ?></td>
		
		<?php endif;?>
		
	<?php endforeach;?>
	
	</tr>
	
<?php endforeach; ?>

</table>
