<div class="panel panel-default">
	<div class="panel-heading" style="background: <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<strong>
			<?php 
			$title = $context->getConfig('absence/search')['title'][$context->getLocale()];
			echo $title;
			?>
			(<span id="mode-text"></span>)
		</strong>
	</div>
	<div class="panel-body">

		<div class="col-md-6">

<!-- Filters -->

		<div class="form-group">
			<label class="col-sm-5 control-label"><span class="glyphicon glyphicon-search"></span></label>
			<div class="col-sm-7">
	    		<button type="button" class="form-control btn btn-default btn-xs" title="<?php echo $this->translate('Erase', 'ppit-core', $context->getLocale()) ?>" id="erase-button">
					<span class="glyphicon glyphicon-remove"></span>
				</button>
			</div>
		</div>
		
<?php foreach ($context->getConfig('absence/search')['main'] as $propertyId => $rendering) : ?>

	<?php if ($propertyId == 'type') : ?> 

		<div class="form-group">
		<label class="col-sm-5 control-label"><?php echo $this->translate('Type', 'ppit-studies', $context->getLocale()) ?></label>
		<div class="col-sm-7">
			<select id="search_type" class="form-control">
				<option value=""></option>
		<?php foreach ($context->getConfig('absence')['types'] as $typeId => $type) : ?>
	    		<option value="<?php echo $typeId ?>"><?php echo $type['labels'][$context->getLocale()] ?></option>
		<?php endforeach;?>
	    	</select>
		</div>

	<?php else : ?>
	
		<?php
		$property = $context->getConfig('absence')['properties'][$propertyId];
		if ($property['type'] == 'repository') $property = $context->getConfig($property['definition']);
		$label = $property['labels'][$context->getLocale()];
		?>
	
		<?php if ($propertyId == 'place_id') : ?>
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $label ?></label>
			<div class="col-sm-7">
				<select id="search_place_id" class="form-control">
					<option value=""></option>
		<?php foreach ($places as $place) : ?>
		    		<option value="<?php echo $place->id ?>"><?php echo $place->caption ?></option>
		<?php endforeach;?>
		    	</select>
			</div>
		</div>

		<?php elseif ($rendering == 'contains') : ?>
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $label ?></label>
			<div class="col-sm-7">
				<input class="form-control" type="text" id="search_<?php echo $propertyId ?>" placeholder="<?php echo $this->translate('Contains', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<?php elseif ($rendering == 'range') : ?>

		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $label ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_min_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_max_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<?php elseif ($rendering == 'select') : ?>
		
		<?php
		$modalities = array();
		if (array_key_exists('p-pit-studies', $context->getPerimeters()) && array_key_exists($propertyId, $context->getPerimeters()['p-pit-studies'])) {
			foreach ($context->getPerimeters()['p-pit-studies'][$propertyId] as $modalityId) {
				$modalities[$modalityId] = $property['modalities'][$modalityId][$context->getLocale()];
			} 
		}
		else {
			foreach ($property['modalities'] as $modalityId => $modality) {
				$modalities[$modalityId] = $modality[$context->getLocale()];
			} 
		}
		?>
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $label ?></label>
			<div class="col-sm-7">
				<select id="search_<?php echo $propertyId ?>" class="form-control">
					<option value=""></option>
		<?php foreach ($modalities as $modalityId => $modalityLabel) : ?>
		    		<option value="<?php echo $modalityId ?>"><?php echo $modalityLabel ?></option>
		<?php endforeach;?>
		    	</select>
			</div>
		</div>

		<?php endif;?>
	<?php endif;?>
<?php endforeach;?>
	
		<div><a id="add-criteria" href="#"><?php echo $this->translate('More criteria', 'ppit-core', $context->getLocale())?></a></div>
		<div id="search-area">
		
<?php foreach ($context->getConfig('absence/search')['more'] as $propertyId => $rendering) : ?>

	<?php if ($propertyId == 'type') : ?> 

		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Type', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select id="search_type" class="form-control">
					<option value=""></option>
		<?php foreach ($context->getConfig('absence')['types'] as $typeId => $type) : ?>
		    		<option value="<?php echo $typeId ?>"><?php echo $type['labels'][$context->getLocale()] ?></option>
		<?php endforeach;?>
		    	</select>
			</div>
		</div>

	<?php else : ?>
	
		<?php
		if ($propertyId == 'school_year') $property = $context->getConfig('student/property/school_year');
		elseif ($propertyId == 'period') $property = $context->getConfig('student/property/school_period');
		elseif ($propertyId == 'name') $property = $context->getConfig('core_account/p-pit-studies')['properties']['name'];
		else $property = $property = $context->getConfig('absence')['properties'][$propertyId];
		$label = $property['labels'][$context->getLocale()];
		?>

		<?php if ($rendering == 'contains') : ?>
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $label ?></label>
			<div class="col-sm-7">
				<input class="form-control" type="text" id="search_<?php echo $propertyId ?>" placeholder="<?php echo $this->translate('Contains', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<?php elseif ($rendering == 'range') : ?>

		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $label ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_min_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_max_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<?php elseif ($rendering == 'select') : ?>

		<?php
		$modalities = array();
		if (array_key_exists('p-pit-studies', $context->getPerimeters()) && array_key_exists($propertyId, $context->getPerimeters()['p-pit-studies'])) {
			foreach ($context->getPerimeters()['p-pit-studies'][$propertyId] as $modalityId) {
				$modalities[$modalityId] = $property['modalities'][$modalityId][$context->getLocale()];
			} 
		}
		else {
			foreach ($property['modalities'] as $modalityId => $modality) {
				$modalities[$modalityId] = $modality[$context->getLocale()];
			} 
		}
		?>
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $label ?></label>
			<div class="col-sm-7">
				<select id="search_<?php echo $propertyId ?>" class="form-control">
					<option value=""></option>
		<?php foreach ($modalities as $modalityId => $modalityLabel) : ?>
		    		<option value="<?php echo $modalityId ?>"><?php echo $modalityLabel ?></option>
		<?php endforeach;?>
		    	</select>
			</div>
		</div>

		<?php endif;?>
	<?php endif;?>
<?php endforeach;?>

		</div>

	    <div>&nbsp;</div>

<!-- Actions -->
	    <div>
	    		<button type="button" class="btn btn-default" title="<?php echo $this->translate('Export', 'ppit-core', $context->getLocale()) ?>" id="export-button">
					<span class="glyphicon glyphicon-cloud-download"></span>
					<span><?php echo $this->translate('Export', 'ppit-core', $context->getLocale())?></span>
				</button>
	    </div>
	    </div>

<!-- Add or update section -->
		<div id="absence-list-panel"></div>
	</div>
</div>
