<div class="panel panel-default">
	<div class="panel-heading" style="background:  <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<strong><?php echo $this->translate('Detail', 'ppit-core', $context->getLocale()) ?></strong>
 		<div class="btn-group pull-right">
			<button type="button" class="btn btn-default" title="<?php echo $this->translate('Return to list', 'ppit-core', $context->getLocale()) ?>" id="remove-anchor">
				<span class="glyphicon glyphicon-remove"></span>
			</button>
 		 </div>
	</div>
	<div class="panel-body">

<?php if ($message != 'OK') : ?>
<!-- Menu -->
		<div>
			<button type="button" class="btn btn-default detail-menu-btn" id="update-anchor" title="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>">
				<span class="glyphicon glyphicon-edit"></span>
			</button>

			<button type="button" class="btn btn-default detail-menu-btn" id="delete-anchor" title="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale())?>">
				<span class="glyphicon glyphicon-trash""></span>
			</button>
		</div>
<?php endif;?>

<!-- Display the audit -->
		<div>&nbsp;</div>
		<?php echo $this->translate('History', 'ppit-core', $context->getLocale()) ?> (<a id="audit-label"><?php echo $this->translate('Show', 'ppit-core', $context->getLocale()) ?></a>)
		<div id="audit-panel" class="panel panel-default">
			<div class="panel-body">
	<?php foreach ($absence->audit as $comment) : ?>
				<div class="row">
					<div class="col-md-12">
						<strong><?php echo $context->decodeDate(substr($comment['time'], 0, 10)).substr($comment['time'], 10) ?>:</strong>&nbsp;
						<?php if (array_key_exists('status', $comment)) echo $comment['status'] ?>&nbsp;
						(<?php echo $comment['n_fn'] ?>)
					</div>
				</div>
				<div class="row">
					<div class="col-md-2" align="right">&nbsp;</div>
					<div class="col-md-10"><em><?php echo $comment['comment'] ?></em></div>
				</div>
	<?php endforeach;?>
			</div>
		</div>
		<div>&nbsp;</div>

<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
		'update_time' => $absence->update_time,
		'message' => $message,
		'error' => $error,
		'csrfForm' => $csrfForm,
		'context' => $context,
));
?>

<?php 
if ($absence->id && $action != 'update' || $message == 'OK') $isDisabled = true; else $isDisabled = false;
?>

<?php if ($message != 'OK') : ?>
	<?php if (!$absence->id) : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input type="submit" id="up-submit-button" class="btn btn-warning" value="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

	<?php elseif ($action == 'update') : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input type="submit" id="up-submit-button" class="btn btn-warning" value="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

	<?php elseif ($action == 'delete') : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input type="submit" id="up-submit-button" class="btn btn-danger" value="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>
	<?php endif;?>
<?php endif;?>

<!-- Name -->

	<div class="form-group" id="product_group">
		<label class="col-sm-5 control-label">&nbsp;</label>
		<div class="col-sm-7">
			<input class="form-control" disabled="disabled" value="<?php echo $absence->name ?>" />
		</div>
	</div>

<!-- Category -->
		<div class="form-group" id="category_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Absence/Lateness', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select class="form-control" id="category" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
					<option value="absence" <?php if ($absence->category == 'absence') echo 'selected="selected"' ?>><?php echo $this->translate('Absence', 'ppit-studies', $context->getLocale()) ?></option>
					<option value="lateness" <?php if ($absence->category == 'lateness') echo 'selected="selected"' ?>><?php echo $this->translate('Lateness', 'ppit-studies', $context->getLocale()) ?></option>
				</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="category_error"></p></div>
		</div>

<!-- Subject -->
<?php $subject = $context->getConfig('absence')['types'][$absence->type]['subject'] ?>
		<div class="form-group" id="subject_group">
			<label class="col-sm-5 control-label">* <?php echo $subject['labels'][$context->getLocale()] ?></label>
			<div class="col-sm-7">
	    		<select class="form-control" id="subject" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
	    			<option value=""><-- <?php echo $this->translate('Please choose', 'ppit-core', $context->getLocale()) ?> --></option>
<?php foreach ($subject['modalities'] as $modalityId => $modality) : ?>
	<?php $caption = $modality[$context->getLocale()]; ?>
	    			<option value="<?php echo $modalityId ?>" <?php if ($absence->subject == $modalityId) echo 'selected="selected"' ?>><?php echo $caption ?></option>
<?php endforeach;?>
	    		</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="subject_error"></p></div>
		</div>

<!-- Absence date -->
<?php $absenceDate = ($absence->date) ? $absence->date : Date('Y-m-d') ?>
		<input type="hidden" id="date" />
		<div class="form-group" id="input_date_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Date', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input class="form-control" id="input_date" value="<?php echo $context->decodeDate($absenceDate) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			</div>
			<div class="col-sm-12"><p class="help-block" id="input_date_error"></p></div>
		</div>

<!-- Duration -->
		<input type="hidden" id="duration" />
		<div class="form-group" id="input_duration_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Lateness duration', 'ppit-studies', $context->getLocale()) ?> (mn)</label>
			<div class="col-sm-7">
				<input class="form-control" id="input_duration" value="<?php echo $absence->duration ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			</div>
			<div class="col-sm-12"><p class="help-block" id="input_duration_error"></p></div>
		</div>

<!-- Motive -->
<?php $motive = $context->getConfig('absence/property/motive') ?>
		<div class="form-group" id="motive_group">
			<label class="col-sm-5 control-label"><?php echo $motive['labels'][$context->getLocale()] ?></label>
			<div class="col-sm-7">
	    		<select class="form-control" id="motive" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
	    			<option value=""><-- <?php echo $this->translate('Please choose', 'ppit-core', $context->getLocale()) ?> --></option>
<?php foreach ($motive['modalities'] as $modalityId => $modality) : ?>
	<?php $caption = $modality[$context->getLocale()]; ?>
	    			<option value="<?php echo $modalityId ?>" <?php if ($absence->motive == $modalityId) echo 'selected="selected"' ?>><?php echo $caption ?></option>
<?php endforeach;?>
	    		</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="motive_error"></p></div>
		</div>

<!-- Observations -->
		<div class="form-group" id="observations_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Observations', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<textarea class="form-control" id="observations" <?php if ($isDisabled) echo 'disabled="disabled"'?>><?php echo $absence->observations ?></textarea>
			</div>
			<div class="col-sm-12"><p class="help-block" id="observations_error"></p></div>
		</div>

<!-- Comment -->
		<div class="form-group" id="comment_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Internal comment (non visible to the parents)', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<textarea class="form-control" id="comment" <?php if ($isDisabled) echo 'disabled="disabled"'?>></textarea>
			</div>
			<div class="col-sm-12"><p class="help-block" id="comment_error"></p></div>
		</div>

<?php if (!$isDisabled) : ?>

	<?php if (!$absence->id) : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="submit-button" class="btn btn-warning" value="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

	<?php elseif ($action == 'update') : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="submit-button" class="btn btn-warning" value="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

	<?php elseif ($action == 'delete') : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="submit-button" class="btn btn-danger" value="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>
	<?php endif;?>
<?php endif;?>

	</form>
	</div>
</div>
