<div class="panel panel-default">
	<div class="panel-heading" style="background:  <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<strong><?php echo $this->translate('Delete an event', 'ppit-commitment', $context->getLocale()) ?></strong>
 		<div class="btn-group pull-right">
			<button type="button" class="btn btn-default" title="<?php echo $this->translate('Return to list', 'ppit-core', $context->getLocale()) ?>" id="remove-anchor">
				<span class="glyphicon glyphicon-remove"></span>
			</button>
 		 </div>
	</div>
	<div class="panel-body">

<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
		'update_time' => $event->update_time,
		'message' => $message,
		'error' => $error,
		'csrfForm' => $csrfForm,
		'context' => $context,
));
?>

<?php if ($message == 'OK') $isDisabled = true; else $isDisabled = false; ?>

	<?php if (!$isDisabled) : ?>
<!-- Up submit -->
		<div class="form-group">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<input name="submit" type="submit" id="up-submit-button" class="btn btn-danger" value="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>">
			</div>
		</div>
	<?php endif;?>

<!-- Category -->
		<div class="form-group" id="category_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Category', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select class="form-control" id="category" disabled="disabled">
	    			<option value=""><-- <?php echo $this->translate('Please choose', 'ppit-core', $context->getLocale()) ?> --></option>
	<?php foreach ($context->getConfig('commitmentEvent/p-pit-studies')['category'] as $categoryId => $category) : ?>
					<option value="<?php echo $categoryId ?>" <?php if ($event->category == $categoryId) echo ' selected="selected"' ?>><?php echo $category['labels'][$context->getLocale()] ?></option>
	<?php endforeach;?>
				</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="category_error"></p></div>
		</div>

<!-- Title -->
		<div class="form-group" id="title_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Object', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<textarea class="form-control" id="title" disabled="disabled"><?php echo $event->title ?></textarea>
			</div>
			<div class="col-sm-12"><p class="help-block" id="title_error"></p></div>
		</div>
		
<!-- Begin time -->
<?php $beginDate = ($event->begin_time) ? substr($event->begin_time, 0, 10) : Date('Y-m-d') ?>
		<input type="hidden" id="begin_date" />
		<div class="form-group" id="input_begin_date_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Begin', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input class="form-control" id="input_begin_date" value="<?php echo $context->decodeDate($beginDate) ?>" disabled="disabled" />
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-5 control-label"></label>
			<div class="col-sm-3">
				<select class="form-control" id="begin_h" disabled="disabled">
<?php for ($i = 0; $i < 24; $i++) : ?>
					<option value="<?php echo sprintf('%02d', $i) ?>" <?php if ((int)substr($event->begin_time, 11,2) == $i) echo ' selected="selected"' ?>><?php echo sprintf('%02d', $i) ?></option>
<?php endfor;?>
				</select>
			</div>
			<label class="col-sm-1 control-label"></label>
			<div class="col-sm-3">
				<select class="form-control" id="begin_m" disabled="disabled">
<?php for ($i = 0; $i < 60; $i++) : ?>
					<option value="<?php echo sprintf('%02d', $i) ?>" <?php if ((int)substr($event->begin_time, 14,2) == $i) echo ' selected="selected"' ?>><?php echo sprintf('%02d', $i) ?></option>
<?php endfor;?>
				</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="input_begin_date_error"></p></div>
		</div>

<!-- End time -->
<?php $endDate = ($event->end_time) ? substr($event->end_time, 0, 10) : null ?>
		<input type="hidden" id="end_date" />
		<div class="form-group" id="input_end_date_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Display end', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input class="form-control" id="input_end_date" value="<?php echo $context->decodeDate($endDate) ?>" disabled="disabled" />
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-5 control-label"></label>
			<div class="col-sm-3">
				<select class="form-control" id="end_h" disabled="disabled">
<?php for ($i = 0; $i < 24; $i++) : ?>
					<option value="<?php echo sprintf('%02d', $i) ?>" <?php if ((int)substr($event->end_time, 11,2) == $i) echo ' selected="selected"' ?>><?php echo sprintf('%02d', $i) ?></option>
<?php endfor;?>
				</select>
			</div>
			<label class="col-sm-1 control-label"></label>
			<div class="col-sm-3">
				<select class="form-control" id="end_m" disabled="disabled">
<?php for ($i = 0; $i < 60; $i++) : ?>
					<option value="<?php echo sprintf('%02d', $i) ?>" <?php if ((int)substr($event->end_time, 14,2) == $i) echo ' selected="selected"' ?>><?php echo sprintf('%02d', $i) ?></option>
<?php endfor;?>
				</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="input_end_date_error"></p></div>
		</div>

<!-- Location -->
		<div class="form-group" id="location_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Location', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" id="location" value="<?php echo $event->location ?>" disabled="disabled" />
			</div>
			<div class="col-sm-12"><p class="help-block" id="location_error"></p></div>
		</div>

	<?php if (!$isDisabled) : ?>
		<div class="form-group">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<input name="submit" type="submit" id="submit-button" class="btn btn-danger" value="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>">
			</div>
		</div>
	<?php endif;?>

	</form>
	</div>
</div>
