<!-- 
/**
 * PpitCore V1.0 (https://github.com/p-pit/PpitCore)
 *
 * @link      https://github.com/p-pit/PpitCore
 * @copyright Copyright (c) 2016 Bruno Lartillot
 * @license   https://github.com/p-pit/PpitCore/blob/master/license.txt GNU-GPL license
 */
-->
			
<!-- Global message -->
<?php if ($requestType == 'POST' && $statusCode == '200') : ?>
	<div id="message">
      <h5 class="alert alert-success my-3 text-center"><?php echo $this->translate('Your request has been registered', 'ppit-core', $context->getLocale()) ?></h5>
	</div>
<?php endif;?>

<?php 
if ($requestType == 'POST' && $statusCode == '200') $isDisabled = true; else $isDisabled = false;
?>

<div class="panel-body">

<h5 class="card-title text-muted"><?php echo $this->translate('Selected groups', 'ppit-core', $context->getLocale()) ?></h5>
     
<?php $i = 0; foreach ($groups as $group) : ?>

<div class="form-group row">
	<label class="col-sm-5 control-label">&nbsp;</label>
	<div class="col-sm-7">
		<input class="form-control" disabled="disabled" value="<?php echo $group->name ?>" />
	</div>
</div>
	
<?php $i++; endforeach;?>

<div class="form-group row">
	<label class="col-sm-5 col-form-label"><?php echo $this->translate('Select the period', 'ppit-studies', $context->getLocale()) ?></label>
	<div class="col-sm-7">
		<select class="form-control" id="period" <?php if ($isDisabled) echo 'disabled' ?>>
            <option/>
<?php foreach ($context->getConfig('student/property/school_period')['modalities'] as $periodId => $period) : ?>
			<option value="<?php echo $periodId?>"><?php echo $context->localize($period) ?></option>
<?php endforeach;?>
		</select>
	</div>
</div>

<?php if ($requestType == 'GET') : ?>
<div class="form-group row">
	<div class="col-sm-5">&nbsp;</div>
	<div class="col-sm-7">
		<button type="button" id="generate-period-button" class="btn btn-warning"><?php echo $this->translate('Generate reports', 'ppit-studies', $context->getLocale()) ?></button>
	</div>
</div>
<?php endif;?>