<!-- 
/**
 * PpitCore V1.0 (https://github.com/p-pit/PpitCore)
 *
 * @link      https://github.com/p-pit/PpitCore
 * @copyright Copyright (c) 2016 Bruno Lartillot
 * @license   https://github.com/p-pit/PpitCore/blob/master/license.txt GNU-GPL license
 */
-->
        <div class="card mt-3">
          <div class="card-body">

<?php if (in_array($requestType, ['POST', 'DELETE'])) : ?>

<!-- Global message -->
            <div id="message">
              <h5 class="alert alert-success my-3 text-center"><?php echo $this->translate('Your request has been registered', 'ppit-core', $context->getLocale()) ?></h5>
            </div>

<?php endif;?>
            
            <h5 class="card-title text-muted"><?php echo $this->translate('Selected notes', 'ppit-studies', $context->getLocale()) ?></h5>
     
<?php $i = 0; foreach ($noteLinks as $note_link_id => $noteLink) : ?>

      <div class="form-group row">
        <div class="col-sm-12">
          <input class="form-control" disabled="disabled" value="<?php echo $noteLink->school_year . ' ' . $noteLink->school_year . ' ' . (($noteLink->class) ? $noteLink->class . ' ' : '') . (($noteLink->group_id) ? $noteLink->group_id . ' ' : '') . $noteLink->subject . ': ' . $noteLink->name . ' (' . $noteLink->value . ')' ?>" />
        </div>
      </div>
      
<?php $i++; endforeach;?>
     
          </div>
        </div>
        
        <div class="card my-4">
          <div class="card-header">
			
			<ul class="nav nav-tabs card-header-tabs">
              <li class="nav-item"><a class="nav-link group-tab active" id="group-update-tab"><?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?></a></li>
			  <li class="nav-item"><a class="nav-link group-tab" id="group-delete-tab"><?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?></a></li>
			</ul>
          </div>
          
          <div class="card-body">

<?php if (!in_array($requestType, ['POST', 'DELETE'])) : ?>

            <div class="group-panel" id="group-update-panel">

              <div class="form-group row">
                <label class="col-sm-5 control-label">Groupe</label>
                <div class="col-sm-1">
                  <input type="checkbox" class="form-control" id="noteLinkCheck-group_id" />
                </div>

                <div class="col-sm-6">
                  <select class="form-control noteLink-group" id="noteLinkGroup-group_id" name="group_id">
                    <option />
      <?php 
    $modalities = array();
    foreach ($groups as $group_id => $group) {
      if ($context->hasRole('manager') || !$myGroups || in_array($group_id, $myGroups)) $modalities[$group_id] = $group;
    }
      ?>
    <?php foreach ($modalities as $modalityId => $modality) : ?>
                    <option value="<?php echo $modalityId ?>"><?php echo $context->localize($modality) ?></option>
    <?php endforeach;?>
                  </select>
                </div>
              </div>

              <div class="form-group row">
                <label class="col-sm-5 control-label">Intervenant</label>
                <div class="col-sm-1">
                  <input type="checkbox" class="form-control" id="noteLinkCheck-teacher_id" />
                </div>

                <div class="col-sm-6">

                  <select class="form-control noteLink-group" id="noteLinkGroup-teacher_id" name="teacher_id">
                    <option />
    <?php foreach ($teachers as $teacher) : ?>
                    <option value="<?php echo $teacher->contact_1_id ?>"><?php echo $teacher->n_fn . ' - ' . $teacher->place_caption ?></option>
    <?php endforeach;?>
                  </select>
                </div>
              </div>
  
              <div class="form-group row">
                <div class="col-sm-5">&nbsp;</div>
                <div class="col-sm-7">
                  <input name="submit" type="submit" id="group-update-button" class="btn btn-warning" value="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>">
                </div>
            </div>

			<div class="group-panel" id="group-delete-panel">
			    <div class="form-group row">
					<div class="col-sm-5">&nbsp;</div>
					<div class="col-sm-7">
						<input name="submit" type="submit" id="group-delete-button" class="btn btn-warning" value="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>">
					</div>
				</div>
            </div>
<?php endif;?> 
         
          </div>
        </div>
