<div class="card">
  <div class="card-header">

<!-- Main menu -->
<?php echo $this->partial('partials/core-menu.phtml') ?>

  </div>
  <div class="card-body">

	<!-- Main panel -->
	<div class="row">
        <input type="hidden" id="limit" value="50" />
		<div class="col-md-12" id="search_panel"></div>
	</div>
  </div>
</div>

<!-- Modal -->

<!-- Form opening tag -->
<div class="modal fade" id="modalForm" tabindex="-1" role="dialog" data-backdrop="static" aria-labelledby="modalFormLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalFormLabel"><?php echo $this->translate('Detail', 'ppit-core', $context->getLocale()) ?></h5>
      <div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" title="<?php echo $this->translate('Cancel', 'ppit-core', $context->getLocale()) ?>">
          <span aria-hidden="true">&times;</span>
        </button>
        </div>
      </div>
      <div class="modal-body">
        <div class="container" id ="note-update-panel"></div>
      </div>
    </div>
  </div>
</div>
