<!-- 
/**
 * PpitAccounting V1.0 (https://github.com/p-pit/PpitAccounting)
 *
 * @link      https://github.com/p-pit/PpitAccounting
 * @copyright Copyright (c) 2016 Bruno Lartillot
 * @license   https://github.com/p-pit/PpitAccounting/blob/master/license.txt GNU-GPL license
 */
-->

<style>
table td { 
  font-size: 0.9rem;
}
</style>

<div class="col-md-12">
 
  <table class="table table-sm table-hover">
    <tr class="table-info">
      <th>&nbsp;</th>
      <th>&nbsp;</th>

<?php if ($type == 'report') : ?>
      <th>&nbsp;</th>
<?php endif;?>

<?php foreach ($content['config']['list'] as $propertyId => $property) : ?>
  <?php 
	if (substr($order, 0, 1) == '-') {
		$dir = 'DESC';
		$major = substr($order, 1);
	}
	else {
		$dir = 'ASC';
		$major = $order;
	}
  ?>
      <th align="center">
        <a type="button" class="btn btn-sm sort_anchor <?php if ($content['major'] == $propertyId) echo 'btn-secondary active '.(($content['major'] == $propertyId) ? (($content['dir'] == 'ASC') ? 'sort_anchor_up' : 'sort_anchor_down') : '') ?>" role="button" id="<?php echo $propertyId ?>-anchor">
          <span><?php echo $context->localize($property['labels']) ?></span>
    <?php if ($content['major'] == $propertyId) : ?>
          <i class="fas fa-caret-<?php echo ($content['dir'] == 'ASC') ? 'up' : 'down' ?>"></i>
    <?php endif ?>
        </a>
		</th>
<?php endforeach;?>

	</tr>
  
    <tr>
      <td>
        <input type="checkbox" class="noteLink-checkbox" id="noteLink-checkbox"></input>
      </td>
 
      <td style="text-align: center">
        <button type="button" class="btn btn-sm btn-outline-primary index-btn noteLink-detail-anchor" data-toggle="tooltip" title="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale())?>" id="note-detail-anchor_0">
          <i class="fas fa-plus" id="group-glyphicon"></i>
        </button>
      </td>
  
      <td class="text-center">
        <div class="input-group input-group-sm">
          <button type="button" class="btn btn-sm btn-outline-primary index-btn noteLink-group-anchor" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('Grouped actions', 'ppit-core', $context->getLocale())?>" id="group-anchor">
            <span class="fas fa-list" id="group-glyphicon"></span>
          </button>
        </div>
      </td>
  
      <td colspan="<?php echo count($listPage['properties']) ?>">&nbsp;</td>
    </tr>

<?php foreach ($content['links'] as $link) : ?>
	
	<tr>
      <td>
        <input type="checkbox" class="noteLink-checkbox noteLink-checkbox-row" id="noteLink_checkbox-<?php echo $link['id'] ?>"></input>
      </td>

<?php if ($type == 'report') : ?>
      <td>
  <?php if ($link['subject'] == 'global') : ?>
    <?php if ($context->getInstance()->caption == 'ESI') : ?>
        <a href="<?php echo $this->url('myGema/downloadReport', ['category' => 'report', 'account_id' => $link['account_id'], 'school_year' => $link['school_year']]) ?>"><?php echo $this->translate('Download in PDF format', 'ppit-studies', $context->getLocale()) ?></a>
    <?php else : ?>
        <a href="<?php echo $this->url('student/download', ['category' => 'report', 'account_id' => $link['account_id'], 'school_year' => $link['school_year'], 'school_period' => $link['school_period']]) ?>"><?php echo $this->translate('Download in PDF format', 'ppit-studies', $context->getLocale()) ?></a>
    <?php endif;?>
  <?php endif;?>        
      </td>
<?php endif;?>

      <td style="text-align: center">
        <button type="button" class="btn btn-sm btn-outline-primary index-btn noteLink-detail-anchor" data-toggle="tooltip" title="<?php echo $this->translate('Detail', 'ppit-core', $context->getLocale())?>" id="note-detail-anchor_<?php echo ($type == 'report') ? $link['id'] : $link['note_id'] ?>">
          <i class="fas fa-search" id="group-glyphicon"></i>
        </button>
      </td>

	<?php foreach ($content['config']['list'] as $propertyId => $property) : ?>
          
        <?php if ($propertyId == 'place_id') : ?>
        <td><?php echo ($link[$propertyId]) ? $property['modalities'][$link[$propertyId]] : '' ?></td>
	
        <?php elseif ($propertyId == 'group_id') : ?>
    		<td><?php echo ($link[$propertyId] && array_key_exists($link[$propertyId], $groups)) ? $groups[$link[$propertyId]]['name'] : (($link[$propertyId]) ? $link[$propertyId] : '') ?></td>
	
        <?php elseif ($propertyId == 'teacher_id') : ?>
    		<td><?php echo ($link[$propertyId] && array_key_exists($link[$propertyId], $teachers)) ? $teachers[$link[$propertyId]]['n_fn'] : (($link[$propertyId]) ? $link[$propertyId] : '') ?></td>
  
        <?php elseif ($propertyId == 'subject') : ?>
        <td><?php echo ($link['subject'] == 'global') ? $this->translate('Global average', 'ppit-studies', $context->getLocale()) : (($link[$propertyId]) ? $context->localize($property['modalities'][$link[$propertyId]]) : '') ?></td>
    
        <?php elseif ($propertyId == 'value') : ?>
        <td>  
          <?php if ($type == 'note') : ?>
            <?php if ($content['config']['list']['value']['type'] == 'number') : ?>
	     	  <?php echo ($link['value'] !== null) ? $link['value'] : 'Non noté' ?>

            <?php else : ?>
              <?php //echo $context->localize($content['config']['list']['value']['modalities'][sprintf($link['value'])]) ?>
    <?php foreach ($content['config']['list']['value']['modalities'] as $categoryId => $category) : ?>
              <?php if ($link['value'] == $categoryId) echo $context->localize($category) ?>
    <?php endforeach;?>
            
            <?php endif;?>
          
          <?php else : ?>
            <?php 
	    	$averageReference = $context->getConfig('student/parameter/average_computation')['reference_value'];
            if (array_key_exists($link['school_year'] . '_' . $link['school_period'] . '_' . $link['account_id'] . '_' . $link['subject'], $averages)) {
				$average = $averages[$link['school_year'] . '_' . $link['school_period'] . '_' . $link['account_id'] . '_' . $link['subject']];
				$average = $context->formatFloat($average['num'] / $average['den'] * $averageReference, 2);
            }
            else $average = 'Non calculé';
			?>
            <?php echo $average ?>
          <?php endif;?>
        </td>
    
		<?php elseif ($property['type'] == 'input') : ?>
		<td><?php echo $link[$propertyId] ?></td>
	
		<?php elseif (in_array($property['type'], ['select', 'dynamic'])) : ?>
		<td><?php echo ($link[$propertyId] && array_key_exists($link[$propertyId], $property['modalities'])) ? $context->localize($property['modalities'][$link[$propertyId]]) : (($link[$propertyId]) ? $link[$propertyId] : '') ?></td>
	
		<?php elseif ($property['type'] == 'number') : ?>
		<td style="text-align: right"><?php echo $context->formatFloat($link[$propertyId], 2) ?></td>
	
		<?php else : ?>
		<td><?php echo $link[$propertyId] ?></td>
		
		<?php endif;?>

	<?php endforeach;?>
	
	</tr>
	
<?php endforeach; ?>

    <tr>
      <td>
        <input type="checkbox" class="noteLink-checkbox" id="down-noteLink-checkbox"></input>
      </td>
    
        <td style="text-align: center">
          <div class="input-group input-group-sm">
            <button type="button" class="btn btn-sm btn-outline-primary index-btn noteLink-group-anchor" id="noteLink_down_group_anchor">
              <i class="fas fa-list" id="group-glyphicon"></i>
            </button>
          </div>
        </td>

<?php if (count($content['links']) == '50') : ?>
        <td style="text-align: center">
          <div class="input-group input-group-sm">
            <button type="button" class="btn btn-sm btn-outline-primary index-btn" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('Display the entire list', 'ppit-core', $context->getLocale())?>" id="more-anchor">
              <i class="fas fa-ellipsis-h" id="more-glyphicon"></i>
            </button>
          </div>
        </td>
<?php else : ?>
        <td>&nbsp;</td>
<?php endif;?>
        <td colspan="<?php echo count($listPage['properties']) ?>">&nbsp;</td>
      </tr>

<?php if ($type == 'note') : ?>

  <tr class="table-info">
    <th>&nbsp;</th>
    <th>&nbsp;</th>

<?php if ($type == 'report') : ?>
      <th>&nbsp;</th>
<?php endif;?>

    <?php $subjectProperty = $content['config']['list']['subject'] ?>

    <th class="text-center" colspan="<?php echo count($content['config']['list']) ?>">

      <select class="px-0 py-0 my-0" id="select-distribution">

      <?php foreach ($content['averages'] as $subjectId => $average) : ?>
        <?php if ($subjectId != 'global') : ?>
          <?php $subject = $subjectProperty['modalities'][$subjectId] ?>
        <option value="<?php echo $subjectId ?>"><?php echo $context->localize($subject) ?></option>
        <?php endif;?>
      <?php endforeach;?>

      <?php if (count($content['links'])) : ?>
        <option value="<?php echo 'global' ?>"><?php echo $this->translate('Global average', 'ppit-studies', $context->getLocale()) ?></option>
      <?php endif;?>

      </select>

      <?php 
      $reference = $context->getConfig('student/parameter/average_computation')['reference_value'];
      ?>
      <?php foreach ($content['averages'] as $subjectId => $average) : ?>
        <?php if ($subjectId != 'global') : ?>
      <span class="distribution" id="distribution_<?php echo $subjectId ?>"><?php echo round($average[0] / $average[1] * $reference * 100) / 100 ?></span>
        <?php endif;?>
      <?php endforeach;?>
  
      <?php if (count($content['links'])) : ?>
      <span class="distribution" id="distribution_global"><?php echo round($content['globalAverage'][0] / $content['globalAverage'][1] * $reference * 100) / 100 ?></span>
      <?php endif;?>
    
    </th>
  </tr>
    
<?php endif;?>

  </table>
</div>
