
<!-- Filters -->
	<form class="form-inline">
      <div class="row">
		
<?php foreach ($configSearch as $propertyId => $property) : ?>
  <?php 
  $label = $context->localize($property['labels']);
  $options = (array_key_exists('options', $property)) ? $property['options'] : [];
  ?>
        <div class="col-md-3">

  <?php if (in_array($property['type'], array('date', 'datetime'))) : ?>

        <div class="input-group input-group-sm mb-2 mr-sm-2">
          <input type="hidden" value="0" class="search_check_value" id="search_check_value-<?php echo $propertyId ?>" />
          <div class="input-group-prepend">
            <button type="button" class="btn btn-secondary input-group-text search_check" id="search_check-<?php echo $propertyId ?>"><?php echo $label ?></button>
          </div>
		  <input class="form-control search_input search_input_date search_input_date_min" type="text" id="search_min-<?php echo $propertyId ?>" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
          <input class="form-control search_input search_input_date search_input_date_max" type="text" id="search_max-<?php echo $propertyId ?>" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
        </div>

  <?php elseif (in_array($property['type'], array('time', 'number'))) : ?>

        <div class="input-group input-group-sm mb-2 mr-sm-2">
          <input type="hidden" value="0" class="search_check_value" id="search_check_value-<?php echo $propertyId ?>" />
          <div class="input-group-prepend">
            <button type="button" class="btn btn-secondary input-group-text search_check" id="search_check-<?php echo $propertyId ?>"><?php echo $label ?></button>
          </div>
          <input class="form-control search_input search_input_text_min" type="text" id="search_min-<?php echo $propertyId ?>" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
          <input class="form-control search_input search_input_text_max" type="text" id="search_max-<?php echo $propertyId ?>" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
        </div>

	<?php elseif (in_array($property['type'], ['select', 'multiselect'])) : ?>

		<?php
		$modalities = array();
	
		if ($propertyId == 'place_id') foreach ($places as $place) {
			$modalities[$place->id] = $place->caption;
		} 
		else foreach ($property['modalities'] as $modalityId => $modality) {
			if (!array_key_exists('archive', $modality) || !$modality['archive']) $modalities[$modalityId] = $context->localize($modality);
		}

		if (array_key_exists('multiple', $options) && $options['multiple']) $multiple = true; else $multiple = false;
		?>
        <div class="input-group input-group-sm mb-2 mr-sm-2">
          <input type="hidden" value="0" class="search_check_value" id="search_check_value-<?php echo $propertyId ?>" />
          <div class="input-group-prepend">
            <button type="button" class="btn btn-secondary input-group-text search_check" id="search_check-<?php echo $propertyId ?>"><?php echo $label ?></button>
          </div>
          <select class="form-control search_input search_input_select <?php if ($multiple) echo 'selectpicker search_selectpicker' ?>" id="search-<?php echo $propertyId ?>" <?php if ($multiple) echo 'data-none-selected-text' ?> <?php if ($multiple) echo 'multiple' ?>>
      <?php if (!$multiple) : ?>
            <option value=""></option>
      <?php endif;?>
      <?php foreach ($modalities as $modalityId => $modalityLabel) : ?>
            <option value="<?php echo $modalityId ?>"><?php echo $modalityLabel ?></option>
      <?php endforeach;?>
            <option value="*">*</option>
          </select>
        </div>
	
	<?php else : ?>
        <div class="input-group input-group-sm mb-2 mr-sm-2">
          <input type="hidden" value="0" class="search_check_value" id="search_check_value-<?php echo $propertyId ?>" />
          <div class="input-group-prepend">
            <button type="button" class="btn btn-secondary input-group-text search_check" id="search_check-<?php echo $propertyId ?>"><?php echo $label ?></button>
          </div>
          <input class="form-control search_input search_input_text" type="text" id="search-<?php echo $propertyId ?>" />
        </div>

	<?php endif;?>
        </div> <!-- col -->
<?php endforeach;?>

        <div class="col-md-3">    
        <div class="input-group input-group-sm mb-2 mr-sm-2">
          <button type="button" class="btn btn-default" disabled title="<?php echo $this->translate('Refresh the list', 'ppit-core', $context->getLocale()) ?>" id="refresh-button">
            <i class="fa fa-sync-alt text-center"></i>
          </button>
          <button type="button" class="btn btn-default input-group-text" disabled title="<?php echo $this->translate('Erase', 'ppit-core', $context->getLocale()) ?>" id="erase-button">
            <i class="fa fa-times text-center"></i>
          </button>
          <a type="button" class="input-group-text btn" role="button" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('Export', 'ppit-core', $context->getLocale()) ?>" id="export-button">
            <i class="fa fa-cloud-download-alt"></i>
          </a>
        </div>
        </div> <!-- col -->
        
        </div> <!-- row -->
      </form>

<!-- Add or update section -->
    <div style="background-color: #ffffff;" class="row">
      <div>&nbsp;</div>
      <input type="hidden" id="limit" value="50" />
      <div class="table-responsive" id="noteLink-list-panel"></div>
    </div>
