<!-- 
/**
 * PpitAccounting V1.0 (https://github.com/p-pit/PpitAccounting)
 *
 * @link      https://github.com/p-pit/PpitAccounting
 * @copyright Copyright (c) 2016 Bruno Lartillot
 * @license   https://github.com/p-pit/PpitAccounting/blob/master/license.txt GNU-GPL license
 */
-->

<style>
table td { 
  font-size: 0.9rem;
}
</style>

<div class="col-md-12">
 
  <table class="table table-sm table-hover">
    <tr class="table-info">

<?php foreach ($content['config']['student_list'] as $propertyId => $property) : ?>
      <th align="center">
        <a type="button" class="btn btn-sm noteLink-sort-anchor <?php if ($content['major'] == $propertyId) echo 'btn-secondary active '.(($content['major'] == $propertyId) ? (($content['dir'] == 'ASC') ? 'noteLink-sort-anchor-up' : 'noteLink-sort-anchor-down') : '') ?>" role="button" id="noteLink_sort_anchor-<?php echo $propertyId ?>">
          <span><?php echo $context->localize($property['labels']) ?></span>
    <?php if ($content['major'] == $propertyId) : ?>
          <i class="fas fa-caret-<?php echo ($content['dir'] == 'ASC') ? 'up' : 'down' ?>"></i>
    <?php endif ?>
        </a>
		</th>
<?php endforeach;?>

	</tr>

<?php foreach ($content['links'] as $link) : ?>
	
	<tr>

	<?php foreach ($content['config']['student_list'] as $propertyId => $property) : ?>
          
        <?php if ($propertyId == 'place_id') : ?>
        <td><?php echo ($link[$propertyId]) ? $property['modalities'][$link[$propertyId]] : '' ?></td>
    
        <?php elseif ($propertyId == 'value') : ?>
        <td>  
          <?php if (true) : //$content['config']['list']['value']['type'] == 'number') : ?>
		  <?php echo $link['value'] ?>

          <?php else : ?>
            <?php echo $context->localize($content['config']['list']['value']['modalities'][sprintf($link['value'])]) ?>
            
          <?php endif;?>
        </td>
    
		<?php elseif ($property['type'] == 'input') : ?>
		<td><?php echo $link[$propertyId] ?></td>
	
		<?php elseif (in_array($property['type'], ['select', 'dynamic'])) : ?>
		<td><?php echo ($link[$propertyId]) ? $context->localize($property['modalities'][$link[$propertyId]]) : '' ?></td>
	
		<?php elseif ($property['type'] == 'number') : ?>
		<td style="text-align: right"><?php echo $context->formatFloat($link[$propertyId], 2) ?></td>
	
		<?php else : ?>
		<td><?php echo $link[$propertyId] ?></td>
		
		<?php endif;?>

	<?php endforeach;?>
	
	</tr>
	
<?php endforeach; ?>

  <tr class="table-info">

    <?php $subjectProperty = $content['config']['list']['subject'] ?>

    <th class="text-center" colspan="<?php echo count($content['config']['list']) ?>">

      <select class="browser-default text-center custom-select px-0 py-0 my-0" id="select-distribution">

      <?php foreach ($content['averages'] as $subjectId => $average) : ?>
        <?php if ($subjectId != 'global') : ?>
          <?php $subject = $subjectProperty['modalities'][$subjectId] ?>
        <option value="<?php echo $subjectId ?>"><?php echo $context->localize($subject) ?></option>
        <?php endif;?>
      <?php endforeach;?>

      <?php if (count($content['links'])) : ?>
        <option value="<?php echo 'global' ?>"><?php echo $this->translate('Global average', 'ppit-studies', $context->getLocale()) ?></option>
      <?php endif;?>

      </select>

      <?php foreach ($content['averages'] as $subjectId => $average) : ?>
        <?php if ($subjectId != 'global') : ?>
      <span class="distribution" id="distribution_<?php echo $subjectId ?>"><?php echo round($average[0] / $average[1] * 2000) / 100 ?></span>
        <?php endif;?>
      <?php endforeach;?>
  
      <?php if (count($content['links'])) : ?>
      <span class="distribution" id="distribution_global"><?php echo round($content['globalAverage'][0] / $content['globalAverage'][1] * 2000) / 100 ?></span>
      <?php endif;?>
    
    </th>
  </tr>

  </table>
</div>
