<div class="panel panel-default">
	<div class="panel-heading" style="background:  <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<strong><?php echo $this->translate('Delete a notification', 'ppit-core', $context->getLocale()) ?></strong>
 		<div class="btn-group pull-right">
			<button type="button" class="btn btn-default" title="<?php echo $this->translate('Return to list', 'ppit-core', $context->getLocale()) ?>" id="remove-anchor">
				<span class="glyphicon glyphicon-remove"></span>
			</button>
 		 </div>
	</div>
	<div class="panel-body">

<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
		'update_time' => $notification->update_time,
		'message' => $message,
		'error' => $error,
		'csrfForm' => $csrfForm,
		'context' => $context,
));
?>

<?php if ($message == 'OK') $isDisabled = true; else $isDisabled = false; ?>

<!-- Up submit -->
	<?php if (!$isDisabled) : ?>
		<div class="form-group">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<input name="submit" type="submit" id="up-submit-button" class="btn btn-danger" value="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>">
			</div>
		</div>
	<?php endif;?>

<!-- Category -->
		<div class="form-group" id="category_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Category', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select class="form-control" id="category" disabled="disabled">
	    			<option value=""><-- <?php echo $this->translate('Please choose', 'ppit-core', $context->getLocale()) ?> --></option>
	<?php foreach ($context->getConfig('commitmentNotification/p-pit-studies')['category'] as $categoryId => $category) : ?>
					<option value="<?php echo $categoryId ?>" <?php if ($notification->category == $categoryId) echo ' selected="selected"' ?>><?php echo $category['labels'][$context->getLocale()] ?></option>
	<?php endforeach;?>
				</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="category_error"></p></div>
		</div>

<!-- Title -->
		<div class="form-group" id="title_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Title', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" id="title" value="<?php echo $notification->title ?>" disabled="disabled" />
			</div>
			<div class="col-sm-12"><p class="help-block" id="title_error"></p></div>
		</div>
		
<!-- Begin date -->
<?php $beginDate = ($notification->begin_date) ? $notification->begin_date : Date('Y-m-d') ?>
		<input type="hidden" id="begin_date" />
		<div class="form-group" id="input_begin_date_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Display start', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input class="form-control" id="input_begin_date" value="<?php echo $context->decodeDate($beginDate) ?>" disabled="disabled" />
			</div>
			<div class="col-sm-12"><p class="help-block" id="input_begin_date_error"></p></div>
		</div>

<!-- End date -->
<?php $endDate = ($notification->end_date) ? $notification->end_date : null ?>
		<input type="hidden" id="end_date" />
		<div class="form-group" id="input_end_date_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Display end', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input class="form-control" id="input_end_date" value="<?php echo $context->decodeDate($endDate) ?>" disabled="disabled" />
			</div>
			<div class="col-sm-12"><p class="help-block" id="input_end_date_error"></p></div>
		</div>

		<hr/>

<!-- Preview -->	

		<div id="content-panel" class="panel panel-default">
			<div class="panel-body">
		
<?php if ($notification->image) : ?>
				<div align="center">
	<?php if (array_key_exists('href', $notification->image)) : ?>
					<a href="<?php echo $notification->image['href'] ?>" target="<?php echo (array_key_exists('target', $notification->image)) ? $notification->image['target'] : '_blank' ?>">
	<?php endif;?>
						<img 
	<?php foreach ($notification->image as $attr => $value) : ?>
		<?php if ($attr == 'src') : ?>
							src="<?php echo $this->basePath($value) ?>"
		<?php elseif ($attr != 'href' && $attr != 'target') : ?>
							<?php echo $attr ?>="<?php echo $value ?>"
		<?php endif;?>
	<?php endforeach;?>
						/>
	<?php if (array_key_exists('href', $notification->image)) : ?>
					</a>
	<?php endif;?>
				</div>
<?php endif;?>
			
				<div><?php echo $notification->content ?></div>
			</div>
		</div>

	<?php if (!$isDisabled) : ?>
		<div class="form-group">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<input name="submit" type="submit" id="submit-button" class="btn btn-danger" value="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>">
			</div>
		</div>
	<?php endif;?>

	</form>
	</div>
</div>
