<div class="panel panel-default">
	<div class="panel-heading" style="background: <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<strong>
			<?php 
			$title = $context->getConfig('commitmentNotification/search/p-pit-studies')['title'][$context->getLocale()];
			echo $title;
			?>
			(<span id="mode-text"></span>)
		</strong>
	</div>
	<div class="panel-body">

<!-- Filters -->

		<div class="form-group">
			<label class="col-sm-5 control-label"><span class="glyphicon glyphicon-search"></span></label>
			<div class="col-sm-7">
	    		<button type="button" class="form-control btn btn-default btn-xs" title="<?php echo $this->translate('Erase', 'ppit-core', $context->getLocale()) ?>" id="erase-button">
					<span class="glyphicon glyphicon-remove"></span>
				</button>
			</div>
		</div>
		
<?php foreach ($context->getConfig('commitmentNotification/search/p-pit-studies')['main'] as $propertyId => $rendering) : ?>

	<?php if ($propertyId == 'category') : ?>

		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Category', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select id="search_category" class="form-control">
					<option />
		<?php foreach ($context->getConfig('commitmentNotification/p-pit-studies')['category'] as $categoryId => $category) : ?>
		    		<option value="<?php echo $categoryId ?>"><?php echo $category['labels'][$context->getLocale()] ?></option>
		<?php endforeach;?>
		    	</select>
			</div>
		</div>

	<?php elseif ($rendering == 'select') : ?>

		<?php
		if ($propertyId == 'property_1') $property = $context->getConfig('student/property/discipline');
		elseif ($propertyId == 'property_4') $property = $context->getConfig('student/property/level');
		elseif ($propertyId == 'property_5') $property = $context->getConfig('student/property/specialty');
		elseif ($propertyId == 'property_6') $property = $context->getConfig('student/property/boarding_school');
		else $property = $context->getConfig('core_account/p-pit-studies')['properties'][$propertyId];
		?>

		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $property['labels'][$context->getLocale()] ?></label>
			<div class="col-sm-7">
				<select id="search_<?php echo $propertyId ?>" class="form-control">
					<option value=""></option>
		<?php foreach ($property['modalities'] as $categoryId => $category) : ?>
		    		<option value="<?php echo $categoryId ?>"><?php echo $category[$context->getLocale()] ?></option>
		<?php endforeach;?>
		    	</select>
			</div>
		</div>

	<?php elseif ($propertyId == 'title') : ?>
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Title', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input class="form-control" type="text" id="search_title" placeholder="<?php echo $this->translate('Contains', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>
	
	<?php elseif ($propertyId == 'begin_date') : ?>

		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Begin of display', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_min_begin_date" class="form-control" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_max_begin_date" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>
	
	<?php elseif ($propertyId == 'end_date') : ?>

		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('End of display', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_min_end_date" class="form-control" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_max_end_date" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>
	
	<?php elseif ($rendering == 'range') : ?>
		
		<?php echo $label = $context->getConfig('core_account/p-pit-studies')['properties'][$propertyId]['labels'][$context->getLocale()]; ?>

		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $label ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_min_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_max_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

	<?php endif;?>
<?php endforeach;?>
	
		<div><a id="add-criteria" href="#"><?php echo $this->translate('More criteria', 'ppit-core', $context->getLocale())?></a></div>
		<div id="search-area">
		
<?php foreach ($context->getConfig('commitmentNotification/search/p-pit-studies')['more'] as $propertyId => $rendering) : ?>

	<?php if ($propertyId == 'category') : ?>

		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Category', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select id="search_category" class="form-control">
					<option />
		<?php foreach ($context->getConfig('commitmentNotification/p-pit-studies')['category'] as $categoryId => $category) : ?>
		    		<option value="<?php echo $categoryId ?>"><?php echo $category['labels'][$context->getLocale()] ?></option>
		<?php endforeach;?>
		    	</select>
			</div>
		</div>

	<?php elseif ($rendering == 'select') : ?>

		<?php
		if ($propertyId == 'property_1') $property = $context->getConfig('student/property/discipline');
		elseif ($propertyId == 'property_4') $property = $context->getConfig('student/property/level');
		elseif ($propertyId == 'property_5') $property = $context->getConfig('student/property/specialty');
		elseif ($propertyId == 'property_6') $property = $context->getConfig('student/property/boarding_school');
		else $property = $context->getConfig('core_account/p-pit-studies')['properties'][$propertyId];
		?>

		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $property['labels'][$context->getLocale()] ?></label>
			<div class="col-sm-7">
				<select id="search_<?php echo $propertyId ?>" class="form-control">
					<option value=""></option>
		<?php foreach ($property['modalities'] as $categoryId => $category) : ?>
		    		<option value="<?php echo $categoryId ?>"><?php echo $category[$context->getLocale()] ?></option>
		<?php endforeach;?>
		    	</select>
			</div>
		</div>

	<?php elseif ($propertyId == 'title') : ?>
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Title', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input class="form-control" type="text" id="search_title" placeholder="<?php echo $this->translate('Contains', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>
	
	<?php elseif ($propertyId == 'begin_date') : ?>

		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Begin of display', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_min_begin_date" class="form-control" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_max_begin_date" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>
	
	<?php elseif ($propertyId == 'end_date') : ?>

		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('End of display', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_min_end_date" class="form-control" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_max_end_date" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>
	
	<?php elseif ($rendering == 'range') : ?>
		
		<?php echo $label = $context->getConfig('core_account/p-pit-studies')['properties'][$propertyId]['labels'][$context->getLocale()]; ?>

		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $label ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_min_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_max_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

	<?php endif;?>
<?php endforeach;?>

		</div>

	    <div>&nbsp;</div>

<!-- Actions -->
	    <div>
	    		<button type="button" class="btn btn-default" title="<?php echo $this->translate('Export', 'ppit-core', $context->getLocale()) ?>" id="export-button">
					<span class="glyphicon glyphicon-cloud-download"></span>
					<span><?php echo $this->translate('Export', 'ppit-core', $context->getLocale())?></span>
				</button>
	    </div>
	    
		<div>&nbsp;</div>

<!-- Add or update section -->
		<div id="notification-list-panel"></div>
	</div>
</div>
