<div class="panel panel-default">
	<div class="panel-heading" style="background:  <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<strong><?php echo $this->translate('Detail', 'ppit-core', $context->getLocale()) ?></strong>
 		<div class="btn-group pull-right">
			<button type="button" class="btn btn-default" title="<?php echo $this->translate('Return to list', 'ppit-core', $context->getLocale()) ?>" id="remove-anchor">
				<span class="glyphicon glyphicon-remove"></span>
			</button>
 		 </div>
	</div>
	<div class="panel-body">

<!-- Menu -->
		<div>
			<button type="button" class="btn btn-default btn-xs detail-menu-btn" title="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale())?>" id="delete-anchor">
				<span class="glyphicon glyphicon-trash" id="group-glyphicon"></span>
			</button>
		</div>

<!-- Display the audit -->
		<div>&nbsp;</div>
		<?php echo $this->translate('History', 'ppit-core', $context->getLocale()) ?> (<a id="audit-label"><?php echo $this->translate('Show', 'ppit-core', $context->getLocale()) ?></a>)
		<div id="audit-panel" class="panel panel-default">
			<div class="panel-body">
	<?php foreach ($notification->audit as $comment) : ?>
				<div class="row">
					<div class="col-md-12">
						<strong><?php echo $context->decodeDate(substr($comment['time'], 0, 10)).substr($comment['time'], 10) ?>:</strong>&nbsp;
						<?php if (array_key_exists('status', $comment)) echo $comment['status'] ?>&nbsp;
						(<?php echo $comment['n_fn'] ?>)
					</div>
				</div>
				<div class="row">
					<div class="col-md-2" align="right">&nbsp;</div>
					<div class="col-md-10"><em><?php echo $comment['comment'] ?></em></div>
				</div>
	<?php endforeach;?>
			</div>
		</div>
		<div>&nbsp;</div>

<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
		'update_time' => $notification->update_time,
		'message' => $message,
		'error' => $error,
		'csrfForm' => $csrfForm,
		'context' => $context,
));
?>

<?php if ($message == 'OK') $isDisabled = true; else $isDisabled = false; ?>

<!-- Up submit -->
	<?php if (!$isDisabled) : ?>
		<div class="form-group">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<input name="submit" type="submit" id="up-submit-button" class="btn btn-warning" value="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>">
			</div>
		</div>
	<?php endif;?>

<!-- Category -->
		<div class="form-group" id="category_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Category', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select class="form-control" id="category" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
	    			<option value=""><-- <?php echo $this->translate('Please choose', 'ppit-core', $context->getLocale()) ?> --></option>
	<?php foreach ($context->getConfig('commitmentNotification/p-pit-studies')['category'] as $categoryId => $category) : ?>
					<option value="<?php echo $categoryId ?>" <?php if ($notification->category == $categoryId) echo ' selected="selected"' ?>><?php echo $category['labels'][$context->getLocale()] ?></option>
	<?php endforeach;?>
				</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="category_error"></p></div>
		</div>

<!-- Title -->
		<div class="form-group" id="title_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Title', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" id="title" value="<?php echo $notification->title ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			</div>
			<div class="col-sm-12"><p class="help-block" id="title_error"></p></div>
		</div>
		
<!-- Begin date -->
<?php $beginDate = ($notification->begin_date) ? $notification->begin_date : Date('Y-m-d') ?>
		<input type="hidden" id="begin_date" />
		<div class="form-group" id="input_begin_date_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Display start', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input class="form-control" id="input_begin_date" value="<?php echo $context->decodeDate($beginDate) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			</div>
			<div class="col-sm-12"><p class="help-block" id="input_begin_date_error"></p></div>
		</div>

<!-- End date -->
<?php $endDate = ($notification->end_date) ? $notification->end_date : null ?>
		<input type="hidden" id="end_date" />
		<div class="form-group" id="input_end_date_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Display end', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input class="form-control" id="input_end_date" value="<?php echo $context->decodeDate($endDate) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			</div>
			<div class="col-sm-12"><p class="help-block" id="input_end_date_error"></p></div>
		</div>

		<hr/>

<!-- Content -->
		<div class="form-group" id="content_group">
			<div class="col-sm-12">
				<textarea class="form-control" rows="8" id="content" <?php if ($isDisabled) echo 'disabled="disabled"'?>><?php echo $notification->content ?></textarea>
			</div>
			<div class="col-sm-12"><p class="help-block" id="content_error"></p></div>
		</div>

<!-- Preview -->	

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7"><?php echo $this->translate('Preview', 'ppit-core', $context->getLocale()) ?> (<a id="content-label"><?php echo $this->translate('Show', 'ppit-core', $context->getLocale()) ?></a>)</div>
		</div>
		<div id="content-panel" class="panel panel-default">
			<div class="panel-body">
		
<?php if ($notification->image) : ?>
				<div align="center">
	<?php if (array_key_exists('href', $notification->image)) : ?>
					<a href="<?php echo $notification->image['href'] ?>" target="<?php echo (array_key_exists('target', $notification->image)) ? $notification->image['target'] : '_blank' ?>">
	<?php endif;?>
						<img 
	<?php foreach ($notification->image as $attr => $value) : ?>
		<?php if ($attr == 'src') : ?>
							src="<?php echo $this->basePath($value) ?>"
		<?php elseif ($attr != 'href' && $attr != 'target') : ?>
							<?php echo $attr ?>="<?php echo $value ?>"
		<?php endif;?>
	<?php endforeach;?>
						/>
	<?php if (array_key_exists('href', $notification->image)) : ?>
					</a>
	<?php endif;?>
				</div>
<?php endif;?>
			
				<div><?php echo $notification->content ?></div>
			</div>
		</div>

<?php if (!$isDisabled) : ?>
<!-- Image -->
		<?php
		$images = array();
		$dir = './public/img/'.$context->getInstance()->caption;
		if ($dh = opendir($dir)) {
			while (($file = readdir($dh)) !== false) {
				if (substr($file, 0, 1) != '.' && preg_match('#\.(jpe?g|gif|png)$#i', $file)) $images[$file] = '/img/'.$context->getInstance()->caption.'/'.$file;
			}
			closedir($dh);
		}
		?>
		<input type="hidden" id="image_src"  <?php if (array_key_exists('src', $notification->image)) echo ' value="'.$notification->image['src'].'"' ?>/>
		
		<div style="text-align: center" id="image-preview">
			<button type="button" id="image-delete-btn" class="btn btn-default" title="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale())?>">
				<span class="glyphicon glyphicon-remove" id="group-glyphicon"></span>
			</button>
			&nbsp;&nbsp;&nbsp;&nbsp;
		
<?php foreach ($images as $name => $path) : ?>
			<input type="hidden" id="image_<?php echo substr($name, 0, strpos($name, '.')) ?>" value="<?php echo $path?>" />
			<a class="image-select" id="image-select_<?php echo substr($name, 0, strpos($name, '.')) ?>" <?php if (array_key_exists('src', $notification->image) && $notification->image['src'] == $path) echo 'style="border-style: solid"' ?>>
				<img width="30" src="<?php echo $this->basePath($path) ?>"/>
			</a>
			&nbsp;&nbsp;&nbsp;&nbsp;
<?php endforeach;?>
		</div>
		<div>&nbsp;</div>
	    <div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-5">
				<input type="file" id="image-upload" class="form-control" />
			</div>
			<div class="col-sm-2">
				<button type="button" id="image-upload-btn" class="btn btn-warning" title="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale())?>">
					<span class="glyphicon glyphicon-cloud-upload" id="group-glyphicon"></span>
				</button>
			</div>
		</div>
		<div>&nbsp;</div>

		<div class="form-group" id="image_style_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Positioning', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select class="form-control" id="image_style" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
					<option value="float:none" <?php if (array_key_exists('style', $notification->image) && $notification->image['style'] == 'float:none') echo ' selected="selected"' ?>><?php echo $this->translate('Default', 'ppit-commitment', $context->getLocale()) ?></option>
					<option value="float:left" <?php if (array_key_exists('style', $notification->image) && $notification->image['style'] == 'float:left') echo ' selected="selected"' ?>><?php echo $this->translate('Left', 'ppit-commitment', $context->getLocale()) ?></option>
					<option value="float:right" <?php if (array_key_exists('style', $notification->image) && $notification->image['style'] == 'float:right') echo ' selected="selected"' ?>><?php echo $this->translate('Right', 'ppit-commitment', $context->getLocale()) ?></option>
				</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="image_style_error"></p></div>
		</div>
		<div class="form-group" id="image_width_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Width in pixels', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" id="image_width" value="<?php echo (array_key_exists('width', $notification->image)) ? $notification->image['width'] : '30' ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			</div>
			<div class="col-sm-12"><p class="help-block" id="image_width_error"></p></div>
		</div>
		<div class="form-group" id="image_href_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Linked URL', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" id="image_href" <?php if (array_key_exists('href', $notification->image)) echo 'value="'.$notification->image['href'].'"' ?> <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			</div>
			<div class="col-sm-12"><p class="help-block" id="image_href_error"></p></div>
		</div>

		<hr/>
<?php endif;?>

		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Attachment', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">&nbsp;</div>
		</div>

		<div class="form-group" id="attachment_label_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Caption', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" id="attachment_label" value="<?php echo $notification->attachment_label ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			</div>
			<div class="col-sm-12"><p class="help-block" id="attachment_label_error"></p></div>
		</div>

		<div class="form-group" id="attachment_path_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('File name', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select class="form-control" id="attachment_path" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
					<option />
	<?php foreach ($documentList as $document) : ?>
					<option value="<?php echo $document ?>" <?php if ($notification->attachment_path == $document) echo 'selected="selected"' ?>><?php echo $document ?></option>
	<?php endforeach;?>
				</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="attachment_path_error"></p></div>
		</div>
		<hr/>

<!--  Criteria -->
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Targeting', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">&nbsp;</div>
			<div class="col-sm-12"><p class="help-block"></p></div>
		</div>

<?php foreach ($context->getConfig('commitmentNotification/update/p-pit-studies')['criteria'] as $criterionId => $unused) : ?>
	<?php $criterion = $context->getConfig('core_account/p-pit-studies')['properties'][$criterionId] ?>
		<div class="form-group" id="<?php echo $criterionId?>_group">
			<label class="col-sm-5 control-label"><?php echo $criterion['labels'][$context->getlocale()] ?></label>
			<div class="col-sm-7">
				<select class="form-control" id="<?php echo $criterionId ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
	    			<option value=""><-- <?php echo $this->translate('Please choose', 'ppit-core', $context->getLocale()) ?> --></option>
	<?php foreach ($criterion['modalities'] as $modalityId => $modality) : ?>
					<option value="<?php echo $modalityId ?>" <?php if (array_key_exists($criterionId, $notification->criteria) && $notification->criteria[$criterionId] == $modalityId) echo ' selected="selected"' ?>><?php echo $modality[$context->getLocale()] ?></option>
	<?php endforeach;?>
				</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="category_error"></p></div>
		</div>
<?php endforeach;?>

		<input type="hidden" id="matching-account-number" value="<?php echo count($notification->matchingAccounts) ?>"/>
<?php $i=0; foreach ($notification->matchingAccounts as $account) : ?>
		<input type="hidden" id="matching-account_<?php echo $i ?>" value="<?php echo $account->id ?>"/>
		<input type="hidden" id="target_<?php echo $account->id ?>"></input>
		<div class="form-group" id="target_<?php echo $account->id ?>_checkbox_group">
			<label class="col-sm-5 control-label"><?php echo $account->name ?></label>
			<div class="col-sm-7">
				<input type="checkbox" id="target_<?php echo $account->id ?>_checkbox" value="<?php echo (array_key_exists($account->id, $notification->target)) ? 1 : 0 ?>" <?php if (array_key_exists($account->id, $notification->target)) echo 'checked="checked"' ?>></input>
			</div>
			<div class="col-sm-12"><p class="help-block" id="target_<?php echo $account->id ?>_checkbox_error"></p></div>
		</div>
<?php $i++; endforeach;?>

		<hr/>

<!-- Comment -->
	<?php if (!$isDisabled) : ?>
		<div class="form-group" id="comment_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Comment (non visible to the student)', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<textarea class="form-control" id="comment"></textarea>
			</div>
			<div class="col-sm-12"><p class="help-block" id="comment_error"></p></div>
		</div>
	<?php endif;?>

	<?php if (!$isDisabled) : ?>
		<div class="form-group">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<input name="submit" type="submit" id="submit-button" class="btn btn-warning" value="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>">
			</div>
		</div>
	<?php endif;?>

	</form>
	</div>
</div>
