<!-- 
/**
 * PpitCore V1.0 (https://github.com/p-pit/PpitCore)
 *
 * @link      https://github.com/p-pit/PpitCore
 * @copyright Copyright (c) 2016 Bruno Lartillot
 * @license   https://github.com/p-pit/PpitCore/blob/master/license.txt GNU-GPL license
 */
-->

<?php echo $this->partial('/partials/search-scripts-v2') ?>

<script>

var criterion = 'begin_date', dir = 'DESC';

// Export the list
function exportAbsenceList() {
	var params = getSearchParams('');
	document.location.href = '<?php echo $this->url('absence/export') ?>' + params + '&major=' + criterion + ((dir =='ASC') ? '&dir=ASC' : '&dir=DESC');
}

// Load the list
function getAbsenceList(params) {		

	// Execute the ajax request
	route = '<?php echo $this->url('absence/listV2') ?>' + params + '&major=' + criterion + ((dir =='ASC') ? '&dir=ASC' : '&dir=DESC') + '&limit=' + $('#limit').val();
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4 && xhttp.status == 200) {
			document.getElementById('absence-list-panel').innerHTML = xhttp.responseText;

            $('#export-button').click(function () { exportAbsenceList(); });
			
			// Connect the sort anchors
			$('.sort_anchor').click(function () {
                criterion = $(this).attr('id').split('-')[0];
                ascCriterion = $('.sort_anchor_up').attr('id');
                descCriterion = $('.sort_anchor_down').attr('id');
                if (criterion + '-anchor' == ascCriterion) dir = 'DESC';
                else if (criterion + '-anchor' == descCriterion) dir = 'ASC';
                else dir = 'ASC';
				getAbsenceList(getSearchParams(''));
			});
      
            // Connect the detail anchors
            $('.absence-detail-anchor').click(function () {
              var id = $(this).attr('id').split('_')[1];
              getAbsenceUpdate(id);
              $(this).removeClass("btn-outline-primary").addClass("btn-primary");
              $('#modalForm').modal('toggle');
            });
		}
	}
	xhttp.send();
}

$('#modalForm').on('hidden.bs.modal', function (e) {
  $('.absence-update-anchor').addClass("btn-outline-primary").removeClass("btn-primary");
  getAbsenceList(getSearchParams(''));
})

function connectAuditPanel(id)
{
	$('#audit-panel').hide();
	$('#audit-label').click(function () {
		if ($('#audit-label').text() == '<?php echo $this->translate('Show', 'ppit-core', $context->getLocale()) ?>') {
			$('#audit-panel').show();
			$('#audit-label').text('<?php echo $this->translate('Mask', 'ppit-core', $context->getLocale()) ?>');
		}
		else {
			$('#audit-panel').hide();
			$('#audit-label').text('<?php echo $this->translate('Show', 'ppit-core', $context->getLocale()) ?>');
		}
	});
}

<?php 
$properties = array();
$properties['category'] = array('type' => 'select', 'mandatory' => true);
$properties['school_period'] = array('type' => 'select', 'mandatory' => true);
$properties['begin_date'] = array('type' => 'date', 'mandatory' => false);
$properties['end_date'] = array('type' => 'date', 'mandatory' => false);
$properties['duration'] = array('type' => 'number', 'mandatory' => false, 'minValue' => 0, 'maxValue' => 999);
$properties['subject'] = array('type' => 'select', 'mandatory' => false);
$properties['motive'] = array('type' => 'select', 'mandatory' => false);
$properties['observations'] = array('type' => 'textarea', 'mandatory' => false, 'maxSize' => 2047);
$properties['comment'] = array('type' => 'textarea', 'mandatory' => false, 'maxSize' => 2047);
$properties['update_time'] = array('type' => 'hidden');

echo $this->partial('/partials/check-update-properties', array('entity' => 'Absence', 'context' => $context, 'properties' => $properties)) 
?>

function connectAbsenceUpdateForm(id, action)
{
	$('#input_begin_date').datepicker();
	$('#input_end_date').datepicker();
	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {
		
		event.preventDefault();

		// Check validity
		var validity = checkAbsenceUpdateProperties();

		if (validity) {

			// Create a new FormData object.
			var formData = new FormData();
			
			// Get the properties values
<?php foreach ($properties as $propertyId => $property) : ?>
				formData.append('<?php echo $propertyId ?>', document.getElementById('<?php echo $propertyId ?>').value);
<?php endforeach ?>
//			formData.append('duration', $('#duration').val());

			var xhttp = new XMLHttpRequest();
			var route;
			route = '<?php echo $this->url('absence/updateV2') ?>/' + id;
			if (action) route += '/' + action;
			xhttp.open('POST', route, true);
			// Set up a handler for when the request finishes.
			xhttp.onload = function () {
				if (xhttp.readyState == 4 && xhttp.status == 200) {
					$('#absence-update-panel').html(xhttp.responseText);			
					connectAuditPanel();
				}
			};
			xhttp.send(formData);
		}
		else return false;
	}
}

function getAbsenceUpdate(id, action) {

	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('absence/updateV2') ?>/' + id;
	if (action) route += '/' + action;

	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4 && xhttp.status == 200) {
			$('#absence-update-panel').html(xhttp.responseText);			
			connectAuditPanel();
			connectAbsenceUpdateForm(id, action);
			if ($('#category').val() != 'absence') $('#input_end_date_group').hide();
			$('#category').change(function () {
				if ($('#category').val() == 'absence') $('#input_end_date_group').show();
				else $('#input_end_date_group').hide();
			});
			$('#category').focus();

			if (id) {
				$('#update-anchor').click(function () { getAbsenceUpdate(id, 'update'); });
				$('#delete-anchor').click(function () { getAbsenceUpdate(id, 'delete'); });
			}
			else $('#add-anchor').click(function () { getAbsenceUpdate(id, 'add'); });
		}
	}
	xhttp.send();
}

function getSearch() {

  // Load the search panel and highlight the menu entry
    let xhttp = new XMLHttpRequest();
    xhttp.open("GET", '<?php echo $this->url('absence/searchV2') ?>', true);
    xhttp.onreadystatechange = function() {
      if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
      if (xhttp.readyState == 4 && xhttp.status == 200) {
        $('#index-panel').html(xhttp.responseText);
	
      	$('#erase-button').click(function () { 
          $('.search_selectpicker').selectpicker('refresh');
          $('.search_check_value').val('0');
          $('.search_check').removeClass('btn-secondary').addClass('btn-default').removeClass('active');
          $('#erase-button').removeClass('btn-success').addClass('btn-default');
          $('#erase-button').attr('disabled', 'disabled');
          getAbsenceList(getSearchParams(''));
        });
        
        $('.search_selectpicker').selectpicker('refresh');
        
        // Connect the date picker on date inputs
        $('.search_input_date').datepicker();
   
        // Trigger the change event on search inputs and refresh the list
        $('.search_input').change(function () {
          if ($(this).attr('id')) {
            var propertyId = $(this).attr('id').split('-')[1];
            $('#erase-button').removeClass('btn-default').addClass('btn-success');
            $('#erase-button').attr('disabled', false);
            $('#search_check-' + propertyId).removeClass('btn-default').addClass('btn-secondary').addClass('active');
            $('#search_check_value-' + propertyId).val('1');
            getAbsenceList(getSearchParams(''));
          }
        }); 

        // Trigger the keyup event on search inputs and refresh the list
        $('.search_input').keyup(function () {
          if ($(this).attr('id')) {
            if ($(this).val().length > 2) {
              var propertyId = $(this).attr('id').split('-')[1];
              $('#erase-button').removeClass('btn-default').addClass('btn-success');
              $('#erase-button').attr('disabled', false);
              $('#search_check-' + propertyId).removeClass('btn-default').addClass('btn-secondary').addClass('active');
              $('#search_check_value-' + propertyId).val('1');
              getAbsenceList(getSearchParams(''));
            }
          }
        });

        // Trigger the click event on per-property checks (allowing to search on empty values) and refresh the list
        $('.search_check').click(function() {
          $('#erase-button').removeClass('btn-default').addClass('btn-success');
          $('#erase-button').attr('disabled', false);
          var propertyId = $(this).attr('id').split('-')[1], check = 'search_check_value-' + propertyId;
          if ($('#' + check).val() == '1') {
            $(this).removeClass('btn-secondary').addClass('btn-default').removeClass('active');
            $('#' + check).val('0');
            $('#search-' + propertyId).val('');
            $('#search_min-' + propertyId).val('');
            $('#search_max-' + propertyId).val('');
          }
          else {
            $(this).removeClass('btn-default').addClass('btn-secondary').addClass('active');
            $('#' + check).val('1');
          }
          getAbsenceList(getSearchParams(''));
        });
     
        getAbsenceList(getSearchParams(''));
      }
    };
    xhttp.send();
}

getSearch();

</script>