
<h4><?php echo $this->translate('Last notes', 'ppit-studies', $context->getLocale()) ?></h4>

<?php $first=true; foreach ($notes as $note) : ?>

		<?php if (!$first) : ?><div>&nbsp;</div><?php endif;?>
		<div>
			<strong><?php echo $context->decodeDate($note->date) ?></strong>
			<?php echo $note->subject ?>:
			<?php echo $context->formatFLoat($note->value, 2) ?>/<?php echo $context->formatFloat($note->reference_value, 0) ?>
	<?php if ($note->observations) : ?>
			<br><?php echo $note->observations ?>
	<?php endif;?>
		</div>

<?php $first=false; endforeach;?>
