<div class="panel panel-default">
	<div class="panel-heading" style="background:  <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<strong><?php echo $this->translate('Delete a note', 'ppit-studies', $context->getLocale()) ?></strong>
 		<div class="btn-group pull-right">
			<button type="button" class="btn btn-default" title="<?php echo $this->translate('Return to list', 'ppit-core', $context->getLocale()) ?>" id="remove-anchor">
				<span class="glyphicon glyphicon-remove"></span>
			</button>
 		 </div>
	</div>
	<div class="panel-body">

<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
		'update_time' => $note->update_time,
		'message' => $message,
		'error' => $error,
		'csrfForm' => $csrfForm,
		'context' => $context,
));
?>

<?php if ($message == 'OK') $isDisabled = true; else $isDisabled = false; ?>

<!-- Name -->

	<div class="form-group" id="product_group">
		<label class="col-sm-5 control-label">&nbsp;</label>
		<div class="col-sm-7">
			<input class="form-control" disabled="disabled" value="<?php echo $note->name ?>" />
		</div>
	</div>

<!-- School year -->
		<div class="form-group" id="school_year_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('School year', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select class="form-control" id="school_year" disabled="disabled">
	<?php foreach ($context->getConfig('student')['properties']['school_year']['modalities'] as $schoolYearId => $schoolYear) : ?>
					<option value="<?php echo $schoolYearId ?>" <?php if ($note->school_year == $schoolYearId) echo ' selected="selected"' ?>><?php echo $schoolYear[$context->getLocale()] ?></option>
	<?php endforeach;?>
				</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="school_year_error"></p></div>
		</div>

<!-- Subject -->
		<div class="form-group" id="subject_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Subject', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<select class="form-control" id="subject" disabled="disabled" ?>>
	    			<option value=""><-- <?php echo $this->translate('Please choose', 'ppit-core', $context->getLocale()) ?> --></option>
<?php foreach ($config['note/update']['types'][$type]['subjects'] as $subject) : ?>
	<?php $caption = $subject[$context->getLocale()]; ?>
	    			<option value="<?php echo $caption ?>" <?php if ($note->subject == $caption) echo 'selected="selected"' ?>><?php echo $caption ?></option>
<?php endforeach;?>
	    		</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="subject_error"></p></div>
		</div>

<!-- Observations -->
		<div class="form-group" id="observations_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Observations', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<textarea class="form-control" id="observations" disabled="disabled" ?><?php echo $note->observations ?></textarea>
			</div>
			<div class="col-sm-12"><p class="help-block" id="observations_error"></p></div>
		</div>

	<?php if (!$isDisabled) : ?>
		<div class="form-group">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<input name="submit" type="submit" id="submit-button" class="btn btn-danger" value="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>">
			</div>
		</div>
	<?php endif;?>

	</form>
	</div>
</div>
