<table class="table table-striped ppit_index">
	<tr>
		<th>&nbsp;</th>

<?php foreach ($context->getConfig('note/list/'.$category) as $propertyId => $rendering) : ?>
		<th align="center">
	<?php 
	if ($propertyId == 'type') $label = $this->translate('Type', 'ppit-core', $context->getLocale());
	elseif ($propertyId == 'school_period') $label = $context->getConfig('student/property/school_period')['labels'][$context->getLocale()];
	elseif ($propertyId == 'class') $label = $context->getConfig('student/property/class')['labels'][$context->getLocale()];
	elseif ($propertyId == 'subject') $label = $context->getConfig('student/property/school_subject')['labels'][$context->getLocale()];
	elseif ($propertyId == 'date') $label = $this->translate('Date', 'ppit-core', $context->getLocale());
	?>
	<?php if ($label) : ?>
			<button type="button" class="btn btn-default btn-xs ppit-sort-anchor" id="<?php echo $propertyId ?>-anchor">
				<span><?php echo $label ?></span>
		<?php if ($major == $propertyId) : ?>
				<span class="glyphicon glyphicon-triangle-<?php echo ($dir == 'ASC') ? 'top' : 'bottom' ?>"></span>
		<?php endif ?>
			</button>
	<?php endif;?>
		</th>
<?php endforeach;?>

	</tr>

<?php foreach ($notes as $note) : ?>
	<?php 
	if ($note->type == 'done-work') $backgroundColor = 'LightGreen';
	elseif ($note->type == 'todo-work') $backgroundColor = 'LightSalmon';
	elseif ($note->type == 'event') $backgroundColor = 'LightBlue';
	else $backgroundColor = null;
	?>
	
	<tr>

		<td style="text-align: center">
			<button type="button" class="btn btn-default index-btn note-detail-anchor" title="<?php echo $this->translate('Detail', 'ppit-core', $context->getLocale())?>" id="note-detail-anchor_<?php echo $note->id ?>">
				<span class="glyphicon glyphicon-zoom-in" id="group-glyphicon"></span>
			</button>
		</td>

	<?php foreach ($context->getConfig('note/list/'.$category) as $propertyId => $rendering) : ?>
	
		<?php if ($propertyId == 'type') : ?>
		<td <?php if ($backgroundColor) echo 'style="background-color: '.$backgroundColor.'"' ?>><?php echo $context->getConfig('note')['types'][$category][$note->type]['labels'][$context->getLocale()] ?></td>

		<?php elseif ($propertyId == 'school_period') : ?>
		<td><?php echo $context->getConfig('student/property/school_period')['modalities'][$note->school_period][$context->getLocale()] ?></td>

		<?php elseif ($propertyId == 'class') : ?>
		<td><?php echo $context->getConfig('student/property/class')['modalities'][$note->class][$context->getLocale()] ?></td>

		<?php elseif ($propertyId == 'subject') : ?>
		<td><?php echo ($note->subject == 'global') ? $this->translate('Staff meeting', 'ppit-studies', $context->getLocale()) : $context->getConfig('student/property/school_subject')['modalities'][$note->subject][$context->getLocale()] ?></td>

		<?php elseif ($propertyId == 'date') : ?>
		<td><?php echo $context->decodeDate($note->date) ?></td>
		
		<?php endif;?>
	<?php endforeach;?>
	
	</tr>
	
	<tr class="detail-row" id="detail-row_<?php echo $note->id ?>" rowspan="2"><td colspan="99"><div class="col-md-6 col-md-offset-3 ppit-panel" id="detail-div_<?php echo $note->id ?>"></div></td></tr>
	<tr class="invisible"><td colspan="99"></td></tr>
	
<?php endforeach; ?>

<?php if ($context->isDemoModeActive()) : ?>
	<?php $qualifier = ($category == 'homework') ? $category : (($type == 'note') ? 'note' : 'report') ?>
				<a style="align: right" class="tip" href="#" title="<?php echo $context->getConfig('demo')['note/list/'.$qualifier][$context->getLocale()] ?>">
				    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
				</a>
<?php endif;?>

</table>
