<table class="table table-striped ppit_index">
	<tr>
		<th>&nbsp;</th>

<?php foreach ($context->getConfig('note/list') as $propertyId => $rendering) : ?>
		<th align="center">
	<?php 
	if ($propertyId == 'type') $label = $this->translate('Type', 'ppit-core', $context->getLocale());
	elseif ($propertyId == 'level') $label = $context->getConfig('student/property/level')['labels'][$context->getLocale()];
	elseif ($propertyId == 'subject') $label = $context->getConfig('student/property/school_subject')['labels'][$context->getLocale()];
	elseif ($propertyId == 'school_year') $label = $context->getConfig('student/property/school_year')['labels'][$context->getLocale()];
	elseif ($propertyId == 'school_period') $label = $context->getConfig('student/property/school_period')['labels'][$context->getLocale()];
	elseif ($propertyId == 'specialty') $label = $context->getConfig('student/property/specialty')['labels'][$context->getLocale()];
	?>
	<?php if ($label) : ?>
			<button type="button" class="btn btn-default btn-xs ppit-sort-anchor" id="<?php echo $propertyId ?>-anchor">
				<span><?php echo $label ?></span>
		<?php if ($major == $propertyId) : ?>
				<span class="glyphicon glyphicon-triangle-<?php echo ($dir == 'ASC') ? 'top' : 'bottom' ?>"></span>
		<?php endif ?>
			</button>
	<?php endif;?>
		</th>
<?php endforeach;?>

	</tr>

<?php foreach ($notes as $note) : ?>
	
	<tr>

		<td style="text-align: center">
			<button type="button" class="btn btn-default btn-xs index-btn note-detail-anchor" title="<?php echo $this->translate('Detail', 'ppit-core', $context->getLocale())?>" id="note-detail-anchor_<?php echo $note->id ?>">
				<span class="glyphicon glyphicon-zoom-in" id="group-glyphicon"></span>
			</button>
		</td>

	<?php foreach ($context->getConfig('note/list') as $propertyId => $rendering) : ?>
	
		<?php if ($propertyId == 'type') : ?>
		<td><?php echo $context->getConfig('note')['types'][$note->type]['labels'][$context->getLocale()] ?></td>

		<?php elseif ($propertyId == 'level') : ?>
		<td><?php echo $context->getConfig('student/property/level')['modalities'][$note->level][$context->getLocale()] ?></td>

		<?php elseif ($propertyId == 'subject') : ?>
		<td><?php echo $context->getConfig('student/property/school_subject')['modalities'][$note->subject][$context->getLocale()] ?></td>

		<?php elseif ($propertyId == 'school_year') : ?>
		<td><?php echo $context->getConfig('student/property/school_year')['modalities'][$note->school_year][$context->getLocale()] ?></td>

		<?php elseif ($propertyId == 'school_period') : ?>
		<td><?php echo $context->getConfig('student/property/school_period')['modalities'][$note->school_period][$context->getLocale()] ?></td>

		<?php elseif ($propertyId == 'specialty') : ?>
		<td><?php echo $context->getConfig('student/property/specialty')['modalities'][$note->specialty][$context->getLocale()] ?></td>
		
		<?php endif;?>
	<?php endforeach;?>
	
	</tr>
	
<?php endforeach; ?>

</table>
