<div class="panel panel-default">
	<div class="panel-heading" style="background: <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<strong>
			<?php
			$title = ($category == 'evaluation') ? $context->getConfig('note/search'.'/'.$category.'/'.$type)['title'][$context->getLocale()] : $context->getConfig('note/search'.'/'.$category)['title'][$context->getLocale()];
			echo $title;
			?>
			(<span id="mode-text"></span>)
		</strong>
	</div>
	<div class="panel-body">

		<div class="col-md-6">

<!-- Filters -->

		<div class="form-group">
			<label class="col-sm-5 control-label"><span class="glyphicon glyphicon-search"></span></label>
			<div class="col-sm-7">
	    		<button type="button" class="form-control btn btn-default btn-xs" title="<?php echo $this->translate('Erase', 'ppit-core', $context->getLocale()) ?>" id="erase-button">
					<span class="glyphicon glyphicon-remove"></span>
				</button>
			</div>
		</div>
		
<?php foreach ($context->getConfig('note/search'.'/'.$category)['main'] as $propertyId => $rendering) : ?>
	<?php 
	$property = $context->getConfig('note')['properties'][$propertyId];
	if ($property['definition'] != 'inline') $property = $context->getConfig($property['definition']);
	$label = $property['labels'][$context->getLocale()];
	?>

	<?php if ($propertyId == 'type') : ?>
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Type', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select id="search_<?php echo $propertyId ?>" class="form-control">
					<option value=""></option>
		<?php foreach ($context->getConfig('note')['types'][$category] as $typeId => $type) : ?>
		    		<option value="<?php echo $typeId ?>"><?php echo $type['labels'][$context->getLocale()] ?></option>
		<?php endforeach;?>
		    	</select>
			</div>
		</div>
	
	<?php elseif ($propertyId == 'date') : ?>

		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Date', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_min_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_max_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>
	
	<?php elseif ($propertyId == 'subject') : ?>
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Subject', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select id="search_<?php echo $propertyId ?>" class="form-control">
					<option value=""></option>
		<?php foreach ($property['modalities'] as $modalityId => $modality) : ?>
		    		<option value="<?php echo $modalityId ?>"><?php echo $modality[$context->getLocale()] ?></option>
		<?php endforeach;?>
					<option value="global"><?php echo $this->translate('Global average', 'ppit-studies', $context->getLocale()) ?></option>
		    	</select>
			</div>
		</div>

	<?php else : ?>
			
		<?php if ($propertyId == 'place_id') : ?>
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $label ?></label>
			<div class="col-sm-7">
				<select id="search_place_id" class="form-control">
					<option value=""></option>
		<?php foreach ($places as $place) : ?>
		    		<option value="<?php echo $place->id ?>"><?php echo $place->caption ?></option>
		<?php endforeach;?>
		    	</select>
			</div>
		</div>
		
		<?php elseif ($rendering == 'contains') : ?>
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $label ?></label>
			<div class="col-sm-7">
				<input class="form-control" type="text" id="search_<?php echo $propertyId ?>" placeholder="<?php echo $this->translate('Contains', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<?php elseif ($rendering == 'range') : ?>

		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $label ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_min_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_max_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<?php elseif ($rendering == 'select') : ?>
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $label ?></label>
			<div class="col-sm-7">
				<select id="search_<?php echo $propertyId ?>" class="form-control">
					<option value=""></option>
		<?php foreach ($property['modalities'] as $modalityId => $modality) : ?>
		    		<option value="<?php echo $modalityId ?>"><?php echo $modality[$context->getLocale()] ?></option>
		<?php endforeach;?>
		    	</select>
			</div>
		</div>

		<?php endif;?>
	<?php endif;?>
<?php endforeach;?>

	    <div>&nbsp;</div>

<!-- Actions -->
	    <div>
	    		<button type="button" class="btn btn-default" title="<?php echo $this->translate('Export', 'ppit-core', $context->getLocale()) ?>" id="export-button">
					<span class="glyphicon glyphicon-cloud-download"></span>
					<span><?php echo $this->translate('Export', 'ppit-core', $context->getLocale())?></span>
				</button>
<?php if ($category == 'evaluation' && $context->hasRole('admin')) : ?>
				<button type="button" class="btn btn-default" title="<?php echo $this->translate('CSV export', 'ppit-core', $context->getLocale()) ?>" id="csv-button">
					<span class="glyphicon glyphicon-cloud-download"></span>
					<span><?php echo $this->translate('CSV export', 'ppit-core', $context->getLocale())?></span>
				</button>
<?php endif;?>
	    </div>
	    </div>
	    
		<div>&nbsp;</div>
		<input type="hidden" id="limit" value="50" />

<!-- Add or update section -->
		<div id="note-list-panel"></div>
	</div>
</div>
