<div class="panel panel-default">
	<div class="panel-heading" style="background:  <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<strong><?php echo $this->translate('Detail', 'ppit-core', $context->getLocale()) ?></strong>
 		<div class="btn-group pull-right">
			<button type="button" class="btn btn-default" title="<?php echo $this->translate('Return to list', 'ppit-core', $context->getLocale()) ?>" id="remove-anchor_<?php echo $note->id ?>">
				<span class="glyphicon glyphicon-remove"></span>
			</button>
 		 </div>
	</div>
	<div class="panel-body">

<?php if ($message != 'OK' && $action == '') : ?>
<!-- Menu -->
		<div>
			<button type="button" class="btn btn-default detail-menu-btn" id="update-anchor" title="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>">
				<span class="glyphicon glyphicon-edit"></span>
			</button>

			<button type="button" class="btn btn-default detail-menu-btn" id="delete-anchor" title="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale())?>">
				<span class="glyphicon glyphicon-trash""></span>
			</button>
		</div>
<?php endif;?>

<?php if ($context->isDemoModeActive()) : ?>
				<a style="align: right" class="tip" href="#" title="<?php echo $context->getConfig('demo')['note/update'][$context->getLocale()] ?>">
				    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
				</a>
<?php endif;?>

<!-- Display the audit -->
		<div>&nbsp;</div>
		<?php echo $this->translate('History', 'ppit-core', $context->getLocale()) ?> (<a id="audit-label_<?php echo $note->id ?>"><?php echo $this->translate('Show', 'ppit-core', $context->getLocale()) ?></a>)
		<div id="audit-panel_<?php echo $note->id ?>" class="panel panel-default">
			<div class="panel-body">
	<?php foreach ($note->audit as $comment) : ?>
				<div class="row">
					<div class="col-md-12">
						<strong><?php echo $context->decodeDate(substr($comment['time'], 0, 10)).substr($comment['time'], 10) ?>:</strong>&nbsp;
						<?php if (array_key_exists('status', $comment)) echo $comment['status'] ?>&nbsp;
						(<?php echo $comment['n_fn'] ?>)
					</div>
				</div>
				<div class="row">
					<div class="col-md-2" align="right">&nbsp;</div>
					<div class="col-md-10"><em><?php echo $comment['comment'] ?></em></div>
				</div>
	<?php endforeach;?>
			</div>
		</div>
		<div>&nbsp;</div>

<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
		'update_time' => $note->update_time,
		'message' => $message,
		'error' => $error,
		'csrfForm' => $csrfForm,
		'context' => $context,
));
?>

<?php if ($note->id && $action != 'update' || $message == 'OK') $isDisabled = true; else $isDisabled = false; ?>

<?php if ($message != 'OK') : ?>
	<?php if (!$note->id) : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input type="submit" id="up-submit-button" class="btn btn-warning" value="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

	<?php elseif ($action == 'update') : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input type="submit" id="up-submit-button" class="btn btn-warning" value="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

	<?php elseif ($action == 'delete') : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input type="submit" id="up-submit-button" class="btn btn-danger" value="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>
	<?php endif;?>
<?php endif;?>

<!-- Names -->
<hr>
	<div class="form-group" id="product_group">
		<label class="col-sm-5 control-label"><?php echo $this->translate('Students', 'ppit-studies', $context->getLocale()) ?></label>
		<div class="col-sm-7">&nbsp;</div>
	</div>
<?php foreach ($note->links as $noteLink) : ?>
	<div class="form-group" id="product_group">
		<label class="col-sm-5 control-label">&nbsp;</label>
		<div class="col-sm-7">
			<input class="form-control" disabled="disabled" value="<?php echo $noteLink->n_fn ?>" />
		</div>
	</div>
<?php endforeach;?>
<hr>

<!-- Place -->
		<div class="form-group" id="place_id_group">
			<label class="col-sm-5 control-label">* <?php echo $context->getConfig('student/property/place')['labels'][$context->getLocale()] ?></label>
			<div class="col-sm-7">
				<select class="form-control" id="place_id" <?php if ($isDisabled || $note->place_id) echo 'disabled="disabled"'?>>
					<option />
	<?php foreach ($places as $place) : ?>
					<option value="<?php echo $place->id ?>" <?php if ($note->place_id == $place->id) echo 'selected="selected"' ?>><?php echo $place->caption ?></option>
	<?php endforeach;?>
				</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="place_id_error"></p></div>
		</div>

<!-- Class -->
		<div class="form-group" id="class_group">
			<label class="col-sm-5 control-label">* <?php echo $context->getConfig('student/property/class')['labels'][$context->getLocale()] ?></label>
			<div class="col-sm-7">
				<select class="form-control" id="class" <?php if ($isDisabled || $note->class) echo 'disabled="disabled"'?>>
					<option />
	<?php foreach ($context->getConfig('student/property/class')['modalities'] as $classId => $class) : ?>
					<option value="<?php echo $classId ?>" <?php if ($note->class == $classId) echo 'selected="selected"' ?>><?php echo $class[$context->getLocale()] ?></option>
	<?php endforeach;?>
				</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="class_error"></p></div>
		</div>

<!-- Subject -->
		<div class="form-group" id="subject_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Subject', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<select class="form-control" id="subject" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
	    			<option value=""><-- <?php echo $this->translate('Please choose', 'ppit-core', $context->getLocale()) ?> --></option>
<?php foreach ($context->getPerimeters()['p-pit-studies']['school_subject'] as $subjectId) : ?>
	<?php
	$subject = $context->getConfig('student/property/school_subject')['modalities'][$subjectId];
	$caption = $subject[$context->getLocale()];
	?>
	    			<option value="<?php echo $subjectId ?>" <?php if ($note->subject == $subjectId) echo 'selected="selected"' ?>><?php echo $caption ?></option>
<?php endforeach;?>
	    		</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="subject_error"></p></div>
		</div>

<!-- Note date -->
<?php $noteDate = ($note->date) ? $note->date : Date('Y-m-d') ?>
		<input type="hidden" id="date" />
		<div class="form-group" id="input_date_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Date', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input class="form-control" id="input_date" value="<?php echo $context->decodeDate($noteDate) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			</div>
			<div class="col-sm-12"><p class="help-block" id="input_date_error"></p></div>
		</div>

<!-- Type -->
		<div class="form-group" id="type_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Notification type', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select class="form-control" id="type" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
					<option value=""><-- <?php echo $this->translate('Please choose', 'ppit-core', $context->getLocale()) ?> --></option>
					<option value="done-work" <?php if ($note->type == 'done-work') echo 'selected="selected"' ?>><?php echo $this->translate('Done work', 'ppit-studies', $context->getLocale()) ?></option>
					<option value="todo-work" <?php if ($note->type == 'todo-work') echo 'selected="selected"' ?>><?php echo $this->translate('Work to do', 'ppit-studies', $context->getLocale()) ?></option>
					<option value="event" <?php if ($note->type == 'event') echo 'selected="selected"' ?>><?php echo $this->translate('Event', 'ppit-studies', $context->getLocale()) ?></option>
				</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="school_year_error"></p></div>
		</div>

<!-- Target date -->
		<input type="hidden" id="target_date" />
<?php $targetDate = ($note->target_date) ? $note->target_date : Date('Y-m-d') ?>
		<div class="form-group" id="input_target_date_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Target date', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input class="form-control" id="input_target_date" value="<?php echo $context->decodeDate($targetDate) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			</div>
			<div class="col-sm-12"><p class="help-block" id="input_target_date_error"></p></div>
		</div>

<!-- Text -->
<?php 
if ($note->type == 'done-work') $backgroundColor = 'LightGreen';
elseif ($note->type == 'todo-work') $backgroundColor = 'LightSalmon';
elseif ($note->type == 'event') $backgroundColor = 'LightBlue';
else $backgroundColor = null;
?>
<?php if ($isDisabled) : ?>
		<div id="observations_group" <?php if ($backgroundColor) echo 'style="background-color: '.$backgroundColor.'"' ?>><?php echo $note->observations ?></div>
<?php else : ?>
		<div class="form-group" id="observations_group" <?php if ($backgroundColor) echo 'style="background-color: '.$backgroundColor.'"' ?>>
			<div class="col-sm-12">
				<textarea class="form-control" id="observations" <?php if ($isDisabled) echo 'disabled="disabled"'?>><?php echo $note->observations ?></textarea>
			</div>
			<div class="col-sm-12"><p class="help-block" id="observations_error"></p></div>
		</div>
<?php endif;?>
		
<!-- Document -->
		<div class="form-group" id="document_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Attachment', 'ppit-commitment', $context->getLocale()) ?>
<?php if ($note->document) : ?>
				<?php $dropbox = $context->getConfig('ppitDocument')['dropbox'] ?>
				<a class="glyphicon glyphicon-paperclip" href="<?php echo $dropboxClient->createTemporaryDirectLink($dropbox['folders']['schooling'].'/'.$note->document)[0] ?>" title="<?php echo $this->translate('Attachment', 'ppit-document', $context->getLocale()) ?>" target=".blank"></a>
<?php endif;?>
			</label>
			<div class="col-sm-7">
				<select class="form-control" id="document" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
					<option />
		<?php foreach ($documentList as $document) : ?>
					<option value="<?php echo $document ?>" <?php if ($note->document == $document) echo 'selected="selected"' ?>><?php echo $document ?></option>
		<?php endforeach;?>
				</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="document_error"></p></div>
		</div>

<!-- Comment -->
	<?php if (!$isDisabled) : ?>
		<div class="form-group" id="comment_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Internal comment (non visible to the parents)', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<textarea class="form-control" id="comment"></textarea>
			</div>
			<div class="col-sm-12"><p class="help-block" id="comment_error"></p></div>
		</div>
	<?php endif;?>

	<?php if (!$isDisabled) : ?>
		<div class="form-group">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<input name="submit" type="submit" id="submit-button" class="btn btn-warning" value="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>">
			</div>
		</div>
	<?php endif;?>

	</form>
	</div>
</div>
