<?php if ($message == 'OK') : ?>

<!-- Global message -->
<div id="message">
  <h5 class="alert alert-success my-3 text-center"><?php echo $this->translate('Your request has been registered', 'ppit-core', $context->getLocale()) ?></h5>
</div>

<?php endif;?>

<?php if ($error == 'Duplicate') : ?>

<!-- Duplicate error -->
<div class="alert alert-danger my-3 text-center"><?php echo $this->translate('This record already exist', 'ppit-core', $context->getLocale()) ?></div>

<?php endif;?>

<?php if ($error == 'Isolation') : ?>

<!-- Isolation error -->
<div class="alert alert-danger my-3 text-center"><?php echo $this->translate('The database has evolved in the meantime, please input again', 'ppit-core', $context->getLocale()) ?></div>

<?php endif;?>

<?php if ($error == 'Consistency') : ?>

<!-- Consistency error -->
<div class="alert alert-danger my-3 text-center"><?php echo $this->translate('The data are not consistent', 'ppit-core', $context->getLocale()) ?></div>

<?php endif;?>

<!-- CSRF -->
<?php $element = $csrfForm->get('csrf') ?>
<div class="form-group">
  <?php echo $this->formElement($element) ?>
<?php if ($this->formElementErrors($element)) : ?>
  <h5 class="alert alert-danger my-3 text-center"><?php echo $this->translate('The form has expired, please input again', 'ppit-core', $context->getLocale()) ?></h5>
<?php endif;?>
</div>

<input type="hidden" id="update_time" value="<?php echo $note->update_time ?>" />

<!-- Display the audit -->

        <div class="card mt-2">
          <div class="card-body">
            <div class="card-title text-muted"><?php echo $this->translate('History', 'ppit-core', $context->getLocale()) ?> (<a id="audit-label"><?php echo $this->translate('Show', 'ppit-core', $context->getLocale()) ?></a>)</div>
            <div id="audit-panel">
  <?php foreach ($note->audit as $comment) : ?>
              <div class="row">
                <div class="col-md-12">
                  <strong><?php echo $context->decodeDate(substr($comment['time'], 0, 10)).substr($comment['time'], 10) ?>:</strong>&nbsp;
                  <?php if (array_key_exists('status', $comment)) echo $comment['status'] ?>&nbsp;
                  (<?php echo $comment['n_fn'] ?>)
                </div>
              </div>
              <div class="row">
                <div class="col-md-2" align="right">&nbsp;</div>
                <div class="col-md-10"><em><?php if (array_key_exists('comment', $comment)) echo $comment['comment'] ?></em></div>
              </div>
  <?php endforeach;?>
            </div>
          </div>
        </div>

<?php if ($message != 'OK') : ?>
<!-- Menu -->
    <div class="my-3">
            <button type="button" class="btn btn-outline-primary" id="update-anchor" data-toggle="tooltip" title="<?php echo $this->translate('Modifier', 'ppit-core', $context->getLocale()) ?>"><i class="fa fa-edit"></i></button>
            <button type="button" class="btn btn-outline-primary" id="delete-anchor" data-toggle="tooltip" title="<?php echo $this->translate('Supprimer', 'ppit-core', $context->getLocale()) ?>"><i class="fa fa-trash-alt"></i></button>
    </div>
<?php endif;?>

<form action="" id="ppit-form" method="post" class="form-horizontal" enctype="multipart/form-data">

<?php if ($note->id && $action != 'update' || $message == 'OK') $isDisabled = true; else $isDisabled = false; ?>

<?php if ($message != 'OK') : ?>
	<?php if (!$note->id) : ?>
		    <div class="form-group row">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input type="submit" id="up-submit-button" class="btn btn-warning" value="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

	<?php elseif ($action == 'update') : ?>
		    <div class="form-group row">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input type="submit" id="up-submit-button" class="btn btn-warning" value="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

	<?php elseif ($action == 'delete') : ?>
		    <div class="form-group row">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input type="submit" id="up-submit-button" class="btn btn-danger" value="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>
	<?php endif;?>
<?php endif;?>

<!-- Names -->
<hr>
	<div class="form-group row" id="product_group">
		<label class="col-sm-5 col-form-label col-form-label-sm"><?php echo $this->translate('Students', 'ppit-studies', $context->getLocale()) ?></label>
		<div class="col-sm-7">&nbsp;</div>
	</div>
<?php foreach ($note->links as $noteLink) : ?>
	<div class="form-group row" id="product_group">
		<label class="col-sm-5 col-form-label col-form-label-sm">&nbsp;</label>
		<div class="col-sm-7">
			<input class="form-control form-control-sm" disabled="disabled" value="<?php echo $noteLink->n_fn ?>" />
		</div>
	</div>
<?php endforeach;?>
<hr>

<!-- Place -->
		<div class="form-group row" id="place_id_group">
			<label class="col-sm-5 col-form-label col-form-label-sm">* <?php echo $context->localize($context->getConfig('student/property/place')['labels']) ?></label>
			<div class="col-sm-7">
				<select class="form-control form-control-sm" id="place_id" <?php if ($isDisabled || $note->place_id) echo 'disabled="disabled"'?>>
					<option />
	<?php foreach ($places as $place) : ?>
					<option value="<?php echo $place->id ?>" <?php if ($note->place_id == $place->id) echo 'selected="selected"' ?>><?php echo $place->caption ?></option>
	<?php endforeach;?>
				</select>
                <div class="invalid-feedback" id="place_id_error"></div>
			</div>
		</div>

<!-- Class -->
		<div class="form-group row" id="class_group">
			<label class="col-sm-5 col-form-label col-form-label-sm">* <?php echo $context->localize($context->getConfig('student/property/class')['labels']) ?></label>
			<div class="col-sm-7">
				<select class="form-control form-control-sm" id="class" <?php if ($isDisabled || $note->class) echo 'disabled="disabled"'?>>
					<option />
	<?php foreach ($context->getConfig('student/property/class')['modalities'] as $classId => $class) : ?>
					<option value="<?php echo $classId ?>" <?php if ($note->class == $classId) echo 'selected="selected"' ?>><?php echo $context->localize($class) ?></option>
	<?php endforeach;?>
				</select>
                <div class="invalid-feedback" id="class_error"></div>
			</div>
		</div>

<!-- Evaluation period -->
		<div class="form-group row" id="school_period_group">
			<label class="col-sm-5 col-form-label col-form-label-sm">* <?php echo $context->localize($context->getConfig('student/property/school_period')['labels']) ?></label>
			<div class="col-sm-7">
				<select class="form-control form-control-sm" id="school_period" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
					<option />
	<?php foreach ($context->getConfig('student/property/school_period')['modalities'] as $modalityId => $modality) : ?>
					<option value="<?php echo $modalityId ?>" <?php if ($modalityId == $note->school_period) echo 'selected="selected"' ?>><?php echo $context->localize($modality) ?></option>
	<?php endforeach;?>
				</select>
                <div class="invalid-feedback" id="school_period_error"></div>
			</div>
		</div>

<!-- Subject -->
<?php 
if (array_key_exists('p-pit-studies', $context->getPerimeters()) && array_key_exists('school_subject', $context->getPerimeters()['p-pit-studies'])) {
	$modalities = array();
	foreach ($context->getPerimeters()['p-pit-studies']['school_subject'] as $modalityId) {
		$modalities[$modalityId] = $context->getConfig('student/property/school_subject')['modalities'][$modalityId];	
	}
}
else $modalities = $context->getConfig('student/property/school_subject')['modalities'];
?>
		<div class="form-group row" id="subject_group">
			<label class="col-sm-5 col-form-label col-form-label-sm"><?php echo $this->translate('Subject', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<select class="form-control form-control-sm" id="subject" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
	    			<option value=""><-- <?php echo $this->translate('Please choose', 'ppit-core', $context->getLocale()) ?> --></option>
<?php foreach ($modalities as $subjectId => $subject) : ?>
	<?php $caption = $context->localize($subject) ?>
	    			<option value="<?php echo $subjectId ?>" <?php if ($note->subject == $subjectId) echo 'selected="selected"' ?>><?php echo $caption ?></option>
<?php endforeach;?>
	    		</select>
                <div class="invalid-feedback" id="subject_error"></div>
			</div>
		</div>

<!-- Note date -->
<?php $noteDate = ($note->date) ? $note->date : Date('Y-m-d') ?>
		<input type="hidden" id="date" />
		<div class="form-group row" id="input_date_group">
			<label class="col-sm-5 col-form-label col-form-label-sm"><?php echo $this->translate('Notification date', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input class="form-control form-control-sm" id="input_date" value="<?php echo $context->decodeDate($noteDate) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
                <div class="invalid-feedback" id="input_date_error"></div>
			</div>
		</div>

<!-- Type -->
		<div class="form-group row" id="type_group">
			<label class="col-sm-5 col-form-label col-form-label-sm">* <?php echo $this->translate('Notification type', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select class="form-control form-control-sm" id="type" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
					<option value=""><-- <?php echo $this->translate('Please choose', 'ppit-core', $context->getLocale()) ?> --></option>
					<option value="done-work" <?php if ($note->type == 'done-work') echo 'selected="selected"' ?>><?php echo $this->translate('Done work', 'ppit-studies', $context->getLocale()) ?></option>
					<option value="todo-work" <?php if ($note->type == 'todo-work') echo 'selected="selected"' ?>><?php echo $this->translate('Work to do', 'ppit-studies', $context->getLocale()) ?></option>
					<option value="event" <?php if ($note->type == 'event') echo 'selected="selected"' ?>><?php echo $this->translate('Event', 'ppit-studies', $context->getLocale()) ?></option>
				</select>
                <div class="invalid-feedback" id="school_year_error"></div>
			</div>
		</div>

<!-- Target date -->
		<input type="hidden" id="target_date" />
<?php $targetDate = ($note->target_date) ? $note->target_date : Date('Y-m-d') ?>
		<div class="form-group row" id="input_target_date_group">
			<label class="col-sm-5 col-form-label col-form-label-sm"><?php echo $this->translate('Work to do or event date', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input class="form-control form-control-sm" id="input_target_date" value="<?php echo $context->decodeDate($targetDate) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
                <div class="invalid-feedback" id="input_target_date_error"></div>
			</div>
		</div>

<!-- Text -->
<?php 
if ($note->type == 'done-work') $backgroundColor = 'LightGreen';
elseif ($note->type == 'todo-work') $backgroundColor = 'LightSalmon';
elseif ($note->type == 'event') $backgroundColor = 'LightBlue';
else $backgroundColor = null;
?>
<?php if ($isDisabled) : ?>
		<div id="observations_group" <?php if ($backgroundColor) echo 'style="background-color: '.$backgroundColor.'"' ?>><?php echo $note->observations ?></div>
<?php else : ?>
		<div class="form-group row" id="observations_group" <?php if ($backgroundColor) echo 'style="background-color: '.$backgroundColor.'"' ?>>
			<div class="col-sm-12">
				<textarea class="form-control fomr-control-sm" id="observations" <?php if ($isDisabled) echo 'disabled="disabled"'?>><?php echo $note->observations ?></textarea>
                <div class="invalid-feedback" id="observations_error"></div>
			</div>
		</div>
<?php endif;?>

<hr>
		
<!-- Document -->
<div class="form-group row" id="document_group">
  <label class="col-sm-5 col-form-label col-form-label-sm"><?php echo $this->translate('Attachment', 'ppit-commitment', $context->getLocale()) ?>
  </label>
  <div class="col-sm-7">
    <input type="hidden" id="document" />
    <a href="<?php echo ($isDisabled && $document) ? $this->url('document/download', ['id' => $document->id]) : '#' ?>" <?php if ($isDisabled && $document) : ?>target="_blank"<?php endif;?> class="document-show-anchor"><?php echo ($document) ? $document->name : $this->translate('Choose among the shared documents', 'ppit-core', $context->getLocale()) ?></a>
    <div class="invalid-feedback" id="document_error"></div>
  </div>
</div>
<div id="document-select-panel"></div>

<hr>

<!-- Comment -->
	<?php if (!$isDisabled) : ?>
		<div class="form-group row" id="comment_group">
			<label class="col-sm-5 col-form-label col-form-label-sm"><?php echo $this->translate('Internal comment (non visible to the parents)', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<textarea class="form-control form-control-sm" id="comment"></textarea>
                <div class="invalid-feedback" id="comment_error"></div>
			</div>
		</div>
	<?php endif;?>

<?php if (!$isDisabled) : ?>

	<?php if (!$note->id) : ?>
		    <div class="form-group row">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="submit-button" class="btn btn-warning" value="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

	<?php elseif ($action == 'update') : ?>
		    <div class="form-group row">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="submit-button" class="btn btn-warning" value="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

	<?php elseif ($action == 'delete') : ?>
		    <div class="form-group row">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="submit-button" class="btn btn-danger" value="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>
	<?php endif;?>
<?php endif;?>

</form>
