<table class="table table-striped ppit_index">
	<tr>
		<th>&nbsp;</th>

<?php foreach ($context->getConfig('commitmentEvent/list/p-pit-studies') as $propertyId => $rendering) : ?>
		<th align="center">
	<?php 
	if ($propertyId == 'begin_time') $label = $this->translate('Begin', 'ppit-commitment', $context->getLocale());
	elseif ($propertyId == 'end_time') $label = $this->translate('End', 'ppit-commitment', $context->getLocale());
	elseif ($propertyId == 'title') $label =  $this->translate('Title', 'ppit-commitment', $context->getLocale());
	else $label = $context->getConfig('core_account/p-pit-studies')['properties'][$propertyId]['labels'][$context->getLocale()];
	?>
	<?php if ($label) : ?>
			<button type="button" class="btn btn-default btn-xs ppit-sort-anchor" id="<?php echo $propertyId ?>-anchor">
				<span><?php echo $label ?></span>
<?php if ($major == $propertyId) : ?>
				<span class="glyphicon glyphicon-triangle-<?php echo ($dir == 'ASC') ? 'top' : 'bottom' ?>"></span>
<?php endif ?>
			</button>
	<?php endif;?>
		</th>
<?php endforeach;?>

	</tr>

<?php foreach ($events as $event) : ?>
	
<!--	<input type="hidden" id="event_<?php //echo $i ?>" value="<?php //echo $event->id ?>" /> -->
	
	<tr style="text-align: center">

		<td style="text-align: center">
			<button type="button" class="btn btn-default btn-xs index-btn event-detail-anchor" title="<?php echo $this->translate('Detail', 'ppit-core', $context->getLocale())?>" id="event-detail-anchor_<?php echo $event->id ?>">
				<span class="glyphicon glyphicon-zoom-in" id="group-glyphicon"></span>
			</button>
		</td>

	<?php foreach ($context->getConfig('commitmentEvent/list/p-pit-studies') as $propertyId => $rendering) : ?>

		<?php if ($propertyId == 'begin_time') : ?>
		<td><?php echo $context->decodeDate($event->begin_time) ?></td>

		<?php elseif ($propertyId == 'end_time') : ?>
		<td><?php echo $context->decodeDate($event->end_time) ?></td>

		<?php elseif ($propertyId == 'title') : ?>
		<td><?php echo $event->title ?></td>

		<?php else : ?>	
			<?php 
			if ($rendering == 'select') $property = $context->getConfig('student/'.$propertyId);
			else $property = $property = $context->getConfig('commitment/account/p-pit-studies')['properties'][$propertyId];
			?>
		
			<?php if ($rendering == 'text') : ?>
		<td><?php echo $event->properties[$propertyId] ?></td>

			<?php elseif ($rendering == 'image') : ?>
		<td style="text-align: center">
			<img height="20" src="<?php echo $this->basePath('/img/'.$context->getInstance()->caption.'/'.$event->properties[$propertyId].'.png') ?>" title="<?php echo $event->properties[$propertyId] ?>" alt="<?php echo $event->properties[$propertyId] ?>" />
		</td>

			<?php elseif ($rendering == 'phone') : ?>
		<td>
			<a href="tel:<?php echo $event->properties[$propertyId] ?>"><?php echo $event->properties[$propertyId] ?></a>
		</td>

			<?php elseif ($rendering == 'select') : ?>
		<td><?php echo $property['modalities'][$event->properties[$propertyId]][$context->getLocale()] ?>
		</td>
	
			<?php else : ?>
		<td><?php echo $event->properties[$propertyId] ?></td>

			<?php endif;?>		
		<?php endif;?>
		
	<?php endforeach;?>
	
	</tr>
	
<?php endforeach; ?>

</table>
