<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
		'update_time' => $progress->update_time,
		'message' => $message,
		'error' => $error,
		'csrfForm' => $csrfForm,
		'context' => $context,
));
?>

<?php if ($message == 'OK') $isDisabled = true; else $isDisabled = false; ?>

<!-- School year -->
		<div class="form-group" id="school_year_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('School year', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select class="form-control" id="school_year" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
	<?php foreach ($context->getConfig('progress')['properties']['school_year']['modalities'] as $schoolYearId => $schoolYear) : ?>
					<option value="<?php echo $schoolYearId ?>"><?php echo $schoolYear[$context->getLocale()] ?></option>
	<?php endforeach;?>
				</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="school_year_error"></p></div>
		</div>

<!-- Period -->
		<div class="form-group" id="period_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Period', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select class="form-control" id="period" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
	    			<option value=""><-- <?php echo $this->translate('Please choose', 'ppit-core', $context->getLocale()) ?> --></option>
	<?php foreach ($context->getConfig('progress')['properties']['period']['modalities'] as $periodId => $period) : ?>
					<option value="<?php echo $periodId ?>"><?php echo $period[$context->getLocale()] ?></option>
	<?php endforeach;?>
				</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="period_error"></p></div>
		</div>

<!-- Comment -->
		<div class="form-group" id="comment_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Comment', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<textarea class="form-control" id="comment" <?php if ($isDisabled) echo 'disabled="disabled"'?>></textarea>
			</div>
			<div class="col-sm-12"><p class="help-block" id="comment_error"></p></div>
		</div>

<?php if ($message != 'OK') : ?>
		<div class="form-group">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<input name="submit" type="submit" id="submit-button" class="btn btn-warning" value="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
			</div>
		</div>
<?php endif;?>

	</form>
