<table class="table table-striped ppit_index">
	<tr>
		<th>&nbsp;</th>

<?php foreach ($context->getConfig('progress/list') as $propertyId => $rendering) : ?>
		<th>
	<?php 
	if ($propertyId == 'property_1') $property = $context->getConfig('student/property/discipline');
	elseif ($propertyId == 'period') $property = $context->getConfig('student/property/discipline_period');
	elseif ($propertyId == 'name') $property = $context->getConfig('core_account/p-pit-studies/property/name');
	else $property = $context->getConfig('core_account/p-pit-studies/property/'.$propertyId);
	$label = $property['labels'][$context->getLocale()];
	?>
	<?php if ($label) : ?>
			<button type="button" class="btn btn-default btn-xs ppit-sort-anchor" id="<?php echo $propertyId ?>-anchor">
				<span><?php echo $label ?></span>
<?php if ($major == $propertyId) : ?>
				<span class="glyphicon glyphicon-triangle-<?php echo ($dir == 'ASC') ? 'top' : 'bottom' ?>"></span>
<?php endif ?>
			</button>
	<?php endif;?>
		</th>
<?php endforeach;?>

	</tr>

<?php $i=0; foreach ($progresses as $progress) : ?>
	
	<input type="hidden" id="progress_<?php echo $i ?>" value="<?php echo $progress->id ?>" />
	<input type="hidden" id="progress-sport_<?php echo $i ?>" value="<?php echo $progress->subject ?>" />
	
	<tr>

		<td style="text-align: center">
			<button type="button" class="btn btn-default btn-xs index-btn progress-detail-anchor" title="<?php echo $this->translate('Detail', 'ppit-core', $context->getLocale())?>" id="progress-detail-anchor_<?php echo $progress->id ?>">
				<span class="glyphicon glyphicon-zoom-in" id="group-glyphicon"></span>
			</button>
		</td>

	<?php foreach ($context->getConfig('progress/list') as $propertyId => $rendering) : ?>
	
		<?php if ($propertyId == 'name') : ?>
		<td><?php echo $progress->name ?></td>

		<?php elseif ($propertyId == 'property_1') : ?>
		<td style="text-align: center">
			<img height="20" src="<?php echo $this->basePath('/img/p-pit-studies/'.$type.'.png') ?>" title="<?php echo $type ?>" alt="<?php echo $type ?>" />
		</td>
	
		<?php elseif ($rendering == 'photo') : ?>
		<td>
			<span class="info">
				<img height="40" src="<?php echo $this->url('vcard/photo', array('id' => $progress->photo)) ?>"/>
				<span><img height="150" src="<?php echo $this->url('vcard/photo', array('id' => $progress->photo)) ?>"/></span>
			</span>
		</td>
	
		<?php elseif ($rendering == 'text') : ?>
		<td><?php echo $progress->properties[$propertyId] ?></td>

		<?php elseif ($rendering == 'image') : ?>
		<td style="text-align: center">
			<img height="20" src="<?php echo $this->basePath('/img/'.$context->getInstance()->caption.'/'.$progress->properties[$propertyId].'.png') ?>" title="<?php echo $progress->properties[$propertyId] ?>" alt="<?php echo $progress->properties[$propertyId] ?>" />
		</td>

		<?php elseif ($rendering == 'phone') : ?>
		<td>
			<a href="tel:<?php echo $progress->properties[$propertyId] ?>"><?php echo $progress->properties[$propertyId] ?></a>
		</td>

		<?php elseif ($rendering == 'select') : ?>
		<td><?php echo $property['modalities'][$progress->properties[$propertyId]][$context->getLocale()] ?>
		</td>
	
		<?php else : ?>
		<td><?php echo $progress->properties[$propertyId] ?></td>
		
		<?php endif;?>
		
	<?php endforeach;?>
	
	</tr>
	
<?php $i++; endforeach; ?>

</table>
