<div class="panel panel-default">
	<div class="panel-heading" style="background: <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<strong>
			<?php 
			$title = $context->getConfig('progress/search')['title'][$context->getLocale()];
			echo $type.': '.$title;
			?>
			(<span id="mode-text"></span>)
		</strong>
	</div>
	<div class="panel-body">

<!-- Filters -->

		<div class="form-group">
			<label class="col-sm-5 control-label"><span class="glyphicon glyphicon-search"></span></label>
			<div class="col-sm-7">
	    		<button type="button" class="form-control btn btn-default btn-xs" title="<?php echo $this->translate('Erase', 'ppit-core', $context->getLocale()) ?>" id="erase-button">
					<span class="glyphicon glyphicon-remove"></span>
				</button>
			</div>
		</div>
		
<?php foreach ($context->getConfig('progress/search')['main'] as $propertyId => $rendering) : ?>

	<?php if ($rendering == 'select') : ?>

		<?php
		if ($propertyId == 'property_1') $property = $context->getConfig('student/property/discipline');
		elseif ($propertyId == 'period') $property = $context->getConfig('student/property/discipline_period');
		elseif ($propertyId == 'school_year') $property = $context->getConfig('student/property/school_year');
		?>
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $property['labels'][$context->getLocale()] ?></label>
			<div class="col-sm-7">
				<select id="search_<?php echo $propertyId ?>" class="form-control">
					<option value=""></option>
		<?php foreach ($property['modalities'] as $modalityId => $modality) : ?>
		    		<option value="<?php echo $modalityId ?>" <?php if ($propertyId == 'property_1' && $modalityId == $type) echo 'selected="selected"' ?>><?php echo $modality[$context->getLocale()] ?></option>
		<?php endforeach;?>
		    	</select>
			</div>
		</div>
	
	<?php elseif ($rendering == 'contains') : ?>
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $context->getConfig('core_account/p-pit-studies/property/'.(($propertyId == 'name') ? 'name' : $propertyId))['labels'][$context->getLocale()] ?></label>
			<div class="col-sm-7">
				<input class="form-control" type="text" id="search_<?php echo $propertyId ?>" placeholder="<?php echo $this->translate('Contains', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

	<?php elseif ($rendering == 'range') : ?>

		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $context->getConfig('core_account/p-pit-studies/property/'.$propertyId)['labels'][$context->getLocale()] ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_min_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_max_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

	<?php endif;?>
<?php endforeach;?>
	
		<div><a id="add-criteria" href="#"><?php echo $this->translate('More criteria', 'ppit-core', $context->getLocale())?></a></div>
		<div id="search-area">
		
<?php foreach ($context->getConfig('progress/search')['more'] as $propertyId => $rendering) : ?>

	<?php if ($rendering == 'select') : ?>

		<?php
		if ($propertyId == 'property_1') $property = $context->getConfig('student/property/discipline');
		elseif ($propertyId == 'period') $property = $context->getConfig('student/property/discipline_period');
		elseif ($propertyId == 'school_year') $property = $context->getConfig('student/property/school_year');
		?>
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $property['labels'][$context->getLocale()] ?></label>
			<div class="col-sm-7">
				<select id="search_<?php echo $propertyId ?>" class="form-control">
					<option value=""></option>
		<?php foreach ($property['modalities'] as $modalityId => $modality) : ?>
		    		<option value="<?php echo $modalityId ?>"><?php echo $modality[$context->getLocale()] ?></option>
		<?php endforeach;?>
		    	</select>
			</div>
		</div>
	
	<?php elseif ($rendering == 'contains') : ?>
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $context->getConfig('core_account/p-pit-studies/property/'.(($propertyId == 'name') ? 'name' : $propertyId))['labels'][$context->getLocale()] ?></label>
			<div class="col-sm-7">
				<input class="form-control" type="text" id="search_<?php echo $propertyId ?>" placeholder="<?php echo $this->translate('Contains', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

	<?php elseif ($rendering == 'range') : ?>

		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $context->getConfig('core_account/p-pit-studies/property/'.$propertyId)['labels'][$context->getLocale()] ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_min_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_max_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

	<?php endif;?>
<?php endforeach;?>

		</div>

	    <div>&nbsp;</div>

<!-- Actions -->
	    <div>
	    		<button type="button" class="btn btn-default" title="<?php echo $this->translate('Export', 'ppit-core', $context->getLocale()) ?>" id="export-button">
					<span class="glyphicon glyphicon-cloud-download"></span>
					<span><?php echo $this->translate('Export', 'ppit-core', $context->getLocale())?></span>
				</button>
	    </div>
	    
		<div>&nbsp;</div>

<!-- Add or update section -->
		<div id="progress-list-panel"></div>
	</div>
</div>
