<div class="panel panel-default">
	<div class="panel-heading" style="background:  <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<strong><?php echo $this->translate('Detail', 'ppit-core', $context->getLocale()) ?></strong>
 		<div class="btn-group pull-right">
			<button type="button" class="btn btn-default" title="<?php echo $this->translate('Return to list', 'ppit-core', $context->getLocale()) ?>" id="remove-anchor">
				<span class="glyphicon glyphicon-remove"></span>
			</button>
 		 </div>
	</div>
	<div class="panel-body">

<!-- Menu -->
		<div>
			<button type="button" class="btn btn-default btn-xs detail-menu-btn" title="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale())?>" id="delete-anchor">
				<span class="glyphicon glyphicon-trash" id="group-glyphicon"></span>
			</button>
		</div>

<!-- Display the audit -->
		<div>&nbsp;</div>
		<?php echo $this->translate('History', 'ppit-core', $context->getLocale()) ?> (<a id="audit-label"><?php echo $this->translate('Show', 'ppit-core', $context->getLocale()) ?></a>)
		<div id="audit-panel" class="panel panel-default">
			<div class="panel-body">
	<?php foreach ($progress->audit as $comment) : ?>
				<div class="row">
					<div class="col-md-12">
						<strong><?php echo $context->decodeDate(substr($comment['time'], 0, 10)).substr($comment['time'], 10) ?>:</strong>&nbsp;
						<?php if (array_key_exists('status', $comment)) echo $comment['status'] ?>&nbsp;
						(<?php echo $comment['n_fn'] ?>)
					</div>
				</div>
				<div class="row">
					<div class="col-md-2" align="right">&nbsp;</div>
					<div class="col-md-10"><em><?php echo $comment['comment'] ?></em></div>
				</div>
	<?php endforeach;?>
			</div>
		</div>
		<div>&nbsp;</div>

<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
		'update_time' => $progress->update_time,
		'message' => $message,
		'error' => $error,
		'csrfForm' => $csrfForm,
		'context' => $context,
));
?>

<?php if ($message == 'OK') $isDisabled = true; else $isDisabled = false; ?>

<!-- Name -->

	<div class="form-group" id="product_group">
		<label class="col-sm-5 control-label">&nbsp;</label>
		<div class="col-sm-7">
			<input class="form-control" disabled="disabled" value="<?php echo $progress->name ?>" />
		</div>
	</div>

<!-- School year -->
		<div class="form-group" id="school_year_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('School year', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select class="form-control" id="school_year" disabled="disabled">
	<?php foreach ($context->getConfig('student/property/school_year')['modalities'] as $schoolYearId => $schoolYear) : ?>
					<option value="<?php echo $schoolYearId ?>" <?php if ($progress->school_year == $schoolYearId) echo ' selected="selected"' ?>><?php echo $schoolYear[$context->getLocale()] ?></option>
	<?php endforeach;?>
				</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="school_year_error"></p></div>
		</div>

<!-- Period -->
		<div class="form-group" id="period_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Period', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select class="form-control" id="period" disabled="disabled">
	    			<option value=""><-- <?php echo $this->translate('Please choose', 'ppit-core', $context->getLocale()) ?> --></option>
	<?php foreach ($context->getConfig('student/property/discipline_period')['modalities'] as $periodId => $period) : ?>
					<option value="<?php echo $periodId ?>" <?php if ($progress->period == $periodId) echo ' selected="selected"' ?>><?php echo $period[$context->getLocale()] ?></option>
	<?php endforeach;?>
				</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="period_error"></p></div>
		</div>

<!-- Up submit -->
	<?php if (!$isDisabled) : ?>
		<div class="form-group">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<input name="submit" type="submit" id="up-submit-button" class="btn btn-warning" value="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>">
			</div>
		</div>
	<?php endif;?>

<!-- Progress date -->
<?php $progressDate = ($progress->date) ? $progress->date : Date('Y-m-d') ?>
		<input type="hidden" id="date" />
		<div class="form-group" id="input_date_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Date', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input class="form-control" id="input_date" value="<?php echo $context->decodeDate($progressDate) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			</div>
			<div class="col-sm-12"><p class="help-block" id="input_date_error"></p></div>
		</div>

<?php $criteria = $context->getConfig('progress'.(($type) ? '/'.$type : ''))['criteria'] ?>

<?php if (array_key_exists('qualitative_criteria', $criteria)) : ?>
	<?php foreach ($criteria['qualitative_criteria'] as $criterionId => $criterion) : ?>

		<?php $criterionValue = (array_key_exists($criterionId, $progress->criteria)) ? $progress->criteria[$criterionId] : null ?>

		<?php if ($criterion['type'] == 'subtitle') : ?>

		<div><strong><?php echo $criterion['labels'][$context->getLocale()]?></strong></div>
		<div>&nbsp;</div>

		<?php else : ?>
			
		<div class="form-group" id="qualitative_<?php echo $criterionId ?>_group">
			<label class="col-sm-5 control-label"><?php echo $criterion['labels'][$context->getlocale()] ?></label>
			<div class="col-sm-7">
				<input class="form-control" id="qualitative_<?php echo $criterionId ?>" value="<?php echo $criterionValue ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			</div>
			<div class="col-sm-12"><p class="help-block" id="qualitative_<?php echo $criterionId ?>_error"></p></div>
		</div>
		
		<?php endif;?>

	<?php endforeach;?>
<?php endif;?>

<?php if (array_key_exists('quantitative_criteria', $criteria)) : ?>
	<?php foreach ($criteria['quantitative_criteria'] as $criterionId => $criterion) : ?>

		<?php 
		$criterionValue = (array_key_exists($criterionId, $progress->criteria)) ? $progress->criteria[$criterionId] : null;
		if ($criterionValue == "NA") $colorCoding = 'red';
		elseif ($criterionValue == "EC") $colorCoding = 'orange';
		elseif ($criterionValue == "AC") $colorCoding = 'green';
		else $colorCoding = null;
		?>
		
		<?php if ($criterion['type'] == 'subtitle') : ?>

<!-- Subtitle -->
		<div><strong><?php echo $criterion['labels'][$context->getLocale()]?></strong></div>
		<div>&nbsp;</div>

		<?php elseif ($criterion['type'] == 'select') : ?>

<!-- Select -->
		<div class="form-group" id="quantitative_<?php echo $criterionId ?>_group">
			<label class="col-sm-5 control-label"><?php echo $criterion['labels'][$context->getlocale()] ?></label>
			<div class="col-sm-1" <?php if ($colorCoding) echo 'style="background-color: '.$colorCoding.'"' ?>>&nbsp;</div>
			<div class="col-sm-1" id="color-coding_<?php echo $criterionId ?>" <?php if ($colorCoding) echo 'style="background-color: '.$colorCoding.'"' ?>>&nbsp;</div>
			<div class="col-sm-5">
				<select class="form-control" id="quantitative_<?php echo $criterionId ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
	    			<option value=""><-- <?php echo $this->translate('Please choose', 'ppit-core', $context->getLocale()) ?> --></option>
		<?php foreach ($criteria['modalities'] as $key => $value) : ?>
					<option value="<?php echo $key ?>" <?php if ($criterionValue == $key) echo ' selected="selected"' ?>><?php echo $criteria['modalities'][$key][$context->getLocale()] ?></option>
		<?php endforeach;?>
				</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="quantitative_<?php echo $criterionId ?>_error"></p></div>
		</div>
			
		<?php else : ?>
		
<!-- Number -->
		<div class="form-group" id="quantitative_<?php echo $criterionId ?>_group">
			<label class="col-sm-5 control-label"><?php echo $criterion['labels'][$context->getlocale()] ?></label>
			<div class="col-sm-7">
				<input class="form-control" id="quantitative_<?php echo $criterionId ?>" value="<?php if (array_key_exists($criterionId, $progress->criteria)) echo  $context->formatFloat($progress->criteria[$criterionId], 2) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			</div>
			<div class="col-sm-12"><p class="help-block" id="quantitative_<?php echo $criterionId ?>_error"></p></div>
		</div>
		
		<?php endif;?>

	<?php endforeach;?>
<?php endif;?>

<!-- Observations -->
		<div class="form-group" id="observations_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Observations', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<textarea class="form-control" id="observations" <?php if ($isDisabled) echo 'disabled="disabled"'?>><?php echo $progress->observations ?></textarea>
			</div>
			<div class="col-sm-12"><p class="help-block" id="observations_error"></p></div>
		</div>

<!-- Status -->
		<div class="form-group" id="status_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Completed', 'ppit-core', $context->getLocale()) ?> ?</label>
			<div class="col-sm-7">
				<input type="checkbox" class="form-control" id="status" <?php if ($progress->status == 'completed') echo 'checked="checked"' ?> value="completed" <?php if ($isDisabled) echo 'disabled="disabled"'?>></checkbox>
			</div>
			<div class="col-sm-12"><p class="help-block" id="status_error"></p></div>
		</div>

<!-- Comment -->
	<?php if (!$isDisabled) : ?>
		<div class="form-group" id="comment_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Comment (non visible to the student)', 'ppit-studies', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<textarea class="form-control" id="comment"></textarea>
			</div>
			<div class="col-sm-12"><p class="help-block" id="comment_error"></p></div>
		</div>
	<?php endif;?>

	<?php if (!$isDisabled) : ?>
		<div class="form-group">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<input name="submit" type="submit" id="submit-button" class="btn btn-warning" value="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>">
			</div>
		</div>
	<?php endif;?>

	</form>
	</div>
</div>
